---
permalink: nfs-trunking/reestablish-client-mount-task.html 
sidebar: sidebar 
keywords: NFS, servers, network, NFS trunking, data, shares, Linux, VMware, mounts, client 
summary: 트렁킹되지 않은 클라이언트 연결을 트렁킹 연결로 변환하려면 Linux 및 VMware 클라이언트의 기존 마운트를 분리하고 LIF에 대한 정보를 사용하여 다시 마운트해야 합니다. 
---
= ONTAP 볼륨 또는 데이터 공유를 NFS 트렁킹에 다시 마운트합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
트렁킹되지 않은 클라이언트 연결을 트렁킹 연결로 변환하려면 Linux 및 VMware 클라이언트의 기존 마운트를 분리하고 LIF에 대한 정보를 사용하여 다시 마운트해야 합니다.

에 대해 자세히 알아보십시오 link:index.html#supported-clients["지원되는 클라이언트"].


NOTE: VMware 클라이언트의 마운트를 해제하면 데이터 저장소의 모든 VM에 대해 중단이 발생합니다. 또는 트렁킹을 사용할 수 있는 새 데이터 저장소를 생성하고 * storage vMotion * 을 사용하여 VM을 이전 데이터 저장소에서 새 데이터 저장소로 이동하는 방법도 있습니다. 자세한 내용은 VMware 설명서를 참조하십시오.

[role="tabbed-block"]
====
.Linux 클라이언트 요구 사항
--
ONTAP 9.16.1 이상 및 Red Hat Enterprise Linux 버전 8.7 이상(RHEL 8의 경우) 또는 9.2 이상(RHEL 9의 경우)을 Linux 클라이언트로 사용하는 경우 트렁킹 그룹에 하나의 마운트 지점만 필요합니다. 다음 옵션을 사용하여 내보낸 볼륨을 이 명령으로 마운트합니다. `trunkdiscovery`

[source, cli]
----
mount <lif_ip>:<volume_name> </mount_path> -o trunkdiscovery,vers=4.1
----
그렇지 않으면 트렁킹 그룹의 각 연결에 대해 별도의 마운트 지점이 필요합니다. 옵션을 사용하여 다음과 유사한 명령을 사용하여 내보낸 볼륨을 마운트합니다 `max_connect`.

[source, cli]
----
mount <lif1_ip>:<volume_name> </mount_path1> -o vers=4.1,max_connect=16
----
[source, cli]
----
mount <lif2_ip>:<volume_name> </mount_path2> -o vers=4.1,max_connect=16
----
버전 (`vers`) 값은 이어야 합니다 `4.1` 이상.

를 클릭합니다 `max_connect` 값은 트렁킹 그룹의 연결 수에 해당합니다.

--
.VMware 클라이언트 요구 사항
--
트렁킹 그룹의 각 연결에 대한 IP 주소를 포함하는 마운트 문이 필요합니다.

다음과 유사한 명령을 사용하여 내보낸 데이터 저장소를 마운트합니다.

`#esxcli storage nfs41 -H lif1_ip, lif2_ip -s /mnt/sh are1 -v nfs41share`

를 클릭합니다 `-H` 값은 트렁킹 그룹의 연결과 일치해야 합니다.

--
====