---
permalink: flexcache/flexcache-duality-faq.html 
sidebar: sidebar 
keywords: duality, faq, frequently asked questions, flexcache, ontap s3, s3, nas, smb, nfs 
summary: ONTAP 9.18.1에 도입된 FlexCache 이중화 기능에 대한 자주 묻는 질문입니다. 
---
= FlexCache 이중성에 대한 FAQ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 ONTAP 9.18.1에서 도입된 FlexCache 이중화에 대한 일반적인 질문에 답변합니다.



== 자주 묻는 질문

."이원성"이란 무엇입니까?
듀얼리티(Duality)는 파일(NAS) 및 객체(S3) 프로토콜을 모두 사용하여 동일한 데이터에 통합적으로 접근할 수 있도록 합니다. FlexCache 지원 없이 ONTAP 9.12.1에서 처음 도입된 듀얼리티는 ONTAP 9.18.1에서 FlexCache 볼륨을 포함하도록 확장되어 FlexCache 볼륨에 캐시된 NAS 파일에 S3 프로토콜 액세스를 허용합니다.

.FlexCache S3 버킷에서 지원되는 S3 작업에는 어떤 것들이 있습니까?
표준 S3 NAS 버킷에서 지원되는 S3 작업은 FlexCache S3 NAS 버킷에서도 지원되지만 `COPY` 작업은 예외입니다. 표준 S3 NAS 버킷에서 지원되지 않는 작업의 최신 목록은 link:https://docs.netapp.com/us-en/ontap/s3-multiprotocol/index.html#s3-and-nas-interoperability["상호 운용성 문서"]를 참조하십시오.

.FlexCache 이중성 기능을 사용하여 FlexCache를 쓰기 후 저장 모드로 사용할 수 있습니까?
아니요. FlexCache 볼륨에 FlexCache S3 NAS 버킷을 생성하려면 FlexCache 볼륨이 *반드시* 쓰기 우회 모드여야 합니다. 쓰기 백 모드로 설정된 FlexCache 볼륨에 FlexCache S3 NAS 버킷을 생성하려고 하면 작업이 실패합니다.

.하드웨어 제한 때문에 클러스터 중 하나를 ONTAP 9.18.1로 업그레이드할 수 없습니다. 캐시 클러스터만 ONTAP 9.18.1을 실행하는 경우 내 클러스터에서 duality가 계속 작동합니까?
아니요. 캐시 클러스터와 오리진 클러스터 모두 최소 유효 클러스터 버전이 9.18.1 이상이어야 합니다. ONTAP 버전 9.18.1보다 이전 버전인 오리진 클러스터와 피어링된 캐시 클러스터에 FlexCache S3 NAS 버킷을 생성하려고 하면 작업이 실패합니다.

.MetroCluster 구성이 있습니다. FlexCache 이중화 기능을 사용할 수 있습니까?
아니요. FlexCache 이중성은 MetroCluster 구성에서 지원되지 않습니다.

.FlexCache S3 NAS 버킷에 있는 파일에 대한 S3 액세스를 감사할 수 있습니까?
S3 감사는 FlexCache 볼륨에서 사용하는 NAS 감사 기능을 통해 제공됩니다. FlexCache 볼륨의 NAS 감사에 대한 자세한 내용은 link:audit-flexcache-volumes-concept.html["FlexCache 감사에 대해 자세히 알아보세요"]를 참조하십시오.

.캐시 클러스터가 원본 클러스터에서 연결이 끊어지면 어떻게 됩니까?
FlexCache S3 NAS 버킷에 대한 S3 요청은 캐시 클러스터가 원본 클러스터에서 연결이 끊어진 경우 `503 Service Unavailable` 오류와 함께 실패합니다.

.FlexCache 이중성을 사용하여 S3 멀티파트 작업을 수행할 수 있습니까?
멀티파트 S3 작업이 제대로 작동하려면 기본 FlexCache 볼륨의 granular-data 필드가 'advanced'로 설정되어 있어야 합니다. 이 필드는 원본 볼륨에 설정된 값으로 설정됩니다.

.FlexCache 이중화 기능은 HTTP와 HTTPS 액세스를 모두 지원합니까?
예. 기본적으로 HTTPS가 필요합니다. 필요한 경우 S3 서비스에서 HTTP 액세스를 허용하도록 구성할 수 있습니다.
