---
permalink: volumes/change-maximum-number-files-allowed-concept.html 
sidebar: sidebar 
keywords: considerations, changing, maximum number of files, allowed, flexvol volume, maximum, files, file 
summary: FlexVol 볼륨에는 포함할 수 있는 최대 파일 수가 있습니다. 이 최대값을 변경할 수 있지만 이 값이 볼륨에 미치는 영향에 유의하십시오. 
---
= ONTAP 의 FlexVol 볼륨에 허용되는 기본 및 최대 파일 수
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexVol 볼륨에는 포함할 수 있는 기본 및 최대 파일 수가 있습니다.  데이터에 많은 수의 파일이 필요한 경우 볼륨에서 허용되는 사용자 표시 파일 수를 최대값까지 늘릴 수 있습니다.  계속 진행하기 전에 제한 사항과 주의사항을 이해해야 합니다.

볼륨에 포함될 수 있는 사용자가 볼 수 있는 파일의 수는 볼륨의 사용 가능한 inode 용량에 따라 결정됩니다.  inode는 파일 정보를 담고 있는 데이터 구조입니다.

ONTAP 새로 생성된 볼륨에 대해 사용 가능한 inode의 기본 및 최대 개수를 볼륨 크기에 따라 다음과 같이 자동으로 설정합니다.

[cols="2,2"]
|===
| 기본 inode 수 | 최대 inode 수 


| 볼륨 크기 32KB당 1개 | 볼륨 크기 4KB당 1개 
|===
볼륨의 크기가 관리자가 수동으로 늘리거나 ONTAP의 자동 크기 조정 기능을 사용하여 자동으로 늘어나면 ONTAP 필요한 경우 사용 가능한 inode의 수도 늘려 볼륨 크기 32KB당 최소 1개의 inode가 있도록 합니다. 이렇게 하여 볼륨 크기가 약 680GB에 도달할 때까지 계속합니다.

ONTAP 9.12.1 및 이전 버전에서는 새 볼륨을 생성하거나 기존 볼륨의 크기를 680GB 이상으로 조정해도 자동으로 추가 inode 용량이 생성되지 않습니다.  모든 크기의 볼륨에 대해 기본 개수보다 더 많은 파일이 필요한 경우 다음을 사용할 수 있습니다. `volume modify` 볼륨에 사용 가능한 inode 수를 최대치까지 늘리는 명령입니다.

ONTAP 9.13.1부터 새 볼륨을 생성하거나 기존 볼륨의 크기를 조정하면 볼륨이 680GB보다 크더라도 사용 가능한 inode의 기본 개수가 볼륨 공간 32KB당 1개의 inode로 설정됩니다.  이 비율은 볼륨이 2,040,109,451의 절대 inode 최대값에 도달할 때까지 지속됩니다.

사용 가능한 inode 수를 줄일 수도 있습니다.  이렇게 하면 inode에 할당된 공간의 양은 바뀌지 않지만, 공개 inode 파일이 사용할 수 있는 최대 공간의 양은 줄어듭니다.  inode에 공간이 할당된 후에는 해당 공간이 볼륨으로 반환되지 않습니다.  따라서 현재 할당된 inode 수보다 최대 inode 수를 낮추는 것은 불가능합니다.

.추가 정보
* xref:display-file-inode-usage-task.html[볼륨에 대한 파일 및 inode 사용을 확인합니다]
* link:++https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/FAQ_-_ONTAP_default_and_maximum_number_of_files_(inodes)++["지식 기반 문서: FAQ - ONTAP 기본 및 최대 파일 수(inode)"]

