---
permalink: volumes/commands-display-space-usage-reference.html 
sidebar: sidebar 
keywords: commands for, displaying, space, usage, information, display 
summary: 스토리지 Aggregate 및 볼륨 명령을 사용하여 Aggregate, 볼륨 및 해당 스냅샷에서 공간이 어떻게 사용되고 있는지 확인할 수 있습니다. 
---
= 공간 사용 정보를 표시하는 명령입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
및 `volume` 명령을 사용하여 `storage aggregate` Aggregate, 볼륨 및 해당 스냅샷에서 공간이 어떻게 사용되고 있는지 확인할 수 있습니다.

ONTAP 9.18.1부터 `storage aggregate show-space` 명령은 논리적 참조 용량 및 논리적 미참조 용량 보고 방식을 변경합니다. 논리적 참조 용량은 모든 객체의 참조된 블록과 조각화된 객체의 미참조 블록을 보고합니다. 논리적 미참조 용량은 전체 임계값을 초과하여 객체 삭제 및 조각 모음 대상이 되는 객체의 미참조 블록만 보고합니다.

예를 들어 ONTAP S3 및 StorageGRID에 대해 기본 애그리게이트 충만도 임계값 40%를 사용하는 경우 객체의 블록 중 60%가 참조되지 않아야 블록이 참조되지 않은 용량으로 보고됩니다.

ONTAP 9.18.1 이전 릴리스에서는 논리적 참조 용량이 모든 객체(전체 객체 및 조각화된 객체 모두)의 참조된 블록을 보고합니다. 논리적 미참조 용량은 모든 객체의 미참조 블록을 보고합니다.

[cols="2*"]
|===
| 정보를 표시하려면... | 이 명령 사용... 


 a| 
사용된 공간 및 사용 가능한 공간 비율, 스냅샷 예약 크기 및 기타 공간 사용 정보에 대한 세부 정보를 포함한 애그리게이트
 a| 
'스토리지 집계 쇼'

`storage aggregate show-space -fields snap-size-total,used-including-snapshot-reserve`



 a| 
디스크 및 RAID 그룹이 애그리게이트에서 사용하는 방법 및 RAID 상태
 a| 
'스토리지 집계 표시 상태'



 a| 
특정 스냅샷을 삭제할 경우 재확보되는 디스크 공간의 양입니다
 a| 
'볼륨 스냅샷 계산-재확보 가능'(고급)



 a| 
볼륨에서 사용하는 공간입니다
 a| 
`volume show -fields size,used,available,percent-used`

`volume show-space`



 a| 
포함하는 애그리게이트의 볼륨이 사용하는 공간 크기입니다
 a| 
볼륨 쇼 풋프린트

|===
.관련 정보
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+aggregate+show["스토리지 애그리게이트 보기"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-space.html["저장 집합 쇼 공간"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-status.html["스토리지 집계 표시 상태"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-compute-reclaimable.html["볼륨 스냅샷 계산 - 재확보 가능"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-show.html["볼륨 표시"^]

