---
permalink: volumes/commands-display-quotas-reference.html 
sidebar: sidebar 
keywords: commands for, display, displaying, information about, quotas 
summary: 명령을 사용하면 적용된 할당량과 리소스 사용량이 포함된 할당량 보고서를 표시하고, 할당량 상태 및 오류에 대한 정보를 표시하거나, 할당량 정책 및 할당량 규칙에 대한 정보를 표시할 수 있습니다. 
---
= 할당량에 대한 정보를 표시하기 위한 ONTAP 명령
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
명령을 사용하면 적용된 할당량과 리소스 사용량이 포함된 할당량 보고서를 표시하고, 할당량 상태 및 오류에 대한 정보를 표시하거나, 할당량 정책 및 할당량 규칙에 대한 정보를 표시할 수 있습니다.

다음 명령은 FlexVol 볼륨에서만 실행할 수 있습니다.

[cols="2*"]
|===
| 원하는 작업 | 이 명령 사용... 


 a| 
적용된 할당량에 대한 정보를 봅니다
 a| 
볼륨 할당량 보고서



 a| 
할당량 타겟의 리소스 사용량(디스크 공간 및 파일 수)을 봅니다
 a| 
볼륨 할당량 보고서



 a| 
파일에 쓸 수 있을 때 영향을 받는 할당량 제한을 확인합니다
 a| 
path 매개 변수가 있는 볼륨 할당량 보고서



 a| 
on, off, initializing 등의 할당상태를 표시합니다
 a| 
볼륨 할당량 표시



 a| 
할당량 메시지 로깅에 대한 정보를 봅니다
 a| 
logmsg 매개 변수가 있는 볼륨 할당량 표시



 a| 
할당량 초기화 및 크기 조정 중에 발생하는 오류를 봅니다
 a| 
인스턴스 매개 변수를 사용한 볼륨 할당량 표시



 a| 
할당량 정책에 대한 정보를 봅니다
 a| 
볼륨 할당량 정책이 표시됩니다



 a| 
할당량 규칙에 대한 정보를 봅니다
 a| 
볼륨 할당량 정책 규칙이 표시됩니다



 a| 
스토리지 가상 머신(SVM, 이전의 Vserver)에 할당된 할당량 정책의 이름을 봅니다.
 a| 
vserver show와 -instance 매개 변수를 함께 사용합니다

|===
에 대한 자세한 내용은 `volume quota` link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+quota["ONTAP 명령 참조입니다"^]을 참조하십시오.



== ONTAP volume quota policy rule show 및 volume quota report 명령은 언제 사용해야 합니까

두 명령 모두 할당량에 대한 정보를 표시하지만 볼륨 할당량 정책 규칙은 구성된 할당량 규칙을 빠르게 표시하고, 시간과 리소스를 더 많이 사용하는 볼륨 할당량 보고서 명령은 적용된 할당량과 리소스 사용량을 표시합니다.

'volume quota policy rule show' 명령은 다음과 같은 용도로 유용합니다.

* 할당량 규칙을 활성화하기 전에 구성을 확인하십시오
+
이 명령은 할당량이 초기화되었는지 또는 크기가 조정되었는지 여부에 관계없이 구성된 모든 할당량 규칙을 표시합니다.

* 시스템 리소스에 영향을 주지 않고 할당량 규칙을 빠르게 봅니다
+
이 명령은 디스크 및 파일 사용량을 표시하지 않으므로 할당량 보고서만큼 리소스를 많이 사용하지 않습니다.

* SVM에 할당되지 않은 할당량 정책에 할당량 규칙을 표시합니다.


에 대한 자세한 내용은 `volume quota policy rule show` link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-policy-rule-show.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

볼륨 할당량 보고서 명령은 다음과 같은 용도로 유용합니다.

* 파생 할당량을 비롯한 적용된 할당량을 봅니다
* 파생 할당량의 영향을 받는 대상을 포함하여 모든 할당량이 사용하는 디스크 공간 및 파일 수를 확인합니다
+
기본 할당량의 경우, 결과 파생 할당량에 대해 사용량이 추적되므로 사용량이 "0"으로 표시됩니다.

* 파일에 대한 쓰기가 허용되는 경우 어떤 할당량 제한이 영향을 미치는지 확인합니다
+
볼륨 할당량 보고서 명령에 '-path' 매개 변수를 추가합니다.



[NOTE]
====
할당량 보고서는 리소스를 많이 사용하는 작업입니다. 클러스터의 많은 FlexVol 볼륨에서 실행하는 경우 완료하는 데 오랜 시간이 걸릴 수 있습니다. 더 효율적인 방법은 SVM의 특정 볼륨에 대한 할당량 보고서를 보는 것입니다.

====
에 대한 자세한 내용은 `volume quota report` link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-report.html["ONTAP 명령 참조입니다"^]을 참조하십시오.
