---
permalink: volumes/control-io-performance-qos-task.html 
sidebar: sidebar 
keywords: control, monitor, i/o performance, flexvol volumes, using storage qos, qos, performance, throttle, flexvol, policy, policy group 
summary: 스토리지 QoS 정책 그룹을 통해 FlexVol 볼륨의 I/O 성능을 제어하여 워크로드를 관리할 수 있습니다. 
---
= 스토리지 QoS로 FlexVol volume I/O 성능을 제어 및 모니터링합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 QoS 정책 그룹에 볼륨을 할당하여 FlexVol 볼륨에 대한 입출력 성능을 제어할 수 있습니다. 입출력 성능을 제어하여 워크로드가 특정 성능 목표를 달성하도록 보장하고, 다른 워크로드에 부정적인 영향을 주는 워크로드를 조절할 수 있습니다.

.이 작업에 대해
정책 그룹은 최대 처리량 제한(예: 100MB/s)을 적용합니다. 최대 처리량을 지정하지 않고 정책 그룹을 생성할 수 있으므로 워크로드를 제어하기 전에 성능을 모니터링할 수 있습니다. 또한 선택적으로 최소 처리량 제한을 지정할 수 있습니다.

SVM, LUN 및 파일을 정책 그룹에 할당할 수도 있습니다.

정책 그룹에 볼륨을 할당하는 것에 대한 다음 요구 사항을 참고하십시오.

* 정책 그룹이 속한 SVM에서 볼륨을 포함해야 합니다.
+
정책 그룹을 생성할 때 SVM을 지정합니다.

* ONTAP 9.18.1부터 QoS 정책이 있는 SVM에 포함된 볼륨에 QoS 정책을 할당할 수 있습니다. 중첩된 QoS 정책을 사용하는 경우 가장 제한적인 정책이 적용됩니다.
* ONTAP 9.14.0부터 QoS 정책이 있는 볼륨에 포함된 qtree에 정책을 할당할 수 있습니다.


스토리지 QoS를 사용하는 방법에 대한 자세한 내용은 를 참조하십시오 link:../system-admin/index.html["시스템 관리 참조"].

.단계
. QoS policy-group create 명령을 사용하여 정책 그룹을 생성합니다.
. 정책 그룹에 볼륨을 할당하려면 'volume create' 명령 또는 '-qos-policy-group' 매개 변수와 함께 'volume modify' 명령을 사용하십시오.
. QoS 통계 명령어를 이용하여 성능 데이터를 확인할 수 있다.
. 필요한 경우 QoS policy-group modify 명령을 사용하여 정책 그룹의 최대 처리량 한도를 조정합니다.


.관련 정보
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=qos+policy-group["qos 정책 그룹"^]
* 링크: https://docs.netapp.com/us-en/ontap-cli/qos-policy-group-create.html [qos 정책 그룹 생성]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["볼륨 생성"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-modify.html["볼륨 수정"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=qos+statistics["QoS 통계"^]

