---
permalink: volumes/enable-temperature-sensitive-efficiency-concept.html 
sidebar: sidebar 
keywords: enable, temperature, sensitive, storage, efficiency, sequential packing 
summary: ONTAP 9.8에 도입된 이 경우, 일부 AFF 볼륨에서 온도에 민감한 스토리지 효율성이 자동으로 활성화되거나 기존 볼륨에서 수동으로 활성화됩니다. 
---
= ONTAP 온도 민감형 스토리지 효율성에 대해 알아보세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 볼륨의 데이터에 액세스하는 빈도를 평가하고 해당 빈도를 데이터에 적용된 압축 정도에 매핑하여 온도 민감형 스토리지 효율성(TSSE) 이점을 제공합니다.  자주 액세스되지 않는 콜드 데이터의 경우 더 큰 데이터 블록이 압축되고, 자주 액세스되고 더 자주 덮어쓰이는 핫 데이터의 경우 더 작은 데이터 블록이 압축되어 프로세스의 효율성이 높아집니다.

TSSE는 ONTAP 9.8에서 도입되었으며 새로 생성된 씬 프로비저닝 AFF 볼륨에서 자동으로 활성화됩니다. 기존의 씬 프로비저닝된 AFF 볼륨과 씬 프로비저닝된 비 AFF DP 볼륨에서 온도에 따른 스토리지 효율성 향상 기능을 활성화할 수 있습니다. TSSE는 고밀도 프로비저닝 볼륨에서 지원되지 않습니다.

다음 플랫폼에는 온도에 따른 저장 효율성이 적용되지 않습니다.

[cols="2"]
|===
| 플랫폼 | ONTAP 버전입니다 


 a| 
* AFF A1K 를 참조하십시오
* AFF A90 를 참조하십시오
* AFF A70 를 참조하십시오
* FAS90를 참조하십시오
* FAS70를 참조하십시오

| 9.15.1 이상 


 a| 
* AFF C80 를 참조하십시오
* AFF C60 를 참조하십시오
* AFF C30 를 참조하십시오
* AFF A50 를 참조하십시오
* AFF A30 를 참조하십시오

| 9.16.1 이상 
|===
이 플랫폼은 다음을 사용합니다.link:../concepts/builtin-storage-efficiency-concept.html["CPU 또는 전용 오프로드 프로세서 스토리지 효율성"] .  압축은 메인 CPU나 전용 오프로드 프로세서를 사용하여 수행되며 핫 데이터나 콜드 데이터에 기반하지 않습니다.


NOTE: 시간이 지남에 따라 볼륨에서 사용되는 공간의 양은 8K 적응형 압축에 비해 TSSE에서 더 두드러질 수 있습니다.  이러한 동작은 TSSE와 8K 적응형 압축 간의 아키텍처 차이로 인해 예상됩니다.

."기본" 및 "효율적인" 모드 도입
ONTAP 9.10.1부터 _default_and_efficient_볼륨 수준 스토리지 효율성 모드는 AFF 시스템에만 도입되었습니다. 두 가지 모드를 통해 파일 압축(기본값) 중에서 선택할 수 있으며, 새 AFF 볼륨을 생성할 때의 기본 모드인 파일 압축(기본값) 또는 온도에 민감한 스토리지 효율성(효율적) 중에서 선택할 수 있습니다. 이 방식은 자동 적응형 압축을 사용하여 자주 액세스하지 않는 콜드 데이터에 대해 압축 절약 효과를 높입니다.

ONTAP 9.10.1 이상으로 업그레이드할 때 볼륨에 현재 활성화된 압축 유형을 기준으로 기존 볼륨에 스토리지 효율성 모드가 할당됩니다. 업그레이드하는 동안 압축이 활성화된 볼륨에 기본 모드가 할당되고, 온도에 민감한 스토리지 효율성을 활성화한 볼륨에 효율적인 모드가 할당됩니다. 압축이 사용되지 않을 경우 스토리지 효율성 모드는 빈 상태로 유지됩니다.

ONTAP 9.10.1link:../volumes/set-efficiency-mode-task.html["온도에 민감한 스토리지 효율성을 명시적으로 설정해야 합니다"]을 사용하여 자동 적응형 압축을 활성화합니다. 하지만 AFF 플랫폼에서 데이터 컴팩션, 자동 중복제거 일정, 인라인 중복제거, 볼륨 간 인라인 중복제거, 볼륨 간 백그라운드 중복제거 등과 같은 기타 스토리지 효율성 기능은 기본 모드와 효율적인 모드 모두에서 기본적으로 사용됩니다.

FabricPool 지원 애그리게이트 및 모든 계층화 정책 유형에서 스토리지 효율성 모드(기본값 및 효율성)가 모두 지원됩니다.

.C-Series 플랫폼에서 온도에 민감한 스토리지 효율성을 지원합니다
온도에 민감한 스토리지 효율성(TSSE)은 AFF C-Series 플랫폼에서 기본적으로 활성화되며, 대상 플랫폼에 다음 릴리스가 설치된 상태에서 볼륨 이동 또는 SnapMirror 사용하여 TSSE가 활성화되지 않은 플랫폼에서 TSSE가 활성화된 C-Series 플랫폼으로 씬 프로비저닝된 볼륨을 마이그레이션할 때도 활성화됩니다.

* ONTAP 9.12.1P4 이상
* ONTAP 9.13.1 이상


자세한 내용은 을 link:../volumes/storage-efficiency-behavior-snapmirror-reference.html["볼륨 이동 및 SnapMirror 작업에 대한 스토리지 효율성 동작"]참조하십시오.

기존의 씬 프로비저닝 볼륨의 경우 온도에 민감한 스토리지 효율성이 자동으로 활성화되지 않습니다. 하지만 다음과 같이 설정할 수 있습니다. link:../volumes/change-efficiency-mode-task.html["스토리지 효율성 모드를 수정합니다"] 수동으로 효율 모드로 전환하세요.


NOTE: 스토리지 효율성 모드를 효율적으로 변경한 후에는 다시 변경할 수 없습니다.

.인접한 물리적 블록을 순차적으로 압축하여 스토리지 효율성 향상
ONTAP 9.13.1 을 시작으로, 온도에 민감한 스토리지 효율성이 인접한 물리적 블록을 순차적으로 압축하여 스토리지 효율성을 더욱 향상합니다. 온도에 민감한 스토리지 효율성을 사용하는 볼륨은 시스템을 ONTAP 9.13.1 로 업그레이드할 때 자동으로 순차적 패킹을 지원합니다. 순차적 패킹이 활성화된 후에는 다음을 수행해야 link:../volumes/run-efficiency-operations-manual-task.html["기존 데이터를 수동으로 다시 압축합니다"]합니다.
