---
permalink: volumes/logical-space-reporting-concept.html 
sidebar: sidebar 
keywords: what, logical, space, reporting, shows 
summary: 볼륨에 대한 논리적 공간 보고를 활성화하면 시스템의 총 공간 외에 사용된 논리적 공간과 사용 가능한 공간이 표시됩니다. 
---
= 논리적 공간 보고
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨에서 논리적 공간 보고를 활성화하면 시스템에서 볼륨의 총 공간 외에 논리적 사용 공간 및 사용 가능한 공간의 양을 표시할 수 있습니다. 또한 Linux 및 Windows 클라이언트 시스템의 사용자는 물리적 사용 공간과 물리적 사용 가능한 공간 대신 논리적 사용 공간 및 사용 가능한 공간을 확인할 수 있습니다.

정의:

* 물리적 공간은 볼륨에서 사용 가능하거나 사용되는 스토리지의 물리적 블록을 나타냅니다.
* 논리적 공간은 볼륨의 사용 가능한 공간을 나타냅니다.
* 사용된 논리적 공간은 물리적 공간과 함께 사용된 공간 및 구성된 스토리지 효율성 기능(예: 중복제거 및 압축)을 통한 절약입니다.


ONTAP 9.5부터 공간 보고와 함께 논리적 공간 적용을 활성화할 수 있습니다.

활성화된 경우 논리적 공간 보고는 'volume show' 명령을 사용하여 다음 매개 변수를 표시합니다.

[cols="25%,75%"]
|===
| 매개 변수 | 의미 


 a| 
논리적 사용
 a| 
지정된 논리적 사용 크기가 있는 볼륨 또는 볼륨에 대한 정보만 표시합니다. 이 값에는 물리적으로 사용된 공간과 함께 스토리지 효율성 기능으로 절약되는 모든 공간이 포함됩니다. 여기에는 스냅숏 예비 공간은 포함되지 않지만 스냅숏 유출이 고려됩니다.



 a| 
논리적-사용-AFS
 a| 
활성 파일 시스템에서 사용하는 지정된 논리적 크기를 가진 볼륨에만 정보를 표시합니다. 이 값은``-logical-used`` 스냅샷 예비 공간을 초과하는 스냅숏 유출 양의 값과 다릅니다.



 a| 
'-logical-available'(논리적-사용 가능)
 a| 
논리적 공간 보고만 활성화되면 물리적 가용 공간만 표시됩니다. 공간 보고와 적용이 모두 설정된 경우 스토리지 효율성 기능에 의해 사용 중인 공간을 고려하여 현재 사용 가능한 여유 공간의 양이 표시됩니다. 여기에는 스냅숏 예비 공간이 포함되지 않습니다.



 a| 
논리적-사용-퍼센트
 a| 
볼륨의 스냅숏 예비 공간을 제외하고 프로비저닝된 크기의 현재 값의 백분율을 표시합니다 `-logical-used`.

이 값에는 볼륨의 효율성 절감이 포함되므로 이 값은 100%보다 클 수 있습니다. `-logical-used-by-afs`  `-logical-used-by-afs`볼륨 값에는 사용된 공간으로 스냅숏 유출이 포함되지 않습니다.  `-physical-used`볼륨 값에는 사용된 공간으로 스냅숏 유출이 포함됩니다.



 a| 
중고
 a| 
사용자 데이터와 파일 시스템 메타데이터가 차지하는 공간의 크기를 표시합니다. 향후 쓰기를 위해 예약되는 공간과 애그리게이트 스토리지 효율성에 의해 절약되는 공간의 합계에 따라 공간과는 다릅니다 `physical-used`. 여기에는 스냅샷 오버플로(스냅샷이 스냅숏 예비 공간을 초과하는 공간)가 포함됩니다. 스냅숏 예비 공간은 포함되지 않습니다.

|===
CLI에서 논리 공간 보고를 활성화하면 System Manager에 논리 사용 공간(%) 및 논리 공간 값이 표시됩니다

클라이언트 시스템은 다음 시스템 디스플레이에 ""사용된"" 공간으로 표시되는 논리 공간을 확인합니다.

* Linux 시스템에서 * df * 출력
* Windows 시스템에서 Windows 탐색기를 사용하여 속성 아래의 공간 세부 정보를 표시합니다.


[NOTE]
====
논리적 공간 강제 적용 없이 논리 공간 보고를 사용하는 경우 클라이언트 시스템에 표시되는 총 용량이 프로비저닝된 공간보다 클 수 있습니다.

====