---
permalink: volumes/quota-resize-reinitialization.html 
sidebar: sidebar 
keywords: when to, use, resizing 
summary: 할당량 크기 조정은 할당량 초기화보다 빠르지만 제한이 있습니다. 
---
= ONTAP 할당량 크기 조정 및 재초기화에 대해 알아보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
할당량 크기 조정은 재초기화보다 빠르지만, 할당량에 특정 변경 사항을 적용하는 경우에는 전체 할당량 재초기화를 수행해야 합니다.



== ONTAP 할당량 조정

다음과 같은 할당량 규칙 변경 시 할당량 크기를 조정할 수 있습니다.

* 기존 할당량 변경.
+
예를 들어, 기존 할당량의 제한을 변경합니다.

* 기본 할당량 또는 기본 추적 할당량이 있는 할당량 타겟에 대한 할당량 추가
* 기본 할당량 또는 기본 추적 할당량 항목이 지정된 할당량을 삭제합니다.
* 개별 사용자 할당량을 하나의 다중 사용자 할당량으로 결합합니다.


[NOTE]
====
할당량을 광범위하게 변경한 후에는 전체 재초기화를 수행하여 모든 변경 사항이 적용되도록 해야 합니다.

====
[NOTE]
====
크기 조정 작업을 사용하여 모든 할당량 변경 사항을 통합할 수 없는 경우 ONTAP에서 경고를 표시합니다. 할당량 보고서를 통해 스토리지 시스템이 특정 사용자, 그룹 또는 qtree의 디스크 사용량을 추적하는지 확인할 수 있습니다. 할당량 보고서에 할당량이 표시되는 경우, 이는 스토리지 시스템이 디스크 공간과 할당량 대상이 소유한 파일 수를 추적하고 있음을 의미합니다.

====
.할당량 크기 조정을 통해 적용할 수 있는 할당량 변경 예시
일부 할당량 규칙 변경은 크기 조정을 통해 적용할 수 있습니다. 다음 할당량을 고려해 보십시오.

[listing]
----

#Quota Target type             disk  files thold sdisk sfile
#------------ ----             ----  ----- ----- ----- -----
*             user@/vol/vol2    50M   15K
*             group@/vol/vol2  750M   85K
*             tree@/vol/vol2      -     -
jdoe          user@/vol/vol2/  100M   75K
kbuck         user@/vol/vol2/  100M   75K
----
다음과 같이 변경한다고 가정합니다.

* 기본 사용자 대상의 파일 수를 늘립니다.
* 기본 사용자 할당량보다 더 많은 디스크 제한이 필요한 새 사용자 할당량인 Boris를 추가합니다.
* kbuck 사용자의 명시적 할당량 항목을 삭제합니다. 이제 새 사용자는 기본 할당량 제한만 필요합니다.


이러한 변경 사항으로 인해 다음과 같은 할당량이 발생합니다.

[listing]
----

#Quota Target type             disk  files thold sdisk sfile
#------------ ----             ----  ----- ----- ----- -----
*             user@/vol/vol2    50M   25K
*             group@/vol/vol2  750M   85K
*             tree@/vol/vol2      -     -
jdoe          user@/vol/vol2/  100M   75K
boris         user@/vol/vol2/  100M   75K
----
크기를 조정하면 이러한 모든 변경 사항이 활성화되지만 전체 할당량을 다시 초기화할 필요는 없습니다.



== ONTAP 할당량 재초기화

할당량의 크기를 조정하는 것이 더 빠르기는 하지만, 할당량에 대한 소규모의 변경 또는 광범위한 변경 작업을 수행하는 경우에는 전체 할당량을 다시 초기화해야 합니다.

다음과 같은 상황에서는 전체 할당량 재초기화가 필요합니다.

* 이전에 할당량이 없는 대상에 대해 할당량을 생성합니다(명시적 할당량이나 기본 할당량에서 파생된 할당량도 아님).
* Qtree의 보안 스타일을 UNIX에서 혼합 또는 NTFS로 변경합니다.
* Qtree의 보안 스타일을 혼합 또는 NTFS에서 UNIX로 변경할 수 있습니다.
* 사용자가 여러 명인 할당량 대상에서 사용자를 제거하거나 사용자가 이미 여러 명인 대상에 사용자를 추가합니다.
* 할당량을 광범위하게 변경합니다.


.초기화가 필요한 할당량 변경 사항의 예
볼륨에 3개의 Qtree가 포함된 볼륨이 있고 볼륨의 유일한 할당량이 3개의 명시적 트리 할당량이라고 가정합니다. 다음 사항을 변경하기로 결정합니다.

* 새 qtree를 추가하고 새 트리 할당량을 생성합니다.
* 볼륨에 대한 기본 사용자 할당량을 추가합니다.


이러한 변경 사항 모두 전체 할당량 초기화가 필요합니다. 크기를 조정해도 할당량은 적용되지 않습니다.
