---
permalink: volumes/space-display-quota-report-unix-client-concept.html 
sidebar: sidebar 
keywords: difference, space usage, displayed, quota report, unix client 
summary: FlexVol volume 또는 qtree의 할당량 보고서에 표시되는 사용된 디스크 공간의 값은 같은 볼륨 또는 qtree에 대해 UNIX 클라이언트에서 표시하는 값과 다를 수 있습니다. 
---
= ONTAP 할당량 보고서와 UNIX 클라이언트에서 표시되는 공간 사용량 차이
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexVol volume 또는 qtree의 할당량 보고서에 표시되는 사용된 디스크 공간의 값은 같은 볼륨 또는 qtree에 대해 UNIX 클라이언트에서 표시하는 값과 다를 수 있습니다. 이 값의 차이는 볼륨 또는 qtree의 데이터 블록을 계산하기 위한 다양한 방법 뒤에 할당량 보고서와 UNIX 명령이 있기 때문입니다.

예를 들어, 볼륨에 데이터가 기록되지 않은 빈 데이터 블록이 있는 파일이 포함된 경우 볼륨에 대한 할당량 보고서에서 공간 사용량을 보고하는 동안 빈 데이터 블록이 계산되지 않습니다. 그러나 볼륨이 UNIX 클라이언트에 마운트되어 있고 파일이 "ls" 명령의 출력으로 표시되면 빈 데이터 블록도 공간 사용량에 포함됩니다. 따라서 "ls" 명령은 할당량 보고서에 표시되는 공간 사용량과 비교하여 더 큰 파일 크기를 표시합니다.

마찬가지로 할당량 보고서에 표시되는 공간 사용량 값도 "df", "du"와 같은 UNIX 명령의 결과로 표시되는 값과 다를 수 있습니다.



[[how-a-quota-report-accounts-for-disk-space-and-file-usage]]
== 할당량 보고서에서 디스크 공간 및 파일 사용량을 확인하는 방법

FlexVol 볼륨 또는 qtree에 대해 할당량 보고서에 지정된 파일 수와 디스크 공간 크기는 볼륨 또는 qtree의 모든 inode에 해당하는 사용된 데이터 블록의 수에 따라 달라집니다.

블록 수에는 일반 및 스트림 파일에 사용되는 직접 및 간접 블록이 모두 포함됩니다. 디렉토리, ACL(액세스 제어 목록), 스트림 디렉토리 및 메타파일에 사용되는 블록이 할당량 보고서에 고려되지 않습니다. UNIX 스파스 파일의 경우 빈 데이터 블록이 할당량 보고서에 포함되지 않습니다.

할당량 하위 시스템은 사용자가 제어할 수 있는 파일 시스템 측면만 고려하고 포함하도록 설계되었습니다. 디렉토리, ACL 및 스냅샷 공간은 모두 할당량 계산에서 제외된 공간의 예입니다. 할당량은 보장이 아닌 제한을 적용하는 데 사용되며 활성 파일 시스템에서만 작동합니다. 할당량 계산에서는 특정 파일 시스템 구문을 계산하지 않으며 압축 또는 중복 제거와 같은 스토리지 효율성을 고려하지 않습니다.

이 절차에서 설명하는 명령에 대한 자세한 내용은 를 link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP 명령 참조입니다"^]참조하십시오.



[[disparity-between-ls-command-and-quota-report-for-space-usage]]
== ls 명령과 공간 사용에 대한 할당량 보고서 간의 불일치입니다

 `ls`명령을 사용하여 UNIX 클라이언트에 마운트된 FlexVol volume의 컨텐츠를 볼 때 출력에 표시되는 파일 크기는 파일의 데이터 블록 유형에 따라 볼륨에 대한 할당량 보고서에 표시되는 공간 사용량과 다를 수 있습니다.

ls 명령의 출력은 파일의 크기만 표시하고 파일에 사용되는 간접 블록은 포함하지 않습니다. 파일의 빈 블록도 명령의 출력에 포함됩니다.

따라서 파일에 빈 블록이 없는 경우 할당량 보고서에 간접 블록이 포함되기 때문에 "ls" 명령으로 표시되는 크기가 할당량 보고서에 지정된 디스크 사용량보다 작을 수 있습니다. 반대로, 파일에 빈 블록이 있으면 "ls" 명령으로 표시되는 크기가 할당량 보고서에 지정된 디스크 사용량보다 클 수 있습니다.

ls 명령의 출력은 파일의 크기만 표시하고 파일에 사용되는 간접 블록은 포함하지 않습니다. 파일의 빈 블록도 명령의 출력에 포함됩니다.

.ls 명령과 할당량 보고서에 사용된 공간 사용량 간의 차이 예
[%collapsible]
====
다음 할당량 보고서는 qtree Q1: 10MB의 한도를 보여줍니다.

[listing]
----

                                      ----Disk----  ----Files-----   Quota
  Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
  -------  --------  ------  -------  -----  -----  ------  ------   ---------
  vol1     q1          tree    user1   10MB  10MB        1       -   q1

...
----
다음 예와 같이 UNIX 클라이언트에서 "ls" 명령을 사용하여 동일한 qtree에 있는 파일의 크기가 할당량 제한을 초과할 수 있습니다.

[listing]
----
[user1@lin-sys1 q1]$ ls -lh
-rwxr-xr-x  1 user1 nfsuser  **27M** Apr 09  2013 file1
----
====
에 대한 자세한 내용은 `ls` link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=ls["ONTAP 명령 참조입니다"^]을 참조하십시오.



[[learn-how-the-df-command-accounts-for-file-size]]
== df 명령이 파일 크기를 어떻게 고려하는지 알아보십시오

'df' 명령에서 공간 사용을 보고하는 방식은 qtree가 포함된 볼륨에 대해 할당량을 설정하거나 해제할지 여부와 qtree 내의 할당량 사용을 추적할지 여부와 같은 두 가지 조건에 따라 달라집니다.

qtree가 포함된 볼륨에 대해 할당량을 설정하고 qtree 내의 할당량 사용을 추적할 때 df 명령으로 보고되는 공간 사용은 할당량 보고서에 지정된 값과 동일합니다. 이 경우 할당량 사용 시 디렉토리, ACL, 스트림 디렉토리 및 메타파일에서 사용되는 블록이 제외됩니다.

볼륨에 할당량이 설정되어 있지 않거나 qtree에 할당량 규칙이 구성되어 있지 않은 경우 보고된 공간 사용에는 볼륨 내의 다른 qtree를 포함하여 전체 볼륨에 대한 디렉토리, ACL, 스트림 디렉토리 및 메타파일에서 사용되는 블록이 포함됩니다. 이 경우 'df' 명령으로 보고되는 공간 사용량이 할당량을 추적할 때 보고되는 예상 값보다 큽니다.

할당량 사용을 추적할 qtree의 마운트 지점에서 df 명령을 실행하면 명령 출력에 할당량 보고서에 지정된 값과 동일한 공간 사용량이 표시됩니다. 대부분의 경우 트리 할당량 규칙에 하드 디스크 제한이 있는 경우 df 명령이 보고하는 총 크기는 디스크 제한과 같고 사용 가능한 공간은 할당량 디스크 제한과 할당량 사용 간의 차이입니다.

그러나 일부 경우 df 명령으로 보고되는 공간은 볼륨 전체에서 사용 가능한 공간과 동일할 수 있습니다. 이 문제는 qtree에 대해 구성된 하드 디스크 제한이 없을 때 발생합니다. ONTAP 9.9.1부터 볼륨 전체에서 사용 가능한 공간이 나머지 트리 할당량 공간보다 작을 때도 발생할 수 있습니다. 이러한 조건 중 하나가 발생할 경우 df 명령으로 보고되는 총 크기는 qtree 내에서 사용된 할당량과 FlexVol 볼륨에서 사용 가능한 공간을 더한 값과 같은 합성 숫자입니다.

[NOTE]
====
이 총 크기는 qtree 디스크 제한이나 볼륨 구성 크기가 아닙니다. 다른 qtree나 백그라운드 스토리지 효율성 활동에 대한 쓰기 활동에도 따라 달라질 수 있습니다.

====
.<code>df</code> 명령 및 할당량 보고서에서 계산된 공간 사용량 예시
[%collapsible]
====
다음 할당량 보고서는 qtree Alice의 경우 디스크 제한인 1GB, qtree Bob의 경우 2GB, qtree Project1의 경우 제한 없음을 보여줍니다.

[listing]
----
C1_vsim1::> quota report -vserver vs0
Vserver: vs0
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol2     alice     tree    1
                                  502.0MB    1GB       2       -   alice
vol2     bob       tree    2
                                   1003MB    2GB       2       -   bob
vol2     project1  tree    3
                                  200.8MB      -       2       -   project1
vol2               tree    *           0B      -       0       -   *
4 entries were displayed.
----
다음 예에서는 qtree Alice와 bob에 대한 'df' 명령의 출력이 할당량 보고서와 같은 사용된 공간 및 디스크 제한과 동일한 총 크기(100만 블록)를 보고합니다. 이는 qtree Alice와 bob에 대한 할당량 규칙에 정의된 디스크 제한이 있고 볼륨 가용 공간(1211MB)이 qtree Alice(523MB) 및 qtree bob(1045MB)에 대해 남아 있는 트리 할당량 공간보다 크기 때문입니다.

[listing]
----
linux-client1 [~]$ df -m /mnt/vol2/alice
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      1024   502       523  50% /mnt/vol2

linux-client1 [~]$ df -m /mnt/vol2/bob
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      2048  1004      1045  50% /mnt/vol2
----
다음 예제에서 qtree Project1의 df 명령 출력은 할당량 보고서와 같은 사용된 공간을 보고합니다. 그러나 총 크기는 총 1412MB의 용량을 제공하기 위해 qtree Project1(201 MB)의 할당량 사용에 전체(1211 MB)의 사용 가능한 공간을 추가하여 합성됩니다. 이는 Qtree Project1의 할당량 규칙에 디스크 제한이 없기 때문입니다.

[listing]
----
linux-client1 [~]$ df -m /mnt/vol2/project1
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      1412   201      1211  15% /mnt/vol2
----
다음 예제는 전체 볼륨에 대한 df 명령의 출력이 Project1과 동일한 사용 가능한 공간을 보고하는 방법을 보여줍니다.

[listing]
----
linux-client1 [~]$ df -m /mnt/vol2
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      2919  1709      1211  59% /mnt/vol2
----
====
이 절차에서 설명하는 명령에 대한 자세한 내용은 를 link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP 명령 참조입니다"^]참조하십시오.



[[disparity-betwee-du-command-and-quota-report-for-space-usage]]
== du 명령어와 할당량 보고서 간의 공간 사용량 불일치

du 명령을 실행하여 UNIX 클라이언트에 마운트된 qtree 또는 FlexVol 볼륨의 디스크 공간 사용량을 확인할 때 사용 값이 qtree 또는 볼륨에 대한 할당량 보고서에 표시되는 값보다 높을 수 있습니다.

du 명령의 출력에는 명령이 실행되는 디렉토리 레벨에서 시작되는 디렉토리 트리를 통해 모든 파일의 전체 공간 사용량이 포함됩니다. du 명령으로 표시되는 사용 값에는 디렉토리의 데이터 블록도 포함되므로 할당량 보고서에 표시되는 값보다 높습니다.

.du 명령과 할당량 보고서에서 확인된 공간 사용량 간의 차이입니다
[%collapsible]
====
다음 할당량 보고서는 qtree Q1: 10MB의 한도를 보여줍니다.

[listing]
----

                                      ----Disk----  ----Files-----   Quota
  Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
  -------  --------  ------  -------  -----  -----  ------  ------   ---------
  vol1     q1        tree    user1    10MB   10MB   1       -        q1

...
----
다음 예에서는 du 명령의 출력에서 디스크 공간 사용량이 할당량 제한을 초과하는 더 높은 값을 표시합니다.

[listing]
----
[user1@lin-sys1 q1]$ du -sh
**11M**     q1
----
====
이 절차에서 설명하는 명령에 대한 자세한 내용은 를 link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP 명령 참조입니다"^]참조하십시오.
