---
permalink: volumes/tree-quotas-concept.html 
sidebar: sidebar 
keywords: how, tree, quotas, work 
summary: 타겟 qtree의 크기가 될 수 있는 범위를 제한하기 위해 qtree를 타겟으로 사용하여 할당량을 생성할 수 있습니다. 이러한 할당량을 트리 할당량이라고도 합니다. 
---
= ONTAP 트리 할당량에 대해 알아보십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
타겟 qtree의 크기가 될 수 있는 범위를 제한하기 위해 qtree를 타겟으로 사용하여 할당량을 생성할 수 있습니다. 이러한 할당량을 _tree quotas_라고도 합니다.


NOTE: 특정 qtree에 대해 사용자 및 그룹 할당량을 생성할 수도 있습니다. 또한 FlexVol 볼륨의 할당량은 해당 볼륨에 포함된 qtree에 의해 상속되는 경우도 있습니다.

qtree에 할당량을 적용하면 디스크 파티션과 비슷한 결과가 발생합니다. 단, 할당량을 변경하여 언제든지 qtree의 최대 크기를 변경할 수 있다는 점이 다릅니다. 트리 할당량을 적용할 때 ONTAP은 소유자의 종류에 관계없이 qtree의 파일 수와 디스크 공간을 제한합니다. 루트 및 BUILTIN\Administrators 그룹의 구성원을 포함하여 어떤 사용자도 쓰기 작업으로 인해 트리 할당량이 초과되는 경우 qtree에 쓸 수 없습니다.

할당량의 크기는 사용 가능한 공간의 특정 양을 보장하지 않습니다. 할당량의 크기는 qtree에 사용할 수 있는 사용 가능한 공간보다 클 수 있습니다. 'volume quota report' 명령을 사용하여 qtree의 사용 가능한 실제 공간을 확인할 수 있습니다.

에 대한 자세한 내용은 `volume quota report` link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-report.html["ONTAP 명령 참조입니다"^]을 참조하십시오.



[[learn-how-ontap-user-and-group-quotas-work-with-qtrees]]
== ONTAP 사용자 및 그룹 할당량이 qtree와 어떻게 연동되는지 알아보십시오

트리 할당량은 qtree의 전체 크기를 제한합니다. 개별 사용자 또는 그룹이 전체 qtree를 사용하지 않도록 하려면 해당 qtree에 대한 사용자 또는 그룹 할당량을 지정합니다.

.qtree의 사용자 할당량 예시
[%collapsible]
====
다음과 같은 할당량 규칙이 있다고 가정합니다.

[listing]
----
cluster1::> volume quota policy rule show -vserver vs0 -volume vol1

Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   ""        ""      off          50MB        -       -        -       45MB
user   jsmith    ""      off          80MB        -       -        -       75MB
----
특정 사용자인 kjones가 vol1에 상주하는 중요한 qtree인 proj1에서 공간을 너무 많이 차지하고 있음을 알 수 있습니다. 다음 할당량 규칙을 추가하여 이 사용자의 공간을 제한할 수 있습니다.

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target "kjones" -qtree "proj1" -disk-limit 20m -threshold 15m

cluster1::> volume quota policy rule show -vserver vs0 -volume vol1

Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   ""        ""      off          50MB        -       -        -       45MB
user   jsmith    ""      off          80MB        -       -        -       75MB
user   kjones    proj1   off          20MB        -       -        -       15MB
----
====


[[learn-how-default-tree-quotas-on-an-ontap-flexvol-volume-create-derived-tree-quotas]]
== ONTAP FlexVol 볼륨의 기본 트리 할당량이 파생 트리 할당량을 생성하는 방법을 알아보십시오

FlexVol 볼륨에 기본 트리 할당량을 생성하면 해당 볼륨의 모든 qtree에 대해 해당 파생 트리 할당량이 자동으로 생성됩니다.

이러한 파생 트리 할당량은 기본 트리 할당량과 동일한 제한을 가집니다. 추가 할당량이 없는 경우 제한 사항은 다음과 같은 영향을 줍니다.

* 사용자는 전체 볼륨에 할당된 qtree의 공간을 사용할 수 있습니다(루트 또는 다른 qtree의 공간을 사용하여 볼륨 제한을 초과하지 않은 경우).
* 각 qtree는 전체 볼륨을 사용하도록 증가할 수 있습니다.


볼륨에 기본 트리 할당량이 있어도 볼륨에 추가된 모든 새 qtree에 계속 영향을 미칩니다. 새 qtree가 생성될 때마다 파생 트리 할당량도 생성됩니다.

모든 파생 할당량과 마찬가지로 파생된 트리 할당량에는 다음과 같은 동작이 표시됩니다.

* 타겟에 명시적 할당량이 없는 경우에만 생성됩니다.
* 할당량 보고서에는 표시되지만 명령을 사용하여 할당량 규칙을 표시할 때는 나타나지 않습니다 `volume quota policy rule show`. 에 대한 자세한 내용은 `volume quota policy rule show` link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-policy-rule-show.html["ONTAP 명령 참조입니다"^]을 참조하십시오.


.파생된 트리 할당량의 예
[%collapsible]
====
qtree 3개(proj1, proj2, proj3)의 볼륨이 있고 디스크 크기를 10GB로 제한하는 proj1 qtree의 명시적 할당량만 트리 할당량입니다. 볼륨에 기본 트리 할당량을 생성하고 볼륨에서 할당량을 다시 초기화하면 할당량 보고서에 네 개의 트리 할당량이 포함됩니다.

[listing]
----
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1     proj1     tree    1           0B   10GB       1       -   proj1
vol1               tree    *           0B   20GB       0       -   *
vol1     proj2     tree    2           0B   20GB       1       -   proj2
vol1     proj3     tree    3           0B   20GB       1       -   proj3
...
----
첫 번째 줄에는 proj1 qtree의 원래 명시적 할당량이 표시됩니다. 이 할당량은 변경되지 않습니다.

두 번째 줄에는 볼륨의 새 기본 트리 할당량이 표시됩니다. 별표(*) 할당량 지정자는 기본 할당량임을 나타냅니다. 이 할당량은 사용자가 생성한 할당량 규칙의 결과입니다.

마지막 두 줄에는 proj2 및 proj3 qtree에 대한 새로운 파생 트리 할당량이 표시됩니다. ONTAP는 볼륨에 대한 기본 트리 할당량의 결과로 이러한 할당량을 자동으로 생성했습니다. 이러한 파생된 트리 할당량은 볼륨의 기본 트리 할당량과 20GB 디스크 제한이 동일합니다. proj1 qtree에 명시적 할당량이 이미 있으므로 ONTAP에서는 proj1 qtree에 대해 파생 트리 할당량을 생성하지 않았습니다.

====


[[learn-how-default-user-quotas-on-an-ontap-flexvol-volume-affect-quotas-for-qtrees]]
== ONTAP FlexVol 볼륨의 기본 사용자 할당량이 qtree의 할당량에 어떤 영향을 미치는지 알아보세요

기본 사용자 할당량이 FlexVol 볼륨에 대해 정의된 경우 명시적 또는 파생 트리 할당량이 있는 해당 볼륨에 포함된 모든 qtree에 대해 기본 사용자 할당량이 자동으로 생성됩니다.

qtree의 기본 사용자 할당량이 이미 있는 경우, 볼륨에 대한 기본 사용자 할당량이 생성될 때 영향을 받지 않습니다.

Qtree에서 자동으로 생성된 기본 사용자 할당량은 볼륨에 대해 생성한 기본 사용자 할당량과 동일한 제한이 있습니다.

qtree에 대한 명시적 사용자 할당량이 관리자가 생성한 qtree의 기본 사용자 할당량을 재정의하는 것과 동일한 방식으로 자동으로 생성된 기본 사용자 할당량을 재정의합니다.
