---
permalink: encryption-at-rest/change-key-management-passphrase-task.html 
sidebar: sidebar 
keywords: changing, onboard, key, management, passphrase 
summary: 정기적으로 온보드 키 관리 암호를 변경하세요.  새로운 암호문구를 저장 시스템 외부의 안전한 장소에 보관하세요. 
---
= ONTAP 온보드 키 관리 암호문구 변경
:allow-uri-read: 


[role="lead"]
NetApp 온보드 키 관리 암호를 정기적으로 변경할 것을 권장합니다. 새로운 암호문구는 저장 시스템 외부의 안전한 장소에 저장해야 합니다.

.시작하기 전에
* 이 작업을 수행하려면 클러스터 또는 SVM 관리자여야 합니다.
* 이 작업에는 고급 권한이 필요합니다.
* MetroCluster 환경에서 로컬 클러스터에서 암호를 업데이트한 후 파트너 클러스터에서 암호 업데이트를 동기화합니다.


.단계
. 고급 권한 레벨로 변경:
+
세트 프리빌리지 고급

. 온보드 키 관리 암호를 변경합니다. 사용하는 명령은 실행 중인 ONTAP 버전에 따라 달라집니다.
+
[role="tabbed-block"]
====
.ONTAP 9.6 이상
--
보안 키 관리자 온보드 업데이트 암호문

--
.ONTAP 9.5 이하
--
보안 키 관리자 업데이트 암호문

--
====
. 32~256자 사이의 암호를 입력하세요. "`cc-mode`"의 경우 64~256자 사이의 암호를 입력하세요.
+
지정된 ""cc-mode"" 암호가 64자 미만이면 키 관리자 설정 작업에 암호 프롬프트가 다시 표시되기 전에 5초의 지연이 발생합니다.

. 암호 확인 프롬프트에서 암호를 다시 입력합니다.
. MetroCluster 구성을 사용하는 경우 파트너 클러스터에서 업데이트된 암호를 동기화하세요.
+
.. ONTAP 버전에 맞는 올바른 명령을 선택하여 파트너 클러스터에서 암호를 동기화하세요.
+
[role="tabbed-block"]
====
.ONTAP 9.6 이상
--
`security key-manager onboard sync`

--
.ONTAP 9.5 이하
--
*** ONTAP 9.5에서 다음을 실행합니다.
+
`security key-manager setup -sync-metrocluster-config`

*** ONTAP 9.4 및 이전 버전에서는 로컬 클러스터에서 암호를 업데이트한 후 20초간 기다린 후 파트너 클러스터에서 다음 명령을 실행합니다.
+
보안 키 관리자 설정



--
====
.. 메시지가 나타나면 새로운 암호를 입력하세요.
+
두 클러스터 모두에서 동일한 암호를 사용해야 합니다.





.작업을 마친 후
나중에 사용할 수 있도록 온보드 키 관리 암호를 저장 시스템 외부의 안전한 위치에 복사합니다.

온보드 키 관리 암호를 변경할 때마다 키 관리 정보를 수동으로 백업하세요.

.관련 정보
* link:backup-key-management-information-manual-task.html["온보드 키 관리 정보를 수동으로 백업합니다"]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-update-passphrase.html["보안 키 관리자 온보드 업데이트 암호 구문"^]

