---
permalink: encryption-at-rest/enable-onboard-key-management-96-later-nse-task.html 
sidebar: sidebar 
keywords: enabling, onboard key management, ontap 9.6, later 
summary: Onboard Key Manager를 사용하여 클러스터가 암호화된 데이터에 액세스하는 데 사용하는 키를 보호할 수 있습니다. 암호화된 볼륨 또는 자체 암호화 디스크에 액세스하는 각 클러스터에서 Onboard Key Manager를 활성화해야 합니다. 
---
= ONTAP 9.6 이상에서 온보드 키 관리를 활성화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Onboard Key Manager를 사용하여 FIPS 드라이브 또는 SED에 대한 클러스터 노드를 인증할 수 있습니다. Onboard Key Manager는 데이터와 동일한 스토리지 시스템의 노드에 인증 키를 제공하는 기본 제공 도구입니다. Onboard Key Manager는 FIPS-140-2 레벨 1을 준수합니다.

Onboard Key Manager를 사용하여 클러스터가 암호화된 데이터에 액세스하는 데 사용하는 키를 보호할 수 있습니다. 암호화된 볼륨 또는 자체 암호화 디스크에 액세스하는 각 클러스터에서 Onboard Key Manager를 활성화해야 합니다.

.이 작업에 대해
클러스터에 노드를 추가할 때마다 보안 키 관리자 온보드 활성화 명령을 실행해야 합니다. MetroCluster 구성에서는 먼저 로컬 클러스터에서 보안 키 관리자 온보드 활성화를 실행한 다음 원격 클러스터에서 동일한 암호를 사용하여 보안 키 관리자 온보드 동기화를 실행해야 합니다.

자세히 알아보세요 `security key-manager onboard enable` 그리고 `security key-manager onboard sync` 에서link:https://docs.netapp.com/us-en/ontap-cli//security-key-manager-onboard-enable.html["ONTAP 명령 참조입니다"^] .

기본적으로 노드를 재부팅할 때는 키 관리자 암호를 입력할 필요가 없습니다. MetroCluster를 제외하고, 사용자가 재부팅 후 암호문을 입력하도록 'cc-mode-enabled=yes' 옵션을 사용할 수 있습니다.

[NOTE]
====
Common Criteria 모드('cc-mode-enabled=yes')에서 Onboard Key Manager를 활성화하면 다음과 같은 방식으로 시스템 동작이 변경됩니다.

* 시스템은 Common Criteria 모드에서 작동 중일 때 연속 실패한 클러스터 암호 시도를 모니터링합니다.
+
NSE(NetApp 스토리지 암호화)가 활성화되어 있고 부팅 시 올바른 클러스터 암호를 입력하지 않으면 시스템이 드라이브를 인증할 수 없고 자동으로 재부팅됩니다. 이 문제를 해결하려면 부팅 프롬프트에서 올바른 클러스터 암호를 입력해야 합니다. 시스템이 부팅되면 24시간 동안 클러스터 암호를 매개 변수로 요구하는 명령에 대해 최대 5회 연속 클러스터 암호를 올바르게 입력할 수 있습니다. 제한에 도달한 경우(예: 클러스터 암호를 5회 연속으로 올바르게 입력하지 않은 경우) 24시간 제한 시간이 경과할 때까지 기다리거나 노드를 재부팅하여 제한을 재설정해야 합니다.

* 시스템 이미지 업데이트는 NetApp RSA-3072 코드 서명 인증서와 SHA-384 코드 서명 다이제스트를 함께 사용하여 일반적인 NetApp RSA-2048 코드 서명 인증서와 SHA-256 코드 서명 다이제스트 대신 이미지 무결성을 확인합니다.
+
업그레이드 명령은 다양한 디지털 서명을 검사하여 이미지 내용이 변경되거나 손상되지 않았는지 확인합니다.  검증이 성공하면 이미지 업데이트는 다음 단계로 진행됩니다.  검증이 실패하면 이미지 업데이트가 실패합니다.  자세히 알아보세요 `cluster image` 에서link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=cluster+image["ONTAP 명령 참조입니다"^] .



====

NOTE: Onboard Key Manager는 휘발성 메모리에 키를 저장합니다. 시스템을 재부팅하거나 정지하면 휘발성 메모리 내용이 지워집니다. 정상적인 작동 조건에서는 시스템을 정지하면 30초 이내에 휘발성 메모리 콘텐츠가 지워집니다.

.시작하기 전에
* NSE를 외부 키 관리(KMIP) 서버와 함께 사용할 경우 외부 키 관리자 데이터베이스를 삭제해야 합니다.
+
link:delete-key-management-database-task.html["외부 키 관리에서 온보드 키 관리로 전환"]

* 이 작업을 수행하려면 클러스터 관리자여야 합니다.
* Onboard Key Manager를 구성하기 전에 MetroCluster 환경을 구성해야 합니다.


.단계
. 키 관리자 설정 명령을 시작합니다.
+
'보안 키 관리자 온보드 활성화-cc-모드 사용 예|아니오'

+

NOTE:  `cc-mode-enabled=yes`재부팅 후 사용자가 키 관리자 암호를 입력하도록 요구하도록 설정합니다.  `- cc-mode-enabled`MetroCluster 구성에서는 옵션이 지원되지 않습니다.  `security key-manager onboard enable`명령이 `security key-manager setup` 명령을 대체합니다.

+
다음 예제에서는 재부팅할 때마다 암호를 입력할 필요 없이 키 관리자 설치 명령을 cluster1에서 시작합니다.

. 32~256자 사이의 암호를 입력하세요. "`cc-mode`"의 경우 64~256자 사이의 암호를 입력하세요.
+

NOTE: 지정된 ""cc-mode"" 암호가 64자 미만이면 키 관리자 설정 작업에 암호 프롬프트가 다시 표시되기 전에 5초의 지연이 발생합니다.

. 암호 확인 프롬프트에서 암호를 다시 입력합니다.
. 시스템이 인증 키를 생성하는지 확인하세요.
+
'보안 키 관리자 키 쿼리 노드

+

NOTE:  `security key-manager key query`명령이 `security key-manager query key` 명령을 대체합니다.

+
에 대한 자세한 내용은 `security key-manager key query` link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-query.html["ONTAP 명령 참조입니다"^]을 참조하십시오.



.작업을 마친 후
나중에 사용할 수 있도록 암호를 스토리지 시스템 외부의 안전한 위치에 복사합니다.

시스템은 클러스터의 복제된 데이터베이스(RDB)에 주요 관리 정보를 자동으로 백업합니다.  재해 복구를 위해 이 정보를 수동으로 백업해야 합니다.

.관련 정보
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=cluster+image["클러스터 이미지 명령"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-external-enable.html["보안 키 관리자 외부 활성화"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-query.html["보안 키 관리자 키 쿼리"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-enable.html["보안 키 관리자 온보드 활성화"^]
* link:delete-key-management-database-task.html["외부 키 관리에서 온보드 키 관리로 전환"]

