---
permalink: encryption-at-rest/modify-external-key-server-96-later-task.html 
sidebar: sidebar 
keywords: modifying, external key management, server, properties 
summary: ONTAP 9.6부터 보안 키 관리자 외부 수정 서버 명령을 사용하여 외부 키 관리 서버의 I/O 시간 초과 및 사용자 이름을 변경할 수 있습니다. 
---
= ONTAP 외부 키 관리 서버 속성 수정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.6부터, 외부 키 관리 서버의 I/O 제한 시간 및 사용자 이름을 변경하기 위해 'Security key-manager external modify-server' 명령어를 사용할 수 있다.

.시작하기 전에
* 이 작업을 수행하려면 클러스터 또는 SVM 관리자여야 합니다.
* 이 작업에는 고급 권한이 필요합니다.
* MetroCluster 환경에서는 관리 SVM을 위해 두 클러스터 모두에서 이러한 단계를 반복해야 합니다.


.단계
. 스토리지 시스템에서 고급 권한 레벨로 변경합니다.
+
세트 프리빌리지 고급

. 클러스터의 외부 키 관리자 서버 속성 수정:
+
`security key-manager external modify-server -vserver admin_SVM -key-server host_name|IP_address:port,... -timeout 0...60 -username user_name`

+
[NOTE]
====
** 타임아웃 값은 KMIP 서버와의 연결을 설정하는 데 걸리는 시간(초)입니다. 0을 지정하면 타임아웃이 없으므로 연결 요청은 무기한 대기할 수 있습니다. 1~60 사이의 값을 지정하면 지정된 시간(초) 내에 KMIP 키 서버에 연결할 수 없는 경우 연결 요청이 타임아웃됩니다.
** 사용자 이름을 변경하면 새 비밀번호를 입력하라는 메시지가 표시됩니다.
** 클러스터 로그인 프롬프트에서 해당 명령을 실행하면  `_admin_SVM_`기본적으로 현재 클러스터의 관리자 SVM이 사용됩니다. 외부 키 관리자 서버 속성을 수정하려면 클러스터 관리자여야 합니다.


====
+
다음 명령을 실행하면 기본 포트 5696에서 수신 대기하는 'cluster1' 외부 키 관리 서버의 시간 초과 값이 45초로 변경됩니다.

+
[listing]
----
clusterl::> security key-manager external modify-server -vserver cluster1 -key-server ks1.local -timeout 45
----
. SVM에 대한 외부 키 관리자 서버 속성을 수정합니다.
+
`security key-manager external modify-server -vserver SVM -key-server host_name|IP_address:port,... -timeout 0...60 -username user_name`

+
[NOTE]
====
** 타임아웃 값은 KMIP 서버와의 연결을 설정하는 데 걸리는 시간(초)입니다. 0을 지정하면 타임아웃이 없으므로 연결 요청은 무기한 대기할 수 있습니다. 1~60 사이의 값을 지정하면 지정된 시간(초) 내에 KMIP 키 서버에 연결할 수 없는 경우 연결 요청이 타임아웃됩니다.
** 사용자 이름을 변경하면 새 비밀번호를 입력하라는 메시지가 표시됩니다.
** SVM 로그인 프롬프트에서 해당 명령을 실행하면  `_SVM_`기본적으로 현재 SVM이 사용됩니다. 외부 키 관리자 서버 속성을 수정하려면 클러스터 또는 SVM 관리자여야 합니다.


====
+
다음 명령을 실행하면 기본 포트 5696에서 수신 대기 중인 'vm1' 외부 키 관리 서버의 사용자 이름과 암호가 변경됩니다.

+
[listing]
----
svml::> security key-manager external modify-server -vserver svm11 -key-server ks1.local -username svm1user
Enter the password:
Reenter the password:
----
. 추가 SVM에 대해 마지막 단계를 반복합니다.


.관련 정보
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-external-modify-server.html["보안 키 관리자 외부 수정 서버"^]

