---
permalink: encryption-at-rest/replace-self-encrypting-disk-task.html 
sidebar: sidebar 
keywords: replacing, fips drive, sed 
summary: 일반 디스크를 교체하는 것과 동일한 방법으로 FIPS 드라이브 또는 SED를 교체할 수 있습니다. 새 데이터 인증 키를 교체 드라이브에 할당하십시오. FIPS 드라이브의 경우 새 FIPS 140-2 인증 키를 할당할 수도 있습니다. 
---
= ONTAP에서 FIPS 드라이브 또는 SED를 교체합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
일반 디스크를 교체하는 것과 동일한 방법으로 FIPS 드라이브 또는 SED를 교체할 수 있습니다. 새 데이터 인증 키를 교체 드라이브에 할당하십시오. FIPS 드라이브의 경우 새 FIPS 140-2 인증 키를 할당할 수도 있습니다.


NOTE: HA 쌍이  https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html["SAS 또는 NVMe 드라이브(SED, NSE, FIPS) 암호화"]을(를) 사용하는 경우 시스템 초기화(부팅 옵션 4 또는 9) 전에 HA 쌍 내의 모든 드라이브에 대해  https://docs.netapp.com/us-en/ontap/encryption-at-rest/return-seds-unprotected-mode-task.html["FIPS 드라이브 또는 SED를 보호되지 않는 모드로 되돌리는 중입니다"] 항목의 지침을 따라야 합니다. 이를 따르지 않으면 드라이브 용도 변경 시 향후 데이터 손실이 발생할 수 있습니다.

.시작하기 전에
* 드라이브에서 사용하는 인증 키의 키 ID를 알아야 합니다.
* 이 작업을 수행하려면 클러스터 관리자여야 합니다.


.단계
. 디스크가 실패로 표시되어 있는지 확인합니다.
+
스토리지 디스크 고장

+
에 대한 자세한 내용은 `storage disk show` link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-show.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

+
[listing]
----
cluster1::> storage disk show -broken
Original Owner: node1
  Checksum Compatibility: block
                                                Drawer                              Usable Physical
    Disk            Outage Reason  HA Shelf Bay  /Slot Chan   Pool    Type    RPM     Size     Size Model
    --------------- ------------- --- ----- --- ------ ---- ------ ------- ------ -------- -------- ----------------
    1.0.12          admin failed   0a     0  12   -/-     A FAILED SSD-NVM      -   1.75TB   1.75TB X4024S173A1T9NTE

Original Owner: node2
  Checksum Compatibility: block
                                                Drawer                              Usable Physical
    Disk            Outage Reason  HA Shelf Bay  /Slot Chan   Pool    Type    RPM     Size     Size Model
    --------------- ------------- --- ----- --- ------ ---- ------ ------- ------ -------- -------- ----------------
    1.0.13          admin failed   0b     0  13   -/-     B FAILED SSD-NVM      -   1.75TB   1.75TB X4024S173A1T9NTF

2 entries were displayed.
[...]
----
. 디스크 쉘프 모델의 하드웨어 가이드에 나와 있는 지침에 따라 장애가 발생한 디스크를 제거하고 새 FIPS 드라이브 또는 SED로 교체합니다.
. 새로 교체한 디스크의 소유권을 할당합니다.
+
'Storage disk assign-disk disk_name-owner node'

+
에 대한 자세한 내용은 `storage disk assign` link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-assign.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

+
[listing]
----
cluster1::> storage disk assign -disk 2.1.1 -owner cluster1-01
----
. 새 디스크가 할당되었는지 확인합니다.
+
스토리지 암호화 디스크 표시

+
에 대한 자세한 내용은 `storage encryption disk show` link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data <id_value>
0.0.1   data <id_value>
1.10.0  data <id_value>
1.10.1  data <id_value>
2.1.1   open 0x0
[...]
----
. 데이터 인증 키를 FIPS 드라이브 또는 SED에 할당합니다.
+
link:assign-authentication-keys-seds-external-task.html["FIPS 드라이브 또는 SED(외부 키 관리)에 데이터 인증 키 할당"]

. 필요한 경우 FIPS 140-2 인증 키를 FIPS 드라이브에 할당합니다.
+
link:assign-fips-140-2-authentication-key-task.html["FIPS 140-2 인증 키를 FIPS 드라이브에 할당"]



.관련 정보
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-assign.html["저장 디스크 할당"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-show.html["저장 디스크 표시"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["저장 암호화 디스크 표시"^]

