---
sidebar: sidebar 
permalink: s3-snapshots/list-restore-s3-snapshot.html 
keywords: s3 snapshots, list, restore, browse S3 snapshots 
summary: ONTAP S3 스냅샷 기능을 사용하면 S3 클라이언트에서 버킷의 S3 스냅샷 콘텐츠를 확인, 탐색 및 복원할 수 있습니다. 
---
= ONTAP S3 스냅샷을 보고 복원합니다
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 9.16.1부터 S3 클라이언트의 버킷에 대한 S3 스냅샷 데이터를 보고 찾아볼 수 있습니다.  ONTAP 9.18.1부터 ONTAP CLI를 사용하여 S3 스냅샷 버킷에 기본적으로 액세스할 수 있습니다.  또한 S3 스냅샷에서 S3 클라이언트의 단일 객체, 객체 세트 또는 전체 버킷을 복원할 수 있습니다.

.시작하기 전에
* ONTAP CLI에서 버킷 스냅샷 복원 작업을 기본적으로 수행하려면 클러스터의 모든 노드에서 ONTAP 9.18.1 이상이 실행되어야 합니다.  ONTAP 9.18.1부터 S3 브라우저는 더 이상 필요하지 않지만 작업은 계속 지원됩니다.
* 주어진 버킷에 대해 한 번에 하나의 스냅샷 복원 작업만 허용됩니다.


.이 작업에 대해
ONTAP 9.16.1부터 ONTAP S3 스냅샷 기능은 수동 및 예약된 스냅샷 생성 및 삭제, S3 버킷에 대한 스냅샷 정책, S3 클라이언트 기반 스냅샷 검색을 포함하여 ONTAP S3 버킷에 대한 기본 스냅샷 기능을 제공합니다.

ONTAP 9.18.1부터 네이티브 ONTAP 스냅샷 복원에 대한 지원이 추가되어 ONTAP 관리자가 S3 브라우저를 사용하지 않고도 특정 시점 복원 기능을 사용할 수 있습니다.  스냅샷에는 현재 버킷 버전만 캡처됩니다.  버전 기록은 캡처되지 않으며 S3 스냅샷 복원 작업으로 복원되지 않습니다.



== S3 스냅샷 나열 및 보기

S3 스냅샷 세부 정보를 보고, 비교하고, 오류를 식별할 수 있습니다. ONTAP CLI를 사용하면 S3 버킷에서 생성된 모든 스냅샷을 나열할 수 있습니다.

.단계
. S3 스냅샷 목록:
+
[listing]
----
vserver object-store-server bucket snapshot show
----
+
클러스터의 모든 버킷에 대해 생성된 S3 스냅샷의 스냅샷 이름, 스토리지 VM, 버킷, 생성 시간 및 인스턴스 UUID를 볼 수 있습니다.

. 버킷 이름을 지정하여 해당 버킷에 대해 생성된 모든 S3 스냅샷의 이름, 생성 시간, 인스턴스 UUID를 볼 수도 있습니다.
+
[listing]
----
vserver object-store-server bucket snapshot show -vserver <svm_name> -bucket <bucket_name>
----




== S3 스냅샷 콘텐츠를 찾아봅니다

환경에서 장애나 문제가 발견되면 S3 버킷 스냅샷의 콘텐츠를 탐색하여 오류를 식별할 수 있습니다. 또한 S3 스냅샷을 탐색하여 오류 없는 콘텐츠를 복원할 수도 있습니다.

S3 스냅샷은 S3 클라이언트에 스냅샷 버킷으로 제공됩니다.  스냅샷 버킷 이름은 다음과 같이 형식화됩니다. `<base_bucket_name>-s3snap-<snapshot_name>` .  다음을 사용하여 스토리지 VM의 모든 스냅샷 버킷을 볼 수 있습니다. `ListBuckets` S3 API 작업.

S3 스냅샷 버킷은 기본 버킷의 액세스 정책을 상속받으며 읽기 전용 작업만 지원합니다.  삭제 및 쓰기 기반 작업은 금지됩니다.  기본 버킷에 액세스할 수 있는 권한이 있는 경우 S3 스냅샷 버킷에서 다음과 같은 읽기 전용 S3 API 작업을 수행할 수도 있습니다. `HeadObject` , `GetObject` , `GetObjectTagging` , `ListObjects` , `ListObjectVersions` , `GetObjectAcl` , 그리고 `CopyObject` .


NOTE: 이 `CopyObject` 작업은 S3 스냅샷 버킷이 소스 버킷의 스냅샷인 경우에만 지원되며, 스냅샷의 스토리지 타겟인 경우에는 지원되지 않습니다.

이러한 작업에 대한 자세한 내용은 을 link:../s3-config/ontap-s3-supported-actions-reference.html["ONTAP S3가 지원되는 작업"]참조하십시오.



== ONTAP 사용하여 S3 스냅샷에서 버킷 복원

ONTAP 9.18.1부터 ONTAP CLI를 사용하여 ONTAP S3 스냅샷을 사용하여 전체 버킷을 복원할 수 있습니다.  선택한 스냅샷이 생성된 시점에 존재했던 버킷 버전만 복원할 수 있습니다.

.단계
. 버킷을 복원하는 데 사용할 스냅샷을 식별하세요.
+
[listing]
----
vserver object-store-server bucket snapshot show
----
. 버킷을 복원합니다.
+
[listing]
----
vserver object-store-server bucket snapshot restore start -vserver <storage VM name> -bucket <bucket name> -snapshot <snapshot name>
----




== S3 클라이언트를 사용하여 S3 버킷 스냅샷에서 데이터 복원

ONTAP 에서 전체 버킷을 복원하는 것 외에도 S3cmd나 S3 Browser와 같은 S3 클라이언트를 사용하여 S3 스냅샷에서 단일 개체, 개체 세트 또는 전체 버킷을 복원할 수도 있습니다.

link:index.html#snapshots-on-versioned-and-non-versioned-buckets["버전이 지정된 스냅샷과 버전이 지정되지 않은 스냅샷에 대해 자세히 알아보세요."]

다음을 사용하여 전체 버킷, 특정 접두사가 있는 개체 또는 단일 개체를 복원할 수 있습니다. `aws s3 cp` 명령.

.단계
. 기본 S3 버킷의 스냅샷을 생성합니다.
+
[source, cli]
----
vserver object-store-server bucket snapshot create -vserver <svm_name> -bucket <base_bucket_name> -snapshot <snapshot_name>
----
. 스냅샷을 사용하여 기본 버킷을 복원합니다.
+
** 전체 버킷을 복원합니다. 스냅샷 버킷 이름을 형식으로 `<base_bucket_name>-s3snap-<snapshot_name>` 사용합니다.
+
[source, cli]
----
aws --endpoint http://<IP> s3 cp s3://<snapshot-bucket-name> s3://<base-bucket>  --recursive
----
** 다음 접두사를 사용하여 디렉터리의 개체를 `dir1` 복원합니다.
+
[source, cli]
----
aws --endpoint http://<IP> s3 cp s3://<snapshot-bucket-name>/dir1 s3://<base_bucket_name>/dir1 --recursive
----
** 이름이 인 단일 개체 복원 `web.py`:
+
[source, cli]
----
aws --endpoint http://<IP> s3 cp s3:// <snapshot-bucket-name>/web.py s3://<base_bucket_name>/web.py
----



