---
permalink: s3-multiprotocol/nas-data-requirements-client-access-reference.html 
sidebar: sidebar 
keywords: s3, mapping, directory, access, configuration, object, nas, bucket 
summary: S3 액세스를 위해 NAS 파일 및 디렉토리를 매핑하면 일부 표준 NAS 동작이 변경된다는 것을 이해하는 것이 중요합니다. 
---
= ONTAP S3 클라이언트 액세스를 위한 NAS 데이터 요구 사항에 대해 알아보세요.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 액세스를 위해 NAS 파일 및 디렉토리를 매핑할 때 몇 가지 고유한 비호환성이 있다는 것을 이해하는 것이 중요합니다. S3 NAS 버킷을 사용하여 NAS 파일 계층을 서비스하기 전에 NAS 파일 계층을 조정해야 할 수 있습니다.

S3 NAS 버킷은 S3 버킷 구문을 사용하여 해당 디렉토리를 매핑함으로써 NAS 디렉토리에 대한 S3 액세스를 제공하며 디렉토리 트리의 파일은 오브젝트로 표시됩니다. 오브젝트 이름은 S3 버킷 구성에 지정된 디렉토리를 기준으로 파일의 슬래시로 구분된 경로 이름입니다.

이 매핑에서는 S3 NAS 버킷을 사용하여 파일 및 디렉토리를 제공할 경우 다음과 같은 몇 가지 요구사항이 발생합니다.

* S3 이름은 1024바이트로 제한되므로 S3를 사용하면 경로 이름이 더 긴 파일에 액세스할 수 없습니다.
* 파일 및 디렉터리 이름은 255자로 제한되므로 개체 이름은 255자 이하의 연속된 비슬래시('/') 문자를 사용할 수 없습니다
* 백슬래시('\') 문자로 구분된 SMB 경로 이름은 S3에 슬래시('/') 문자를 포함하는 객체 이름으로 표시됩니다.
* 일부 합법적인 S3 객체 이름 쌍은 매핑된 NAS 디렉토리 트리에서 공존할 수 없습니다. 예를 들어, 합법적인 S3 객체 이름인 "part1/part2"와 "part1/part2/part3"은 NAS 디렉토리 트리에 동시에 존재할 수 없는 파일에 매핑됩니다. "part1/part2"는 첫 번째 이름에서는 파일이고 다른 이름에서는 디렉토리이기 때문입니다.
+
** "part1/part2"가 기존 파일인 경우 S3에서 "part1/part2/part3"을 생성하는 데 실패합니다.
** "part1/part2/part3"이 기존 파일인 경우 S3에서 "part1/part2"를 생성하거나 삭제하면 실패합니다.
** 기존 오브젝트의 이름과 일치하는 S3 오브젝트 생성은 NAS에 있지만 정확히 일치해야 하는 기존 오브젝트(버전이 지정되지 않은 버킷)를 대체합니다. 위의 예제에서는 이름이 충돌하는 동안 이름이 일치하지 않으므로 기존 개체를 제거하지 않습니다.




객체 저장소는 매우 많은 수의 임의의 이름을 지원하도록 설계되었지만, NAS 디렉토리 구조는 매우 많은 수의 이름이 하나의 디렉토리에 저장되면 성능 문제가 발생할 수 있습니다. 특히, 슬래시('/') 문자가 없는 이름은 모두 NAS 매핑의 루트 디렉토리에 배치됩니다. "NAS 친화적"이지 않은 이름을 광범위하게 사용하는 애플리케이션은 NAS 매핑보다는 실제 객체 저장소 버킷에 호스팅하는 것이 더 좋습니다.
