---
settings:
  name: ONTAP 9
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  search: ontap, ontap-metrocluster, ontap-sm-classic, ontap-fli, ontap-flexarray,
    ontap-automation, ontap-cli-9121
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,fr-fr,de-de
sidebar:
  entries:
  - title: ONTAP 문서
    url: "/index.html"
  - title: 릴리즈 노트
    url: "/release-notes.html"
  - title: System Manager와 BlueXP의 통합
    url: "/sysmgr-integration-bluexp-concept.html"
  - section: introduction-concepts
  - section: setup-upgrade
  - section: cluster-admin
  - section: volume-admin
  - section: network-management
  - section: nas-management
  - section: san-management
  - section: object-storage-management
  - section: security-encryption
  - section: data-protection-disaster-recovery
  - section: event-performance-monitoring
  - title: ONTAP 설명서 페이지
    url: "/concepts/manual-pages.html"
  - title: 법적 고지
    url: "/reference_legal_notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
  sidebar_label: 모든 ONTAP 제품 설명서
