---
sidebar: sidebar 
permalink: task_cp_monitor_cluster_performance_ci.html 
keywords: netapp, ontap, cluster, performance, monitor, monitoring, headroom, cpu, cpus, data infrastructure insights, troubleshoot, optimize, private data center, Kafka, MongoDB, Nginx, Active IQ Unified Manager, cluster performance, monitor performance 
summary: Data Infrastructure Insights를 사용하면 퍼블릭 클라우드와 프라이빗 데이터 센터를 포함한 모든 리소스를 모니터링하고, 문제를 해결하고, 최적화할 수 있습니다. 
---
= ONTAP Data Infrastructure Insights를 사용하여 클러스터 성능 모니터링
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Data Infrastructure Insights는 전체 인프라에 대한 가시성을 제공하는 모니터링 도구입니다. Data Infrastructure Insights를 사용하면 퍼블릭 클라우드와 프라이빗 데이터 센터를 포함한 모든 리소스를 모니터링하고, 문제를 해결하고, 최적화할 수 있습니다.



== Data Infrastructure Insights는 두 가지 버전으로 제공됩니다.

Data Infrastructure Insights Basic Edition은 NetApp Data Fabric 자산을 모니터링하고 최적화하도록 특별히 설계되었습니다. HCI와 FAS(All Flash AFF)를 포함한 모든 NetApp 리소스 간의 연결을 무료로 제공하는 고급 분석 기능을 제공합니다.

Data Infrastructure Insights Standard Edition은 NetApp Data Fabric 지원 인프라 구성 요소뿐만 아니라 멀티 벤더 및 멀티 클라우드 환경에도 중점을 둡니다. 풍부한 기능을 통해 100개 이상의 서비스 및 리소스에 대한 지원을 이용할 수 있습니다.

온프레미스 데이터 센터에서 여러 퍼블릭 클라우드에 이르기까지 다양한 리소스를 활용하는 오늘날의 환경에서는 애플리케이션 자체에서 스토리지 어레이의 백엔드 디스크에 이르기까지 전체적인 상황을 파악하는 것이 중요합니다. 애플리케이션 모니터링을 위한 추가 지원(Kafka, MongoDB 및 Nginx 등)은 최적의 활용률 수준뿐 아니라 완벽한 위험 버퍼에서도 운영하는 데 필요한 정보와 지식을 제공합니다.

두 에디션(기본 및 표준) 모두 NetApp Active IQ Unified Manager와 통합할 수 있습니다. Active IQ Unified Manager를 사용하는 고객은 Data Infrastructure Insights 사용자 인터페이스 내에서 조인 정보를 확인할 수 있습니다. Active IQ Unified Manager에 게시된 알림은 간과되지 않으며 Data Infrastructure Insights의 이벤트와 연관시킬 수 있습니다. 즉, 두 마리 토끼를 동시에 잡을 수 있습니다.



== 모든 리소스를 모니터링, 문제 해결 및 최적화합니다

데이터 인프라 인사이트를 활용하면 문제 해결에 걸리는 시간을 크게 줄이고 최종 사용자에게 영향을 미치지 않도록 방지할 수 있습니다. 또한 클라우드 인프라 비용을 줄일 수 있습니다. 실행 가능한 인텔리전스로 데이터를 보호하여 내부자 위협에 대한 노출을 줄입니다.

Data Infrastructure Insights를 사용하면 퍼블릭 클라우드부터 데이터 센터까지 전체 하이브리드 인프라에 대한 가시성을 한곳에서 확보할 수 있습니다. 필요에 따라 맞춤 구성할 수 있는 관련 대시보드를 즉시 만들 수 있습니다. 조직의 요구 사항에 따라 구체적이고 관련 있는 조건부 경고를 만들 수도 있습니다.

고급 이상 징후 탐지 기능을 통해 문제가 발생하기 전에 사전에 해결할 수 있습니다. 리소스 경합 및 성능 저하를 자동으로 확인하여 영향을 받는 워크로드를 신속하게 복원할 수 있습니다. 스택 내 여러 구성 요소 간의 관계를 자동으로 계층 구조로 만들어 문제 해결 작업을 더욱 빠르게 수행할 수 있습니다.

환경 전반에서 사용되지 않거나 버려진 리소스를 식별할 수 있으므로, 인프라의 크기를 적절하게 조정하고 전체 비용을 최적화할 기회를 찾을 수 있습니다.

데이터 인프라 인사이트는 Kubernetes 아키텍처를 이해하기 위해 시스템 토폴로지를 시각화합니다. 문제가 있는 노드를 비롯하여 Kubernetes 클러스터의 상태를 모니터링하고 문제가 발생하면 확장할 수 있습니다.

Data Infrastructure Insights는 고급 머신 러닝과 이상 탐지를 통해 조직 데이터가 악의적이거나 손상된 사용자에 의해 오용되는 것을 방지하고 내부 위협에 대한 실행 가능한 정보를 제공합니다.

Data Infrastructure Insights를 사용하면 Kubernetes 메트릭을 시각화하여 포드, 노드, 클러스터 간의 관계를 완벽하게 이해할 수 있습니다. 현재 처리 중인 로드뿐만 아니라 클러스터 또는 작업 포드의 상태를 평가할 수 있으므로 K8S 클러스터의 명령을 수행하고 배포 상태와 비용을 모두 제어할 수 있습니다.

.관련 링크
* link:https://docs.netapp.com/us-en/cloudinsights/task_cloud_insights_onboarding_1.html["데이터 인프라 인사이트 시작하기"^]

