---
sidebar: sidebar 
permalink: task_cp_monitor_cluster_performance_ci.html 
keywords: netapp, ontap, cluster, performance, monitor, monitoring, headroom, cpu, cpus, data infrastructure insights, troubleshoot, optimize, private data center, Kafka, MongoDB, Nginx, Active IQ Unified Manager, cluster performance, monitor performance 
summary: Data Infrastructure Insights를 사용하면 퍼블릭 클라우드와 프라이빗 데이터 센터를 포함한 모든 리소스를 모니터링하고, 문제를 해결하고, 최적화할 수 있습니다. 
---
= ONTAP Data Infrastructure Insights를 사용하여 클러스터 성능 모니터링
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Data Infrastructure Insights는 전체 인프라에 대한 가시성을 제공하는 모니터링 도구입니다. Data Infrastructure Insights를 사용하면 퍼블릭 클라우드와 프라이빗 데이터 센터를 포함한 모든 리소스를 모니터링하고, 문제를 해결하고, 최적화할 수 있습니다.



== 모든 리소스를 모니터링, 문제 해결 및 최적화합니다

데이터 인프라 인사이트를 활용하면 문제 해결에 걸리는 시간을 크게 줄이고 최종 사용자에게 영향을 미치지 않도록 방지할 수 있습니다. 또한 클라우드 인프라 비용을 줄일 수 있습니다. 실행 가능한 인텔리전스로 데이터를 보호하여 내부자 위협에 대한 노출을 줄입니다.

Data Infrastructure Insights를 사용하면 퍼블릭 클라우드부터 데이터 센터까지 전체 하이브리드 인프라에 대한 가시성을 한곳에서 확보할 수 있습니다. 필요에 따라 맞춤 구성할 수 있는 관련 대시보드를 즉시 만들 수 있습니다. 조직의 요구 사항에 따라 구체적이고 관련 있는 조건부 경고를 만들 수도 있습니다.

고급 이상 징후 탐지 기능을 통해 문제가 발생하기 전에 사전에 해결할 수 있습니다. 리소스 경합 및 성능 저하를 자동으로 확인하여 영향을 받는 워크로드를 신속하게 복원할 수 있습니다. 스택 내 여러 구성 요소 간의 관계를 자동으로 계층 구조로 만들어 문제 해결 작업을 더욱 빠르게 수행할 수 있습니다.

환경 전반에서 사용되지 않거나 버려진 리소스를 식별할 수 있으므로, 인프라의 크기를 적절하게 조정하고 전체 비용을 최적화할 기회를 찾을 수 있습니다.

데이터 인프라 인사이트는 Kubernetes 아키텍처를 이해하기 위해 시스템 토폴로지를 시각화합니다. 문제가 있는 노드를 비롯하여 Kubernetes 클러스터의 상태를 모니터링하고 문제가 발생하면 확장할 수 있습니다.

Data Infrastructure Insights는 고급 머신 러닝과 이상 탐지를 통해 조직 데이터가 악의적이거나 손상된 사용자에 의해 오용되는 것을 방지하고 내부 위협에 대한 실행 가능한 정보를 제공합니다.

Data Infrastructure Insights를 사용하면 Kubernetes 메트릭을 시각화하여 포드, 노드, 클러스터 간의 관계를 완벽하게 이해할 수 있습니다. 현재 처리 중인 로드뿐만 아니라 클러스터 또는 작업 포드의 상태를 평가할 수 있으므로 K8S 클러스터의 명령을 수행하고 배포 상태와 비용을 모두 제어할 수 있습니다.

.관련 링크
* link:https://docs.netapp.com/us-en/cloudinsights/task_cloud_insights_onboarding_1.html["데이터 인프라 인사이트 시작하기"^]

