---
permalink: tape-backup/assign-tape-aliases-concept.html 
sidebar: sidebar 
keywords: aliasing, ppn, physical, path, name, sn, serial, number, medium, changer, alias, name 
summary: '에일리어싱은 장치 식별 과정을 간소화합니다. 앨리어싱은 테이프 또는 미디어 체인저의 물리적 경로 이름(PPN) 또는 일련 번호(SN)를 영구적이지만 수정할 수 있는 별칭 이름에 바인딩합니다.' 
---
= 테이프 앨리어싱 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
에일리어싱은 장치 식별 과정을 간소화합니다. 앨리어싱은 테이프 또는 미디어 체인저의 물리적 경로 이름(PPN) 또는 일련 번호(SN)를 영구적이지만 수정할 수 있는 별칭 이름에 바인딩합니다.

다음 표에서는 테이프 드라이브(또는 테이프 라이브러리 또는 미디어 체인저)가 항상 단일 별칭 이름과 연결되도록 하는 테이프 앨리어싱을 사용하는 방법을 설명합니다.

|===
| 시나리오 | 별칭을 다시 할당합니다 


 a| 
시스템이 재부팅될 때
 a| 
테이프 드라이브는 이전 별칭을 자동으로 재할당합니다.



 a| 
테이프 디바이스가 다른 포트로 이동할 때
 a| 
새 주소를 가리키도록 별칭을 조정할 수 있습니다.



 a| 
둘 이상의 시스템에서 특정 테이프 디바이스를 사용하는 경우
 a| 
사용자는 모든 시스템에 대해 별칭을 동일하게 설정할 수 있습니다.

|===
[NOTE]
====
Data ONTAP 8.1.x에서 Data ONTAP 8.2.x로 업그레이드하면 Data ONTAP 8.2.x의 테이프 별칭 기능이 기존 테이프 별칭 이름을 수정합니다. 이러한 경우 백업 애플리케이션에서 테이프 별칭 이름을 업데이트해야 할 수 있습니다.

====
테이프 별칭을 할당하면 백업 디바이스의 논리적 이름(예: st0 또는 MC1)과 포트, 테이프 드라이브 또는 미디어 체인저에 영구적으로 할당되는 이름이 일치하게 됩니다.

[NOTE]
====
st0과 st00은 서로 다른 논리적 이름입니다.

====
[NOTE]
====
논리 이름 및 일련 번호는 장치에 액세스하는 경우에만 사용됩니다. 디바이스에 액세스한 후에는 물리적 경로 이름을 사용하여 모든 오류 메시지를 반환합니다.

====
앨리어싱에는 물리적 경로 이름과 일련 번호라는 두 가지 유형의 이름을 사용할 수 있습니다.



== 물리적 경로 이름에 대해 알아보세요

물리적 경로 이름(PPN)은 ONTAP가 스토리지 시스템에 접속된 SCSI-2/3 어댑터 또는 스위치(특정 위치)를 기반으로 테이프 드라이브 및 테이프 라이브러리에 할당하는 숫자 주소 시퀀스입니다. PPN은 전기 이름이라고도 합니다.

직접 연결된 장치의 PPN은 'host_adapter' 형식을 사용한다. device_id_lun

[NOTE]
====
LUN 값이 0이 아닌 테이프 및 미디어 체인저 디바이스에 대해서만 LUN 값이 표시됩니다. 즉, LUN 값이 0이면 PPN의 'LUN' 부분이 표시되지 않습니다.

====
예를 들어, PPN 8.6은 호스트 어댑터 번호가 8이고, 장치 ID는 6이며, 논리 장치 번호(LUN)는 0임을 나타냅니다.

SAS 테이프 장치도 직접 연결 장치입니다. 예를 들어, PPN 5c.4는 스토리지 시스템에서 SAS HBA가 슬롯 5에 연결되어 있고 SAS 테이프가 SAS HBA의 포트 C에 연결되어 있고 장치 ID가 4임을 나타냅니다.

Fibre Channel 스위치 접속 디바이스의 PPN은 'switch:port_id' 형식을 사용합니다. device_id_lun

예를 들어, PPN my_switch:5.3L2는 my_switch라는 스위치의 포트 5에 연결된 테이프 드라이브가 장치 ID 3으로 설정되어 있고 LUN 2를 가지고 있음을 나타냅니다.

LUN(논리 유닛 번호)은 드라이브에 의해 결정됩니다. Fibre Channel, SCSI 테이프 드라이브 및 라이브러리 및 디스크에는 PPN이 있습니다.

테이프 드라이브 및 라이브러리의 PPN은 스위치의 이름이 변경되거나, 테이프 드라이브 또는 라이브러리가 이동하거나, 테이프 드라이브 또는 라이브러리를 다시 구성하지 않는 한 변경되지 않습니다. 재부팅 후 PPN은 변경되지 않습니다. 예를 들어 my_switch:5.3L2라는 테이프 드라이브가 제거되고 디바이스 ID와 LUN이 동일한 새 테이프 드라이브가 스위치 my_switch의 포트 5에 연결된 경우 my_switch:5.3L2를 사용하여 새 테이프 드라이브에 액세스할 수 있습니다.



== 일련 번호에 대해 알아보세요

일련 번호(SN)는 테이프 드라이브 또는 미디어 체인저의 고유 식별자입니다. ONTAP는 WWN 대신 SN을 기반으로 별칭을 생성합니다.

SN은 테이프 드라이브 또는 미디어 체인저의 고유 식별자이므로 테이프 드라이브 또는 미디어 체인저에 대한 여러 연결 경로에 관계없이 별칭은 동일하게 유지됩니다. 이를 통해 스토리지 시스템은 테이프 라이브러리 구성에서 동일한 테이프 드라이브 또는 미디어 체인저를 추적할 수 있습니다.

테이프 드라이브 또는 미디어 체인저가 연결된 Fibre Channel 스위치의 이름을 바꾸어도 테이프 드라이브 또는 미디어 체인저의 SN은 변경되지 않습니다. 그러나 테이프 라이브러리에서 기존 테이프 드라이브를 새 테이프 드라이브로 교체할 경우 ONTAP는 테이프 드라이브의 SN이 변경되므로 새 별칭을 생성합니다. 또한 기존 테이프 드라이브를 테이프 라이브러리의 새 슬롯으로 이동하거나 테이프 드라이브의 LUN을 다시 매핑할 경우 ONTAP는 해당 테이프 드라이브에 대한 새 별칭을 생성합니다.

[NOTE]
====
백업 애플리케이션을 새로 생성된 별칭으로 업데이트해야 합니다.

====
테이프 장치의 SN은 S N[xxxxxxxxxx]L[X] 형식을 사용합니다

X는 영숫자 문자이고 L은 테이프 디바이스의 LUN입니다. LUN이 0이면 문자열 L의 X 부분이 표시되지 않습니다.

각 SN은 최대 32자로 구성되며, SN의 형식은 대/소문자를 구분하지 않습니다.
