---
permalink: tape-backup/dump-backup-concept.html 
sidebar: sidebar 
keywords: dump, backup, qtree, file, system, data 
summary: 덤프 백업은 미리 정의된 프로세스를 사용하여 파일 시스템 데이터를 디스크에서 테이프로 씁니다. 볼륨, qtree 또는 전체 볼륨이나 qtree가 아닌 하위 트리를 백업할 수 있습니다. 
---
= ONTAP NDMP를 사용한 덤프 백업 작동 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
덤프 백업은 미리 정의된 프로세스를 사용하여 파일 시스템 데이터를 디스크에서 테이프로 씁니다. 볼륨, qtree 또는 전체 볼륨이나 qtree가 아닌 하위 트리를 백업할 수 있습니다.

다음 표에서는 ONTAP에서 덤프 경로로 표시된 개체를 백업하는 데 사용하는 프로세스를 설명합니다.

[cols="1,4"]
|===
| 단계 | 조치 


 a| 
1
 a| 
전체 볼륨 또는 전체 qtree 백업보다 작은 경우 ONTAP에서는 백업할 파일을 식별하기 위해 디렉토리를 통과합니다. 전체 볼륨 또는 qtree를 백업하는 경우 ONTAP는 이 단계를 2단계와 결합합니다.



 a| 
2
 a| 
전체 볼륨 또는 전체 qtree 백업의 경우 ONTAP는 백업할 볼륨 또는 qtree의 디렉토리를 식별합니다.



 a| 
3
 a| 
ONTAP는 디렉토리를 테이프에 기록합니다.



 a| 
4
 a| 
ONTAP는 파일을 테이프에 씁니다.



 a| 
5
 a| 
ONTAP는 ACL 정보(해당되는 경우)를 테이프에 기록합니다.

|===
덤프 백업에서는 백업에 데이터 스냅샷을 사용합니다. 따라서 백업을 시작하기 전에 볼륨을 오프라인으로 전환할 필요가 없습니다.

덤프 백업은 생성하는 각 스냅샷의 이름을 `snapshot_for_backup.n` 지정합니다. 여기서 는 0부터 시작하는 정수입니다. `n` 덤프 백업이 스냅샷을 생성할 때마다 정수를 1씩 증가시킵니다. 스토리지 시스템이 재부팅되면 정수가 0으로 재설정됩니다. 백업 작업이 완료되면 덤프 엔진이 이 스냅샷을 삭제합니다.

ONTAP에서 동시에 여러 덤프 백업을 수행하면 덤프 엔진이 여러 개의 스냅샷을 생성합니다. 예를 들어 ONTAP에서 두 개의 덤프 백업을 동시에 실행하는 경우 데이터가 백업되는 볼륨에서 다음 스냅샷을 찾을 수 있습니다. `snapshot_for_backup.0` `snapshot_for_backup.1`

[NOTE]
====
스냅샷에서 백업하는 경우 덤프 엔진은 추가 스냅샷을 생성하지 않습니다.

====


== 덤프 엔진이 백업하는 데이터 유형입니다

덤프 엔진을 사용하여 데이터를 테이프에 백업함으로써 재해 또는 컨트롤러 중단을 방지할 수 있습니다. 덤프 엔진은 파일, 디렉토리, qtree 또는 전체 볼륨과 같은 데이터 오브젝트를 백업할 뿐 아니라 각 파일에 대한 여러 유형의 정보를 백업할 수 있습니다. 덤프 엔진이 백업할 수 있는 데이터의 유형과 고려해야 할 제한 사항을 알면 재해 복구에 대한 접근 방식을 계획하는 데 도움이 됩니다.

덤프 엔진은 파일의 데이터 백업 외에도 각 파일에 대한 다음 정보를 필요에 따라 백업할 수 있습니다.

* UNIX GID, 소유자 UID 및 파일 권한
* UNIX 액세스, 생성 및 수정 시간
* 파일 형식
* 파일 크기
* DOS 이름, DOS 속성 및 생성 시간입니다
* 1,024개의 ACE(액세스 제어 항목)가 있는 ACL(액세스 제어 목록)
* Qtree 정보
* 접합 경로


연결 경로는 심볼 링크로 백업됩니다.

* LUN 및 LUN 복제
+
전체 LUN 개체를 백업할 수 있지만 LUN 개체 내에서 단일 파일을 백업할 수는 없습니다. 마찬가지로, LUN 내에 단일 파일이 아니라 전체 LUN 개체를 복원할 수 있습니다.

+
[NOTE]
====
덤프 엔진은 LUN 클론을 독립 LUN으로 백업합니다.

====
* VM 정렬 파일
+
Data ONTAP 8.1.2 이전 릴리즈에서는 VM 정렬 파일의 백업이 지원되지 않습니다.



[NOTE]
====
스냅샷 지원 LUN 클론이 7-Mode에서 작동하는 Data ONTAP에서 ONTAP로 전환되면 일관성 없는 LUN이 됩니다. 덤프 엔진이 일관성 없는 LUN을 백업하지 않습니다.

====
볼륨에 데이터를 복구할 때는 복구 중인 LUN에서 클라이언트 입출력이 제한됩니다. LUN 제한은 덤프 복원 작업이 완료된 경우에만 제거됩니다. 마찬가지로, SnapMirror 단일 파일 또는 LUN 복원 작업 중에 클라이언트 I/O는 복원 중인 파일 및 LUN 모두에서 제한됩니다. 이 제한은 단일 파일 또는 LUN 복원 작업이 완료된 경우에만 제거됩니다. 덤프 복원 또는 SnapMirror 단일 파일 또는 LUN 복원 작업이 수행되고 있는 볼륨에서 덤프 백업을 수행하는 경우 클라이언트 I/O 제한이 있는 파일 또는 LUN은 백업에 포함되지 않습니다. 이러한 파일 또는 LUN은 클라이언트 입출력 제한이 제거된 경우 이후의 백업 작업에 포함됩니다.

[NOTE]
====
Data ONTAP 8.3에서 실행 중이며 테이프에 백업된 LUN은 이전 릴리즈가 아닌 8.3 이상 릴리즈로만 복원할 수 있습니다. LUN이 이전 릴리즈로 복원되면 LUN이 파일로 복원됩니다.

====
SnapVault 보조 볼륨 또는 볼륨 SnapMirror 대상을 테이프에 백업하는 경우 볼륨의 데이터만 백업됩니다. 연결된 메타데이터는 백업되지 않습니다. 따라서 볼륨을 복원하려고 하면 해당 볼륨의 데이터만 복원됩니다. volume SnapMirror 관계에 대한 정보는 백업에서 제공되지 않으므로 복원되지 않습니다.

Windows NT 권한만 있는 파일을 덤프하고 UNIX 스타일 qtree 또는 볼륨으로 복원하면 해당 qtree 또는 볼륨에 대한 기본 UNIX 권한이 파일에 부여됩니다.

UNIX 사용 권한만 있는 파일을 덤프하고 NTFS 스타일 qtree 또는 볼륨으로 복원하면 해당 qtree 또는 볼륨에 대한 기본 Windows 사용 권한이 파일에 부여됩니다.

다른 덤프 및 복원으로 사용 권한이 보존됩니다.

VM 정렬 파일과 'VM 정렬 섹터' 옵션을 백업할 수 있습니다. VM 정렬 파일에 대한 자세한 내용은 을 참조하십시오 link:../volumes/index.html["논리적 스토리지 관리"].
