---
permalink: tape-backup/dump-restore-event-log-message-format-concept.html 
sidebar: sidebar 
keywords: event, dump, restore, log, message, 
summary: 각 덤프 및 복원 이벤트에 대해 백업 로그 파일에 메시지가 기록됩니다. 
---
= ONTAP 덤프 및 복원 이벤트 로그 메시지 형식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
각 덤프 및 복원 이벤트에 대해 백업 로그 파일에 메시지가 기록됩니다.

덤프 및 복원 이벤트 로그 메시지의 형식은 다음과 같습니다.

'_TYPE TIMESTAMP IDENTIFIER EVENT (EVENT_INFO) _'

다음 목록에서는 이벤트 로그 메시지 형식의 필드를 설명합니다.

* 각 로그 메시지는 다음 표에 설명된 유형 표시기 중 하나로 시작됩니다.
+
|===
| 유형 | 설명 


 a| 
로그
 a| 
이벤트를 로깅하는 중입니다



 a| 
DMP
 a| 
덤프 이벤트



 a| 
RST
 a| 
복원 이벤트

|===
* 타임 스탬프는 이벤트의 날짜와 시간을 표시합니다.
* 덤프 이벤트의 식별자 필드에는 덤프 경로와 덤프의 고유 ID가 포함됩니다. 복구 이벤트의 '식별자' 필드는 복구 대상 경로 이름만 고유 식별자로 사용합니다. 로깅 관련 이벤트 메시지에는 '식별자' 필드가 포함되지 않습니다.




== ONTAP 로깅 이벤트에 대해 알아보세요

로그로 시작하는 메시지의 이벤트 필드는 로깅 시작 또는 로깅 종료를 지정합니다.

다음 표에 나와 있는 이벤트 중 하나가 포함되어 있습니다.

|===
| 이벤트 | 설명 


 a| 
Start_Logging(로깅 시작)
 a| 
로깅의 시작 또는 비활성화된 후 로깅이 다시 설정되었음을 나타냅니다.



 a| 
Stop_Logging(로깅 중지)
 a| 
로깅이 해제되었음을 나타냅니다.

|===


== ONTAP 덤프 이벤트에 대해 알아보세요

덤프 이벤트의 이벤트 필드에는 이벤트 유형 다음에 괄호 안에 이벤트 관련 정보가 표시됩니다.

다음 표에서는 덤프 작업에 대해 기록될 수 있는 이벤트, 설명 및 관련 이벤트 정보를 설명합니다.

|===
| 이벤트 | 설명 | 이벤트 정보 


 a| 
시작
 a| 
NDMP 덤프가 시작되었습니다
 a| 
덤프 레벨과 덤프 유형입니다



 a| 
끝
 a| 
덤프가 성공적으로 완료되었습니다
 a| 
처리된 데이터의 양입니다



 a| 
중단
 a| 
작업이 취소됩니다
 a| 
처리된 데이터의 양입니다



 a| 
옵션
 a| 
지정된 옵션이 나열됩니다
 a| 
NDMP 옵션을 포함한 모든 옵션과 관련 값



 a| 
tape_open 을 참조하십시오
 a| 
테이프가 읽기/쓰기를 위해 열려 있습니다
 a| 
새 테이프 디바이스 이름입니다



 a| 
테이프_닫기
 a| 
읽기/쓰기를 위해 테이프가 닫혀 있습니다
 a| 
테이프 디바이스 이름입니다



 a| 
변경 단계
 a| 
덤프가 새 처리 단계로 들어가고 있습니다
 a| 
새 단계 이름입니다



 a| 
오류
 a| 
덤프에 예기치 않은 이벤트가 발생했습니다
 a| 
오류 메시지



 a| 
스냅샷
 a| 
스냅샷이 생성되거나 배치됩니다
 a| 
스냅샷의 이름과 시간입니다



 a| 
base_dump입니다
 a| 
내부 메타파일의 기본 덤프 항목이 있습니다
 a| 
기본 덤프의 레벨 및 시간(증분 덤프에만 해당)

|===


== ONTAP 복원 이벤트에 대해 알아보세요

복원 이벤트의 이벤트 필드에는 이벤트 유형 다음에 이벤트 관련 정보가 괄호 안에 표시됩니다.

다음 표에서는 복구 작업을 위해 기록할 수 있는 이벤트, 설명 및 관련 이벤트 정보에 대한 정보를 제공합니다.

|===
| 이벤트 | 설명 | 이벤트 정보 


 a| 
시작
 a| 
NDMP 복구가 시작되었습니다
 a| 
복구 레벨 및 복구 유형



 a| 
끝
 a| 
복원이 성공적으로 완료되었습니다
 a| 
처리된 파일 수 및 데이터 양



 a| 
중단
 a| 
작업이 취소됩니다
 a| 
처리된 파일 수 및 데이터 양



 a| 
옵션
 a| 
지정된 옵션이 나열됩니다
 a| 
NDMP 옵션을 포함한 모든 옵션과 관련 값



 a| 
tape_open 을 참조하십시오
 a| 
테이프가 읽기/쓰기를 위해 열려 있습니다
 a| 
새 테이프 디바이스 이름입니다



 a| 
테이프_닫기
 a| 
읽기/쓰기를 위해 테이프가 닫혀 있습니다
 a| 
테이프 디바이스 이름입니다



 a| 
변경 단계
 a| 
복원이 새 처리 단계로 들어가고 있습니다
 a| 
새 단계 이름입니다



 a| 
오류
 a| 
복원에서 예기치 않은 이벤트가 발생합니다
 a| 
오류 메시지

|===