---
permalink: tape-backup/manage-node-scoped-ndmp-mode-concept.html 
sidebar: sidebar 
keywords: manage, node, scope, ndmp, mode, flexvol, volume, command, option, backup, restore 
summary: NDMP 옵션과 명령을 사용하여 노드 레벨에서 NDMP를 관리할 수 있습니다. options 명령을 사용하여 NDMP 옵션을 수정할 수 있습니다. 테이프 백업 및 복구 작업을 수행하려면 NDMP 관련 자격 증명을 사용하여 스토리지 시스템을 액세스해야 합니다. 
---
= FlexVol 볼륨에 대한 ONTAP 노드 범위 NDMP 모드 관리에 대해 알아보세요.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NDMP 옵션과 명령을 사용하여 노드 레벨에서 NDMP를 관리할 수 있습니다. 'options' 명령을 사용하여 NDMP 옵션을 수정할 수 있습니다. 테이프 백업 및 복구 작업을 수행하려면 NDMP 관련 자격 증명을 사용하여 스토리지 시스템을 액세스해야 합니다.

에 대한 자세한 내용은 `options` link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=options["ONTAP 명령 참조입니다"^]을 참조하십시오.



== ONTAP 노드 범위 NDMP 모드를 관리하기 위한 명령

'system services ndmp' 명령을 사용하여 노드 레벨에서 NDMP를 관리할 수 있습니다. 이러한 명령 중 일부는 더 이상 사용되지 않으며 향후 주요 릴리즈에서 제거될 예정입니다.

다음 NDMP 명령은 고급 권한 수준에서만 사용할 수 있습니다.

* '시스템 서비스 NDMP 서비스 종료
* '시스템 서비스 NDMP 서비스 시작'
* '시스템 서비스 NDMP 서비스 중지'
* '시스템 서비스 NDMP 로그 시작'
* 'System services ndmp log stop'(시스템 서비스 NDMP 로그 중지)


|===
| 원하는 작업 | 이 명령 사용... 


 a| 
NDMP 서비스를 설정합니다
 a| 
'System services NDMP on' *



 a| 
NDMP 서비스를 해제합니다
 a| 
'시스템 서비스 NDMP 꺼짐' *



 a| 
NDMP 구성을 표시합니다
 a| 
'system services ndmp show' * 를 참조하십시오



 a| 
NDMP 구성을 수정합니다
 a| 
'시스템 서비스 NDMP 수정' *



 a| 
기본 NDMP 버전을 표시합니다
 a| 
'시스템 서비스 NDMP 버전' *



 a| 
NDMP 서비스 구성을 표시합니다
 a| 
'시스템 서비스 NDMP 서비스 쇼'



 a| 
NDMP 서비스 구성을 수정합니다
 a| 
'시스템 서비스 NDMP 서비스 수정'



 a| 
모든 NDMP 세션을 표시합니다
 a| 
'시스템 서비스 NDMP 상태'



 a| 
모든 NDMP 세션에 대한 자세한 정보를 표시합니다
 a| 
'System services ndmp probe



 a| 
지정된 NDMP 세션을 종료합니다
 a| 
'시스템 서비스 NDMP kill'



 a| 
모든 NDMP 세션을 종료합니다
 a| 
'시스템 서비스 NDMP kill-all'



 a| 
NDMP 암호를 변경합니다
 a| 
'시스템 서비스 NDMP 암호' *



 a| 
노드 범위 NDMP 모드를 설정합니다
 a| 
'System services NDMP node-scope-mode on' *



 a| 
노드 범위 NDMP 모드를 해제합니다
 a| 
'System services NDMP node-scope-mode off' *



 a| 
노드 범위의 NDMP 모드 상태를 표시합니다
 a| 
'System services NDMP node-scope-mode status' *



 a| 
모든 NDMP 세션을 강제로 종료합니다
 a| 
'시스템 서비스 NDMP 서비스 종료



 a| 
NDMP 서비스 데몬을 시작합니다
 a| 
'시스템 서비스 NDMP 서비스 시작'



 a| 
NDMP 서비스 데몬을 중지합니다
 a| 
'시스템 서비스 NDMP 서비스 중지'



 a| 
지정된 NDMP 세션에 대해 로깅을 시작합니다
 a| 
'시스템 서비스 NDMP 로그 시작' *



 a| 
지정된 NDMP 세션에 대한 로깅을 중지합니다
 a| 
'System services ndmp log stop' *

|===
* 이러한 명령은 더 이상 사용되지 않으며 향후 주요 릴리즈에서 제거될 예정입니다.


에 대한 자세한 내용은 `system services ndmp` link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+services+ndmp["ONTAP 명령 참조입니다"^]을 참조하십시오.



== 노드 범위 NDMP 모드의 사용자 인증

노드 범위 NDMP 모드에서는 NDMP 관련 자격 증명을 사용하여 스토리지 시스템에 액세스해야 테이프 백업 및 복구 작업을 수행할 수 있습니다.

기본 사용자 ID는 ""root""입니다. 노드에서 NDMP를 사용하기 전에 NDMP 사용자와 연결된 기본 NDMP 암호를 변경해야 합니다. 기본 NDMP 사용자 ID를 변경할 수도 있습니다.

.관련 정보
xref:commands-manage-node-scoped-ndmp-reference.adoc[노드 범위의 NDMP 모드를 관리하는 명령입니다]

xref:node-scoped-ndmp-mode-concept.adoc[노드 범위의 NDMP 모드는 무엇입니까]
