---
permalink: tape-backup/ndmp-modes-concept.html 
sidebar: sidebar 
keywords: ndmp, mode, operation, backup, restore, node, level, svm 
summary: '노드 레벨 또는 스토리지 가상 머신(SVM) 레벨에서 테이프 백업 및 복원 작업을 수행하도록 선택할 수 있습니다. SVM 레벨에서 이러한 작업을 성공적으로 수행하려면 SVM에서 NDMP 서비스를 사용하도록 설정해야 합니다.' 
---
= ONTAP NDMP 작동 모드에 대해 알아보세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드 레벨 또는 스토리지 가상 머신(SVM) 레벨에서 테이프 백업 및 복원 작업을 수행하도록 선택할 수 있습니다. SVM 레벨에서 이러한 작업을 성공적으로 수행하려면 SVM에서 NDMP 서비스를 사용하도록 설정해야 합니다.

Data ONTAP 8.2에서 Data ONTAP 8.3으로 업그레이드할 경우 8.2에서 사용되는 NDMP 작업 모드는 업그레이드 후에도 8.2에서 8.3으로 유지됩니다.

Data ONTAP 8.2 이상을 사용하여 새 클러스터를 설치하는 경우 NDMP는 기본적으로 SVM 범위의 NDMP 모드에 있습니다. 노드 범위 NDMP 모드에서 테이프 백업 및 복구 작업을 수행하려면 노드 범위 NDMP 모드를 명시적으로 설정해야 합니다.



== 노드 범위 ONTAP NDMP 모드에 대해 알아보세요

노드 범위의 NDMP 모드에서는 노드 수준에서 테이프 백업 및 복구 작업을 수행할 수 있습니다. Data ONTAP 8.2에서 사용되는 NDMP 작업 모드는 업그레이드 후에도 8.2에서 8.3으로 유지됩니다.

노드 범위의 NDMP 모드에서는 볼륨을 소유하는 노드에서 테이프 백업 및 복구 작업을 수행할 수 있습니다. 이러한 작업을 수행하려면 볼륨 또는 테이프 디바이스를 소유한 노드에서 호스팅되는 LIF에 NDMP 제어 연결을 설정해야 합니다.

[NOTE]
====
이 모드는 더 이상 사용되지 않으며 향후 주요 릴리즈에서 제거될 예정입니다.

====


== SVM 범위 ONTAP NDMP 모드에 대해 알아보세요

SVM에서 NDMP 서비스가 활성화되어 있는 경우 SVM(스토리지 가상 시스템) 레벨에서 테이프 백업 및 복원 작업을 성공적으로 수행할 수 있습니다. 백업 애플리케이션이 CAB 확장을 지원하는 경우 클러스터 SVM의 여러 노드에서 호스팅되는 모든 볼륨을 백업 및 복원할 수 있습니다.

NDMP 제어 연결은 다른 LIF 유형에 설정할 수 있습니다. SVM 범위의 NDMP 모드에서 이러한 LIF는 데이터 SVM 또는 관리 SVM에 속합니다. 이 LIF를 소유한 SVM에서 NDMP 서비스를 사용하도록 설정한 경우에만 LIF에서 연결을 설정할 수 있습니다.

데이터 LIF는 데이터 SVM에 속하며 인터클러스터 LIF, 노드 관리 LIF 및 클러스터 관리 LIF는 관리 SVM에 속합니다.

SVM 범위의 NDMP 모드에서 백업 및 복원 작업에 대한 볼륨 및 테이프 장치의 가용성은 NDMP 제어 연결이 설정된 LIF 유형과 CAB 확장의 상태에 따라 다릅니다. 백업 애플리케이션이 CAB 확장 및 볼륨을 지원하고 테이프 디바이스가 동일한 선호도를 공유하는 경우 백업 애플리케이션은 3방향 백업 또는 복구 작업 대신 로컬 백업 또는 복구 작업을 수행할 수 있습니다.

.관련 정보
xref:commands-manage-node-scoped-ndmp-reference.adoc[노드 범위의 NDMP 모드를 관리하는 명령입니다]
