---
permalink: tape-backup/snapshot-copies-during-smtape-backup-concept.html 
sidebar: sidebar 
keywords: snapshot, copy, smtape, backup, baseline, incremental, snapmirror 
summary: SMTape 기준 백업 및 증분 백업 중에 스냅샷이 사용되는 방식을 이해해야 합니다. 또한 SMTape를 사용하여 백업을 수행하는 동안 유의해야 할 고려 사항도 있습니다. 
---
= SMTape 백업 중 ONTAP 스냅샷 사용에 대해 알아보세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMTape 기준 백업 및 증분 백업 중에 스냅샷이 사용되는 방식을 이해해야 합니다. 또한 SMTape를 사용하여 백업을 수행하는 동안 유의해야 할 고려 사항도 있습니다.



== 기본 백업

기준 백업을 수행하는 동안 테이프에 백업할 스냅샷의 이름을 지정할 수 있습니다. 스냅샷이 지정되지 않은 경우 볼륨의 액세스 유형(읽기/쓰기 또는 읽기 전용)에 따라 스냅샷이 자동으로 생성되거나 기존 스냅샷이 사용됩니다. 백업에 대한 스냅샷을 지정하면 지정된 스냅샷보다 오래된 모든 스냅샷도 테이프에 백업됩니다.

백업에 대한 스냅샷을 지정하지 않으면 다음과 같은 현상이 발생합니다.

* 읽기/쓰기 볼륨의 경우 스냅샷이 자동으로 생성됩니다.
+
새로 생성된 스냅샷과 모든 이전 스냅샷이 테이프에 백업됩니다.

* 읽기 전용 볼륨의 경우 최신 스냅샷을 포함한 모든 스냅샷이 테이프에 백업됩니다.
+
백업이 시작된 후에 생성된 새 스냅샷은 백업되지 않습니다.





== 증분 백업

SMTape 증분 또는 차등 백업 작업의 경우 NDMP 호환 백업 애플리케이션에서 스냅샷을 생성하고 관리합니다.

증분 백업 작업을 수행하는 동안 항상 스냅샷을 지정해야 합니다. 성공적인 증분 백업 작업의 경우 이전 백업 작업(기본 또는 증분) 중에 백업된 스냅샷이 백업이 수행되는 볼륨에 있어야 합니다. 이 백업된 스냅샷을 사용하려면 백업 정책을 구성할 때 이 볼륨에 할당된 스냅샷 정책을 고려해야 합니다.



== SnapMirror 대상에 대한 SMTape 백업 고려 사항

* 데이터 보호 미러 관계는 복제를 위해 대상 볼륨에 임시 스냅샷을 생성합니다.
+
SMTape 백업에 이러한 스냅샷을 사용해서는 안 됩니다.

* 동일한 볼륨에서 SMTape 백업 작업 중에 데이터 보호 미러 관계의 대상 볼륨에서 SnapMirror 업데이트가 발생하면 SMTape에서 백업한 스냅샷은 소스 볼륨에서 삭제되지 않아야 합니다.
+
백업 작업 중에 SMTape는 대상 볼륨의 스냅샷을 잠급니다. 소스 볼륨에서 해당 스냅샷이 삭제되면 후속 SnapMirror 업데이트 작업이 실패합니다.

* 증분 백업 중에는 이러한 스냅샷을 사용하지 마십시오.

