---
sidebar: sidebar 
permalink: software_setup/setup-cluster.html 
keywords: install, installing, cluster, set up, setup, configure, disk, data ports, guided setup, local tiers, aggregate, vserver, volume, configuring ONTAP on a new cluster, configuring a new cluster, assign a node-management IP address, node, DNS server, host name, hostname, NTP server, synchronize time, create a local tier, configure protocol, SSD, provision storage, add LUN, add volume, add namespace, volume, vserver, configure ONTAP on a new cluster, configuration 
summary: System Manager는 클러스터를 설정하고 스토리지를 구성하기 위한 간단하고 쉬운 워크플로우를 제공합니다. 
---
= ONTAP 클러스터를 생성하고 노드를 결합합니다
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp은 System Manager를 사용하여 새 클러스터를 생성하는 것이 좋습니다. System Manager는 클러스터 설정을 위한 간단하고 쉬운 워크플로를 제공합니다. MetroCluster 구성에서 ONTAP 9.7 이하를 실행 중이거나 특정 플랫폼에서 IPv6 전용 클러스터를 구성해야 하는 경우에만 ONTAP CLI(명령줄 인터페이스)를 사용해야 합니다.

.이 작업에 대해
이 절차는 link:https://docs.netapp.com/us-en/ontap-systems-family/index.html["AFF, ASA, FAS"^] 및 link:https://docs.netapp.com/us-en/ontap-afx/index.html["AFX 시스템"^]에 적용됩니다. ASA r2 시스템(ASA A1K, ASA A90, ASA A70, ASA A50, ASA A30, ASA A20 또는 ASA C30)이 있는 경우 link:https://docs.netapp.com/us-en/asa-r2/install-setup/initialize-ontap-cluster.html["수행할 수 있습니다"^]를 따라 System Manager를 사용하여 ONTAP 클러스터를 설정하십시오. ASA r2 시스템은 SAN 전용 고객을 위한 간소화된 ONTAP 환경을 제공합니다.

ONTAP 9.13.1부터는 ONTAP CLI를 사용하여 초기 클러스터 설정 중에 AFF A800 및 FAS8700 플랫폼의 관리 LIF에 IPv6 주소를 할당할 수 있습니다. ONTAP 9.13.1 이전 버전의 ONTAP 릴리즈나 다른 플랫폼의 ONTAP 9.13.1 이상 버전의 경우, System Manager를 사용하여 IPv4 주소를 사용하여 클러스터를 생성한 다음 클러스터 설정을 완료한 후 주소를 생성해야 link:convert-ipv4-to-ipv6-task.html["IPv6로 변환합니다"]합니다.


NOTE: System Manager는 ONTAP 9.6 이하 버전에서 IPv6 네트워킹이 필요한 배포를 지원하지 않습니다.

.시작하기 전에
* 해당 플랫폼 모델의 설치 및 설정 지침에 따라 새 스토리지 시스템에 케이블을 연결하고 전원을 켜야 합니다.
+
link:https://docs.netapp.com/us-en/ontap-systems/index.html["ONTAP 하드웨어 시스템 설명서"^]를 참조하십시오.

* 클러스터 스위치가 시스템 설치에 포함된 경우 새 스토리지 시스템의 클러스터 포트에 대한 클러스터 스위치 모델의 케이블링 및 구성 고려 사항을 검토하십시오. link:https://docs.netapp.com/us-en/ontap-systems-switches/index.html["ONTAP 하드웨어 시스템용 스위치 설명서"^]을 참조하십시오.
+
.. *지원되는 스위치* 타일에서 *클러스터 스위치* 또는 *공유 스위치* 를 선택합니다.
.. 스위치 모델에 대한 *설치* 설명서를 선택합니다.
.. *케이블 연결 및 구성 고려 사항 검토* 항목을 검색하여 스토리지 시스템에 대해 검토하십시오.


* link:gather_cluster_setup_information.html["필요한 정보를 수집합니다"] 을 눌러 클러스터 설정을 완료합니다.
* 클러스터 내 통신을 위해 클러스터의 각 노드에서 클러스터 네트워크 인터페이스를 구성해야 합니다.
* CLI를 사용하여 IPv6를 구성하는 경우 SSH를 사용하여 시스템에 액세스할 수 있도록 BMC(기본 관리 컨트롤러)에서 IPv6를 구성해야 합니다.


.단계
[role="tabbed-block"]
====
.시스템 관리자
--
. 노드 관리 IP 주소를 할당합니다
+
** Windows 컴퓨터
+
... Windows 컴퓨터를 컨트롤러와 동일한 서브넷에 연결합니다.
+
이렇게 하면 노드 관리 IP 주소가 시스템에 자동으로 할당됩니다.

... 네트워크 * 드라이브를 열어 노드를 검색합니다.
... 노드를 선택하여 클러스터 설정 마법사를 시작합니다.


** Windows 이외의 컴퓨터
+
... 클러스터에 추가할 모든 노드의 전원을 켭니다.
+
이는 클러스터 설정을 검색할 수 있도록 하는 데 필요합니다.

... 첫 번째 노드의 콘솔에 연결합니다.
+
노드가 부팅된 다음 콘솔에서 클러스터 설정 마법사가 시작됩니다.

+
[listing]
----
Welcome to the cluster setup wizard....
----
... AutoSupport 설명을 확인합니다.
+
[listing]
----
Type yes to confirm and continue {yes}: yes
----
+
AutoSupport는 기본적으로 사용하도록 설정되어 있습니다.

... 화면의 지침에 따라 노드에 관리 IP 주소를 할당합니다.
... 웹 브라우저에서 구성한 노드 관리 IP 주소를 입력합니다"https://node-management-IP"[].
+
System Manager가 클러스터의 나머지 노드를 자동으로 검색합니다.





. Initialize storage system * 에 클러스터 이름과 admin 암호를 입력합니다.
. 네트워킹 * 에 클러스터 관리 IP 주소, 서브넷 마스크 및 게이트웨이를 입력합니다.
. 도메인 이름 서비스를 사용하여 호스트 이름을 확인하려면 * DNS(도메인 이름 서비스) 사용 * 을 선택한 다음 DNS 서버 정보를 입력합니다.
. 클러스터 전체에서 시간을 동기화하기 위해 NTP(네트워크 시간 프로토콜)를 사용하려면 * 기타 * 에서 * 시간 서비스 사용(NTP) * 을 선택하고 NTP 서버 정보를 입력합니다.
. 제출 * 을 선택합니다.


--
.ONTAP CLI를 참조하십시오
--
. 클러스터에 추가할 모든 노드의 전원을 켭니다.
+
이 작업은 클러스터 설정을 검색하는 데 필요합니다.

. 첫 번째 노드의 콘솔에 연결합니다.
+
노드가 부팅된 다음 콘솔에서 클러스터 설정 마법사가 시작됩니다.

+
[listing]
----
Welcome to the cluster setup wizard....
----
. AutoSupport 설명을 확인합니다.
+
[listing]
----
Type yes to confirm and continue {yes}: yes
----
+
AutoSupport는 기본적으로 사용하도록 설정되어 있습니다.

. 화면의 지침에 따라 노드에 관리 IP 주소를 할당합니다.
+
ONTAP 9.13.1부터 A800 및 FAS8700 플랫폼에서 관리 LIF에 IPv6 주소를 할당할 수 있습니다. ONTAP 9.13.1 이전 릴리즈 또는 다른 플랫폼에서 9.13.1 이상인 경우 관리 LIF에 IPv4 주소를 할당한 다음 클러스터 설정을 완료한 후 IPv6로 변환해야 합니다.

. 계속하려면 * Enter * 를 누르십시오.
+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
----
. 새 클러스터 생성:
+
.. 를 입력합니다 `create`
.. 시스템 기본값을 그대로 사용하거나 값을 직접 입력합니다.
.. 설정이 완료된 후 클러스터에 로그인하여 클러스터가 활성 상태이고 첫 번째 노드가 정상 상태인지 확인합니다. `cluster show`
+
다음 예에서는 첫 번째 노드(cluster1-01)가 정상이고 참여할 자격이 있는 클러스터를 보여 줍니다.

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
cluster1-01           true    true
----
+
필요한 경우, 명령을 사용하여 클러스터 설정 마법사에 액세스하고 admin 또는 노드 SVM에 대해 입력한 값을 변경할 수 있습니다 `cluster setup`.



. 클러스터에 노드 연결:
+
한 번에 하나의 노드를 클러스터에 결합할 수 있습니다. 각 노드에 대해 결합 작업을 완료해야 하며, 다음 노드에 대한 연결을 시작하려면 노드가 클러스터의 일부여야 합니다.

+
NL-SAS 드라이브가 24개 이하인 FAS2720를 사용하는 경우 스토리지 구성 기본값이 액티브/패시브로 설정되어 있는지 확인하여 성능을 최적화해야 합니다. 자세한 내용은 의 설명서를 link:../disks-aggregates/setup-active-passive-config-root-data-task.html["루트 데이터 파티셔닝을 사용하여 노드에 대한 액티브-패시브 구성을 설정합니다"]참조하십시오.

+
.. 클러스터에 참여하려는 노드에 로그인합니다.
+
콘솔에서 클러스터 설정 마법사가 시작됩니다.

+
[listing]
----
Welcome to the cluster setup wizard....
----
.. AutoSupport 설명을 확인합니다.
+

NOTE: AutoSupport는 기본적으로 사용하도록 설정되어 있습니다.



+
[listing]
----
Type yes to confirm and continue {yes}: yes
----
+
.. 화면의 지침에 따라 노드에 IP 주소를 할당합니다.
+
ONTAP 9.13.1부터 A800 및 FAS8700 플랫폼에서 관리 LIF에 IPv6 주소를 할당할 수 있습니다. ONTAP 9.13.1 이전 릴리즈 또는 다른 플랫폼에서 9.13.1 이상인 경우 관리 LIF에 IPv4 주소를 할당한 다음 클러스터 설정을 완료한 후 IPv6로 변환해야 합니다.

.. 계속하려면 * Enter * 를 누르십시오.
+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
----
.. 를 입력합니다 `join`
.. 화면의 지침에 따라 노드를 설정하고 클러스터에 연결합니다.
.. 설정이 완료되면 노드가 정상 상태이며 클러스터에 참여할 수 있는지 확인합니다. `cluster show`
+
다음 예에서는 두 번째 노드(cluster1-02)가 클러스터에 결합된 후의 클러스터를 보여 줍니다.

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
cluster1-01           true    true
cluster1-02           true    true
----


. 7단계를 반복하여 나머지 노드를 모두 연결합니다.


--
====
.다음 단계
* 필요한 경우 link:convert-ipv4-to-ipv6-task.html["IPv4에서 IPv6로 변환"].
* link:task_check_cluster_with_config_advisor.html["Active IQ Config Advisor를 실행하여 구성을 검증하고 일반적인 구성 오류를 확인합니다"]..

