---
sidebar: sidebar 
permalink: high-availability/ha-pair-encryption.html 
keywords: cluster network, encryption, TLS, data-in-flight 
summary: HA 쌍 노드 간 암호화 통신 구성 
---
= ONTAP HA 트래픽에 대한 암호화 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.18.1부터 고가용성(HA) 쌍 노드 간 네트워크 트래픽에 대한 암호화를 구성할 수 있습니다.  이 암호화는 HA 쌍의 노드 간에 전송되는 고객 데이터와 메타데이터를 보호합니다.

.이 작업에 대해
* HA 트래픽 암호화는 기본적으로 비활성화되어 있습니다.
* HA 트래픽 암호화를 활성화하거나 비활성화하면 클러스터의 모든 HA 쌍에 영향을 미칩니다.  개별 노드에 대해 암호화를 활성화하거나 비활성화할 수 없습니다.
* HA 트래픽 암호화를 활성화하면 HA 쌍 노드 간에 전송되는 모든 고객 데이터와 메타데이터가 암호화됩니다.  파일 시스템 메타데이터 및 하트비트 메시지와 같은 일부 HA 트래픽은 암호화되지 않습니다.
* HA 트래픽 암호화가 활성화되고 클러스터에 새 HA 쌍이 추가되면 다음을 다시 실행하여 새 노드에 대한 HA 트래픽 암호화를 수동으로 활성화해야 합니다. `security ha-network modify -enabled true` 명령.


.시작하기 전에
* 당신은 ONTAP 관리자여야 합니다. `admin` 다음 절차를 수행하려면 권한 수준이 필요합니다.
* HA 트래픽 암호화를 활성화하기 전에 다음을 수행해야 합니다.link:../encryption-at-rest/configure-external-key-management-concept.html["외부 키 관리를 구성합니다"] .
* HA 트래픽 암호화를 활성화하려면 클러스터의 모든 노드에서 ONTAP 9.18.1 이상을 실행해야 합니다.


.단계
. HA 트래픽에 대한 현재 암호화 상태를 확인하세요.
+
[source, cli]
----
security ha-network show
----
+
이 명령은 각 노드의 HA 트래픽 암호화의 현재 상태를 보여줍니다.

+
[source]
----
security ha-network show
Node                  Enabled
--------------------- --------------------
node1                 true
node2                 true
node3                 true
node4                 true
4 entries were displayed.
----
. HA 트래픽에 대한 암호화를 활성화하거나 비활성화합니다.


[source, cli]
----
security ha-network modify -enabled <true|false>
----
이 명령은 클러스터의 모든 노드에 대해 암호화된 HA 트래픽을 활성화하거나 비활성화합니다.  클러스터에 새로운 HA 쌍이 추가되면 이 명령을 다시 실행하여 새 노드에 대한 HA 트래픽 암호화를 활성화해야 합니다.
