---
sidebar: sidebar 
permalink: high-availability/halt-reboot-node-wo-takeover-task.html 
keywords: high availability pair, hair, inhibit-takeover, reboot, epsilon, HA 
summary: '노드 또는 쉘프에 대해 특정 하드웨어 유지 관리를 수행할 때 테이크오버 없이 2노드 클러스터의 노드를 중단하거나 재부팅하는 경우 파트너 노드를 가동하여 중단 시간을 제한하려는 경우 또는 수동 테이크오버(takeover)에 방해가 되는 문제가 있고 파트너 노드의 집계를 유지하고 데이터를 서비스하려는 경우 또한 기술 지원 부서에서 문제 해결을 지원하는 경우 이러한 작업의 일부로 이 절차를 수행할 수 있습니다.' 
---
= 2노드 클러스터에서 인수를 시작하지 않고 ONTAP 노드를 중지하거나 재부팅합니다.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
노드 또는 쉘프에 대해 특정 하드웨어 유지 관리를 수행할 때 테이크오버 없이 2노드 클러스터의 노드를 중단하거나 재부팅하는 경우 파트너 노드를 가동하여 중단 시간을 제한하려는 경우 또는 수동 테이크오버(takeover)에 방해가 되는 문제가 있고 파트너 노드의 집계를 유지하고 데이터를 서비스하려는 경우 또한 기술 지원 부서에서 문제 해결을 지원하는 경우 이러한 작업의 일부로 이 절차를 수행할 수 있습니다.

.이 작업에 대해
* Takeover를 금지('-inhibit-takeover TRUE' 매개 변수 사용)하기 전에 클러스터 HA를 비활성화합니다.


[CAUTION]
====
* 2노드 클러스터에서 클러스터 HA는 노드 1개의 장애가 클러스터를 비활성화하지 않도록 보장합니다. 하지만 '-inhibit-takeover true' 매개 변수를 사용하기 전에 클러스터 HA를 해제하지 않으면 두 노드 모두 데이터 제공을 중단합니다.
* 클러스터 HA를 해제하기 전에 노드를 중단 또는 재부팅하려고 시도하면 ONTAP는 경고를 표시하고 클러스터 HA를 비활성화하라는 메시지를 표시합니다.


====
* LIF(논리 인터페이스)를 온라인 상태로 유지하려는 파트너 노드로 마이그레이션합니다.
* 중단하거나 재부팅하는 노드에서 유지할 애그리게이트가 있는 경우 온라인 상태로 유지하려는 노드로 이동합니다.


.단계
. 두 노드가 모두 정상 상태인지 확인합니다.
+
[source, cli]
----
cluster show
----
+
두 노드 모두 '건강' 칼럼에 '참'이 나타납니다.

+
[listing]
----
cluster::> cluster show
Node         Health  Eligibility
------------ ------- ------------
node1        true     true
node2        true     true
----
+
에 대한 자세한 내용은 `cluster show` link:https://docs.netapp.com/us-en/ontap-cli/cluster-show.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

. 중지하거나 재부팅할 노드의 모든 LIF를 파트너 노드로 마이그레이션하십시오.
+
[source, cli]
----
network interface migrate-all -node <node_name>
----
+
에 대한 자세한 내용은 `network interface migrate-all` link:https://docs.netapp.com/us-en/ontap-cli/network-interface-migrate-all.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

. 중지하거나 재부팅할 노드에 노드가 다운된 상태에서 온라인 상태로 유지하려는 애그리게이트가 있는 경우 파트너 노드로 재배치하십시오.
+
.. 중지하거나 재부팅할 노드의 애그리게이트를 표시합니다.
+
[source, cli]
----
storage aggregates show -node <node_name>
----
+
예를 들어, node1은 중단되거나 재부팅될 노드입니다.

+
[listing]
----
cluster::> storage aggregates show -node node1
Aggregate  Size  Available  Used%  State  #Vols   Nodes   RAID  Status
---------  ----  ---------  -----  -----  -----   -----   ----  ------
aggr0_node_1_0
           744.9GB   32.68GB   96% online       2 node1    raid_dp,
                                                                normal
aggr1       2.91TB    2.62TB   10% online       8 node1    raid_dp,
                                                                normal
aggr2
            4.36TB    3.74TB   14% online      12 node1    raid_dp,
                                                                normal
test2_aggr  2.18TB    2.18TB    0% online       7 node1    raid_dp,
                                                                normal
4 entries were displayed.
----
.. 애그리게이트를 파트너 노드로 이동합니다.
+
[source, cli]
----
storage aggregate relocation start -node <node_name> -destination <node_name> -aggregate-list <aggregate_name>
----
+
예를 들어, aggr1, aggr2 및 test2_aggr 애그리게이트를 노드 1에서 노드 2로 이동하는 경우:

+
'Storage aggregate relocation start -node_node1_-destination_node2_-aggregate-list_aggr1_,_aggr2_,_test2_aggr_'



. 클러스터 HA 비활성화:
+
[source, cli]
----
cluster ha modify -configured false
----
+
클러스터 HA가 비활성화되면 epsilon은 자동으로 노드 1로 이동합니다. 반환 출력은 HA가 비활성화되었음을 확인합니다: `Notice: HA is disabled`

+

NOTE: 이 작업을 수행해도 스토리지 페일오버가 비활성화되지 않습니다.

. 정지 또는 재부팅할 노드가 노드 1인 경우 epsilon을 노드 2로 이동합니다.
+
.. 권한 수준을 고급으로 설정합니다.
+
[source, cli]
----
set -privilege advanced
----
.. 노드 2가 정상이며 epsilon 할당에 적합한지 확인하십시오.
+
[source, cli]
----
cluster show
----
.. 노드 1에서 epsilon을 제거합니다.
+
[source, cli]
----
cluster modify -node <node1_name> -epsilon false
----
.. 노드 2에 epsilon을 할당합니다.
+
[source, cli]
----
cluster modify -node <node2_name> -epsilon true
----
.. epsilon이 노드 2에 있는지 확인합니다.
+
[source, cli]
----
cluster show
----


. 대상 노드를 중지 또는 재부팅하고 테이크오버를 억제합니다.
+
[cols="1h,1h"]
|===


 a| 
테이크오버를 시작하지 않고 노드를 중지합니다.
 a| 
[source, cli]
----
system node halt -node _node_name_ -inhibit-takeover true
----


 a| 
테이크오버를 시작하지 않고 노드를 재부팅합니다.
 a| 
[source, cli]
----
system node reboot -node _node_name_ -inhibit-takeover true
----
|===
+

NOTE: 명령 출력에 계속할 것인지 묻는 경고가 표시됩니다. y를 입력합니다.

. 파트너가 다운된 동안 여전히 온라인 상태인 노드가 정상 상태인지 확인합니다.
+
[source, cli]
----
cluster show
----
+
온라인 노드의 경우 "참"이 "상태" 열에 나타납니다.

+

NOTE: 명령 출력에서 클러스터 HA가 구성되지 않았다는 경고 메시지가 표시됩니다. 이 경고는 무시해도 됩니다.

. 노드를 중지하거나 재부팅하는 데 필요한 작업을 수행합니다.
. LOADER 프롬프트에서 오프라인 상태인 노드를 부팅합니다.
+
[source, cli]
----
boot_ontap
----
. 두 노드가 모두 정상 상태인지 확인합니다.
+
[source, cli]
----
cluster show
----
+
두 노드 모두 '건강' 칼럼에 '참'이 나타납니다.

+

NOTE: 명령 출력에 클러스터 HA가 구성되지 않았다는 경고가 표시됩니다. 지금은 경고를 무시할 수 있습니다.

. 클러스터 HA 재활성화:
+
[source, cli]
----
cluster ha modify -configured true
----
. 이 절차의 앞부분에서 애그리게이트를 파트너 노드로 재배치한 경우 홈 노드로 다시 이동합니다.
+
[source, cli]
----
storage aggregate relocation start -node <node_name> -destination <node_name> -aggregate-list <aggregate_name>
----
+
예를 들어, aggr1, aggr2 및 test2_aggr을 노드 node2에서 노드 node1로 이동하는 경우:'storage aggregate relocation start -node_node2_-destination_node1_-aggregate-list_aggr1_,_aggr2_,_test2_aggr_'입니다

. LIF를 홈 포트로 되돌리기:
+
.. 홈 상태가 아닌 LIF 보기:
+
[source, cli]
----
network interface show -is-home false
----
+
에 대한 자세한 내용은 `network interface show` link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

.. 다운 노드에서 마이그레이션되지 않은 비홈 LIF가 있는 경우 되돌리기 전에 LIF를 이동해도 되는지 확인하십시오.
.. 안전하다면 모든 LIF를 홈으로 되돌리십시오.
+
[source, cli]
----
 network interface revert *
----
+
에 대한 자세한 내용은 `network interface revert` link:https://docs.netapp.com/us-en/ontap-cli/network-interface-revert.html["ONTAP 명령 참조입니다"^]을 참조하십시오.





.관련 정보
* link:https://docs.netapp.com/us-en/ontap-cli/cluster-ha-modify.html["클러스터 ha 수정"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-relocation-start.html["저장소 집계 재배치 시작"^]

