---
permalink: san-config/configure-fc-adapters-initiator-target.html 
sidebar: sidebar 
keywords: configure, fc adapters, initiator mode, target mode, FC-NVMe, FC adapter speed 
summary: 온보드 FC 어댑터 및 일부 FC 확장 어댑터 카드는 이니시에이터 또는 대상 포트로 구성할 수 있습니다. 다른 FC 확장 어댑터는 출고 시 이니시에이터 또는 대상으로 구성되므로 변경할 수 없습니다. 
---
= FC 어댑터를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
온보드 FC 어댑터 및 일부 FC 확장 어댑터 카드는 이니시에이터 또는 대상 포트로 개별적으로 구성할 수 있습니다. 다른 FC 확장 어댑터는 출고 시 이니시에이터 또는 대상으로 구성되므로 변경할 수 없습니다. FC SFP+ 어댑터로 구성된 지원 UTA2 카드를 통해서도 추가 FC 포트를 사용할 수 있습니다.

이니시에이터 포트를 사용하여 백엔드 디스크 쉘프 및 외부 스토리지 어레이에 직접 연결할 수 있습니다. 타겟 포트는 FC 스위치에만 연결할 수 있습니다.

FC용으로 구성된 온보드 포트 및 CNA/UTA2 포트의 수는 컨트롤러의 모델에 따라 다릅니다. 지원되는 타겟 확장 어댑터도 컨트롤러 모델에 따라 다릅니다. 컨트롤러 모델에 지원되는 온보드 FC 포트 및 타겟 확장 어댑터의 전체 목록은 를 참조하십시오link:https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^].



== 이니시에이터 모드에 맞게 FC 어댑터를 구성합니다

이니시에이터 모드는 FlexArray 가상화 또는 FLI(Foreign LUN Import)를 사용하여 포트를 테이프 드라이브, 테이프 라이브러리 또는 타사 스토리지에 연결하는 데 사용됩니다.

.시작하기 전에
* 어댑터에 있는 LIF는 해당 LIF가 구성원인 포트 세트에서 제거해야 합니다.
* 물리적 포트의 속성을 타겟에서 이니시에이터로 변경하기 전에 수정할 물리적 포트를 사용하는 모든 SVM(스토리지 가상 머신)의 모든 LIF를 마이그레이션 또는 제거해야 합니다.


[NOTE]
====
NVMe/FC는 이니시에이터 모드를 지원합니다.

====
.단계
. 어댑터에서 모든 LIF를 제거합니다.
+
[source, cli]
----
network interface delete -vserver _SVM_name_ -lif _lif_name_,_lif_name_
----
. 어댑터를 오프라인 상태로 전환:
+
[source, cli]
----
network fcp adapter modify -node _node_name_ -adapter _adapter_port_ -status-admin down
----
+
어댑터가 오프라인 상태가 되지 않으면 시스템의 해당 어댑터 포트에서 케이블을 분리할 수도 있습니다.

. 어댑터를 타겟에서 이니시에이터로 변경합니다.
+
[source, cli]
----
system hardware unified-connect modify -t initiator _adapter_port_
----
. 변경한 어댑터를 호스팅하는 노드를 재부팅합니다.
. FC 포트가 구성에 맞는 올바른 상태로 구성되었는지 확인합니다.
+
[source, cli]
----
system hardware unified-connect show
----
. 어댑터를 다시 온라인으로 전환합니다.
+
[source, cli]
----
node run -node _node_name_ storage enable adapter _adapter_port_
----




== FC 어댑터를 타겟 모드로 구성합니다

타겟 모드는 포트를 FC 이니시에이터에 연결하는 데 사용됩니다.

FC 프로토콜 및 FC-NVMe 프로토콜에 사용할 FC 어댑터를 구성하는 데 동일한 단계가 사용됩니다. 하지만 특정 FC 어댑터만 FC-NVMe를 지원합니다. FC-NVMe 프로토콜을 지원하는 어댑터 목록은 를 참조하십시오link:https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^].

.단계
. 어댑터를 오프라인 상태로 전환:
+
[source, cli]
----
node run -node _node_name_ storage disable adapter _adapter_name_
----
+
어댑터가 오프라인 상태가 되지 않으면 시스템의 해당 어댑터 포트에서 케이블을 분리할 수도 있습니다.

. 어댑터를 이니시에이터에서 타겟으로 변경합니다.
+
[source, cli]
----
system node hardware unified-connect modify -t target -node _node_name_ adapter _adapter_name_
----
. 변경한 어댑터를 호스팅하는 노드를 재부팅합니다.
. 타겟 포트의 구성이 올바른지 확인합니다.
+
[source, cli]
----
network fcp adapter show -node _node_name_
----
. 어댑터를 온라인으로 전환합니다.
+
[source, cli]
----
network fcp adapter modify -node _node_name_ -adapter _adapter_port_ -state up
----




== FC 어댑터 속도를 구성합니다

자동 협상을 사용하는 대신 어댑터 대상 포트 속도를 연결할 장치의 속도와 일치하도록 구성해야 합니다. autonegotiation으로 설정된 포트는 Takeover/Giveback 또는 기타 중단 후 다시 연결하는 데 더 오랜 시간이 걸릴 수 있습니다.

.이 작업에 대해
이 작업에는 클러스터의 모든 SVM(Storage Virtual Machine)과 모든 LIF가 포함되므로 이 작업의 범위를 제한하려면 '-home-port' 및 '-home-lif' 매개 변수를 사용해야 합니다. 이러한 매개 변수를 사용하지 않으면 클러스터에 있는 모든 LIF에 작업이 적용되며, 이는 바람직하지 않을 수 있습니다.

.시작하기 전에
이 어댑터를 홈 포트로 사용하는 모든 LIF는 오프라인 상태여야 합니다.

.단계
. 이 어댑터의 모든 LIF를 오프라인 상태로 전환:
+
[source, cli]
----
network interface modify -vserver * -lif * { -home-node node1 -home-port 0c } -status-admin down
----
. 어댑터를 오프라인 상태로 전환:
+
[source, cli]
----
network fcp adapter modify -node node1 -adapter 0c -state down
----
+
어댑터가 오프라인 상태가 되지 않으면 시스템의 해당 어댑터 포트에서 케이블을 분리할 수도 있습니다.

. 포트 어댑터의 최대 속도를 확인합니다.
+
[source, cli]
----
fcp adapter show -instance
----
+
어댑터 속도를 최대 속도 이상으로 수정할 수 없습니다.

. 어댑터 속도를 변경합니다.
+
[source, cli]
----
network fcp adapter modify -node node1 -adapter 0c -speed 16
----
. 어댑터를 온라인으로 전환합니다.
+
[source, cli]
----
network fcp adapter modify -node node1 -adapter 0c -state up
----
. 어댑터에 있는 모든 LIF를 온라인으로 전환합니다.
+
[source, cli]
----
network interface modify -vserver * -lif * { -home-node node1 -home-port 0c } -status-admin up
----

