---
permalink: san-config/determine-supported-nodes-task.html 
sidebar: sidebar 
keywords: determine, number, supported, nodes, san configurations 
summary: ONTAP에서 지원하는 클러스터당 노드 수는 ONTAP 버전, 클러스터의 스토리지 컨트롤러 모델, 클러스터 노드의 프로토콜에 따라 다릅니다. 
---
= ONTAP 클러스터당 지원되는 최대 노드 및 SAN 호스트를 결정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터당 지원되는 노드 수는 ONTAP 버전, 컨트롤러 모델 및 클러스터 노드의 프로토콜에 따라 다릅니다. 클러스터에 연결할 수 있는 최대 SAN 호스트 수도 사용자의 특정 구성에 따라 다릅니다.



== 클러스터당 지원되는 최대 노드를 확인합니다

클러스터의 노드가 FC, FC-NVMe, FCoE 또는 iSCSI에 대해 구성된 경우 해당 클러스터는 SAN 노드 제한으로 제한됩니다. 클러스터의 컨트롤러에 기반한 노드 제한은 _Hardware Universe_에 나열되어 있습니다.

.단계
. 로 이동합니다 https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^].
. 왼쪽 위에서 * 홈 * 옆에 있는 * 플랫폼 * 을 선택한 다음 플랫폼 유형을 선택합니다.
. 사용 중인 ONTAP 버전을 선택합니다.
+
플랫폼을 선택할 수 있는 새 열이 표시됩니다.

. 솔루션에 사용되는 플랫폼을 선택하십시오.
. Choose your Specifications(사양 선택) * 에서 * Select All(모두 선택) * 을 선택 취소합니다.
. Max Nodes per Cluster(NAS/SAN) * 를 선택합니다.
. 결과 표시 * 를 클릭합니다.


.결과
선택한 플랫폼에 대한 클러스터당 최대 노드가 표시됩니다.



== 클러스터에서 더 많은 FC 호스트를 지원할 수 있는지 확인합니다

FC 및 FC-NVMe 구성의 경우 시스템에서 이니시에이터-타겟 nexuse(ITN) 수를 사용하여 클러스터에 호스트를 더 추가할 수 있는지 확인해야 합니다.

ITN은 호스트의 이니시에이터에서 스토리지 시스템의 타겟으로 연결되는 하나의 경로를 나타냅니다. FC 및 FC-NVMe 구성의 노드당 최대 ITN 수는 2,048개입니다. 최대 ITN 수 미만이면 계속해서 클러스터에 호스트를 추가할 수 있습니다.

클러스터에서 사용되는 ITN 수를 확인하려면 클러스터의 각 노드에 대해 다음 단계를 수행하십시오.

.단계
. 특정 노드에서 모든 LIF를 식별합니다.
. 노드의 모든 LIF에 대해 다음 명령을 실행합니다.
+
[source, cli]
----
fcp initiator show -fields wwpn, lif
----
+
명령 출력의 하단에 표시되는 항목 수는 해당 LIF의 ITN 수를 나타냅니다.

. 각 LIF에 대해 표시되는 ITN 수를 기록합니다.
. 클러스터의 모든 노드에 있는 각 LIF의 ITN 수를 추가합니다.
+
이 합계는 클러스터의 ITN 수를 나타냅니다.





== 클러스터에서 더 많은 iSCSI 호스트를 지원할 수 있는지 확인합니다

노드에 직접 연결할 수 있거나 하나 이상의 스위치를 통해 연결할 수 있는 호스트의 수는 사용 가능한 이더넷 포트의 수에 따라 달라집니다. 사용 가능한 이더넷 포트 수는 컨트롤러의 모델 및 컨트롤러에 설치된 어댑터의 수와 유형에 따라 결정됩니다. 컨트롤러 및 어댑터에 지원되는 이더넷 포트 수는 _Hardware Universe_에서 확인할 수 있습니다.

모든 다중 노드 클러스터 구성의 경우, 클러스터에 호스트를 더 추가할 수 있는지 여부를 알 수 있도록 노드당 iSCSI 세션 수를 결정해야 합니다. 클러스터가 노드당 최대 iSCSI 세션 수보다 많은 경우 계속해서 클러스터에 호스트를 추가할 수 있습니다. 노드당 최대 iSCSI 세션 수는 클러스터의 컨트롤러 유형에 따라 달라집니다.

.단계
. 노드에서 모든 타겟 포털 그룹을 식별합니다.
. 노드의 모든 타겟 포털 그룹에 대한 iSCSI 세션 수를 확인합니다.
+
[source, cli]
----
iscsi session show -tpgroup _tpgroup_
----
+
명령 출력 하단에 표시되는 항목 수는 해당 타겟 포털 그룹에 대한 iSCSI 세션 수를 나타냅니다.

. 각 타겟 포털 그룹에 대해 표시되는 iSCSI 세션 수를 기록합니다.
. 노드의 각 타겟 포털 그룹에 대한 iSCSI 세션 수를 추가합니다.
+
총계 는 노드의 iSCSI 세션 수를 나타냅니다.


