---
permalink: san-config/fibre-channel-fcoe-zoning-concept.html 
sidebar: sidebar 
keywords: fibre, channel, fcoe zoning 
summary: FC, FC-NVMe 또는 FCoE 존은 패브릭 내 하나 이상의 포트를 논리적으로 그룹화한 것입니다. 장치가 서로 보고, 연결하고, 서로 세션을 만들고, 통신하려면 두 포트 모두 공통 영역 구성원이 있어야 합니다. 단일 이니시에이터 조닝을 사용하는 것이 좋습니다. 
---
= 파이버 채널 및 FCoE 조닝 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FC, FC-NVMe 또는 FCoE 존은 패브릭 내 하나 이상의 포트를 논리적으로 그룹화한 것입니다. 장치가 서로 보고, 연결하고, 세션을 만들고, 통신할 수 있으려면 두 포트가 모두 같은 존의 구성원이어야 합니다.

조닝을 사용하면 공통 영역을 공유하는 엔드 포인트에 대한 액세스 및 연결을 제한하여 보안을 강화할 수 있습니다. 같은 존에 없는 포트는 서로 통신할 수 없습니다. 이렇게 하면 이니시에이터 HBA 간의 _crosstalk_가 감소되거나 제거됩니다. 연결 문제가 발생할 경우 조닝(zoning)을 통해 문제를 특정 포트 세트로 격리하여 해결 시간을 단축할 수 있습니다.

조닝으로 인해 특정 포트에 대해 사용 가능한 경로 수가 감소하고 호스트와 스토리지 시스템 사이의 경로 수가 감소합니다. 예를 들어, 일부 호스트 OS 다중 경로 솔루션에는 관리 가능한 경로 수에 제한이 있습니다. 조닝을 통해 호스트에 표시되는 경로 수를 줄일 수 있으므로 호스트에 대한 경로가 호스트 운영 체제에서 허용하는 최대 경로를 초과하지 않도록 할 수 있습니다.



== World Wide Name 기반 조닝

WWN(World Wide Name)을 기반으로 하는 조닝은 영역 내에 포함할 구성원의 WWN을 지정합니다. 일부 스위치 공급업체에서는 WWNN(World Wide Node Name) 조닝을 사용할 수 있지만, ONTAP에서 조닝(Zoning)을 사용하면 WWPN(World Wide Port Name) 조닝을 사용해야 합니다.

특정 포트를 올바르게 정의하고 NPIV를 효과적으로 사용하려면 WWPN 조닝이 필요합니다. FC 스위치는 노드에 있는 물리적 포트의 WWPN이 아니라 대상 LIF(논리 인터페이스)의 WWPN을 사용하여 조닝되어야 합니다. 물리적 포트의 WWPN은 ""50"으로 시작하고 LIF의 WWPN은 ""20"으로 시작합니다.

WWPN 조닝을 사용하면 디바이스가 Fabric에 물리적으로 연결된 위치에 따라 액세스가 결정되지 않으므로 유연성이 제공됩니다. 영역을 재구성하지 않고도 한 포트에서 다른 포트로 케이블을 이동할 수 있습니다.
