---
permalink: san-config/host-support-multipathing-concept.html 
sidebar: sidebar 
keywords: host, support, multipathing 
summary: 'ONTAP는 항상 FC 및 iSCSI 경로 모두에 ALUA(Asymmetric Logical Unit Access)를 사용합니다. FC 및 iSCSI 프로토콜에서 ALUA를 지원하는 호스트 구성을 사용해야 합니다.' 
---
= SAN 호스트 다중 경로에 대한 ONTAP 지원
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP는 FC와 iSCSI 호스트의 다중 경로에 대해 ALUA(Asymmetric Logical Unit Access) 소프트웨어를 사용합니다.

ONTAP 9.5부터 ANA(Asynchronous Namespace Access)를 사용하는 NVMe 호스트에 대해 다중 경로 HA(고가용성) 쌍 페일오버/반환이 지원됩니다. ONTAP 9.4에서 NVMe는 호스트에서 타겟으로의 경로를 하나만 지원하므로 애플리케이션 호스트는 HA 파트너에 대한 경로 페일오버를 관리해야 합니다.

ALUA 또는 ANA를 지원하는 특정 호스트 구성에 대한 자세한 내용은 를 참조하십시오 https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^] 및 https://docs.netapp.com/us-en/ontap-sanhost/index.html["ONTAP SAN 호스트 구성"] 호스트 운영 체제를 위한 것입니다.

HA 구성에서는 MPIO(다중 경로 I/O) 소프트웨어라고도 하는 다중 경로 소프트웨어를 사용하는 것이 좋습니다. SAN 호스트에서 LUN 또는 NVMe 네임스페이스에 여러 경로를 통해 액세스할 수 있도록 다중 경로 소프트웨어가 필요합니다. 이 소프트웨어는 운영 체제에 LUN 또는 NVMe 네임스페이스에 대한 모든 경로에 대해 단일 디스크를 제공합니다. 다중 경로 소프트웨어가 없으면 운영 체제가 각 경로를 별개의 디스크로 인식하여 데이터 손상이 발생할 수 있습니다.

다음 중 하나가 있는 경우 솔루션은 여러 경로를 포함하는 것으로 간주됩니다.

* 호스트의 단일 이니시에이터 포트에서 SVM의 여러 SAN LIF에 연결됩니다
* 여러 이니시에이터 포트를 SVM의 단일 SAN LIF에 연결합니다
* 여러 이니시에이터 포트를 SVM의 여러 SAN LIF에 연결합니다


LUN 및 네임스페이스에 액세스하는 데 사용되는 경로를 제한하려면 Selective LUN Map, FC 스위치 zoning 또는 portset을 사용해야 합니다.

.관련 정보
link:../san-admin/multipath-automatic-lif-failover-support.html["ONTAP에서 지원하는 SAN multipath 구성"]에 대해 알아보십시오.



== 클러스터의 호스트에서 노드까지 권장되는 경로 수입니다

호스트에서 클러스터의 각 노드로 이어지는 경로가 8개를 초과할 수 없습니다. 또한 호스트 OS 및 호스트에서 사용되는 다중 경로에 대해 지원할 수 있는 총 경로 수를 초과하지 않아야 합니다.

클러스터에 4개 이상의 노드가 있거나 모든 노드에서 SVM이 사용하는 4개 이상의 타겟 포트가 있는 경우 다음 방법을 사용하여 노드의 LUN에 액세스하는 데 사용할 수 있는 경로 수를 제한하여 권장되는 최대 8개 경로를 초과하지 않도록 할 수 있습니다.

* link:../san-admin/selective-lun-map-concept.html["선택적 LUN 맵(SLM)"]
+
SLM은 호스트에서 LUN으로 가는 경로 수를 LUN을 소유한 노드와 소유 노드의 HA 파트너에 있는 경로로만 줄입니다. SLM은 기본적으로 활성화되어 있습니다.클러스터의 SVM(스토리지 가상 머신)에서 사용하는 SLM을 통해 각 보고 노드에 연결되는 LUN당 최소 2개의 경로가 있어야 합니다. 이렇게 하면 단일 장애 지점이 제거되고 구성 요소 장애 발생 시에도 시스템이 정상적으로 작동할 수 있습니다.

* link:../san-admin/limit-lun-access-portsets-igroups-concept.html["포트 세트"]
+
Portset을 SLM과 함께 사용하여 특정 타겟에 대한 액세스를 특정 이니시에이터에 추가로 제한할 수 있습니다. 포트 세트와 함께 SLM을 사용하는 경우 LUN을 소유한 노드의 HA 파트너와 해당 노드의 포트셋 LIF 세트에서 LUN에 액세스할 수 있습니다.

* 호스트의 이니시에이터 그룹(igroup) 매핑
+
이니시에이터 그룹을 정의하고 이를 LUN에 매핑하여 어떤 이니시에이터가 LUN에 액세스할 수 있는지 제어할 수 있습니다.

* link:../san-config/fc-fcoe-recommended-zoning-configuration.html["FC 스위치 조닝"]
+
호스트에 다중 경로 솔루션이 설치되어 있지 않거나, SAN에 4개 이상의 호스트가 연결되어 있거나, 클러스터의 노드에 SLM이 구현되어 있지 않은 경우 zoning 구성을 생성해야 합니다.


