---
permalink: upgrade/concept_mixed_version_requirements.html 
sidebar: sidebar 
keywords: ontap, upgrade, mixed, version, clusters, mixed-version nodes, requirements 
summary: 혼합 버전 ONTAP 클러스터는 ONTAP 9.8 및 9.12.1과 같이 두 가지 주요 ONTAP 릴리스를 실행하는 노드로 구성됩니다. 혼합 버전 ONTAP 클러스터는 특정 시나리오에서만 지원됩니다. 
---
= 혼합 버전 클러스터에 대한 ONTAP 버전의 호환성을 확인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
혼합 버전 ONTAP 클러스터에서 노드는 서로 다른 두 주요 ONTAP 버전을 단시간 동안 실행합니다. 예를 들어, ONTAP 9.8 및 9.12.1 또는 ONTAP 9.9.1 및 9.13.1을 실행하는 노드가 포함된 클러스터는 혼합 버전 클러스터입니다. ONTAP 9.9.1P1 및 9.9.1P5와 같이 동일한 버전 내에서 서로 다른 패치 수준을 실행하는 노드가 있는 클러스터는 혼합 버전 클러스터가 아닙니다.


NOTE: 혼합 버전 클러스터는 Cloud Volumes ONTAP에 대해 지원되지 않습니다.

NetApp는 제한된 기간 및 특정 시나리오에서 혼합 버전 ONTAP 클러스터를 지원합니다.

다음은 ONTAP 클러스터가 혼합 버전 상태가 되는 가장 일반적인 시나리오입니다.

* 대규모 클러스터에서 ONTAP 소프트웨어 업그레이드
+
대규모 클러스터의 모든 노드를 업그레이드하는 데 며칠 또는 몇 주가 걸릴 수 있습니다. 클러스터는 모든 노드가 업그레이드될 때까지 혼합 버전으로 전환되고 유지됩니다.

* 클러스터에 새 노드를 추가할 계획이라면 ONTAP 소프트웨어 업그레이드가 필요합니다
+
클러스터에 새 노드를 추가하여 용량을 확장하거나, 컨트롤러를 완전히 교체하는 프로세스에서 새 노드를 추가할 수 있습니다. 어느 경우든 기존 컨트롤러에서 새 시스템의 새로운 노드로 데이터를 마이그레이션할 수 있도록 혼합 버전 상태를 입력해야 할 수 있습니다.



최적의 클러스터 운영을 위해서는 클러스터가 혼합 버전 상태에 있는 시간이 최대한 짧아야 합니다. 혼합 버전 상태에서 클러스터가 지원을 받을 수 있는 최대 기간은 클러스터에서 가장 낮은 ONTAP 버전에 따라 다릅니다.

[cols="2"]
|===
| 혼합 버전 클러스터에서 실행 중인 ONTAP의 최하위 버전이 다음과 같은 경우... | 그런 다음 최대 혼합 버전 상태를 유지할 수 있습니다. 


| ONTAP 9.8 이상 | 90일 


| ONTAP 9.7 이하 | 7일 
|===
클러스터가 혼합 버전 상태에 있는 동안에는 업그레이드 또는 데이터 마이그레이션 프로세스에 필요한 명령을 제외하고 클러스터 작업 또는 구성을 변경하는 명령을 입력할 수 없습니다. 예를 들어, LIF 마이그레이션, 계획된 스토리지 페일오버 작업 또는 대규모 오브젝트 생성 또는 삭제 등의 작업은 업그레이드 및 데이터 마이그레이션이 완료될 때까지 수행해서는 안 됩니다.



== ONTAP 소프트웨어 업그레이드에 지원되는 혼합 버전 클러스터

최신 릴리스에서 직접 업그레이드할 수 있도록 지원되는 모든 ONTAP 버전과 함께 혼합 버전 상태를 입력할 수 있습니다. 예를 들어, ONTAP 9.11.1을 실행하는 경우 ONTAP 9.15.1을 실행하는 노드와 혼합 버전 상태를 입력할 수 있습니다. ONTAP 9.11.1 및 ONTAP 9.16.1을 실행하는 노드에서는 혼합 버전 상태를 입력할 수 없습니다. ONTAP 9.16.1은 ONTAP 9.11.1에서 직접 업그레이드할 수 없습니다.


NOTE: ONTAP 패치(P) 릴리스 버전은 혼합 버전 클러스터의 호환성에 영향을 미치지 않습니다. 예를 들어 ONTAP 9.11.1P6을 실행 중인 경우, 혼합 버전 클러스터 호환성을 위한 현재 ONTAP 릴리스는 ONTAP 9.11.1입니다. 또는 ONTAP 9.12.1을 실행 중이고 ONTAP 9.15.1P2로 업그레이드하려는 경우, 혼합 버전 클러스터 호환성을 위한 대상 ONTAP 릴리스는 ONTAP 9.15.1입니다.

현재 릴리스에서 직접 업그레이드를 지원하지 않는 ONTAP 버전으로 업그레이드하려면 다단계 업그레이드를 수행해야 합니다. 다단계 업그레이드에서는 먼저 현재 릴리스에서 직접 업그레이드할 수 있도록 지원되는 가장 높은 릴리스의 혼합 버전 상태를 입력합니다. 업그레이드를 완료한 다음 대상 릴리스로 별도의 업그레이드를 수행합니다. 예를 들어, 최신 릴리즈가 ONTAP 9.10.1이고 ONTAP 9.16.1로 업그레이드하려는 경우 먼저 혼합 버전 상태를 입력하여 모든 노드를 ONTAP 9.14.1로 업그레이드한 다음 ONTAP 9.14.1에서 ONTAP 9.16.1로 별도로 업그레이드합니다. 및 에 대해 자세히 link:concept_upgrade_paths.html#types-of-upgrade-paths["다단계 업그레이드"]link:concept_upgrade_paths.html#supported-upgrade-paths["지원되는 업그레이드 경로"]알아보십시오.

혼합 버전 클러스터에는 두 개의 주요 ONTAP 릴리즈만 포함될 수 있습니다. 예를 들어, ONTAP 9.13.1 및 9.15.1을 실행하는 노드 또는 ONTAP 9.13.1 및 9.16.1을 실행하는 노드와 혼합 버전 클러스터를 구성할 수 있습니다. ONTAP 9.13.1, 9.15.1 및 9.16.1을 실행하는 노드에서는 혼합 버전 클러스터를 사용할 수 없습니다.

[cols="25,25,50"]
|===
| 현재 ONTAP 릴리스를 사용하는 경우… | 대상 ONTAP 릴리스는 다음과 같습니다. | 업그레이드를 위한 혼합 버전 상태는... 


| 9.16.1 | 9.17.1 | 지원 


.2+| 9.15.1 | 9.17.1 | 지원 


| 9.16.1 | 지원 


.3+| 9.14.1 | 9.17.1 | 지원 


| 9.16.1 | 지원 


| 9.15.1 | 지원 


.4+| 9.13.1 | 9.17.1 | 지원 


| 9.16.1 | 지원 


| 9.15.1 | 지원 


| 9.14.1 | 지원 


.5+| 9.12.1 | 9.17.1 | 지원되지 않습니다 


| 9.16.1 | 지원 


| 9.15.1 | 지원 


| 9.14.1 | 지원 


| 9.13.1 | 지원 


.6+| 9.11.1 | 9.17.1 | 지원되지 않습니다 


| 9.16.1  a| 
지원되지 않습니다



| 9.15.1 | 지원 


| 9.14.1 | 지원 


| 9.13.1 | 지원 


| 9.12.1 | 지원 


.7+| 9.10.1 | 9.17.1 | 지원되지 않습니다 


| 9.16.1  a| 
지원되지 않습니다



| 9.15.1  a| 
지원되지 않습니다



| 9.14.1 | 지원 


| 9.13.1 | 지원 


| 9.12.1 | 지원 


| 9.11.1 | 지원 


.8+| 9.9.1 | 9.17.1 | 지원되지 않습니다 


| 9.16.1  a| 
지원되지 않습니다



| 9.15.1  a| 
지원되지 않습니다



| 9.14.1  a| 
지원되지 않습니다



| 9.13.1 | 지원 


| 9.12.1 | 지원 


| 9.11.1 | 지원 


| 9.10.1 | 지원 


.9+| 9.8 | 9.17.1 | 지원되지 않습니다 


| 9.16.1  a| 
지원되지 않습니다



| 9.15.1  a| 
지원되지 않습니다



| 9.14.1  a| 
지원되지 않습니다



| 9.13.1  a| 
지원되지 않습니다



| 9.12.1 | 지원 


| 9.11.1 | 지원 


| 9.10.1  a| 
지원



| 9.9.1 | 지원 
|===


== ONTAP 클러스터에 새 노드 추가

클러스터에 새 노드를 추가할 계획이고 해당 노드에 현재 클러스터에서 실행 중인 버전보다 더 최신 버전의 ONTAP가 필요한 경우, 새 노드를 추가하기 전에 클러스터에서 기존 노드에서 지원되는 소프트웨어 업그레이드를 수행해야 합니다. 클러스터에 추가할 노드에 필요한 최소 버전의 ONTAP로 기존 노드를 모두 업그레이드하는 것이 좋습니다. 그러나 기존 노드 중 일부가 최신 버전의 ONTAP를 지원하지 않기 때문에 이 작업이 불가능할 경우 업그레이드 프로세스의 일부로 제한된 시간 동안 혼합 버전 상태를 입력해야 합니다.

.단계
. link:concept_upgrade_methods.html["업그레이드"] 새로운 컨트롤러에 필요한 최소 ONTAP 버전을 지원하지 않는 노드는 지원하는 최대 ONTAP 버전까지 지원합니다.
+
예를 들어, FAS8080이 ONTAP 9.5를 실행하는 ONTAP FAS8010을 실행하는 새 C-Series 플랫폼을 추가하려는 경우 FAS8080을 ONTAP 9.8(지원되는 최대 ONTAP 버전)으로 업그레이드해야 합니다.

. link:../system-admin/add-nodes-cluster-concept.html["클러스터에 새 노드를 추가합니다"^].
. link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-create-aggregate-move-volumes.html["데이터를 마이그레이션합니다"^] 클러스터에서 제거 중인 노드에서 새로 추가한 노드로 이동합니다.
. link:../system-admin/remove-nodes-cluster-concept.html["클러스터에서 지원되지 않는 노드를 제거합니다"^]..
. link:concept_upgrade_methods.html["업그레이드"] 클러스터의 나머지 노드는 새 노드와 동일한 버전으로 유지됩니다.
+
필요한 경우 전체 클러스터(새 노드 포함)를 로 업그레이드합니다 link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU2["권장되는 최신 패치 릴리스"] 새 노드에서 실행되는 ONTAP 버전의 번호입니다.



데이터 마이그레이션에 대한 자세한 내용은 다음을 참조하십시오.

* link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-create-aggregate-move-volumes.html["애그리게이트를 생성하고 볼륨을 새 노드로 이동합니다"^]
* link:https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_linux_iscsi_hosts_from_mcc_fc_to_mcc_ip_nodes.html#setting-up-new-iscsi-connections["SAN 볼륨 이동에 대한 새 iSCSI 연결을 설정합니다"^]
* link:../encryption-at-rest/encrypt-existing-volume-task.html["암호화를 사용하여 볼륨 이동"^]

