---
permalink: upgrade/create-upgrade-plan.html 
sidebar: sidebar 
keywords: ontap, upgrade, plan, planning, upgrade advisor, upgrade health checker, advisor, digital advisor, active iq, create an upgrade plan 
summary: Active IQ Digital Advisor 또는 Upgrade Health Checker의 Upgrade Advisor를 사용하여 사용자 환경 및 클러스터 구성에 맞는 업그레이드 보고서를 자동으로 생성할 수 있습니다. 
---
= Upgrade Advisor 또는 Upgrade Health Checker를 사용하여 ONTAP 업그레이드를 준비하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Digital Advisor 또는 Upgrade Health Checker의 Upgrade Advisor를 사용하여 환경 및 클러스터 구성에 맞는 업그레이드 보고서를 자동으로 생성할 수 있습니다. 두 도구 모두 업그레이드 계획을 수립하고 차단 요소와 경고를 식별하며 불확실성과 위험을 최소화하는 데 도움이 되는 인텔리전스를 제공합니다.



== Upgrade Advisor로 업그레이드 준비

Upgrade Advisor는 최신 ONTAP 버전으로 업그레이드하여 해결할 수 있는 환경의 문제를 식별하고 업그레이드하려는 ONTAP 버전에서 주의해야 할 문제에 대한 보고서를 제공합니다. Upgrade Advisor는 또한 권장 업그레이드 경로를 제시하고 클러스터 구성에 맞는 업그레이드 계획을 생성합니다.

Upgrade Advisor는 클라우드 기반의 UI 중심 환경을 선호하는 소규모 환경의 사용자에게 특히 적합합니다.

.시작하기 전에
* Upgrade Advisor를 사용하려면 link:https://www.netapp.com/us/services/support-edge.aspx["SupportEdge 서비스"^] 계약이 link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["디지털 자문업체"^]에 대해 활성화되어 있어야 합니다.
* 업그레이드 어드바이저가 업그레이드 계획을 생성하는 데 필요한 AutoSupport 로그에 자동으로 액세스하려면 AutoSupport가 활성화되어 있어야 합니다. AutoSupport를 활성화하지 않은 경우 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_manually_upload_AutoSupport_messages_to_NetApp_in_ONTAP_9["AutoSupport 파일을 수동으로 업로드합니다"^].


.단계
. https://aiq.netapp.com/["Active IQ Digital Advisor를 시작합니다"^]
. 디지털 자문link:https://docs.netapp.com/us-en/active-iq/task_view_risk_and_take_action.html["클러스터와 관련된 모든 위험을 확인하고 수동으로 수정 조치를 취할 수 있습니다"^].
+
ONTAP 업그레이드를 수행하기 전에 * 소프트웨어 구성 변경 *, * 하드웨어 구성 변경 * 및 * 하드웨어 교체 * 범주에 포함된 위험을 해결해야 합니다.

. 권장 업그레이드 경로 및 를 검토합니다 link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["업그레이드 계획을 생성합니다"^].


.다음 단계
* 를 검토해야 합니다 link:../release-notes/index.html["ONTAP 릴리즈 노트"] Upgrade Advisor가 클러스터에 권장하는 타겟 ONTAP 릴리즈의 경우 Upgrade Advisor에서 생성한 계획에 따라 클러스터를 업그레이드해야 합니다.
* 당신은 해야 한다 link:reboot-sp-bmc.html["SP 또는 BMC를 재부팅합니다"] 업그레이드 시작 전.




== Upgrade Health Checker로 업그레이드 준비

Upgrade Health Checker는 규모가 크거나 복잡한 환경, 인터넷 접속이 제한적인 환경, 또는 기존 자동화 및 오케스트레이션 프레임워크를 사용하는 사용자에게 적합한 온프레미스 도구입니다. Upgrade Health Checker를 사용하기 위해 SupportEdge 계약이 필요한 것은 아닙니다.

.시작하기 전에
업그레이드 계획을 생성하는 데 사용하려면 먼저 link:https://docs.netapp.com/us-en/upgrade-health-checker/set-up-upgrade-health-checker.html["Upgrade Health Checker를 다운로드하고 설정합니다"]해야 합니다.

.단계
. link:https://docs.netapp.com/us-en/upgrade-health-checker/generate-report-upgrade-health-checker.html["Upgrade Health Checker를 사용하여 업그레이드 계획 생성"^].


.다음 단계
* 클러스터에 권장되는 대상 ONTAP 릴리스에 대한 link:../release-notes/index.html["ONTAP 릴리즈 노트"]을(를) 검토한 다음 Upgrade Health Checker에서 생성된 계획에 따라 클러스터를 업그레이드해야 합니다.
* 당신은 해야 한다 link:reboot-sp-bmc.html["SP 또는 BMC를 재부팅합니다"] 업그레이드 시작 전.

