---
permalink: upgrade/index.html 
sidebar: sidebar 
keywords: upgrade overview, upgrade, digital advisor, summary, upgrade ontap, upgrading ontap, upgrade, upgrading, ontap, software, on-premise, prepare, preparation, major upgrade, minor upgrade, patch upgrade, upgrade assistance, upgrade help, upgrade technical support 
summary: ONTAP 업그레이드를 통해 새롭고 향상된 기능을 활용할 수 있습니다. 시작하기 전에 권장 단계에 따라 업그레이드를 준비합니다. 
---
= ONTAP 업그레이드에 대해 알아봅니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 소프트웨어를 업그레이드할 때 새롭고 개선된 ONTAP 기능을 활용하여 비용 절감, 중요한 워크로드 가속화, 보안 향상, 조직에 제공되는 데이터 보호 범위 확장에 도움이 됩니다.

주요 ONTAP 업그레이드는 더 낮은 번호의 ONTAP 릴리스에서 더 높은 번호의 ONTAP 릴리스로 이동하는 것을 의미합니다. 예를 들어 클러스터를 ONTAP 9.14.1에서 ONTAP 9.18.1로 업그레이드하는 경우가 있습니다. 마이너(또는 패치) 업그레이드는 동일한 번호의 릴리스 내에서 더 낮은 ONTAP 버전에서 더 높은 ONTAP 버전으로 이동하는 것을 의미합니다. 예를 들어 클러스터를 ONTAP 9.17.1P1에서 9.17.1P4로 업그레이드하는 경우가 있습니다.

업그레이드를 시작하려면 다음 방법 중 하나를 사용하여 준비할 수 있습니다.

* 업그레이드 어드바이저
+
Active IQ Digital Advisor(Digital Advisor라고도 함)에 대한 활성 SupportEdge 계약이 있는 경우 link:create-upgrade-plan.html["Upgrade Advisor로 업그레이드 준비"]. Upgrade Advisor는 클러스터를 평가하고 구성에 맞는 업그레이드 계획을 수립하여 불확실성과 위험을 최소화하는 데 도움이 되는 인텔리전스를 제공합니다.

+
Upgrade Advisor는 클라우드 기반의 사용자 인터페이스 중심 환경을 선호하는 소규모 환경의 사용자에게 적합합니다.

+
자세한 내용은 link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["업그레이드 어드바이저"^]을 참조하십시오.

* 업그레이드 상태 점검기
+
또한 link:create-upgrade-plan.html["Upgrade Health Checker를 사용하여 업그레이드 준비"]할 수도 있습니다. Upgrade Health Checker는 현장에서 포괄적인 상태 점검을 수행하여 업그레이드 차단 요인과 경고를 식별하는 업그레이드 자문 서비스 툴입니다. Upgrade Health Checker를 사용하는 데 SupportEdge 계약이 필요하지 않습니다.

+
Upgrade Health Checker는 규모가 크거나 복잡한 환경, 인터넷 액세스가 제한적이거나 기존 자동화 및 오케스트레이션 프레임워크가 있는 사용자에게 적합합니다.

+
자세한 내용은 link:https://docs.netapp.com/us-en/upgrade-health-checker/learn-about-upgrade-health-checker.html["업그레이드 상태 점검기"^]을 참조하십시오.

* 수동 준비
+
Upgrade Advisor 또는 Upgrade Health Checker 도구를 사용하지 않는 경우 link:prepare.html["수동으로 업그레이드 준비"]. 수동 준비에는 알려진 문제나 차단 요소를 확인하고 클러스터가 업그레이드에 필요한 요구 사항을 충족하는지 확인하기 위한 여러 작업이 포함됩니다.

+
자세한 내용은 link:prepare.html["수동 업그레이드 준비"^]을 참조하십시오.



업그레이드를 준비하고 나면 을 사용하여 업그레이드를 수행하는 것이 좋습니다link:task_upgrade_andu_sm.html["System Manager에서 자동 무중단 업그레이드(ANDU"]. ANDU는 ONTAP의 고가용성(HA) 장애 조치 기술을 활용하여 클러스터에서 업그레이드 중에 중단 없이 데이터를 계속 제공할 수 있도록 합니다.


NOTE: ONTAP 9.12.1부터 System Manager가 NetApp Console과 완벽하게 통합되었습니다.  시스템에 콘솔이 구성된 경우 시스템 페이지를 통해 업그레이드할 수 있습니다.

ONTAP 소프트웨어 업그레이드에 도움이 필요한 경우 NetApp 프로페셔널 서비스는 을 제공합니다 link:https://www.netapp.com/pdf.html?item=/media/8144-sd-managed-upgrade-service.pdf["관리형 업그레이드 서비스"^]. 이 서비스를 사용하는 데 관심이 있는 경우 NetApp 세일즈 담당자 또는 에게 문의하십시오 link:https://www.netapp.com/forms/sales-contact/["NetApp의 영업 문의 양식 제출"^]. Managed Upgrade Service 및 기타 유형의 업그레이드 지원은 를 사용하는 고객에게 제공됩니다 link:https://www.netapp.com/pdf.html?item=/media/8845-supportedge-expert-service.pdf["SupportEdge Expert 서비스"^] 추가 비용 없음.

.관련 정보
* link:concept_upgrade_paths.html["지원되는 업그레이드 경로"]

