---
permalink: upgrade/prepare.html 
sidebar: sidebar 
keywords: upgrade, ontap, prepare, digital advisor, preparation, before you upgrade, plan, upgrade overview, upgrade summary, upgrade health checker 
summary: ONTAP 업그레이드를 준비하면 업그레이드 위험 또는 차단기를 식별하고 완화하며 구성에 적용되는 특별한 고려 사항을 파악할 수 있습니다. 
---
= ONTAP 소프트웨어 업그레이드를 수동으로 준비합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
수동으로 업그레이드를 준비하는 경우, 알려진 문제나 장애 요소를 확인하고 클러스터가 업그레이드에 필요한 요구 사항을 충족하는지 확인하기 위해 여러 작업을 완료해야 합니다. 예를 들어, 클러스터에서 SSL FIPS 모드가 활성화되어 있고 관리자 계정이 인증에 SSH 공개 키를 사용하는 경우, 대상 ONTAP 릴리스에서 호스트 키 알고리즘이 지원되는지 확인해야 합니다.


NOTE: Active IQ Digital Advisor 또는 Upgrade Health Checker에서 Upgrade Advisor를 사용하면 수동 준비가 필요하지 않습니다. 두 도구 모두 업그레이드 계획을 수립하고, 문제점과 경고를 식별하고, 불확실성과 위험을 최소화하는 데 도움이 되는 정보를 제공합니다. link:create-upgrade-plan.html["Upgrade Advisor 또는 Upgrade Health Checker를 사용하여 업그레이드 준비"]에 대해 자세히 알아보십시오.

.단계
. link:choose-target-version.html["대상 ONTAP 릴리스를 선택합니다"].
. 대상 릴리스에 대한 의 _업그레이드 주의_및_알려진 문제 및 제한 사항_섹션을 검토하십시오link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 릴리즈 노트"].
+
_업그레이드 주의 사항_ 업그레이드하기 전에 알아야 할 잠재적인 문제에 대해 설명합니다. _알려진 문제 및 제한 사항_ 업그레이드 후 발생할 수 있는 예기치 않은 시스템 동작을 설명합니다.

+
릴리스 정보에 액세스하려면 NetApp 계정으로 로그인하거나 계정을 만들어야 합니다.

. link:confirm-configuration.html["하드웨어 구성에 대한 ONTAP 지원을 확인합니다"].
+
하드웨어 플랫폼, 클러스터 관리 스위치, MetroCluster IP 스위치가 타겟 릴리즈를 지원해야 합니다.  클러스터가 SAN용으로 구성된 경우 SAN 구성이 완전히 지원되어야 합니다.

. link:task_check_for_common_configuration_errors_using_config_advisor.html["Active IQ Config Advisor를 사용하여 일반적인 구성 오류가 없는지 확인합니다."]
. 지원되는 ONTAP를 검토합니다 link:concept_upgrade_paths.html#supported-upgrade-paths["업그레이드 경로"] 직접 업그레이드를 수행할 수 있는지 또는 업그레이드를 단계별로 완료해야 하는지 여부를 확인하려면
. link:task_verifying_the_lif_failover_configuration.html["LIF 페일오버 구성을 확인합니다"].
+
업그레이드를 수행하기 전에 클러스터의 페일오버 정책과 페일오버 그룹이 올바르게 구성되어 있는지 확인해야 합니다.

. link:concept_verify_svm_routing.html["SVM 라우팅 구성을 확인합니다"].
. link:special-considerations.html["특별 고려 사항을 확인합니다"] 확인할 수 있습니다.
+
클러스터에 특정 구성이 있는 경우 ONTAP 소프트웨어 업그레이드를 시작하기 전에 수행해야 할 특정 작업이 있습니다.

. link:reboot-sp-bmc.html["SP 또는 BMC를 재부팅합니다"].

