---
permalink: upgrade/snapmirror-cascade-relationship-blocked.html 
sidebar: sidebar 
keywords: ontap, upgrade, 9.9.1. 9.10.1, update, cascade, LTR, long term retention, snapshots, considerations, secondary storage 
summary: '클러스터에 SnapMirror 계단식 배열 관계가 구성되어 있는 경우 업그레이드하기 전에 LTR(장기 보존) 스냅샷을 해제해야 할 수 있습니다' 
---
= ONTAP 업그레이드 전에 장기 보존 스냅샷을 비활성화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9의 모든 버전에서 계단식 볼륨 관계에서 장기 보존(LTR) 스냅샷은 계단식 볼륨의 최종 SnapMirror 대상 볼륨에서만 지원됩니다.  캐스케이드의 중간 볼륨에서 LTR 스냅샷을 활성화하면 백업과 스냅샷이 누락됩니다.

자세히 알아보세요 link:../data-protection/long-term-retention-snapshots-concept.html["장기 보존 스냅샷"^] .

캐스케이드의 중간 볼륨에서 LTR 스냅샷이 활성화된 지원되지 않는 구성이 있는 경우 기술 지원 및 참조에 문의하세요.link:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/Cascading_a_volume_with_Long-Term_Retention_(LTR)_snapshots_enabled_is_not_supported["기술 자료 문서 장기 보존(LTR) 스냅샷이 활성화된 볼륨을 계단식으로 배열하는 것은 지원되지 않습니다."^] 도움이 필요하면.

다음 ONTAP 버전에서는 최종 SnapMirror 대상 볼륨을 제외한 캐스케이드의 모든 볼륨에서 LTR 스냅샷을 활성화할 수 없습니다.

* 9.15.1 이상
* 9.14.1P2 및 P4-P14
* 9.13.1P9-P17
* 9.12.1 P12-P19
* 9.11.1P15-P20
* 9.10.1P18-P20
* 9.9.1P20


캐스케이드의 중간 볼륨에서 LTR 스냅샷을 활성화할 수 있는 ONTAP 버전에서 이를 차단하는 ONTAP 버전으로 업그레이드하기 전에 LTR 스냅샷을 비활성화하여 백업 및 스냅샷 누락을 방지해야 합니다.

다음 시나리오에서 조치를 취해야 합니다.

* LTR(장기 보존) 스냅샷은 "A > B > C" SnapMirror 계단식 또는 더 큰 계단식 복수의 다른 중간 SnapMirror 대상 볼륨에 있는 "B" 볼륨에 구성됩니다.
* LTR 스냅샷은 SnapMirror 정책 규칙에 적용되는 스케줄에 의해 정의됩니다. 이 규칙은 소스 볼륨에서 스냅샷을 복제하지 않고 대상 볼륨에 직접 스냅샷을 생성합니다.
+

NOTE: 일정 및 SnapMirror 정책에 대한 자세한 내용은 기술 자료 문서 를 참조하십시오 https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/How_does_the_schedule_parameter_in_an_ONTAP_9_SnapMirror_policy_rule_work["ONTAP 9 SnapMirror 정책 규칙에서 "schedule" 매개 변수는 어떻게 작동합니까?"^].



.단계
. 중간 볼륨의 SnapMirror 정책에서 LTR 규칙을 제거합니다.
+
[listing]
----
Secondary::> snapmirror policy remove-rule -vserver <> -policy <> -snapmirror-label <>
----
+
자세히 알아보세요  `snapmirror policy remove-rule` 에서 link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-remove-rule.html["ONTAP 명령 참조입니다"^] .

. LTR 일정을 사용하지 않고 SnapMirror 레이블에 대한 규칙을 다시 추가합니다.
+
[listing]
----
Secondary::> snapmirror policy add-rule -vserver <> -policy <> -snapmirror-label <> -keep <>
----
+

NOTE: SnapMirror 정책 규칙에서 LTR 스냅샷을 제거하면 SnapMirror가 소스 볼륨에서 지정된 레이블을 가진 스냅샷을 가져옵니다. 소스 볼륨의 스냅샷 정책에 대한 스케줄을 추가하거나 수정하여 적절하게 레이블이 지정된 스냅샷을 생성해야 할 수도 있습니다.

+
에 대한 자세한 내용은 `snapmirror policy add-rule` link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-add-rule.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

. 필요한 경우 소스 볼륨 스냅샷 정책에 대한 일정을 수정하거나 생성하여 SnapMirror 레이블을 사용하여 스냅샷을 생성할 수 있습니다.
+
[listing]
----
Primary::> volume snapshot policy modify-schedule -vserver <> -policy <> -schedule <> -snapmirror-label <>
----
+
[listing]
----
Primary::> volume snapshot policy add-schedule -vserver <> -policy <> -schedule <> -snapmirror-label <> -count <>
----



NOTE: LTR 스냅샷은 SnapMirror 계단식 구성을 사용하는 최종 SnapMirror 대상 볼륨에 대해 계속 활성화할 수 있습니다.
