---
permalink: upgrade/snapmirror-cascade-relationship-blocked.html 
sidebar: sidebar 
keywords: ontap, upgrade, 9.9.1. 9.10.1, update, cascade, LTR, long term retention, snapshots, considerations, secondary storage 
summary: 클러스터에 SnapMirror 캐스케이드 관계가 구성되어 있는 경우 업그레이드하기 전에 장기 보존 스냅샷을 비활성화해야 할 수 있습니다. 
---
= ONTAP 업그레이드 전에 장기 보존 스냅샷을 비활성화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
계층형 볼륨 관계에서 장기 보존 스냅샷은 모든 ONTAP 9 버전에서 계층 구조의 최종 SnapMirror 대상 볼륨에서만 지원됩니다. 캐스케이드 구조의 중간 볼륨에서 장기 보존 스냅샷을 활성화하면 백업 및 스냅샷이 누락될 수 있습니다.

자세히 알아보세요link:../data-protection/long-term-retention-snapshots-concept.html["장기 보존 스냅샷"] .

캐스케이드 구성에서 중간 볼륨에 장기 보존 스냅샷이 활성화된 지원되지 않는 구성이 있는 경우 기술 지원팀에 문의하고 다음 링크를 참조하십시오. https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/Cascading_a_volume_with_Long-Term_Retention_ (long-term retention)_snapshots_enabled_is_not_supported[NetApp 기술 자료: 장기 보존(LTR) 스냅샷이 활성화된 볼륨의 캐스케이드 구성은 지원되지 않습니다^]

다음 ONTAP 버전에서는 최종 SnapMirror 대상 볼륨을 제외한 캐스케이드의 모든 볼륨에서 장기 보존 스냅샷을 활성화할 수 없습니다.

* 9.15.1 이상
* 9.14.1P2 및 P4부터 P14까지
* 9.13.1P9부터 P17까지
* 9.12.1 P12부터 P19까지
* 9.11.1P15부터 P20까지
* 9.10.1P18부터 P20까지
* 9.9.1P20


캐스케이드 구성의 중간 볼륨에 장기 보존 스냅샷을 활성화할 수 있는 ONTAP 버전에서 해당 기능을 차단하는 ONTAP 버전으로 업그레이드하기 전에 백업 및 스냅샷 누락을 방지하기 위해 장기 보존 스냅샷을 비활성화해야 합니다.

다음 시나리오에서 조치를 취해야 합니다.

* 장기 보존 스냅샷은 "A > B > C" SnapMirror 캐스케이드에서 "B" 볼륨 또는 더 큰 캐스케이드의 다른 중간 SnapMirror 대상 볼륨에 구성됩니다.
* 장기 보존 스냅샷은 SnapMirror 정책 규칙에 적용되는 일정에 따라 정의됩니다. 이 규칙은 소스 볼륨의 스냅샷을 복제하지 않고 대상 볼륨에 직접 스냅샷을 생성합니다.
+

NOTE: 일정 및 SnapMirror 정책에 대한 자세한 내용은 다음을 참조하세요.link:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/How_does_the_schedule_parameter_in_an_ONTAP_9_SnapMirror_policy_rule_work["NetApp 지식 기반: ONTAP 9 SnapMirror 정책 규칙의 "일정" 매개변수는 어떻게 작동합니까?"^] .



.단계
. 캐스케이드의 중간 볼륨에 있는 SnapMirror 정책에서 장기 보존 규칙을 제거합니다.
+
[listing]
----
Secondary::> snapmirror policy remove-rule -vserver <> -policy <> -snapmirror-label <>
----
+
자세히 알아보세요  `snapmirror policy remove-rule` 에서 link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-remove-rule.html["ONTAP 명령 참조입니다"^] .

. 장기 보존 일정 없이 SnapMirror 레이블에 대한 규칙을 다시 추가하세요.
+
[listing]
----
Secondary::> snapmirror policy add-rule -vserver <> -policy <> -snapmirror-label <> -keep <>
----
+

NOTE: SnapMirror 정책 규칙에서 장기 보존 스냅샷을 제거하면 SnapMirror 지정된 레이블이 있는 스냅샷을 소스 볼륨에서 가져옵니다. 적절한 레이블이 지정된 스냅샷을 생성하려면 소스 볼륨의 스냅샷 정책에 일정을 추가하거나 수정해야 할 수도 있습니다.

+
에 대한 자세한 내용은 `snapmirror policy add-rule` link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-add-rule.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

. 필요한 경우 소스 볼륨 스냅샷 정책에 대한 일정을 수정하거나 생성하여 SnapMirror 레이블을 사용하여 스냅샷을 생성할 수 있습니다.
+
[listing]
----
Primary::> volume snapshot policy modify-schedule -vserver <> -policy <> -schedule <> -snapmirror-label <>
----
+
[listing]
----
Primary::> volume snapshot policy add-schedule -vserver <> -policy <> -schedule <> -snapmirror-label <> -count <>
----



NOTE: SnapMirror 캐스케이드 구성에서 최종 SnapMirror 대상 볼륨에 대해 장기 보존 스냅샷을 활성화할 수 있습니다.
