---
permalink: performance-admin/adaptive-qos-policy-groups-task.html 
sidebar: sidebar 
keywords: use, adaptive, qos, policy, groups 
summary: 적응형 QoS 정책 그룹을 사용하면 볼륨 크기가 변경될 때 IOPS와 TB|GB의 비율을 유지하면서 처리량 상한 또는 하한 크기를 자동으로 확장할 수 있습니다. 이는 대규모 구축 환경에서 수백 또는 수천 개의 워크로드를 관리할 때 큰 이점입니다. 
---
= ONTAP에서 적응형 QoS 정책 그룹 사용
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
_적응형 QoS_ 정책 그룹을 사용하면 볼륨 크기에 맞게 처리량 상한선이나 하한선을 자동으로 조정하여 볼륨 크기가 변경되더라도 IOPS 대 TB/GB 비율을 유지할 수 있습니다.  이는 대규모 배포에서 수백 또는 수천 개의 작업 부하를 관리할 때 상당한 이점입니다.

.시작하기 전에
* ONTAP 9.3 이상을 실행해야 합니다. 적응형 QoS 정책 그룹은 ONTAP 9.3부터 사용할 수 있습니다.
* 정책 그룹을 생성하려면 클러스터 관리자여야 합니다.


.이 작업에 대해
스토리지 개체는 적응형 정책 그룹 또는 비적응 정책 그룹의 구성원일 수 있지만 둘 다 속할 수는 없습니다. 스토리지 오브젝트 및 정책의 SVM은 동일해야 합니다. 스토리지 객체가 온라인 상태여야 합니다.

적응형 QoS 정책 그룹은 항상 공유되지 않습니다. 정의된 처리량 상한 또는 최저값은 각 구성원 워크로드에 개별적으로 적용됩니다.

스토리지 오브젝트 크기에 대한 처리량 제한의 비율은 다음 필드의 상호 작용에 의해 결정됩니다.

* `expected-iops`할당된 TB/GB당 예상 최소 IOPS입니다.
+
[NOTE]
====
 `expected-iops` 는 AFF 플랫폼에서만 보장됩니다. `expected-iops` 계층화 정책이 "없음"으로 설정되어 있고 클라우드에 블록이 없는 경우에만 FabricPool에 대해 보장됩니다. `expected-iops` SnapMirror 동기식 관계에 없는 볼륨에 대해 보장합니다.

====
* `peak-iops`할당되거나 사용된 TB/GB당 가능한 최대 IOPS입니다.
* 'expected-IOPS-allocation'은 할당된 공간(기본값)이나 사용된 공간을 예상 IOPS에 사용할지 여부를 지정합니다.
+
[NOTE]
====
ONTAP 9.5 이상에서 '예상 IOPS 할당'을 사용할 수 있습니다. ONTAP 9.4 이하 버전에서는 지원되지 않습니다.

====
* peak-IOPS-allocation은 peak-IOPS를 위해 할당된 공간과 사용된 공간(기본값)을 사용할지 여부를 지정한다.
* 절대 최소 IOPS는 절대 최소 IOPS의 수입니다. 이 필드는 매우 작은 스토리지 객체와 함께 사용할 수 있습니다. 절대분 IOPS가 계산된 예상 IOPS보다 크면 peak-IOPS와 expected-IOPS를 모두 재정의합니다.
+
예를 들어, 'expected-IOPS'를 1,000 IOPS/TB로 설정하고 볼륨 크기가 1GB 미만인 경우 계산된 'expected-IOPS'는 IOP가 분수 값이 됩니다. 계산된 피크 IOPS는 이보다 훨씬 적은 비율입니다. 절대-최소-IOPS를 실제 값으로 설정하면 이러한 문제를 방지할 수 있습니다.

* 블록 크기 는 애플리케이션 입출력 블록 크기를 지정합니다. 기본값은 32K입니다. 유효한 값은 8K, 16K, 32K, 64K, any입니다. Any는 블록 크기가 적용되지 않음을 의미합니다.




== 기본 적응형 QoS 정책 그룹

다음 표에 나와 있는 것처럼 세 가지 기본 적응형 QoS 정책 그룹을 사용할 수 있습니다. 이러한 정책 그룹을 볼륨에 직접 적용할 수 있습니다.

|===


| 기본 정책 그룹입니다 | 예상 IOPS/TB | 최대 IOPS/TB | 절대 최소 IOPS 


 a| 
"익스트림"
 a| 
6,144
 a| 
12,288
 a| 
1000입니다



 a| 
'퍼포먼스'
 a| 
2,048
 a| 
4,096개
 a| 
500입니다



 a| 
값
 a| 
128
 a| 
512
 a| 
75를

|===


== 스토리지 개체 정책 그룹 할당 제한 사항

어떤 경우에는 정책 그룹에 저장 객체를 할당할 수 없습니다. 저장 객체를 포함하는 객체나 해당 객체의 자식 객체가 정책 그룹에 속해 있는 경우입니다.

ONTAP 9.18.1부터 중첩된 QoS 정책을 사용할 수 있습니다. 이를 통해 SVM과 같은 포함 개체와 볼륨과 같은 자식 개체 모두에 정책 그룹을 할당할 수 있습니다.  멀티 테넌트 환경에서 중첩된 QoS 정책을 사용하면 관리자가 SVM 내의 볼륨과 Q트리에서 SVM의 QoS 제한을 세분화하고, 컴퓨팅 환경 전반에서 스토리지 리소스의 균형을 맞추는 동시에 미션 크리티컬 워크로드의 우선 순위를 지정할 수 있습니다.

다음 개체 쌍에 대해 중첩된 QoS 정책이 지원됩니다.

* SVM에 포함된 SVM 및 FlexVol 또는 FlexGroup 볼륨.
* 볼륨 내의 FlexVol 또는 FlexGroup 볼륨과 qtree.


중첩된 QoS 정책의 경우 적용 가능한 가장 제한적인 정책이 사용됩니다.

다음 표에는 제한 사항이 나열되어 있습니다.

|===
| 다음을 할당하는 경우... | 그러면 정책 그룹에 할당할 수 없습니다. 


 a| 
SVM을 정책 그룹으로 이동합니다
 a| 
SVM에 포함된 모든 저장 객체.


NOTE: ONTAP 9.18.1을 실행 중인 경우 SVM에 포함된 FlexVol 및 FlexGroup 볼륨을 정책 그룹에 할당할 수 있습니다.



 a| 
볼륨을 정책 그룹에
 a| 
볼륨이나 자식 LUN이 포함된 SVM입니다.


NOTE: ONTAP 9.18.1 이상을 실행 중인 경우 볼륨이 포함된 SVM을 정책 그룹에 할당할 수 있습니다.  또한 FlexVol 또는 FlexGroup 볼륨의 qtree를 할당할 수 있습니다.



 a| 
정책 그룹에 LUN을 지정합니다
 a| 
LUN을 포함하는 볼륨 또는 SVM



 a| 
파일을 정책 그룹에 저장합니다
 a| 
파일이 포함된 볼륨 또는 SVM

|===
.단계
. 적응형 QoS 정책 그룹을 생성합니다.
+
'QOS adaptive-policy-group create-policy group_group_-vserver_SVM_-expected-IOPS_number_of_IOPS_/TB|GB-peak-IOPS_number_of_IOPS_/TB|GB-expected-IOPS-allocation-space|used-space-peak-peak-IOPS-allocation-space|used-space-space-absolute-min-64K_K_number_K_number_K_number_K_K_number|K_K_K_number|K_MB|K_

+
에 대한 자세한 내용은 `qos adaptive-policy-group create` link:https://docs.netapp.com/us-en/ontap-cli/qos-adaptive-policy-group-create.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

+
[NOTE]
====
ONTAP 9.5 이상에서 '-expected-IOPS-allocation' 및 '-block-size를 사용할 수 있다. 이러한 옵션은 ONTAP 9.4 이전 버전에서는 지원되지 않습니다.

====
+
다음 명령을 실행하면 300 IOPS/TB로 설정된 adpg-app1 Adaptive QoS 정책 그룹, 1,000 IOPS/TB로 설정된 -peak-IOPS, 사용된 공간으로 설정된 -peak-IOPS-allocation, 50 IOPS로 설정된 -absolute-min-IOPS 정책 그룹,

+
[listing]
----
cluster1::> qos adaptive-policy-group create -policy group adpg-app1 -vserver vs2 -expected-iops 300iops/tb -peak-iops 1000iops/TB -peak-iops-allocation used-space -absolute-min-iops 50iops
----
. 적응형 QoS 정책 그룹을 볼륨에 적용합니다.
+
'volume create-vserver SVM-volume_volume_-aggregate_aggregate_-size_number_of_TB|GB-QoS-adaptive-policy-group_policy_group_'

+
에 대한 자세한 내용은 `volume create` link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

+
다음 명령은 Adaptive QoS 정책 그룹 'adpg-app1'을 볼륨 'app1'에 적용합니다.

+
[listing]
----
cluster1::> volume create -vserver vs1 -volume app1 -aggregate aggr1 -size 2TB -qos-adaptive-policy-group adpg-app1
----
+
다음 명령은 새 볼륨 app4와 기존 볼륨 app5에 기본 적응형 QoS 정책 그룹 "extreme"을 적용합니다. 정책 그룹에 대해 정의된 처리량 상한은 볼륨 app4 및 app5에 개별적으로 적용됩니다.

+
[listing]
----
cluster1::> volume create -vserver vs4 -volume app4 -aggregate aggr4 -size 2TB -qos-adaptive-policy-group extreme
----
+
[listing]
----
cluster1::> volume modify -vserver vs5 -volume app5 -qos-adaptive-policy-group extreme
----

