---
permalink: performance-admin/adaptive-qos-policy-groups-task.html 
sidebar: sidebar 
keywords: use, adaptive, qos, policy, groups 
summary: 적응형 QoS 정책 그룹을 사용하면 볼륨 크기에 따라 처리량 상한 또는 하한을 자동으로 조정하여 볼륨 크기 변화에 따른 IOPS 대 TB 또는 GB 비율을 유지할 수 있습니다. 이는 대규모 배포 환경에서 수백 또는 수천 개의 워크로드를 관리할 때 매우 유용한 이점입니다. 
---
= ONTAP 적응형 QoS 정책 그룹을 사용하여 처리량을 설정하세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
_적응형 QoS_ 정책 그룹을 사용하면 볼륨 크기에 맞게 처리량 상한선이나 하한선을 자동으로 조정하여 볼륨 크기가 변경되더라도 IOPS 대 TB/GB 비율을 유지할 수 있습니다.  이는 대규모 배포에서 수백 또는 수천 개의 작업 부하를 관리할 때 상당한 이점입니다.

.시작하기 전에
* 정책 그룹을 생성하려면 클러스터 관리자여야 합니다.
* 정책 그룹에 추가하려는 스토리지 객체는 비적응형 정책 그룹의 멤버여야 합니다
+
스토리지 객체는 적응형 정책 그룹 또는 비적응형 정책 그룹의 구성원일 수 있지만 둘 다에 속할 수는 없습니다.

* 스토리지 객체의 SVM과 정책은 동일해야 합니다.
* 스토리지 객체는 온라인 상태여야 합니다.


.이 작업에 대해
* 적응형 QoS 정책 그룹은 항상 공유되지 않습니다. 정의된 처리량 상한 또는 최저값은 각 구성원 워크로드에 개별적으로 적용됩니다.
* 적응형 및 비적응형 QoS 정책 그룹은 기본적으로 워크로드의 처리량 상한을 1초 동안 50%까지 일시적으로 높여 단기적인 성능 향상 요구에 대응하도록 자동으로 활성화됩니다. ONTAP 9.19.1부터는 이러한 기본 설정을 수정할 수 있습니다. ONTAP 9.18.1 이하 버전에서는 이러한 설정을 변경할 수 없습니다.
+
다음 옵션을 사용하여 기본 설정을 수정하십시오.

+
[cols="3"]
|===
| 옵션을 선택합니다 | 설명 | 기본 설정 


 a| 
`burst-percent`
| 처리량 증가율(%) | 50% 


 a| 
`burst duration`
| 처리량 증가 기간(초) | 1초 


 a| 
`burst-iops`
| 지정된 버스트 지속 시간 동안 처리량 상한선을 초과하는 최대 IOPS 수 | 0 
|===
* 스토리지 오브젝트 크기에 대한 처리량 제한의 비율은 다음 필드의 상호 작용에 의해 결정됩니다.
+
** `expected-iops`할당된 TB/GB당 예상 최소 IOPS입니다.
** `peak-iops`할당되거나 사용된 TB/GB당 가능한 최대 IOPS입니다.
** `expected-iops-allocation` 예상 IOPS에 할당된 공간(기본값) 또는 사용된 공간을 사용할지 여부를 지정합니다.
** peak-IOPS-allocation은 peak-IOPS를 위해 할당된 공간과 사용된 공간(기본값)을 사용할지 여부를 지정한다.
** 절대 최소 IOPS는 절대 최소 IOPS의 수입니다. 이 필드는 매우 작은 스토리지 객체와 함께 사용할 수 있습니다. 절대분 IOPS가 계산된 예상 IOPS보다 크면 peak-IOPS와 expected-IOPS를 모두 재정의합니다.
+
예를 들어, 'expected-IOPS'를 1,000 IOPS/TB로 설정하고 볼륨 크기가 1GB 미만인 경우 계산된 'expected-IOPS'는 IOP가 분수 값이 됩니다. 계산된 피크 IOPS는 이보다 훨씬 적은 비율입니다. 절대-최소-IOPS를 실제 값으로 설정하면 이러한 문제를 방지할 수 있습니다.

** 블록 크기 는 애플리케이션 입출력 블록 크기를 지정합니다. 기본값은 32K입니다. 유효한 값은 8K, 16K, 32K, 64K, any입니다. Any는 블록 크기가 적용되지 않음을 의미합니다.




.단계
. 적응형 QoS 정책 그룹을 생성합니다.
+
[source, cli]
----
qos adaptive-policy-group create -policy group <policy_group> -vserver <SVM> -expected-iops <number_of_iops>/TB|GB -peak-iops <number_of_iops>/TB|GB -expected-iops-allocation-space|used-space -peak-iops-allocation allocated-space|used-space -absolute-min-iops <number_of_iops> -block-size 8K|16K|32K|64K|ANY
----
+
에 대한 자세한 내용은 `qos adaptive-policy-group create` link:https://docs.netapp.com/us-en/ontap-cli/qos-adaptive-policy-group-create.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

+
[NOTE]
====
ONTAP 9.5 이상에서 '-expected-IOPS-allocation' 및 '-block-size를 사용할 수 있다. 이러한 옵션은 ONTAP 9.4 이전 버전에서는 지원되지 않습니다.

====
+
다음 명령을 실행하면 300 IOPS/TB로 설정된 adpg-app1 Adaptive QoS 정책 그룹, 1,000 IOPS/TB로 설정된 -peak-IOPS, 사용된 공간으로 설정된 -peak-IOPS-allocation, 50 IOPS로 설정된 -absolute-min-IOPS 정책 그룹,

+
[listing]
----
cluster1::> qos adaptive-policy-group create -policy group adpg-app1 -vserver vs2 -expected-iops 300iops/tb -peak-iops 1000iops/TB -peak-iops-allocation used-space -absolute-min-iops 50iops
----
. 적응형 QoS 정책 그룹을 볼륨에 적용합니다.
+
[source, cli]
----
volume create -vserver SVM -volume <volume_name> -aggregate <aggregate> -size <number_of_ TB|GB> -qos-adaptive-policy-group<_policy_group>
----
+
에 대한 자세한 내용은 `volume create` link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

+
다음 명령은 Adaptive QoS 정책 그룹 'adpg-app1'을 볼륨 'app1'에 적용합니다.

+
[listing]
----
cluster1::> volume create -vserver vs1 -volume app1 -aggregate aggr1 -size 2TB -qos-adaptive-policy-group adpg-app1
----
+
다음 명령은 새 볼륨 app4와 기존 볼륨 app5에 기본 적응형 QoS 정책 그룹 "extreme"을 적용합니다. 정책 그룹에 대해 정의된 처리량 상한은 볼륨 app4 및 app5에 개별적으로 적용됩니다.

+
[listing]
----
cluster1::> volume create -vserver vs4 -volume app4 -aggregate aggr4 -size 2TB -qos-adaptive-policy-group extreme
----
+
[listing]
----
cluster1::> volume modify -vserver vs5 -volume app5 -qos-adaptive-policy-group extreme
----




== 기본 적응형 QoS 정책 그룹

기본적으로 세 가지 적응형 QoS 정책 그룹을 사용할 수 있습니다. 이러한 정책 그룹을 볼륨에 직접 적용할 수 있습니다.

|===


| 기본 정책 그룹입니다 | 예상 IOPS/TB | 최대 IOPS/TB | 절대 최소 IOPS 


 a| 
"익스트림"
 a| 
6,144
 a| 
12,288
 a| 
1000입니다



 a| 
'퍼포먼스'
 a| 
2,048
 a| 
4,096개
 a| 
500입니다



 a| 
값
 a| 
128
 a| 
512
 a| 
75를

|===