---
permalink: performance-admin/set-throughput-ceiling-qos-task.html 
sidebar: sidebar 
keywords: setting, throughput, ceiling, qos 
summary: QoS 최대값 또는 처리량 상한은 경쟁하는 워크로드와 관계없이 특정 워크로드의 처리량이 최대 IOPS 또는 MBps, 또는 IOPS 및 MBps를 초과하지 않도록 보장합니다. 중요도가 낮은 워크로드가 과도한 성능 리소스를 소비하여 중요도가 높은 워크로드의 성능을 저하시키는 것을 방지하기 위해 처리량 상한을 설정하십시오. 
---
= ONTAP QoS 정책 그룹을 사용하여 처리량 상한을 설정하세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
QoS 최대값 또는 처리량 상한은 경쟁하는 워크로드와 관계없이 특정 워크로드의 처리량이 최대 IOPS 또는 MBps, 또는 IOPS 및 MBps를 초과하지 않도록 보장합니다. 중요도가 낮은 워크로드가 과도한 성능 리소스를 소비하여 중요도가 높은 워크로드의 성능을 저하시키는 것을 방지하기 위해 처리량 상한을 설정하십시오.

QoS 정책 그룹을 생성할 때 처리량 상한을 지정하거나 워크로드를 모니터링한 후 지정할 수 있습니다.

link:guarantee-throughput-qos-task.html["처리량 상한에 대해 자세히 알아보십시오"].

.시작하기 전에
* 정책 그룹을 생성하고 이를 SVM에 적용하려면 클러스터 관리자여야 합니다.


.이 작업에 대해
* 적응형 및 비적응형 QoS 정책 그룹은 기본적으로 워크로드의 처리량 상한을 1초 동안 50%까지 일시적으로 높여 단기적인 성능 향상 요구에 대응하도록 자동으로 활성화됩니다. ONTAP 9.19.1부터는 이러한 기본 설정을 수정할 수 있습니다. ONTAP 9.18.1 이하 버전에서는 이러한 설정을 변경할 수 없습니다.
+
다음 옵션을 사용하여 기본 설정을 수정하십시오.

+
[cols="3"]
|===
| 옵션을 선택합니다 | 설명 | 기본 설정 


 a| 
`burst-percent`
| 처리량 증가율(%) | 50% 


 a| 
`burst duration`
| 처리량 증가 기간(초) | 1초 


 a| 
`burst-iops`
| 지정된 버스트 지속 시간 동안 처리량 상한선을 초과하는 최대 IOPS 수 | 0 
|===
* _비공유_ QoS 정책 그룹을 사용하면 정의된 처리량 상한이 각 멤버 워크로드에 개별적으로 적용되도록 지정할 수 있습니다. 그렇지 않으면 정책 그룹은 _공유_됩니다. 이 경우 정책 그룹에 할당된 워크로드의 총 처리량은 지정된 상한을 초과할 수 없습니다.
+
비공유 정책 그룹을 지정하기 위해 QoS policy-group create 명령에 대해 -is-shared=false를 설정합니다.

* 천장에 대한 처리량 제한을 IOPS, MB/s 또는 IOPS, MB/s로 지정할 수 있습니다 IOPS와 MB/s를 모두 지정하는 경우, 어느 한쪽의 제한에 먼저 도달하더라도 적용됩니다.
+
[NOTE]
====
동일한 워크로드에 대해 천장과 바닥을 설정하는 경우 IOPS만 사용하여 천장에 대한 처리량 제한을 지정할 수 있습니다.

====
* QoS 제한이 적용되는 스토리지 개체는 정책 그룹이 속한 SVM에 포함되어 있어야 합니다. 여러 정책 그룹이 동일한 SVM에 속할 수 있습니다.
* 포함하는 객체 또는 해당 하위 객체가 정책 그룹에 속해 있는 경우 스토리지 객체를 정책 그룹에 할당할 수 없습니다.
* 정책 그룹을 동일한 유형의 스토리지 객체에 적용하는 것은 QoS 모범 사례입니다.


.단계
. 정책 그룹 생성:
+
[source, cli]
----
qos policy-group create -policy-group <policy_group> -vserver <SVM> -max-throughput <number_of_iops_|Mb/S|iops,Mb/S> -is-shared <true|false>
----
+
에 대한 자세한 내용은 `qos policy-group create` link:https://docs.netapp.com/us-en/ontap-cli/qos-policy-group-create.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

+
명령을 사용하여 처리량 한도를 조정할 수 `qos policy-group modify` 있습니다.

+
다음 예제는 최대 처리량이 5,000 IOPS인 공유 정책 그룹 `pg-vs1`을 생성합니다.

+
[listing]
----
cluster1::> qos policy-group create -policy-group pg-vs1 -vserver vs1 -max-throughput 5000iops -is-shared true
----
+
다음 예시는 최대 처리량 100 IOPS 및 400 Kb/S를 갖는 비공유 정책 그룹 `pg-vs3`을 생성합니다.

+
[listing]
----
cluster1::> qos policy-group create -policy-group pg-vs3 -vserver vs3 -max-throughput 100iops,400KB/s -is-shared false
----
+
다음 예제는 처리량 제한이 없는 비공유 정책 그룹 `pg-vs4`을 생성합니다.

+
[listing]
----
cluster1::> qos policy-group create -policy-group pg-vs4 -vserver vs4 -is-shared false
----
+
에 대한 자세한 내용은 `qos policy-group modify` link:https://docs.netapp.com/us-en/ontap-cli/qos-policy-group-modify.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

. SVM, 파일, 볼륨 또는 LUN에 정책 그룹 적용:
+
[source, cli]
----
vserver create -vserver <SVM> -qos-policy-group <policy_group>
----
+
다음 예에서는 정책 그룹 `pg-vs1`을 SVM `vs1`에 적용합니다.

+
[listing]
----
cluster1::> vserver create -vserver vs1 -qos-policy-group pg-vs1
----
+
다음 예에서는 정책 그룹 `pg-app`을 볼륨 `app1` 및 `app2`에 적용합니다.

+
[listing]
----
cluster1::> volume create -vserver vs2 -volume app1 -aggregate aggr1 -qos-policy-group pg-app
----
+
[listing]
----
cluster1::> volume create -vserver vs2 -volume app2 -aggregate aggr1 -qos-policy-group pg-app
----
. 정책 그룹 성능 모니터링:
+
[source, cli]
----
qos statistics performance show
----
+
에 대한 자세한 내용은 `qos statistics performance show` link:https://docs.netapp.com/us-en/ontap-cli/qos-statistics-performance-show.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

+
[NOTE]
====
클러스터의 성능 모니터링 호스트의 툴을 사용하여 성능을 모니터링하지 마십시오.

====
+
다음 예에서는 정책 그룹 성능을 보여 줍니다.

+
[listing]
----
cluster1::> qos statistics performance show
Policy Group           IOPS      Throughput   Latency
-------------------- -------- --------------- ----------
-total-                 12316       47.76MB/s  1264.00us
pg_vs1                   5008       19.56MB/s     2.45ms
_System-Best-Effort        62       13.36KB/s     4.13ms
_System-Background         30           0KB/s        0ms
----
. 워크로드 성능 모니터링:
+
[source, cli]
----
qos statistics workload performance show
----
+
[NOTE]
====
클러스터의 성능 모니터링 호스트의 툴을 사용하여 성능을 모니터링하지 마십시오.

====
+
다음 예에서는 워크로드 성능을 보여 줍니다.

+
[listing]
----
cluster1::> qos statistics workload performance show
Workload          ID     IOPS      Throughput    Latency
--------------- ------ -------- ---------------- ----------
-total-              -    12320        47.84MB/s  1215.00us
app1-wid7967      7967     7219        28.20MB/s   319.00us
vs1-wid12279     12279     5026        19.63MB/s     2.52ms
_USERSPACE_APPS     14       55        10.92KB/s   236.00us
_Scan_Backgro..   5688       20            0KB/s        0ms
----
+
다음은 최대 처리량을 2000 IOPS로, 버스트 비율을 25%로, 버스트 지속 시간을 5초로 설정한 워크로드에 대한 출력 예입니다.

+
[listing]
----
cluster1::> qos statistics workload performance show -workload test_vol_nfs_pct25-wid54260

Workload	                ID	    IOPS
--------------------------- -----   ----
test_vol_nfs_pct25-wid54260	54260	2564
-total-	-	                        3704
test_vol_nfs_pct25-wid54260	54260	2527
-total-	-	                        3105
test_vol_nfs_pct25-wid54260	54260	2550
-total-	-	                        3445
test_vol_nfs_pct25-wid54260	54260	2476
-total-	-	                        3460
test_vol_nfs_pct25-wid54260	54260	2479
-total-	-	                        3511
test_vol_nfs_pct25-wid54260	54260	1996
-total-	-	                        2197
test_vol_nfs_pct25-wid54260	54260	2068
-total-	-	                        2057
test_vol_nfs_pct25-wid54260	54260	2087
-total-	-	                        3119

----
+
에 대한 자세한 내용은 `qos statistics workload performance show` link:https://docs.netapp.com/us-en/ontap-cli/qos-statistics-workload-performance-show.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

+
 `qos statistics workload latency show` 명령을 사용하여 QoS 워크로드에 대한 자세한 지연 시간 통계를 볼 수 있습니다.

+
 `qos statistics workload latency show`에 대해 자세히 알아보려면 link:https://docs.netapp.com/us-en/ontap-cli/qos-statistics-workload-latency-show.html["ONTAP 명령 참조입니다"^]를 참조하세요.


