---
permalink: san-admin/flexclone-luns-protect-your-data-concept.html 
sidebar: sidebar 
keywords: use, flexclone, luns, protect, your, data 
summary: FlexClone LUN은 활성 볼륨 또는 스냅샷에 있는 다른 LUN의 쓰기 가능한 시점 복제본입니다. 클론 및 상위 항목은 서로 영향을 주지 않고 독립적으로 수정할 수 있습니다. 
---
= ONTAP FlexClone LUN으로 데이터를 보호합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexClone LUN은 활성 볼륨 또는 스냅샷에 있는 다른 LUN의 쓰기 가능한 시점 복제본입니다. 클론 및 상위 항목은 서로 영향을 주지 않고 독립적으로 수정할 수 있습니다.

FlexClone LUN을 사용하여 LUN의 읽기/쓰기 복사본을 여러 개 생성할 수 있습니다.

.FlexClone LUN을 생성하는 이유
* 테스트를 위해 LUN의 임시 복사본을 생성해야 합니다.
* 운영 데이터에 대한 액세스 권한을 부여하지 않고 추가 사용자가 데이터 복사본을 사용할 수 있도록 해야 합니다.
* 원본 데이터는 변경되지 않은 형식으로 유지하면서 조작 및 예상 작업에 사용할 데이터베이스 복제본을 만들려는 경우
* LUN 데이터의 특정 부분 집합(볼륨 그룹의 특정 논리적 볼륨 또는 파일 시스템, 또는 파일 시스템의 특정 파일 또는 파일 세트)를 원래 LUN의 나머지 데이터를 복원하지 않고 원래 LUN에 복사합니다. 이 작업은 LUN과 LUN 클론의 마운트를 동시에 지원하는 운영 체제에서 가능합니다. SnapDrive for UNIX는 'Snap connect' 명령을 통해 이를 지원합니다.
* 동일한 운영 체제를 사용하는 여러 SAN 부팅 호스트가 필요합니다.


FlexClone LUN은 처음에 부모 LUN과 공간을 공유합니다. 기본적으로 FlexClone LUN은 상위 LUN의 공간 예약 속성을 상속합니다. 예를 들어, 상위 LUN이 공간이 예약되지 않은 경우 FlexClone LUN도 기본적으로 공간이 예약되지 않습니다. 그러나 공간 예약 LUN인 상위에서 공간 예약 FlexClone LUN을 생성할 수 있습니다.

LUN을 클론 복제하면 블록 공유가 백그라운드에서 수행되며 블록 공유가 완료될 때까지 볼륨 스냅샷을 생성할 수 없습니다.

'볼륨 스냅샷 자동 삭제 수정' 명령을 사용하여 FlexClone LUN 자동 삭제 기능을 사용하도록 볼륨을 구성해야 합니다. 그렇지 않으면 FlexClone LUN이 자동으로 삭제되지만 FlexClone 자동 삭제에 대해 볼륨이 구성되지 않은 경우 FlexClone LUN이 삭제되지 않습니다.

FlexClone LUN을 생성할 때 FlexClone LUN 자동 삭제 기능은 기본적으로 해제되어 있습니다. FlexClone LUN을 자동으로 삭제하려면 먼저 모든 FlexClone LUN에서 수동으로 활성화해야 합니다. 반씩 볼륨 프로비저닝을 사용하고 이 옵션으로 제공되는 "'최선 노력'' 쓰기 보장을 원하는 경우, _ALL_FlexClone LUN을 자동 삭제할 수 있도록 해야 합니다.

[NOTE]
====
스냅샷에서 FlexClone LUN을 생성할 때 LUN은 공간 효율적인 백그라운드 프로세스를 사용하여 스냅샷에서 자동으로 분할되므로 LUN이 계속해서 스냅샷에 의존하거나 추가 공간을 소비하지 않습니다. 이 백그라운드 분할이 완료되지 않고 이 스냅샷이 자동으로 삭제되면 해당 FlexClone LUN에 대한 FlexClone 자동 삭제 기능을 해제했더라도 해당 FlexClone LUN이 삭제됩니다. 백그라운드 분할이 완료된 후 해당 스냅샷이 삭제되더라도 FlexClone LUN은 삭제되지 않습니다.

====
.관련 정보
* link:../volumes/create-flexclone-file-flexclone-lun-task.html["FlexClone LUN을 생성합니다"]
* link:../volumes/configure-flexvol-delete-flexclone-files-luns-task.html["FlexClone LUN을 자동으로 삭제하도록 FlexVol volume을 구성합니다"]
* link:../volumes/prevent-flexclone-file-lun-automatic-deleted-task.html["FlexClone LUN이 자동으로 삭제되지 않도록 방지합니다"]

