---
sidebar: sidebar 
permalink: san-admin/multipath-automatic-lif-failover-support.html 
keywords: netapp, ontap, san, multipath, automatic lif failover, supported configurations, active-active, local-active, active-active-scsi-only, multipathing, 
summary: 클러스터에서 ONTAP 버전을 중단 없이 업데이트할 수 있습니다. 
---
= ONTAP 시스템의 SAN 다중 경로 및 자동 LIF 페일오버 지원에 대해 알아보십시오
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
다중 경로 구성에서는 호스트와 스토리지 시스템 간에 여러 네트워크 경로가 구성되어 하나의 경로를 사용할 수 없게 될 경우 서비스 중단을 방지하기 위해 I/O를 대체 경로로 리디렉션할 수 있습니다. 자동 LIF 페일오버를 사용하면 논리 인터페이스(LIF)의 홈 포트가 비정상 상태가 되거나 스토리지 페일오버가 발생할 경우 해당 논리 인터페이스가 자동으로 다른 포트로 마이그레이션됩니다. 자동 LIF 페일오버를 지원하는 다중 경로는 페일오버 경로 전환 없이도 I/O를 가장 최적화된 사용 가능한 경로로 원활하게 재라우팅합니다.



== SAN 지원 다중 경로 구성

SAN 환경에서 지원되는 다중 경로 구성은 다음과 같습니다.

로컬-액티브:: LUN 또는 네임스페이스를 소유한 노드의 경로는 활성화되어 최적화됩니다. HA 파트너의 경로는 활성화되어 있지만 최적화되지 않습니다.
액티브-액티브:: LUN 또는 네임스페이스를 소유하는 HA 쌍의 모든 경로가 활성화되고 최적화됩니다.
액티브-액티브-SCSI-전용:: LUN 또는 네임스페이스를 소유한 노드의 경로는 활성 상태이며 최적화되어 있습니다. HA 파트너의 경로는 SAN 프로토콜에 따라 활성 최적화 또는 활성 비최적화 상태일 수 있습니다. 활성-활성-SCSI 전용 구성은 ASA 시스템에서만 지원됩니다.


SAN 다중 경로 구성 지원은 스토리지 시스템 및 ONTAP 버전에 따라 다릅니다.

[cols="1,1,1,1"]
|===
| 시스템 | ONTAP 버전입니다 | 지원되는 다중 경로 구성 | 기본 다중 경로 구성 


| FAS | 9.0 이상 | 로컬-액티브 | 로컬-액티브 


.2+| AFF | 9.19.1 이상  a| 
* 액티브-액티브
* 로컬-액티브

| 로컬-액티브 


| 9.18.1 이하 | 로컬-액티브 | 로컬-액티브 


.2+| ASA | 9.19.1 이상  a| 
* 액티브-액티브
* 액티브-액티브-SCSI-전용

| 액티브-액티브 


| 9.18.1 이하  a| 
* 액티브-액티브
* 액티브-액티브-SCSI-전용

| 액티브-액티브-SCSI-전용 


| ASA r2 | 9.16.1 이상 | 액티브-액티브 | 액티브-액티브 
|===


== 구성별 기본 LIF 페일오버 동작

다중 경로 구성에 따라 호스트와 스토리지 시스템 간의 경로는 active-optimized 또는 active-non-optimized입니다. active-optimized 경로에서 스토리지 페일오버가 발생하면 호스트는 I/O를 재개하기 위해 페일오버 경로의 ALUA 또는 ANA 전환을 기다릴 필요가 없습니다. active-non-optimized 경로의 경우, I/O를 재개하려면 ALUA 또는 ANA가 장애가 발생한 경로에서 HA 파트너로 I/O를 전환해야 합니다. link:../san-config/host-support-multipathing-concept.html["ALUA 및 ANA"]에 대해 자세히 알아보십시오.

[cols="1,1,1,1,1"]
|===
| 다중 경로 구성 | 프로토콜 | 기본 LIF 페일오버 정책 | 소유 노드 경로 | HA 파트너 경로 


| 로컬-액티브  a| 
* iSCSI
* NVMe/TCP
* NVMe/FC

| 로컬 전용 | 액티브 최적화 | 액티브-비최적화 


.2+| 액티브-액티브  a| 
* iSCSI
* NVMe/TCP

| sfo-partner-only | 액티브 최적화 | 액티브 최적화 


 a| 
* FCP
* NVMe/FC

| 해당 없음 영구 포트는 페일오버에 사용됩니다 | 액티브 최적화 | 액티브 최적화 


.4+| active-active-scsi-only(ASA 플랫폼에서만 사용 가능) | iSCSI | sfo-partner-only | 액티브 최적화 | 액티브 최적화 


| NVMe/TCP | 로컬 전용 | 액티브 최적화 | 액티브-비최적화 


| FC | 해당 없음 영구 포트는 페일오버에 사용됩니다 | 액티브 최적화 | 액티브 최적화 


| NVMe/FC | 해당 없음 영구 포트는 페일오버에 사용됩니다 | 액티브 최적화 | 액티브-비최적화 
|===


== 자동 LIF 페일오버 지원

자동 LIF 페일오버는 iSCSI 및 NVMe/TCP 프로토콜을 실행하는 active-active 다중 경로 구성과 iSCSI 프로토콜을 실행하는 active-active-scsi-only 다중 경로 구성에서 지원됩니다. LIF는 기본적으로 시스템에서 생성된 sfo-partner-only 페일오버 정책을 사용하도록 구성됩니다. sfo-partner-only 기본 정책은 수정할 수 있습니다.

로컬 활성 다중 경로 구성에서는 자동 LIF 페일오버가 지원되지 않습니다. 로컬 전용 기본 정책은 수정할 수 없습니다.

FC 또는 NVMe-FC 프로토콜을 실행하는 액티브-액티브 다중 경로 구성은 페일오버를 위해 영구 포트를 사용합니다. 영구 포트는 ONTAP 9.8부터 지원되며 페일오버 정책을 사용하지 않습니다. link:../san-config/asa-support-limitations.html["영구 포트 지원"]에 대해 자세히 알아보십시오.

자동 LIF 페일오버 지원 여부는 스토리지 시스템, ONTAP 버전 및 SAN 프로토콜에 따라 다릅니다.

[cols="1,1,1,1"]
|===
| 시스템 | ONTAP 버전입니다 | SAN 프로토콜 | LIF 페일오버 지원 


| FAS | 9.0 이상 | 모두 | 지원되지 않습니다 


.4+| AFF .3+| 9.19.1 이상 | iSCSI | 액티브-액티브 또는 액티브-액티브-SCSI 전용 다중 경로 구성을 사용한 자동 LIF 페일오버 


| NVMe/TCP | 액티브-액티브 다중 경로 구성을 사용한 자동 LIF 페일오버 


 a| 
* FC
* NVMe/FC

| 영구 포트를 사용한 페일오버 


| 9.18.1 이하 | 모두 | 지원되지 않습니다 


.9+| ASA .3+| 9.19.1 이상 | iSCSI | 액티브-액티브 또는 액티브-액티브-SCSI 전용 다중 경로 구성을 사용한 자동 LIF 페일오버 


| NVMe/TCP | 액티브-액티브 다중 경로 구성을 사용한 자동 LIF 페일오버 


 a| 
* FC
* NVMe/FC

| 영구 포트를 사용한 페일오버 


.3+| 9.11.1 ~ 9.18.1 | iSCSI | 자동 LIF 페일오버 


| FC | 영구 포트를 사용한 페일오버 


 a| 
* NVMe/FC
* NVMe/TCP

| 지원되지 않습니다 


.2+| 9.8에서 9.10.1까지 | FC | 영구 포트를 사용한 페일오버 


 a| 
* iSCSI
* NVMe/FC
* NVMe/TCP

| 지원되지 않습니다 


| 9.7 | 모두 | 지원되지 않습니다 


.2+| ASA r2 .2+| 9.19.1 이상  a| 
* iSCSI
* NVMe/TCP

| 액티브-액티브 다중 경로 구성을 사용한 자동 LIF 페일오버 


 a| 
* FC
* NVMe/FC

| 영구 포트를 사용한 페일오버 
|===


== 다중 경로 구성 제한 사항

SnapMirror 액티브 동기화 관계의 스토리지 가상 머신(SVM) 및 MetroCluster 구성에 대한 SAN 다중 경로 구성 제한 사항이 있습니다.

* *SnapMirror Active Sync*
+
SVM이 SnapMirror 활성 동기화 관계에 있는 경우 소스 SVM과 대상 SVM의 다중 경로 구성이 동일해야 합니다. 소스 SVM과 대상 SVM의 다중 경로 구성이 다른 것은 지원되지 않습니다.

* *MetroCluster 구성*
+
기본 사이트와 보조 사이트의 스토리지 시스템 유형은 동일해야 합니다.





== AFF 시스템에서의 능동-능동 다중 경로

ONTAP 9.19.1부터 AFF 시스템은 SAN 환경에서 SVM 레벨의 자동 LIF 페일오버를 지원하는 액티브-액티브 다중 경로를 제공합니다. 이를 통해 페일오버 시간을 단축하여 SAN 고객은 기존 ASA 시스템에서만 가능했던 무중단 경로 복원력과 로드 밸런싱 기능을 AFF 시스템에서 미션 크리티컬 워크로드에 적용할 수 있습니다. AFF 시스템의 액티브-액티브 다중 경로 지원과 자동 LIF 페일오버를 통해 관리 도메인을 통합하고, 스토리지 공간을 최적화하며, 기존 NAS 투자를 활용하고, 모든 프로토콜 요구 사항에 대해 단일 스토리지 시스템으로 표준화하는 동시에 엄격한 가용성 및 성능 SLA를 충족할 수 있습니다.

AFF 시스템에서는 ONTAP 9.19.1 이상에서 새 SVM을 생성할 때만 액티브-액티브 다중 경로를 구성할 수 있습니다. SVM은 로컬 액티브 구성에서 액티브-액티브 구성으로 변환할 수 없습니다.

로컬-액티브 다중 경로로 구성된 SVM에서 액티브-액티브 다중 경로로 구성된 SVM으로 기존 LUN 및 네임스페이스를 이동할 수 있습니다. LUN 또는 네임스페이스를 새 SVM으로 이동하는 경우, 데이터 제공을 시작하기 전에 호스트를 새 SVM에 다시 매핑해야 합니다.


NOTE: 클러스터가 ONTAP 9.19.1 이상을 실행 중이고 FAS 및 AFF 시스템을 모두 포함하는 경우 모든 시스템에 대해 로컬 액티브 다중 경로 구성을 사용해야 합니다. 동일한 클러스터 내에서 FAS 시스템에는 로컬 액티브 구성을, AFF 시스템에는 액티브 액티브 구성을 사용하는 것은 권장되지 않습니다.

.관련 정보
* link:asa-iscsi-lif-fo-task.html:["ASA 시스템에서 자동 iSCSI LIF 페일오버"]에 대해 자세히 알아보십시오.
* link:https://docs.netapp.com/us-en/asa-r2/administer/manage-client-vm-access.html#create-a-lif-network-interface["ASA r2 시스템에서 자동 iSCSI LIF 페일오버"^]에 대해 자세히 알아보십시오.

