---
permalink: smb-config/configure-dns-host-name-resolution-task.html 
sidebar: sidebar 
keywords: vserver, name-service, service, dns, command, enable, svm, host-name, resolution, host, name, resolve, external, enable dns for host-name resolution 
summary: vserver services name-service dns 명령을 사용하여 SVM에서 DNS를 활성화하고 호스트 이름 확인에 DNS를 사용하도록 구성할 수 있습니다. 호스트 이름은 외부 DNS 서버를 사용하여 확인됩니다. 
---
= ONTAP SMB 호스트 이름 확인을 위해 DNS를 활성화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
명령을 사용하여 SVM에서 DNS를 사용하도록 설정하고, 호스트 이름 확인에 DNS를 사용하도록 구성할 수 `vserver services name-service dns` 있습니다. 호스트 이름은 외부 DNS 서버를 사용하여 확인됩니다. 에 대한 자세한 내용은 `vserver services name-service dns` link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+services+name-service+dns["ONTAP 명령 참조입니다"^]을 참조하십시오.

.시작하기 전에
호스트 이름 조회에 사이트 전체 DNS 서버를 사용할 수 있어야 합니다.

단일 장애 지점을 방지하려면 둘 이상의 DNS 서버를 구성해야 합니다.  `vserver services name-service dns create`DNS 서버 이름을 하나만 입력하면 명령이 경고를 표시합니다. 에 대한 자세한 내용은 `vserver services name-service dns create` link:https://docs.netapp.com/us-en/ontap-cli/vserver-services-name-service-dns-create.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

.이 작업에 대해
에 대해 자세히 link:../networking/configure_dynamic_dns_services.html["SVM에서 동적 DNS 구성"]알아보십시오.

.단계
. SVM에서 DNS를 활성화합니다. 'vserver services name-service dns create-vserver vserver_name-domain domain_name-name-servers ip_address-state enabled'
+
다음 명령을 실행하면 SVM VS1 에서 외부 DNS 서버 서버가 활성화됩니다.

+
[listing]
----
vserver services name-service dns create -vserver vs1.example.com -domains example.com -name-servers 192.0.2.201,192.0.2.202 -state enabled
----
+
[NOTE]
====
를 클릭합니다 `vserver services name-service dns create` Command는 자동 구성 유효성 검사를 수행하고 ONTAP에서 이름 서버에 연결할 수 없는 경우 오류 메시지를 보고합니다.

====
. 'vserver services name-service dns show' 명령을 사용하여 DNS 도메인 구성을 표시합니다.
+
다음 명령을 실행하면 클러스터의 모든 SVM에 대한 DNS 구성이 표시됩니다.

+
[listing]
----
vserver services name-service dns show
                                             Name
Vserver           State     Domains             Servers
----------------- --------- ------------------- -------------
cluster1          enabled   example.com         192.0.2.201,
                                                192.0.2.202
vs1.example.com   enabled   example.com         192.0.2.201,
                                                192.0.2.202
----
+
다음 명령을 실행하면 SVM VS1 에 대한 자세한 DNS 구성 정보가 표시됩니다.

+
[listing]
----
vserver services name-service dns show -vserver vs1.example.com
               Vserver: vs1.example.com
               Domains: example.com
          Name Servers: 192.0.2.201, 192.0.2.202
    Enable/Disable DNS: enabled
        Timeout (secs): 2
      Maximum Attempts: 1
----
. 'vserver services name-service dns check' 명령어를 이용하여 이름 서버의 상태를 확인한다.
+
[listing]
----
vserver services name-service dns check -vserver vs1.example.com

Vserver           Name Server     Status       Status Details
----------------  -------------   ----------   --------------------------
vs1.example.com   10.0.0.50         up         Response time (msec): 2
vs1.example.com   10.0.0.51         up         Response time (msec): 2
----

