---
permalink: disks-aggregates/assign-aggregates-svms-task.html 
sidebar: sidebar 
keywords: assign, aggregate, local tier, svm, storage vm, vserver 
summary: ' 스토리지 가상 머신(스토리지 VM 또는 SVM, 이전의 Vserver)에 하나 이상의 로컬 계층을 할당하는 경우 해당 SVM의 볼륨을 포함하는 로컬 계층만 사용할 수 있습니다. A' 
---
= ONTAP의 스토리지 VM(SVM)에 로컬 계층을 할당합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 가상 머신(스토리지 VM 또는 SVM, 이전의 Vserver)에 하나 이상의 로컬 계층을 할당하는 경우 해당 스토리지 VM(SVM)의 볼륨을 포함하는 로컬 계층만 사용할 수 있습니다.


NOTE: ONTAP 9.7 이전에는 System Manager에서 _aggregate_를 사용하여 _ 로컬 계층을 설명합니다. ONTAP 버전에 관계없이 ONTAP CLI에서는 _aggregate_라는 용어를 사용합니다. 로컬 계층에 대한 자세한 내용은 을 link:../disks-aggregates/index.html["디스크 및 로컬 계층"]참조하십시오.

.시작하기 전에
스토리지 VM에 할당할 스토리지 VM과 로컬 계층이 이미 있어야 합니다.

.이 작업에 대해
스토리지 VM에 로컬 계층을 할당하면 스토리지 VM이 서로 격리되도록 할 수 있습니다. 이는 멀티 테넌시 환경에서 특히 중요합니다.

.단계
. SVM에 이미 할당된 로컬 계층 목록을 확인하십시오.
+
'vserver show-fields aggr-list'를 선택합니다

+
SVM에 현재 할당된 로컬 계층이 표시됩니다. 할당된 로컬 계층이 없는 경우 `-` 이 표시됩니다.

. 요구사항에 따라 다음과 같이 할당된 로컬 계층을 추가 또는 제거합니다.
+
|===


| 원하는 작업 | 이 명령 사용... 


 a| 
추가 로컬 계층을 할당합니다
 a| 
'vserver add-aggregate'를 선택합니다



 a| 
로컬 계층의 할당을 취소합니다
 a| 
'vserver remove-aggregate'

|===
+
나열된 로컬 계층이 SVM에 할당되거나 SVM에서 제거됩니다. SVM에 할당되지 않은 애그리게이트를 사용하는 볼륨이 SVM에 이미 있는 경우 경고 메시지가 표시되지만 명령이 성공적으로 완료됩니다. SVM에 이미 할당되었고 명령에 이름을 지정하지 않은 로컬 계층은 영향을 받지 않습니다.



.예
다음 예에서는 로컬 계층 aggr1 및 aggr2가 SVM svm1에 할당됩니다.

'vserver add-aggregate-vserver svm1 - aggr1, aggr2'
