---
permalink: disks-aggregates/commands-display-space-usage-reference.html 
sidebar: sidebar 
keywords: commands, display, space usage, information 
summary: 스토리지 Aggregate 및 볼륨 명령을 사용하여 로컬 계층과 볼륨 및 해당 스냅샷에서 공간이 어떻게 사용되고 있는지 확인할 수 있습니다. 
---
= 공간 사용 정보를 표시하기 위한 ONTAP 명령입니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
및 `volume` 명령을 사용하여 `storage aggregate` 로컬 계층, 볼륨 및 해당 스냅샷에서 공간이 어떻게 사용되고 있는지 확인할 수 있습니다.


NOTE: ONTAP 9.7 이전에는 System Manager에서 _aggregate_를 사용하여 _ 로컬 계층을 설명합니다. ONTAP 버전에 관계없이 ONTAP CLI에서는 _aggregate_라는 용어를 사용합니다. 로컬 계층에 대한 자세한 내용은 을 link:../disks-aggregates/index.html["디스크 및 로컬 계층"]참조하십시오.

|===


| 정보를 표시하려면... | 이 명령 사용... 


 a| 
사용된 공간 및 사용 가능한 공간 비율에 대한 세부 정보, 스냅숏 예비 공간 크기 및 기타 공간 사용 정보가 포함된 로컬 계층
 a| 
Storage aggregate show'Storage aggregate show'Storage aggregate show-space-fields snap-size-total, used-including-snapshot-reserve'라는 내용이 있습니다



 a| 
디스크 및 RAID 그룹이 로컬 계층에서 사용되는 방법 및 RAID 상태
 a| 
'스토리지 집계 표시 상태'



 a| 
특정 스냅샷을 삭제할 경우 재확보되는 디스크 공간의 양입니다
 a| 
'볼륨 스냅샷 계산-재확보 가능'



 a| 
볼륨에서 사용하는 공간입니다
 a| 
볼륨 표시 필드 크기 사용 가능 비율 사용 공간 볼륨 표시 공간



 a| 
포함하는 로컬 계층의 볼륨에서 사용하는 공간의 양입니다
 a| 
볼륨 쇼 풋프린트

|===
.관련 정보
* link:../concepts/manual-pages.html["ONTAP 명령 참조입니다"]

