---
permalink: disks-aggregates/commands-manage-aggregates-reference.html 
sidebar: sidebar 
keywords: commands, manage, aggregates 
summary: storage aggregate 명령을 사용하여 로컬 계층을 관리할 수 있습니다. 
---
= 로컬 계층 관리를 위한 ONTAP 명령
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
명령을 사용하여 `storage aggregate` 로컬 계층을 관리합니다.


NOTE: ONTAP 9.7 이전에는 System Manager에서 _aggregate_를 사용하여 _ 로컬 계층을 설명합니다. ONTAP 버전에 관계없이 ONTAP CLI에서는 _aggregate_라는 용어를 사용합니다. 로컬 계층에 대한 자세한 내용은 을 link:../disks-aggregates/index.html["디스크 및 로컬 계층"]참조하십시오.

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
All Flash Pool 로컬 계층의 캐시 크기를 표시합니다
 a| 
'Storage aggregate show-fields hybrid-cache-size-total-hybrid-cache-size-total > 0'



 a| 
로컬 계층의 디스크 정보 및 상태를 표시합니다
 a| 
'스토리지 집계 표시 상태'



 a| 
노드별 스페어 디스크를 표시합니다
 a| 
'스토리지 집계 show-spare-disks'



 a| 
클러스터의 루트 로컬 계층을 표시합니다
 a| 
'Storage aggregate show-has-mroot true'입니다



 a| 
로컬 계층의 기본 정보 및 상태를 표시합니다
 a| 
'스토리지 집계 쇼'



 a| 
로컬 계층에 사용되는 스토리지의 유형을 표시합니다
 a| 
'스토리지 집계 표시 필드 스토리지 유형'입니다



 a| 
로컬 계층을 온라인으로 전환합니다
 a| 
'Storage aggregate online



 a| 
로컬 계층을 삭제합니다
 a| 
'저장소 집계 삭제'



 a| 
로컬 계층을 Restricted 상태로 전환합니다
 a| 
'저장소 집계 제한'



 a| 
로컬 계층의 이름을 바꿉니다
 a| 
'저장소 집계 이름 바꾸기'



 a| 
로컬 계층을 오프라인으로 전환합니다
 a| 
'저장소 집계 오프라인'



 a| 
로컬 계층의 RAID 유형을 변경합니다
 a| 
'스토리지 집계 수정-raidtype'

|===
.관련 정보
* https://docs.netapp.com/us-en/ontap-cli["ONTAP 명령 참조입니다"^]

