---
permalink: disks-aggregates/convert-raid-dp-tec-task.html 
sidebar: sidebar 
keywords: convert, raid-dp, raid-tec, raid policy 
summary: 3중 패리티 보호를 추가하려면 RAID-DP에서 RAID-TEC로 전환할 수 있습니다. 로컬 계층에 사용되는 디스크 크기가 4TiB보다 큰 경우 RAID-TEC를 사용하는 것이 좋습니다. 
---
= ONTAP RAID-DP에서 RAID-TEC로 변환합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
3중 패리티 보호를 추가하려면 RAID-DP에서 RAID-TEC로 전환할 수 있습니다. 로컬 계층에 사용되는 디스크 크기가 4TiB보다 큰 경우 RAID-TEC를 사용하는 것이 좋습니다.


NOTE: ONTAP 9.7 이전에는 System Manager에서 _aggregate_를 사용하여 _ 로컬 계층을 설명합니다. ONTAP 버전에 관계없이 ONTAP CLI에서는 _aggregate_라는 용어를 사용합니다. 로컬 계층에 대한 자세한 내용은 을 link:../disks-aggregates/index.html["디스크 및 로컬 계층"]참조하십시오.

.시작하기 전에
변환할 로컬 계층에 최소 7개의 디스크가 있어야 합니다.

.이 작업에 대해
* 하드 디스크 드라이브(HDD) 로컬 계층을 RAID-DP에서 RAID-TEC로 변환할 수 있습니다. 여기에는 Flash Pool 로컬 계층의 HDD 계층이 포함됩니다.


.-disktype을 사용하여 각 디스크 유형을 변경해야 하는 flashpools/hybrid aggregates 프로세스
[-T, -disktype {ATA | BSAS | FCAL | FSAS | LUN | MSATA | SAS | SSD | VMDISK | SSD-NVM | SSD-CAP | SSD-ZNS | VMLUN | VMLUN-SSD}] - 디스크 유형

이 매개변수는 수정할 RAID 그룹의 디스크 유형을 지정합니다. Flash Pool의 경우 HDD 계층 또는 SSD 계층 중 하나를 지정합니다. HDD 계층이 두 가지 이상의 디스크 유형으로 구성된 경우, 사용 중인 디스크 유형 중 하나를 지정하면 해당 계층이 수정됩니다. 현재 aggregate RAID 유형이 mixed_raid_type인 경우 이 매개변수는 필수입니다.

.단계
. 로컬 계층이 온라인 상태이고 최소 6개의 디스크가 있는지 확인합니다.
+
'Storage aggregate show-status-aggregate_aggregate_name_'

. 로컬 계층을 RAID-DP에서 RAID-TEC로 전환:
+
'Storage aggregate modify -aggregate_aggregate_name_-raidtype RAID_Tec'

. 로컬 계층 RAID 정책이 RAID-TEC인지 확인합니다.
+
'STORAGE AGGATE SHOW_AGGATE_NAME_'



.관련 정보
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-modify.html["저장소 집계 수정"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-status.html["스토리지 집계 표시 상태"^]

