---
permalink: disks-aggregates/create-local-syncmirror-task.html 
sidebar: sidebar 
keywords: ontap 9, create, aggregates, syncmirror, sync mirror, add, local tier 
summary: 로컬 계층을 수동으로 생성할 때 SyncMirror 활성화하여 로컬 계층 데이터를 동기적으로 미러링할 수 있습니다. 
---
= SyncMirror 활성화된 ONTAP 로컬 계층 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
로컬 계층을 수동으로 생성할 때 SyncMirror 활성화하여 로컬 계층 데이터를 동기적으로 미러링할 수 있습니다.

자세히 알아보세요 link:../concepts/mirrored-unmirrored-aggregates-concept.html["미러링 및 미러링되지 않은 로컬 계층"] .

.시작하기 전에
* 클러스터는 내부 저장소만으로 초기화되어야 합니다.
* 두 노드 모두에서 클러스터 설정이 완료되어야 합니다.


.이 작업에 대해
이 절차는 각 클러스터 노드에 동일한 크기의 미러링된 데이터 로컬 계층을 생성하며, 각 로컬 계층의 디스크 수는 44개입니다.

.단계
. 저장소 자동 할당 비활성화:
+
`storage disk option modify -node * -autoassign off`

. 자동 할당이 비활성화되었는지 확인하세요.
+
'스토리지 디스크 옵션 표시'

. 외부 선반을 부착합니다.
. 풀 1을 지정하여 각 노드에 외부 드라이브를 할당합니다.
+
`storage disk assign -disk <disk ID> -owner <node name> -pool 1`

. 각 노드에서 루트 로컬 계층을 미러링합니다.
+
`storage aggregate mirror -aggregate <node1 root-aggr>`

+
`storage aggregate mirror -aggregate <node2 root-aggr>`

+

NOTE: 풀 1의 드라이브는 플렉스 0의 드라이브와 일치하도록 자동으로 분할됩니다.

. 노드 1에서 디스크 수를 44개로 설정하여 미러링된 데이터 로컬 계층을 만듭니다.  이렇게 하면 풀 0에서 22개의 파티션이 선택되고, 풀 1에서 22개의 파티션이 선택됩니다.
+
`storage aggregate create -node <node1 name> -aggregate <node1 aggr-name> -diskcount 44 -mirror true`

. 노드 2에서 디스크 수를 44개로 설정하여 미러링된 데이터 로컬 계층을 만듭니다.  이렇게 하면 풀 0에서 22개의 파티션이 선택되고, 풀 1에서 22개의 파티션이 선택됩니다.
+
`storage aggregate create -node <node2 name> -aggregate <node2 aggr-name> -diskcount 44 -mirror true`

. 동일한 크기의 로컬 계층이 성공적으로 생성되었는지 확인하세요.
+
'스토리지 집계 쇼'



.관련 정보
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-assign.html["저장 디스크 할당"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-option-modify.html["저장 디스크 옵션 수정"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-option-show.html["저장 디스크 옵션 표시"^]

