---
permalink: disks-aggregates/determine-control-volume-space-aggregate-concept.html 
sidebar: sidebar 
keywords: determine, control, volume, space usage, aggregate, local tier 
summary: 로컬 계층에서 가장 많은 공간을 사용하는 FlexVol 볼륨과 특히 볼륨 내의 기능을 확인할 수 있습니다. 
---
= ONTAP 로컬 계층에 있는 볼륨의 공간 사용량을 확인하고 제어합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
로컬 계층에서 가장 많은 공간을 사용하는 FlexVol 볼륨과 특히 볼륨 내의 기능을 확인할 수 있습니다.

 `volume show-footprint`명령은 볼륨의 설치 공간 또는 포함된 로컬 계층 내의 공간 사용에 대한 정보를 제공합니다.


NOTE: ONTAP 9.7 이전에는 System Manager에서 _aggregate_를 사용하여 _ 로컬 계층을 설명합니다. ONTAP 버전에 관계없이 ONTAP CLI에서는 _aggregate_라는 용어를 사용합니다. 로컬 계층에 대한 자세한 내용은 을 link:../disks-aggregates/index.html["디스크 및 로컬 계층"]참조하십시오.

 `volume show-footprint`명령을 실행하면 오프라인 볼륨을 비롯하여 로컬 계층에 있는 각 볼륨의 공간 사용에 대한 세부 정보가 표시됩니다. 이 명령은 및 `aggregate show-space` 명령의 출력 사이의 간격을 `volume show-space` 연결합니다. 모든 백분율은 로컬 계층 크기의 백분율로 계산됩니다.

다음 예에서는 testvol이라는 볼륨에 대한 'volume show-footprint' 명령 출력을 보여 줍니다.

....
cluster1::> volume show-footprint testvol

      Vserver : thevs
      Volume  : testvol

      Feature                                   Used    Used%
      --------------------------------    ----------    -----
      Volume Data Footprint                  120.6MB       4%
      Volume Guarantee                        1.88GB      71%
      Flexible Volume Metadata               11.38MB       0%
      Delayed Frees                           1.36MB       0%
      Total Footprint                         2.01GB      76%
....
다음 표에서는 'volume show-footprint' 명령의 출력 중 일부 주요 행과 해당 기능을 통해 공간 사용을 줄이기 위해 수행할 수 있는 작업을 설명합니다.

|===


| 행/피처 이름 | 행의 설명/내용 | 줄일 수 있는 방법이 있습니다 


 a| 
'볼륨 데이터 사용 공간'
 a| 
활성 파일 시스템에 있는 볼륨의 데이터에 의해 포함된 로컬 계층에서 사용된 총 공간 및 볼륨의 스냅숏에 사용된 공간입니다. 이 행에는 예약된 공간이 포함되지 않습니다.
 a| 
* 볼륨에서 데이터를 삭제하는 중입니다.
* 볼륨에서 스냅샷을 삭제하는 중입니다.




 a| 
볼륨 보증
 a| 
로컬 계층의 볼륨에서 향후 쓰기를 위해 예약한 공간의 양입니다. 예약된 공간의 양은 볼륨의 보장 유형에 따라 다릅니다.
 a| 
보장 유형을 없음으로 변경합니다.



 a| 
'유연한 볼륨 메타데이터'
 a| 
로컬 계층에서 볼륨의 메타데이터 파일이 사용하는 총 공간입니다.
 a| 
제어할 직접적인 방법이 없습니다.



 a| 
'해방된'
 a| 
ONTAP이 성능에 사용했으며 즉시 해제할 수 없는 블록입니다. SnapMirror 대상의 경우 이 행의 값은 "0"이며 표시되지 않습니다.
 a| 
제어할 직접적인 방법이 없습니다.



 a| 
파일 작업 메타데이터
 a| 
파일 작업 메타데이터에 예약된 총 공간입니다.
 a| 
제어할 직접적인 방법이 없습니다.



 a| 
토털 풋프린트
 a| 
로컬 계층에서 볼륨이 사용하는 총 공간입니다. 모든 행의 합계입니다.
 a| 
볼륨에서 사용하는 공간을 줄이는 데 사용되는 모든 방법

|===
.관련 정보
https://www.netapp.com/pdf.html?item=/media/19670-tr-3483.pdf["NetApp 기술 보고서 3483: NetApp SAN 또는 IP SAN 엔터프라이즈 환경에서 씬 프로비저닝"^]
