---
permalink: disks-aggregates/fast-zeroing-drives-concept.html 
sidebar: sidebar 
keywords: fast, zero, drives 
summary: ONTAP 9.4 이상 버전이 새로 설치된 시스템에서 ONTAP 9.4 이상으로 시스템이 재초기화되는 경우 _fast zeroing_을 사용하여 드라이브를 제로화할 수 있습니다. 
---
= ONTAP 드라이브를 수동으로 빠르게 0으로 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.4 이상 버전이 새로 설치된 시스템에서 ONTAP 9.4 이상으로 시스템이 재초기화되는 경우 _fast zeroing_을 사용하여 드라이브를 제로화할 수 있습니다.

빠른 제로화 _ 를 사용하면 드라이브가 초 내에 제로화됩니다. 이 작업은 프로비저닝 전에 자동으로 수행되며, 스페어 드라이브가 추가될 때 시스템 초기화, 로컬 계층 생성 또는 로컬 계층 확장에 걸리는 시간을 크게 줄여줍니다.

_Fast zeroing_은 SSD와 HDD에서 모두 지원됩니다.


NOTE: _Fast zeroing_은 ONTAP 9.3 이전 버전에서 업그레이드된 시스템에서는 지원되지 않습니다. ONTAP 9.4 이상을 새로 설치하거나 시스템을 다시 초기화해야 합니다. 또한 ONTAP 9.3 이하에서는 ONTAP에 의해 드라이브가 자동으로 제로화되지만 프로세스가 더 오래 걸립니다.

드라이브를 수동으로 제로화할 필요가 있는 경우 다음 방법 중 하나를 사용할 수 있습니다. ONTAP 9.4 이상에서는 수동으로 드라이브를 제로화하는 데 몇 초 밖에 걸리지 않습니다.

[role="tabbed-block"]
====
.CLI 명령
--
* CLI 명령을 사용하여 드라이브를 빠르게 제로합니다 *

.이 작업에 대해
이 명령을 사용하려면 관리자 권한이 필요합니다.

.단계
. CLI 명령을 입력합니다.
+
[source, cli]
----
storage disk zerospares
----


--
.부팅 메뉴 옵션
--
* 부팅 메뉴에서 옵션을 선택하여 드라이브를 빠르게 제로화 * 합니다

.이 작업에 대해
* 빠른 제로화 기능 향상은 ONTAP 9.4 이전의 릴리즈에서 업그레이드된 시스템을 지원하지 않습니다.


.단계
. 부팅 메뉴에서 다음 옵션 중 하나를 선택합니다.
+
** (4) 구성을 청소하고 모든 디스크를 초기화합니다
** (9a) 모든 디스크의 파티션을 해제하고 해당 소유권 정보를 제거합니다
** (9b) 전체 디스크로 구성 정리 및 노드 초기화




--
====
.관련 정보
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-zerospares.html["저장 디스크 제로 스페어"^]

