---
permalink: disks-aggregates/manage-local-tiers-overview-concept.html 
sidebar: sidebar 
keywords: local tier, aggregate, prepare, add, create, disks, RAID, delete, manage local tier, manage aggregate 
summary: 'System Manager 또는 CLI를 사용하여 로컬 계층을 추가하고, 사용을 관리하고, 용량(디스크)을 추가할 수 있습니다.' 
---
= ONTAP 로컬 계층 관리에 대해 자세히 알아보십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager 또는 ONTAP CLI를 사용하여 로컬 계층을 추가하고, 사용을 관리하고, 용량(디스크)을 추가할 수 있습니다.


NOTE: ONTAP 9.7 이전에는 System Manager에서 _aggregate_를 사용하여 _ 로컬 계층을 설명합니다. ONTAP 버전에 관계없이 ONTAP CLI에서는 _aggregate_라는 용어를 사용합니다. 로컬 계층에 대한 자세한 내용은 을 link:../disks-aggregates/index.html["디스크 및 로컬 계층"]참조하십시오.

다음 작업을 수행할 수 있습니다.

* link:add-local-tier-overview-task.html["로컬 계층을 추가(생성)합니다"]
+
로컬 계층을 추가하려면 특정 워크플로를 따릅니다. 로컬 계층에 필요한 디스크 또는 디스크 파티션 수를 결정하고 로컬 계층을 생성하는 데 사용할 방법을 결정합니다. ONTAP에서 구성을 할당하도록 하여 로컬 계층을 자동으로 추가하거나 수동으로 구성을 지정할 수 있습니다.

* link:manage-use-local-tiers-overview-task.html["로컬 계층의 사용을 관리합니다"]
+
기존 로컬 계층의 경우 이름을 바꾸거나 미디어 비용을 설정하거나 드라이브 및 RAID 그룹 정보를 확인할 수 있습니다. 로컬 계층의 RAID 구성을 수정하고 로컬 계층을 스토리지 VM(SVM)에 할당할 수 있습니다. 로컬 계층의 RAID 구성을 수정하고 로컬 계층을 스토리지 VM(SVM)에 할당할 수 있습니다. 로컬 계층에 상주하는 볼륨과 로컬 계층에서 사용하는 공간을 확인할 수 있습니다. 볼륨에서 사용할 수 있는 공간의 양을 제어할 수 있습니다. HA 쌍으로 로컬 계층 소유권을 재배치할 수 있습니다. 로컬 계층을 삭제할 수도 있습니다.

* link:add-capacity-local-tier-overview-task.html["로컬 계층에 용량(디스크)을 추가합니다"]
+
다른 방법을 사용하여 특정 워크플로우를 따라 용량을 추가합니다. 디스크를 로컬 계층에 추가하고 드라이브를 노드 또는 쉘프에 추가할 수 있습니다. 필요한 경우 잘못 정렬된 스페어 파티션을 수정할 수 있습니다.


