---
permalink: flexgroup/increase-capacity-task.html 
sidebar: sidebar 
keywords: increase, size, flexgroup, volume, flex group 
summary: 기존 볼륨 구성 요소에 용량을 추가하거나 새로운 멤버 볼륨으로 FlexGroup 볼륨을 확장하여 FlexGroup 볼륨 크기를 늘립니다. 
---
= ONTAP FlexGroup 볼륨의 크기를 늘립니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexGroup 볼륨의 크기를 늘리려면 FlexGroup 볼륨의 모든 기존 멤버 볼륨(구성 요소)에 용량을 추가하거나 새로운 멤버 볼륨으로 FlexGroup 볼륨을 확장하면 됩니다.  FlexGroup 볼륨은 200개를 초과하는 멤버 볼륨을 가질 수 없습니다.

필요한 경우 FlexGroup 볼륨 내의 개별 볼륨 크기를 늘릴 수도 있습니다.

.시작하기 전에
Aggregate에 충분한 공간이 있어야 합니다.

.이 작업에 대해
공간을 더 추가하려면 FlexGroup 볼륨의 전체 크기를 늘릴 수 있습니다. FlexGroup 볼륨의 크기를 늘리면 FlexGroup 볼륨의 기존 구성원 볼륨의 크기가 조정됩니다.

성능을 향상시키려면 FlexGroup 볼륨을 확장할 수 있습니다. 다음과 같은 경우 FlexGroup 볼륨을 확장하고 새 구성원 볼륨을 추가할 수 있습니다.

* 클러스터에 새 노드가 추가되었습니다.
* 기존 노드에 새 로컬 계층(애그리게이트)이 생성되었습니다.
* FlexGroup 볼륨의 기존 구성원 볼륨이 하드웨어의 최대 FlexVol 크기(100TB 또는 300TB(가 활성화된 경우)에 도달했으므로 link:../volumes/enable-large-vol-file-support-task.html["대용량 지원"]구성원 볼륨을 추가하지 않으면 FlexGroup 볼륨의 크기를 조정할 수 없습니다.


[NOTE]
====
더 많은 멤버를 포함하도록 FlexGroup 볼륨을 수정하는 경우 이전에 생성된 스냅샷은 "부분"으로 간주되며 클라이언트에서만 액세스할 수 있습니다.  `.snapshot` 디렉토리 또는 *이전 버전* 탭.

스냅샷이 "부분"으로 간주되면 SnapRestore 작업에 사용할 수 없습니다. 그러나 부분 스냅샷을 사용하여 개별 파일을 복원할 수 있습니다.  `.snapshot` 디렉토리 또는 *이전 버전* 탭.

====
ONTAP 9.3 이전 릴리즈에서는 SnapMirror 관계가 설정된 후 FlexGroup 볼륨을 확장하지 마십시오. ONTAP 9.3 이전의 릴리즈에서 SnapMirror 관계를 끊은 후 소스 FlexGroup 볼륨을 확장하는 경우 대상 FlexGroup 볼륨에 대한 기본 전송을 다시 수행해야 합니다. ONTAP 9.3부터 SnapMirror 관계에 있는 FlexGroup 볼륨을 확장할 수 있습니다.

.단계
. 필요에 따라 FlexGroup 볼륨의 용량 또는 성능을 늘려서 FlexGroup 볼륨의 크기를 늘립니다.
+
|===


| 를 증가하려면... | 다음을 수행하십시오. 


 a| 
FlexGroup 볼륨의 용량입니다
 a| 
FlexGroup 볼륨의 모든 멤버 볼륨 크기를 조정합니다.

`volume modify -vserver <svm_name> -volume <fg_name> -size <new_size>`



 a| 
FlexGroup 볼륨의 성능입니다
 a| 
새 구성원 볼륨(구성 요소)을 추가하여 FlexGroup 볼륨 확장:

'+volume expand-vserver vserver_name-volume fg_name-aggr-list 집계 이름,... [-aggr-list-multiplier f구성요소_per_aggr]+'

'-aggr-list-multiplier' 파라미터의 기본값은 1이다.

를 사용하여 FlexGroup 볼륨을 확장할 link:../fabricpool/index.html["FabricPool"]경우 모든 로컬 계층(애그리게이트)을 동일한 클라우드 계층에 연결해야 합니다.

|===


기존 애그리게이트(로컬 계층) 또는 구성원 볼륨이 최대 용량(각각 100/300TB 또는 20억 개의 파일)에 도달하지 않았다면 구성원 볼륨을 추가하는 대신 FlexGroup 볼륨의 전체 크기를 늘리는 것이 더 낫습니다.

기존 볼륨 크기 또는 파일 수를 늘릴 수 없거나 FlexGroup를 새 하드웨어로 확장하는 경우에만 볼륨 확장을 사용하십시오. 일관된 성능을 보장하려면 모든 노드에 동일한 수의 구성원 볼륨을 추가해야 합니다. 예를 들어, 기존 FlexGroup 볼륨에 노드당 4개의 구성원 볼륨이 있는 8개의 구성원 볼륨이 있는 경우 노드당 두 개의 구성원을 추가하면 구성원 볼륨 12개가 되고 노드당 6개의 구성원 볼륨이 됩니다.

새 노드에 새 구성원을 추가할 때 기존 노드와 같이 노드당 구성원 볼륨의 일관된 수를 유지하십시오. 예를 들어, 기존 FlexGroup 볼륨에 노드당 4개의 구성원 볼륨이 있는 8개의 구성원 볼륨이 있는 경우 FlexGroup 볼륨을 새 노드로 확장할 경우 4개의 구성원 볼륨을 추가하여 12개의 구성원 FlexGroup 볼륨을 추가해야 합니다.

FlexGroup 볼륨에 새 멤버를 추가하면 빈 새 멤버 볼륨을 사용하기 위해 수집 휴리스틱이 변경되며, 새 멤버 볼륨이 기존 멤버 볼륨과 밸런싱될 때까지 새 데이터 수집의 전체 시스템 성능에 영향을 미칠 수 있습니다.

.예
* 기존 구성원 볼륨의 용량을 늘리는 예 *

다음 예에서는 FlexGroup 볼륨 volX에 20TB 공간을 추가하는 방법을 보여 줍니다.

[listing]
----
cluster1::> volume modify -vserver svm1 -volume volX -size +20TB
----
FlexGroup 볼륨에 16개의 구성원 볼륨이 있는 경우 각 구성원 볼륨의 공간이 1.25TB씩 증가합니다.

* 새 구성원 볼륨을 추가하여 성능을 향상시키는 예 *

다음 예에서는 FlexGroup 볼륨에 기본 로컬 계층(집계) 각각에 2개씩 총 4개의 추가 멤버 볼륨을 추가하는 방법을 보여줍니다.  `fg1` :

[listing]
----
cluster1::> volume expand -vserver svm1 -volume fg1 -aggr-list aggr1,aggr2 -aggr-list-multiplier 2
----
새 구성원 볼륨의 크기는 기존 구성원 볼륨의 크기와 동일합니다.

.개별 볼륨의 크기를 늘리세요
FlexGroup 볼륨에서 개별 멤버 볼륨의 크기를 늘리려면 다음을 사용할 수 있습니다. `volume resize` 명령.

.단계
. 단일 FlexGroup 멤버 볼륨의 크기를 늘리세요.
+
`volume size -volume <volume_name> -vserver <svm1> -new-size <new_size>`

+
다음 예제에서는 FlexGroup 멤버 볼륨 FG_0003의 크기를 3.7GB로 늘립니다.

+
[listing]
----
volume size -volume FG__0003 -vserver svm1 -new-size 3.7GB
vol size: Volume "svm1:FG__0003" size set to 3.70g.
----

