---
permalink: flexgroup/protect-snapshot-copies-task.html 
sidebar: sidebar 
keywords: protect, flexgroup, volume, snapshot, copy, flex group, snap shot, manually, manual, automatically, automatic, policy 
summary: 스냅샷 생성을 자동으로 관리하는 스냅샷 정책을 생성하거나 FlexGroup 볼륨에 대한 스냅샷을 수동으로 생성할 수 있습니다. ONTAP에서 FlexGroup 볼륨의 각 구성요소에 대한 스냅샷을 생성할 수 있는 경우에만 FlexGroup 볼륨에 대해 유효한 스냅샷이 생성됩니다. 
---
= 스냅샷을 사용하여 ONTAP FlexGroup 볼륨을 보호합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스냅샷 생성을 자동으로 관리하는 스냅샷 정책을 생성하거나 FlexGroup 볼륨에 대한 스냅샷을 수동으로 생성할 수 있습니다. ONTAP에서 FlexGroup 볼륨의 각 구성요소에 대한 스냅샷을 생성할 수 있는 경우에만 FlexGroup 볼륨에 대해 유효한 스냅샷이 생성됩니다.

.이 작업에 대해
* 스냅샷 정책과 연결된 FlexGroup 볼륨이 여러 개인 경우 FlexGroup 볼륨 일정이 겹치지 않도록 해야 합니다.
* ONTAP 9.8부터 FlexGroup 볼륨에서 지원되는 최대 스냅샷 수는 1023개입니다.



NOTE: ONTAP 9.8부터 `volume snapshot show` FlexGroup 볼륨에 대한 명령은 가장 최근에 소유한 블록을 계산하지 않고 논리적 블록을 사용하여 스냅샷 크기를 보고합니다. 이 새로운 크기 계산 방법을 사용하면 스냅샷 크기가 이전 버전의 ONTAP에서 계산한 크기보다 크게 나타날 수 있습니다.

.단계
. 스냅샷 정책을 생성하거나 스냅샷을 수동으로 생성합니다.
+
|===


| 을(를) 만들려면... | 이 명령을 입력하십시오... 


 a| 
스냅샷 정책
 a| 
볼륨 스냅샷 정책 생성


NOTE: FlexGroup 볼륨의 스냅샷 정책과 연결된 스케줄의 간격은 30분 이상이어야 합니다.

FlexGroup 볼륨을 생성할 때 `default` 스냅샷 정책이 FlexGroup 볼륨에 적용됩니다.



 a| 
수동으로 스냅샷 생성
 a| 
'볼륨 스냅샷 생성'


NOTE: FlexGroup 볼륨에 대한 스냅샷을 생성한 후에는 스냅샷의 속성을 수정할 수 없습니다. 속성을 수정하려면 스냅샷을 삭제한 다음 다시 생성해야 합니다.

|===


스냅샷이 생성되면 FlexGroup 볼륨에 대한 클라이언트 액세스가 잠시 중단됩니다.

. FlexGroup 볼륨에 대해 유효한 스냅샷이 생성되었는지 확인합니다. `volume snapshot show -volume volume_name -fields state`
+
[listing]
----
cluster1::> volume snapshot show -volume fg -fields state
vserver volume snapshot               state
------- ------ ---------------------- -----
fg_vs   fg     hourly.2016-08-23_0505 valid
----
. FlexGroup 볼륨 구성 요소에 대한 스냅샷 보기: `volume snapshot show -is-constituent true`
+
[listing]
----
cluster1::> volume snapshot show -is-constituent true
                                                                 ---Blocks---
Vserver  Volume   Snapshot                                  Size Total% Used%
-------- -------- ------------------------------------- -------- ------ -----
fg_vs    fg__0001
                  hourly.2016-08-23_0505                    72MB     0%   27%
         fg__0002
                  hourly.2016-08-23_0505                    72MB     0%   27%
         fg__0003
                  hourly.2016-08-23_0505                    72MB     0%   27%
...
         fg__0016
                  hourly.2016-08-23_0505                    72MB     0%   27%
----

