---
permalink: flexgroup/provision-automatically-task.html 
sidebar: sidebar 
keywords: provision, flexgroup, volume, automatic, create, flex group, aggregate, space 
summary: 'FlexGroup 볼륨을 생성할 때 ONTAP에서 로컬 계층(애그리게이트)을 자동으로 선택하여 FlexGroup 볼륨을 프로비저닝하도록 선택할 수 있습니다. 최적의 성능을 위한 모범 사례에 따라 로컬 계층을 선택합니다.' 
---
= ONTAP FlexGroup 볼륨을 자동으로 프로비저닝합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexGroup 볼륨을 생성할 때 ONTAP에서 기본 로컬 계층(애그리게이트)을 선택하여 FlexGroup 볼륨을 자동으로 프로비저닝하도록 선택할 수 있습니다. 최적의 성능과 용량을 위한 Best Practice에 따라 로컬 계층을 선택합니다.

.시작하기 전에
클러스터의 각 노드에는 하나 이상의 로컬 계층이 있어야 합니다.

[NOTE]
====
비활성 데이터를 계층화할 FlexGroup 볼륨을 생성할 경우 각 노드에 FabricPool가 활성화된 로컬 계층이 하나 이상 있어야 합니다.

====
.이 작업에 대해
ONTAP는 각 노드에서 사용 가능한 공간이 가장 많은 2개의 로컬 계층을 선택하여 FlexGroup 볼륨을 생성합니다. 2개의 로컬 계층을 사용할 수 없는 경우 ONTAP는 노드당 하나의 로컬 계층을 선택하여 FlexGroup 볼륨을 생성합니다.

ONTAP 9.15.1부터 FlexGroup 볼륨을 자동으로 프로비저닝할 때 ONTAP는 BP(균형 잡힌 배치)를 사용하여 로컬 계층과 FlexGroup 구성원(구성) 볼륨 레이아웃을 선택합니다. BP의 한 가지 측면은 '없음' 보장(씬 프로비저닝) FlexGroup 볼륨을 생성할 때 로컬 계층의 오버 프로비저닝을 제한하는 방법입니다. 전체 FlexGroup 볼륨의 크기는 로컬 계층에서 사용 가능한 공간의 양에 따라 제한되지만, 이 제한은 '볼륨'이 보장하는(씩 프로비저닝된) FlexGroup 볼륨에 대한 제한보다 큽니다. REST API 또는 ONTAP CLI를 사용하여 FlexGroup 볼륨을 생성할 `auto-provision-as` 경우 이 제한으로 인해 공간이 부족하여 프로비저닝이 실패할 수 있습니다. 더 작은 FlexGroup 볼륨을 생성하거나 매개 변수를 사용하면 이러한 문제를 방지할 수 link:create-task.html["FlexGroup 볼륨을 생성하고 로컬 계층을 수동으로 선택합니다"] `aggr-list` 있습니다.

.단계
. FlexGroup 볼륨 프로비저닝:
+
`volume create -vserver svm_name -volume fg_vol_name –auto-provision-as flexgroup -size fg_size [–encrypt true] [-qos-policy-group qos_policy_group_name] [-support-tiering true] [-granular-data advanced]`

+
ONTAP 9.16.1부터  (`-granular-data advanced`CLI에서 를 활성화하여 파일이 10GB보다 클 때 여러 FlexGroup 멤버 볼륨에 걸쳐 데이터를 쓸 수 link:../enable-adv-capacity-flexgroup-task.html["고급 용량 밸런싱"]있습니다.

+
ONTAP 9.5부터 FabricPool를 사용하는 로컬 계층에 FlexGroup 볼륨을 생성할 수 있습니다. FabricPool가 활성화된 상태에서 로컬 계층에서 FlexGroup 볼륨을 자동으로 프로비저닝하려면 매개 변수 를 로 `true` 설정해야 `-support-tiering` 합니다. FabricPool에 대해서는 볼륨 보증이 항상 으로 설정되어야 `none` 합니다. FlexGroup 볼륨에 대한 계층화 정책 및 계층화 최소 냉각 기간을 지정할 수도 있습니다.

+
link:../disks-aggregates/index.html["디스크 및 애그리게이트 관리"]

+
FlexGroup 볼륨의 처리량 한도(QoS Max)를 지정할 수 있습니다. 이로 인해 FlexGroup 볼륨이 사용할 수 있는 성능 리소스가 제한됩니다. ONTAP 9.4부터 FlexGroup 볼륨에 대한 처리량 층(QoS Min) 및 적응형 QoS를 지정할 수 있습니다.

+
link:../performance-admin/index.html["성능 관리"]

+
FlexGroup 볼륨에서 암호화를 활성화하려면 매개 변수를 로 `true` 설정할 수 `-encrypt` 있습니다. 암호화된 볼륨을 만들려면 볼륨 암호화 라이센스와 키 관리자를 설치해야 합니다.

+

NOTE: 생성 시 FlexGroup 볼륨에서 암호화를 활성화해야 합니다. 기존 FlexGroup 볼륨에서는 암호화를 설정할 수 없습니다.

+
link:../encryption-at-rest/index.html["유휴 데이터의 암호화"]

+
"size" 매개 변수는 FlexGroup 볼륨의 크기를 KB, MB, GB, TB 또는 PB 단위로 지정합니다.

+
다음 예에서는 400TB 크기의 FlexGroup 볼륨을 프로비저닝하는 방법을 보여줍니다.

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
다음 예에서는 처리량 상한에 대한 QoS 정책 그룹을 생성하는 방법과 FlexGroup 볼륨에 적용하는 방법을 보여 줍니다.

+
[listing]
----
cluster1::> qos policy-group create -policy group pg-vs1 -vserver vs1 -max-throughput 5000iops
----
+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -qos-policy-group pg-vs1
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
다음 예에서는 FabricPool가 활성화된 상태에서 로컬 계층에서 400TB 크기의 FlexGroup 볼륨을 프로비저닝하는 방법을 보여줍니다.

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -support-tiering true -tiering-policy auto
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
FlexGroup 볼륨은 클러스터의 각 노드에 8개의 구성원 볼륨으로 생성됩니다. 구성원 볼륨은 각 노드에서 가장 큰 두 로컬 계층 간에 균등하게 분산됩니다.

+
기본적으로 FlexGroup 볼륨은 AFF 시스템을 제외하고 '볼륨' 공간 보장 설정으로 생성됩니다. AFF 시스템의 경우 기본적으로 FlexGroup 볼륨은 'none' 공간 보장으로 생성됩니다.

. 접합 경로로 FlexGroup 볼륨을 마운트합니다.
+
`volume mount -vserver vserver_name -volume vol_name -junction-path junction_path`

+
[listing]
----
cluster1::> volume mount -vserver vs0 -volume fg2 -junction-path /fg2
----


.작업을 마친 후
클라이언트에서 FlexGroup 볼륨을 마운트해야 합니다.

ONTAP 9.6 이하 버전을 실행 중이고 SVM(스토리지 가상 시스템)에 NFSv3 및 NFSv4가 모두 구성되어 있는 경우 클라이언트에서 FlexGroup 볼륨을 마운트하지 못할 수 있습니다. 이러한 경우 클라이언트에서 FlexGroup 볼륨을 마운트할 때 NFS 버전을 명시적으로 지정해야 합니다.

[listing]
----
# mount -t nfs -o vers=3 192.53.19.64:/fg2 /mnt/fg2
# ls /mnt/fg2
file1  file2
----