---
permalink: flexgroup/snapvault-backup-concept.html 
sidebar: sidebar 
keywords: consider, create, snapvault, backup, relation, unified, data, protection, flexgroup, volume 
summary: SnapVault 볼륨에 대한 FlexGroup 백업 관계 및 통합 데이터 보호 관계를 생성할 때 고려해야 할 사항에 대해 알고 있어야 합니다. 
---
= SnapVault 백업 관계를 생성할 때의 고려 사항 및 FlexGroup 볼륨에 대한 통합 데이터 보호 관계
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapVault 볼륨에 대한 FlexGroup 백업 관계 및 통합 데이터 보호 관계를 생성할 때 고려해야 할 사항에 대해 알고 있어야 합니다.

* 최신 공용 스냅샷보다 최신 상태의 대상 볼륨에 스냅샷을 보존할 수 있는 옵션을 사용하여 SnapVault 백업 관계 및 통합 데이터 보호 관계를 다시 동기화할 수 `-preserve` 있습니다.
* FlexGroup 볼륨에서는 장기 보존이 지원되지 않습니다.
+
장기 보존을 통해 소스 볼륨에 스냅샷을 저장할 필요 없이 대상 볼륨에 스냅샷을 직접 생성할 수 있습니다.

* FlexGroup 볼륨에 대해서는 '스냅샷' 명령 '만료 시간' 옵션이 지원되지 않습니다.
* SnapVault 백업 관계 및 통합 데이터 보호 관계의 대상 FlexGroup 볼륨에서는 스토리지 효율성을 구성할 수 없습니다.
* FlexGroup 볼륨에 대한 SnapVault 백업 관계 및 통합 데이터 보호 관계의 스냅샷의 이름은 변경할 수 없습니다.
* FlexGroup 볼륨은 하나의 백업 관계나 복구 관계의 소스 볼륨일 수 있습니다.
+
FlexGroup 볼륨은 두 SnapVault 관계, 두 개의 복구 관계 또는 SnapVault 백업 관계 및 복구 관계의 소스가 될 수 없습니다.

* 소스 FlexGroup 볼륨에서 스냅샷을 삭제하고 동일한 이름의 스냅샷을 다시 생성하는 경우 대상 볼륨에 동일한 이름의 스냅샷이 있을 경우 대상 FlexGroup 볼륨으로의 다음 업데이트 전송이 실패합니다.
+
FlexGroup 볼륨에 대해 스냅샷 이름을 바꿀 수 없기 때문입니다.


