---
permalink: flexcache-writeback/flexcache-write-back-guidelines.html 
sidebar: sidebar 
keywords: tr-4743, flexcache writeback, flexcache write-back, flexcache, write-back, write back, guidelines, best practices, performance, ontap tr, netapp tr 
summary: FlexCache write-back을 사용할 때 최적의 성능을 보장하려면 다음 지침을 따르십시오. 
---
= ONTAP FlexCache write-back 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexCache 쓰기 저장에는 원본과 캐시 간의 많은 복잡한 상호작용이 포함됩니다. 최적의 성능을 얻으려면 환경이 다음 지침을 따라야 합니다. 이 가이드라인은 콘텐츠 생성 당시 사용 가능한 최신 주요 ONTAP 버전(ONTAP 9.17.1)을 기반으로 합니다.

비운영 환경에서 운영 워크로드를 테스트하는 것이 가장 좋습니다. 이 지침을 벗어나는 FlexCache Write-Back을 구현할 경우 더욱 중요합니다.

다음 지침은 NetApp에서 내부적으로 잘 테스트되었습니다. 이 호텔 안에 머무시는 것이 좋습니다. 그렇지 않으면 예기치 않은 동작이 발생할 수 있습니다.

* ONTAP 9.17.1P1에서는 FlexCache 쓰기 저장 기능에 대한 중요한 개선 사항이 도입되었습니다. 9.17.1P1 이후에는 원본 클러스터와 캐시 클러스터 모두에서 현재 권장되는 릴리스를 실행하는 것이 *_강력히_* 권장됩니다. 9.17.1 코드라인을 실행할 수 없는 경우, 다음으로 제안되는 릴리스는 최신 P 릴리스인 9.16.1입니다. ONTAP 9.15.1에는 FlexCache 쓰기 저장에 필요한 모든 수정 사항과 개선 사항이 포함되어 있지 않으므로 프로덕션 워크로드에는 권장되지 않습니다.
* 현재 반복에서 FlexCache write-back 캐시는 전체 FlexCache 볼륨에 대해 단일 구성요소로 구성해야 합니다. 다중 구성 FlexCache는 캐시에서 원치 않는 데이터 제거를 초래할 수 있습니다.
* 100GB 미만의 파일에 대해 테스트를 실행했으며, 캐시와 원본 간의 WAN 왕복 시간이 200ms를 초과하지 않도록 했습니다. 이러한 한도를 벗어나는 작업 부하로 인해 예상치 못한 성능 특성이 나타날 수 있습니다.
* SMB 대체 데이터 스트림에 쓰면 주 파일이 캐시에서 제거됩니다. 기본 파일의 모든 더티 데이터를 오리진으로 플러시해야 해당 파일에 대해 다른 작업을 수행할 수 있습니다. 대체 데이터 스트림도 오리진으로 전달됩니다.
* 파일 이름을 바꾸면 파일이 캐시에서 제거됩니다. 파일의 모든 더티 데이터를 오리진으로 플러시해야 해당 파일에 대해 다른 작업을 수행할 수 있습니다.
* 이때 write-back 지원 FlexCache 볼륨의 파일에 대해 변경하거나 설정할 수 있는 유일한 속성은 다음과 같습니다.
+
** 타임스탬프
** 모드 비트
** NT ACL을 선택합니다
** 소유자
** 그룹
** 크기
+
변경되거나 설정된 다른 특성은 오리진으로 전달되어 캐시에서 파일을 제거할 수 있습니다. 캐시에서 다른 속성을 변경하거나 설정해야 할 경우, 어카운트 팀에 PVR을 개설하도록 요청하십시오.



* 오리진에서 생성된 스냅샷으로 인해 해당 오리진 볼륨과 연결된 모든 write-back 지원 캐시에서 미처리 더티 데이터를 모두 불러옵니다. 이렇게 하려면 많은 양의 쓰기 저장 작업이 진행 중인 경우 이러한 더티 파일을 제거하는 데 시간이 걸릴 수 있으므로 여러 번 작업을 다시 시도해야 할 수 있습니다.
* 쓰기를 위한 SMB 기회 잠금(Oplock)은 쓰기 백이 활성화된 FlexCache 볼륨에서 지원되지 않습니다.
* 원점은 80% 미만으로 남아 있어야 합니다. 오리진 볼륨에 20% 이상의 공간이 남아 있지 않으면 캐시 볼륨에 전용 잠금 위임이 부여되지 않습니다. 이 경우 다시 쓰기 가능 캐시에 대한 호출은 오리진으로 전달됩니다. 이렇게 하면 오리진에서 공간이 부족해지는 것을 방지할 수 있으며, 이로 인해 다시 쓰기 가능 캐시에 더티 데이터가 분리된 상태로 남게 됩니다.
* 낮은 대역폭 및/또는 손실이 많은 클러스터 간 네트워크는 FlexCache 쓰기 성능에 상당한 부정적인 영향을 미칠 수 있습니다. 작업 부하에 따라 크게 달라지므로 특정 대역폭 요구 사항은 없지만 캐시와 원본 간의 클러스터 간 링크 상태를 확인하는 것이 *_강력히_* 권장됩니다.

