---
permalink: flexcache-writeback/flexcache-write-back-prerequisites.html 
sidebar: sidebar 
keywords: tr-4743, flexcache writeback, flexcache write-back, prerequisites, technical report, netapp tr, ontap tr 
summary: 쓰기 저장 모드로 FlexCache를 배포하기 전에 이러한 소프트웨어, 라이센스 및 시스템 구성 요구 사항을 충족하는지 확인하십시오. 
---
= ONTAP FlexCache write-back 사전 요구 사항
:allow-uri-read: 


[role="lead"]
쓰기 저장 모드로 FlexCache를 배포하기 전에 이러한 성능, 소프트웨어, 라이센스 및 시스템 구성 요구 사항을 충족하는지 확인하십시오.



[[cpu-and-memory]]
== CPU 및 메모리

쓰기 저장이 활성화된 캐시에서 시작된 쓰기 저장 메시지를 수용하기 위해 각 원본 클러스터 노드에 최소 128GB의 RAM과 20개의 CPU가 있는 것이 __**강력히 권장**__됩니다. A400 이상과 동일합니다. 오리진 클러스터가 복수 쓰기 가능 FlexCaches의 오리진으로 작동하는 경우 더 많은 CPU와 RAM이 필요합니다.


CAUTION: 작업 부하에 크기가 작은 원본을 사용하면 다시 쓰기 가능 캐시 또는 오리진에서 성능에 큰 영향을 줄 수 있습니다.



[[ontap-version]]
== ONTAP 버전입니다

* 원본은 ONTAP 9.15.1 이상을 실행해야 합니다. 그러나 ONTAP 9.15.1에는 FlexCache 쓰기 지연에 필요한 모든 수정 사항과 개선 사항이 포함되어 있지 않으므로 프로덕션 워크로드에는 권장되지 않습니다. ONTAP 9.17.1P1에서 FlexCache 쓰기 지연에 대한 중요한 개선 사항이 도입되었습니다. 원본 및 캐시 클러스터 모두에서 9.17.1P1 이후의 현재 권장 릴리스를 실행할 것을 강력히 권장합니다. ONTAP 9.17.1을 실행할 수 없는 경우, 9.16.1의 최신 P 릴리스가 차선책으로 권장되는 릴리스입니다.
+

NOTE: 환경에서 FlexCache 쓰기 되돌림을 구현하기 전에 link:flexcache-write-back-guidelines.html["FlexCache write-back 지침"]을 검토하는 것을 *_강력히_* 권장합니다.

* write-back 모드에서 작동해야 하는 캐싱 클러스터는 *_must_ * ONTAP 9.15.1 이상을 실행하고 있습니다.
* 쓰기 백 모드로 작동할 필요가 없는 모든 캐싱 클러스터는 FlexCache 볼륨을 지원하는 모든 ONTAP 버전을 실행할 수 있습니다.




[[licensing]]
== 라이센싱

ONTAP 구매에 쓰기 작업 모드를 포함한 FlexCache가 포함됩니다. 추가 라이센스가 필요하지 않습니다.



[[peering]]
== 피어링

* 오리진 및 캐시 클러스터는 이어야 합니다 link:../flexcache-writeback/flexcache-writeback-enable-task.html["클러스터 피어링된"]
* 원본 및 캐시 클러스터의 SVM(서버 가상 머신)은 FlexCache 옵션을 사용해야 합니다 link:../flexcache-writeback/flexcache-writeback-enable-task.html["SVM 피어링이 발생했습니다"] .



NOTE: 캐시 클러스터를 다른 캐시 클러스터로 피어링할 필요가 없습니다. 또한 캐시 SVM을 다른 캐시 SVM에 피어링할 필요가 없습니다.
