---
sidebar: sidebar 
permalink: s3-snapmirror/index.html 
keywords: snapmirror s3 buckets, snapmirror buckets SVM, snapmirror s3 data protection, hybrid cloud bundle, snapmirror s3 relationship, VM peering, cluster and storage VM peering, Fan-in deployments, data protection, snapmirror s3 policy, peering 
summary: ONTAP 9.10.1부터 친숙한 SnapMirror 미러링 및 백업 기능을 사용하여 ONTAP S3 오브젝트 저장소의 버킷을 보호할 수 있습니다. 
---
= ONTAP SnapMirror S3에 대해 알아보십시오
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 9.10.1부터 SnapMirror 미러링 및 백업 기능을 사용하여 ONTAP S3 오브젝트 저장소의 버킷을 보호할 수 있습니다. 표준 SnapMirror와 달리 SnapMirror S3를 통해 AWS S3와 같은 비 NetApp 대상에 대한 미러링 및 백업을 수행할 수 있습니다.

SnapMirror S3는 ONTAP S3 버킷에서 다음 대상에 이르는 액티브 미러 및 백업 계층을 지원합니다.

[cols="50,25,25"]
|===
| 타겟 | 액티브 미러 및 테이크오버 지원 | 백업 및 복원을 지원합니까? 


 a| 
ONTAP S3

* 버킷이 동일한 SVM에 포함됩니다
* 동일한 클러스터에서 서로 다른 SVM의 버킷
* SVM의 다양한 클러스터에서 버킷

| 예 | 예 


| StorageGRID | 아니요 | 예 


| 설치하고 | 아니요 | 예 


| Azure용 Cloud Volumes ONTAP | 예 | 예 


| AWS 환경을 위한 Cloud Volumes ONTAP | 예 | 예 


| Google Cloud용 Cloud Volumes ONTAP | 예 | 예 
|===
ONTAP S3 서버에서 기존 버킷을 보호하거나 데이터 보호를 즉시 활성화할 수 있는 새로운 버킷을 생성할 수 있습니다.



== SnapMirror S3 요구사항

* ONTAP 버전입니다
+
소스 및 대상 클러스터에서 ONTAP 9.10.1 이상이 실행되고 있어야 합니다.

+

NOTE: SnapMirror S3는 MetroCluster 구성에서 지원되지 않습니다.

* 라이센싱
+
에서 사용할 수 있는 라이센스는 다음과 같습니다 link:../system-admin/manage-licenses-concept.html["ONTAP 1 을 참조하십시오"] ONTAP 소스 및 대상 시스템에서 다음 항목에 대한 액세스를 제공하려면 소프트웨어 제품군이 필요합니다.

+
** ONTAP S3 프로토콜 및 스토리지
** SnapMirror S3에서 다른 NetApp 오브젝트 저장소 타겟(ONTAP S3, StorageGRID, Cloud Volumes ONTAP) 공략
** SnapMirror S3에서 AWS S3(에서 사용 가능link:../data-protection/install-snapmirror-cloud-license-task.html["ONTAP One 호환성 번들"])를 비롯한 타사 오브젝트 저장소 공략
** 클러스터에서 ONTAP 9.10.1을 실행 중인 link:../fabricpool/install-license-aws-azure-ibm-task.html["FabricPool 라이센스"]경우 가 필요합니다.


* ONTAP S3
+
** ONTAP S3 서버에서 소스 및 타겟 SVM을 실행해야 합니다.
** TLS 액세스를 위한 CA 인증서를 S3 서버를 호스팅하는 시스템에 설치하는 것이 좋지만 반드시 필요한 것은 아닙니다.
+
*** S3 서버의 인증서를 서명하는 데 사용되는 CA 인증서는 S3 서버를 호스팅하는 클러스터의 관리 스토리지 VM에 설치해야 합니다.
*** 자체 서명된 CA 인증서 또는 외부 CA 공급업체에서 서명한 인증서를 사용할 수 있습니다.
*** 소스 또는 대상 스토리지 VM이 HTTPS에서 수신 대기 중이 아닌 경우 CA 인증서를 설치할 필요가 없습니다.




* 피어링(ONTAP S3 타겟용)
+
** 인터클러스터 LIF를 구성해야 하며(원격 ONTAP 대상용), 소스 및 대상 클러스터의 인터클러스터 LIF가 소스 및 대상 S3 서버 데이터 LIF에 연결할 수 있습니다.
** 소스 및 타겟 클러스터를 피어링했습니다(원격 ONTAP 타겟의 경우).
** 소스 및 타겟 스토리지 VM을 모든 ONTAP 타겟에 대해 피어링했습니다.


* SnapMirror 정책
+
** 모든 SnapMirror S3 관계에 S3별 SnapMirror 정책이 필요하지만 여러 관계에 동일한 정책을 사용할 수 있습니다.
** 사용자 고유의 정책을 만들거나 다음 값을 포함하는 기본 * 연속 * 정책을 사용할 수 있습니다.
+
*** 스로틀(처리량/대역폭의 상한) - 무제한
*** 복구 지점 목표 시간: 1시간(3600초)







NOTE: SnapMirror 관계에 있는 두 개의 S3 버킷이 있을 때 개체의 현재 버전이 만료(삭제됨)되도록 라이프사이클 정책이 구성된 경우 동일한 작업이 파트너 버킷에 복제된다는 것을 알아야 합니다. 파트너 버킷이 읽기 전용 또는 패시브 인 경우에도 마찬가지입니다.

* 루트 사용자 키 SnapMirror S3 관계에 필요한 스토리지 VM 루트 사용자 액세스 키는 ONTAP에서 기본적으로 할당하지 않습니다. SnapMirror S3 관계를 처음 생성할 때 소스 및 대상 스토리지 VM에 키가 있는지 확인해야 하며, 키가 없으면 키를 다시 생성해야 합니다. 다시 생성해야 하는 경우 액세스 및 암호 키 쌍을 사용하는 모든 클라이언트 및 모든 SnapMirror 오브젝트 저장소 구성을 새 키로 업데이트해야 합니다.


S3 서버 구성에 대한 자세한 내용은 다음 항목을 참조하십시오.

* link:../task_object_provision_enable_s3_server.html["스토리지 VM에서 S3 서버를 활성화합니다"]
* link:../s3-config/index.html["ONTAP S3 구성 프로세스 정보"]


클러스터 및 스토리지 VM 피어링에 대한 자세한 내용은 다음 항목을 참조하십시오.

* link:../task_dp_prepare_mirror.html["미러링 및 보관 준비(System Manager, 1-6단계)"]
* link:../peering/index.html["클러스터 및 SVM 피어링(CLI)"]




== 지원되는 SnapMirror 관계

SnapMirror S3는 팬아웃 및 계단식 관계를 지원합니다. 개요는 을 참조하십시오link:../data-protection/supported-deployment-config-concept.html["팬아웃 및 캐스케이드 데이터 보호 구축"].

SnapMirror S3는 팬인 구축(여러 소스 버킷과 단일 대상 버킷 간의 데이터 보호 관계)을 지원하지 않습니다. SnapMirror S3는 여러 클러스터에서 단일 보조 클러스터로 여러 버킷 미러를 지원할 수 있지만 각 소스 버킷에는 보조 클러스터에 자체 대상 버킷이 있어야 합니다.

SnapMirror S3는 MetroCluster 환경에서 지원되지 않습니다.



== S3 버킷에 대한 액세스 제어

새 버킷을 생성할 때 사용자 및 그룹을 생성하여 액세스를 제어할 수 있습니다.

SnapMirror S3는 소스 버킷에서 타겟 버킷으로 오브젝트를 복제하지만 소스 오브젝트 저장소의 사용자, 그룹 및 정책을 타겟 오브젝트 저장소로 복제하지 않습니다.

페일오버 이벤트 중에 클라이언트가 대상 버킷에 액세스할 수 있도록 대상 오브젝트 저장소에서 사용자, 그룹 정책, 권한 및 유사한 구성 요소를 구성해야 합니다.

대상 클러스터에서 사용자가 생성될 때 소스 키를 수동으로 제공하는 경우 소스 및 대상 사용자가 동일한 액세스 및 암호 키를 사용할 수 있습니다. 예를 들면 다음과 같습니다.

[listing]
----
vserver object-store-server user create -vserver svm1 -user user1 -access-key "20-characters" -secret-key "40-characters"
----
자세한 내용은 다음 항목을 참조하십시오.

* link:../task_object_provision_add_s3_users_groups.html["S3 사용자 및 그룹 추가(System Manager)"]
* link:../s3-config/create-s3-user-task.html["S3 사용자 생성(CLI)"]
* link:../s3-config/create-modify-groups-task.html["S3 그룹 생성 또는 수정(CLI)"]




== SnapMirror S3에서 S3 오브젝트 잠금 및 버전 관리를 사용합니다

오브젝트 잠금 및 버전 관리가 활성화된 ONTAP 버킷에서 SnapMirror S3를 사용할 수 있으며 다음과 같은 몇 가지 사항을 고려해야 합니다.

* 오브젝트 잠금이 설정된 상태로 소스 버킷을 복제하려면 대상 버킷에도 오브젝트 잠금이 설정되어 있어야 합니다. 또한 소스와 대상 모두에 버전 관리가 활성화되어 있어야 합니다. 이렇게 하면 두 버킷의 기본 보존 정책이 서로 다른 경우 삭제 내용을 대상 버킷에 미러링할 필요가 없습니다.
* S3 SnapMirror는 오브젝트의 기간별 버전을 복제하지 않습니다. 개체의 현재 버전만 복제됩니다.


Object Locked 객체가 대상 버킷으로 미러링되면 원래 보존 시간이 유지됩니다. 잠금 해제된 객체가 복제되면 대상 버킷의 기본 보존 기간이 적용됩니다. 예를 들면 다음과 같습니다.

* 버킷 A의 기본 보존 기간은 30일이고 버킷 B의 기본 보존 기간은 60일입니다. Bucket A에서 Bucket B로 복제된 객체는 Bucket B의 기본 보존 기간보다 작더라도 30일 보존 기간을 유지합니다
* 버킷 A에는 기본 보존 기간이 없고 버킷 B에는 기본 보존 기간이 60일입니다. 잠금 해제된 객체가 버킷 A에서 버킷 B로 복제되면 60일의 보존 기간이 적용됩니다. 객체가 Bucket A에서 수동으로 잠길 경우 Bucket B로 복제될 때 원래 보존 기간이 유지됩니다
* 버킷 A의 기본 보존 기간은 30일이고 버킷 B의 기본 보존 기간은 없습니다. 버킷 A에서 버킷 B로 복제된 객체는 30일의 보존 기간을 유지합니다.

