= 
:allow-uri-read: 


Windows를 사용하는 SMB 클라이언트는 파일당 읽기 전용 비트를 설정할 수 있습니다. NFS 클라이언트는 파일당 읽기 전용 비트를 사용하는 프로토콜 작업이 없으므로 파일당 읽기 전용 비트를 설정하지 않습니다.

ONTAP는 Windows를 사용하는 SMB 클라이언트가 해당 파일을 생성할 때 파일에 읽기 전용 비트를 설정할 수 있습니다. 또한 ONTAP는 NFS 클라이언트와 SMB 클라이언트 간에 파일이 공유될 때 읽기 전용 비트를 설정할 수 있습니다. 일부 소프트웨어는 NFS 클라이언트 및 SMB 클라이언트에서 사용할 때 읽기 전용 비트를 사용하도록 설정해야 합니다.

ONTAP가 NFS 클라이언트와 SMB 클라이언트 간에 공유되는 파일에 대해 적절한 읽기 및 쓰기 권한을 유지하려면 다음 규칙에 따라 읽기 전용 비트를 처리합니다.

* NFS는 읽기 전용 비트가 설정된 파일을 쓰기 권한 비트가 설정되지 않은 것처럼 처리합니다.
* NFS 클라이언트가 모든 쓰기 권한 비트를 사용하지 않도록 설정하고 이전에 해당 비트 중 하나 이상이 활성화된 경우 ONTAP는 해당 파일에 대해 읽기 전용 비트를 설정합니다.
* NFS 클라이언트가 쓰기 권한 비트를 설정하면 ONTAP는 해당 파일에 대해 읽기 전용 비트를 해제합니다.
* 파일에 대한 읽기 전용 비트가 설정되어 있고 NFS 클라이언트가 해당 파일에 대한 권한을 검색하려고 하면 파일에 대한 권한 비트가 NFS 클라이언트로 전송되지 않고 ONTAP는 쓰기 권한 비트가 마스킹된 상태로 NFS 클라이언트에 사용 권한 비트를 전송합니다.
* 파일에 대한 읽기 전용 비트가 설정되어 있고 SMB 클라이언트가 읽기 전용 비트를 사용하지 않도록 설정한 경우 ONTAP는 해당 파일에 대한 소유자의 쓰기 권한 비트를 설정합니다.
* 읽기 전용 비트가 설정된 파일은 루트에서만 쓸 수 있습니다.


읽기 전용 비트는 다음과 같은 방식으로 ACL 및 Unix 모드 비트와 상호 작용합니다.

파일에 읽기 전용 비트가 설정된 경우:

* 해당 파일의 ACL에는 변경 사항이 없습니다. NFS 클라이언트는 읽기 전용 비트가 설정되기 전과 동일한 ACL을 보게 됩니다.
* 파일에 대한 쓰기 접근을 허용하는 모든 Unix 모드 비트는 무시됩니다.
* NFS와 SMB 클라이언트는 모두 파일을 읽을 수 있지만, 수정할 수는 없습니다.
* ACL 및 UNIX 모드 비트는 읽기 전용 비트 때문에 무시됩니다. 즉, ACL이 쓰기 액세스를 허용하더라도 읽기 전용 비트는 수정을 방지합니다.


파일에 읽기 전용 비트가 설정되지 않은 경우:

* ONTAP ACL 및 UNIX 모드 비트를 기반으로 액세스를 결정합니다.
+
** ACL 또는 UNIX 모드 비트가 쓰기 액세스를 거부하는 경우 NFS 및 SMB 클라이언트는 파일을 수정할 수 없습니다.
** ACL이나 UNIX 모드 비트가 쓰기 액세스를 거부하지 않으면 NFS 및 SMB 클라이언트가 파일을 수정할 수 있습니다.




[NOTE]
====
파일 권한 변경은 SMB 클라이언트에 즉시 적용되지만 NFS 클라이언트가 특성 캐싱을 사용하는 경우 NFS 클라이언트에 즉시 적용되지 않을 수 있습니다.

====