---
sidebar: sidebar 
permalink: networking/commands_for_managing_firewall_service_and_policies.html 
keywords: manage, managing, firewall, fire, wall, service, policy, policies, commands for managing firewall service and policies, system services firewall, system services firewall policy, network interface modify, system services firewall modify, system services firewall show, system services firewall policy create, network interface modify -lif lifname -firewall-policy, system services firewall policy modify, system services firewall policy show, system services firewall policy clone, system services firewall policy delete 
summary: 방화벽 서비스를 관리합니다 
---
= 방화벽 서비스 및 정책을 관리하는 ONTAP 명령
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
'system services firewall' 명령어를 이용하여 방화벽 서비스를 관리하고, 'system services firewall policy' 명령을 이용하여 방화벽 정책을 관리하고, 'network interface modify' 명령을 사용하여 LIF의 방화벽 설정을 관리할 수 있다.

ONTAP 9.10.1 시작:

* 방화벽 정책은 더 이상 사용되지 않으며 LIF 서비스 정책으로 교체됩니다. 이전에는 방화벽 정책을 사용하여 온보드 방화벽을 관리했습니다. 이 기능은 이제 LIF 서비스 정책을 사용하여 구현됩니다.
* 모든 방화벽 정책이 비어 있으며 기본 방화벽에서 포트를 열지 않습니다. 대신 LIF 서비스 정책을 사용하여 모든 포트를 열어야 합니다.
* 방화벽 정책에서 LIF 서비스 정책으로 전환하기 위해 9.10.1 이상으로 업그레이드한 후에는 작업이 필요하지 않습니다. 이전 ONTAP 릴리즈에서 사용 중인 방화벽 정책과 일치하는 LIF 서비스 정책이 자동으로 구성됩니다. 사용자 지정 방화벽 정책을 만들고 관리하는 스크립트나 기타 도구를 사용하는 경우 대신 해당 스크립트를 업그레이드하여 사용자 지정 서비스 정책을 만들어야 할 수 있습니다.


자세한 내용은 을 참조하십시오 link:lifs_and_service_policies96.html["ONTAP 9.6 이상의 LIF 및 서비스 정책"].

|===


| 원하는 작업 | 이 명령 사용... 


 a| 
방화벽 서비스를 활성화 또는 비활성화합니다
 a| 
시스템 서비스 방화벽 수정



 a| 
방화벽 서비스의 현재 구성을 표시합니다
 a| 
'시스템 서비스 방화벽 쇼'



 a| 
방화벽 정책을 생성하거나 기존 방화벽 정책에 서비스를 추가합니다
 a| 
'시스템 서비스 방화벽 정책 생성



 a| 
LIF에 방화벽 정책을 적용합니다
 a| 
네트워크 인터페이스 수정-lif lifname-firewall-policy



 a| 
방화벽 정책과 연결된 IP 주소 및 넷마스크를 수정합니다
 a| 
시스템 서비스 방화벽 정책 수정



 a| 
방화벽 정책에 대한 정보를 표시합니다
 a| 
'시스템 서비스 방화벽 정책 표시



 a| 
기존 정책의 정확한 사본인 새 방화벽 정책을 생성합니다
 a| 
'시스템 서비스 방화벽 정책 클론



 a| 
LIF에서 사용되지 않는 방화벽 정책을 삭제합니다
 a| 
'시스템 서비스 방화벽 정책 삭제

|===
.관련 정보
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+services+firewall["시스템 서비스 방화벽"^]
* link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html["네트워크 인터페이스 수정"^]

