---
sidebar: sidebar 
permalink: networking/configure_failover_groups_and_policies_for_lifs_overview.html 
keywords: lif, failover, fail, over, target, automatic, automatically, port, link, failure, group, broadcast, domain, lif failover is the automatic migration of a lif to a different network port in response to a link failure, configure failover groups and policies for lifs overview, network interface show -failover 
summary: LIF 페일오버는 링크 장애에 대한 응답으로 LIF를 다른 네트워크 포트로 자동 마이그레이션하는 것입니다. 
---
= ONTAP 네트워크에서의 LIF 페일오버에 대해 알아보십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
LIF 페일오버는 LIF의 현재 포트에서 링크 장애가 발생할 경우 LIF가 다른 네트워크 포트로 자동 마이그레이션되는 것을 의미합니다. 이 기능은 SVM에 대한 연결을 위한 고가용성을 제공하는 핵심 구성요소입니다. LIF 페일오버를 구성하려면 페일오버 그룹을 생성하고, 페일오버 그룹을 사용하도록 LIF를 수정하고, 페일오버 정책을 지정해야 합니다.

SAN 프로토콜 LIF의 경우 페일오버 그룹을 사용한 LIF 페일오버는 지원되지 않습니다. link:../san-admin/multipath-automatic-lif-failover-support.html["SAN 다중 경로 및 자동 LIF 페일오버 지원"]에 대해 알아보십시오.

페일오버 그룹에는 ONTAP 클러스터의 하나 이상의 노드에서 가져온 네트워크 포트(물리적 포트, VLAN 및 인터페이스 그룹) 집합이 포함됩니다. 페일오버 그룹에 있는 네트워크 포트는 LIF에서 사용할 수 있는 페일오버 대상을 정의합니다. 페일오버 그룹에는 클러스터 관리 LIF, 노드 관리 LIF, 인터클러스터 LIF 및 NAS 데이터 LIF를 할당할 수 있습니다.


IMPORTANT: LIF가 유효한 페일오버 대상이 없이 구성되면 LIF가 페일오버를 시도할 때 중단이 발생합니다. 명령을 사용하여 페일오버 구성을 확인할 수 `network interface show -failover` 있습니다. 에 대한 자세한 내용은 `network interface show` link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

브로드캐스트 도메인을 생성하면 동일한 네트워크 포트를 포함하는 동일한 이름의 페일오버 그룹이 자동으로 생성됩니다. 이 페일오버 그룹은 시스템에서 자동으로 관리됩니다. 즉, 포트가 브로드캐스트 도메인에서 추가되거나 제거될 때 포트가 이 페일오버 그룹에서 자동으로 추가 또는 제거됩니다. 이 기능은 고유한 페일오버 그룹을 관리하지 않으려는 관리자에게 효율적으로 제공됩니다.

ONTAP 9.19.1부터 ONTAP 시스템 정의 페일오버 그룹 정책은 NAS 데이터 LIF의 페일오버 타겟을 동적으로 확장하여 클러스터 내 사용 가능한 모든 노드의 브로드캐스트 도메인에 있는 사용 가능한 모든 포트를 포함할 수 있습니다. 시스템 정의 정책을 모든 페일오버 그룹에 적용할 수 있습니다. ONTAP 9.19.1 이전에는 이 정책이 적용된 LIF는 클러스터 내에서 다른 하나의 노드로만 페일오버할 수 있었습니다. 해당 노드가 쿼럼을 충족하지 못하면 다른 노드가 사용 가능하더라도 LIF는 페일오버되지 않았습니다.

.관련 정보
link:https://docs.netapp.com/us-en/asa-r2/administer/manage-client-vm-access.html#create-a-lif-network-interface["ASA r2 시스템의 자동 LIF 페일오버"^]에 대해 알아보십시오.
