---
permalink: concepts/builtin-storage-efficiency-concept.html 
sidebar: sidebar 
keywords: storage efficiency, built-in, platform, controller, offload 
summary: ONTAP 9.15.1부터 AFF A70, AFF A90 및 AFF A1K 플랫폼에 자동 스토리지 효율성 및 데이터 컴팩션이 내장되어 있습니다. 
---
= CPU 또는 전용 오프로드 프로세서 스토리지 효율성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
특정 AFF 및 FAS 플랫폼에서는 CPU 또는 전용 오프로드 프로세서 저장 효율성이 기본적으로 활성화됩니다.  이러한 플랫폼은 온도에 민감한 저장 효율성을 사용하지 않습니다.  압축은 데이터가 차가워질 때까지 기다리지 않고 시작되며, 메인 CPU나 전용 오프로드 프로세서를 사용하여 수행됩니다.  이러한 플랫폼은 압축 데이터의 저장 효율성을 더욱 개선하기 위해 연속적인 물리적 블록을 순차적으로 패킹하는 방식도 사용합니다.

CPU 또는 전용 오프로드 프로세서 스토리지 효율성은 다음 플랫폼과 ONTAP 버전에서 사용할 수 있습니다.

[cols="2"]
|===
| 플랫폼 | ONTAP 버전입니다 


 a| 
* AFF A1K 를 참조하십시오
* AFF A90 를 참조하십시오
* AFF A70 를 참조하십시오
* FAS90를 참조하십시오
* FAS70를 참조하십시오

| 9.15.1 이상 


 a| 
* AFF A50 를 참조하십시오
* AFF A30 를 참조하십시오

| 9.16.1 이상 
|===

NOTE: SnapMirror 기술을 사용하여 마이그레이션된 데이터는 AFF A20 플랫폼에서 32k 인라인 압축으로 자동 변환됩니다.  하지만 AFF A20 플랫폼은 CPU나 전용 오프로드 프로세서의 저장 효율성을 지원하지 않습니다.

다음 플랫폼의 경우 스토리지 효율성이 자동으로 활성화되므로 구성이 필요하지 않습니다.  이는 새로 생성된 모든 씬 프로비저닝 볼륨과 기존 데이터(다른 플랫폼에서 이동된 볼륨 포함)에 적용됩니다.  중복 제거는 공간 보장 설정에 관계없이 활성화됩니다.  압축과 데이터 압축은 모두 공간 보장을 없음으로 설정해야 합니다.  볼륨 이동이나 SnapMirror 기술을 사용하여 마이그레이션된 데이터는 자동으로 32k 인라인 압축으로 변환됩니다.

* AFF A1K 를 참조하십시오
* AFF A90 를 참조하십시오
* AFF A70 를 참조하십시오
* AFF A50 를 참조하십시오
* AFF A30 를 참조하십시오


다음 플랫폼의 경우, ONTAP 9.15.1 이상으로 업그레이드하기 전에 스토리지 효율성이 활성화되었던 기존 씬 프로비저닝 볼륨에서만 스토리지 효율성이 기본적으로 활성화됩니다.  CLI 또는 REST API 방법을 사용하여 새로 생성된 볼륨에서 스토리지 효율성을 활성화할 수 있습니다.  볼륨 이동이나 SnapMirror 기술을 사용하여 마이그레이션된 데이터는 원래 플랫폼에서 압축이 활성화된 경우에만 32k 인라인 압축으로 변환됩니다.

* FAS90를 참조하십시오
* FAS70를 참조하십시오


지원되는 플랫폼 중 하나로 컨트롤러를 업그레이드하는 방법에 대한 정보는 다음을 참조하세요. https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["ONTAP 하드웨어 업그레이드 설명서"^] .
