---
permalink: concepts/builtin-storage-efficiency-concept.html 
sidebar: sidebar 
keywords: storage efficiency, built-in, platform, controller, offload, aff a1k, aff a90, aff a70, fas90, fas70, aff a50, aff a30 
summary: 특정 AFF 및 FAS 시스템에서는 전용 오프로드 프로세서를 사용한 스토리지 효율성 향상이 지원됩니다. 이러한 시스템은 온도에 민감한 스토리지 효율성 향상 기능을 사용하지 않습니다. 압축은 데이터가 차가워지기를 기다리지 않고 바로 시작되며, 전용 오프로드 프로세서를 사용하여 수행됩니다. 
---
= ONTAP 전용 오프로드 프로세서 스토리지 효율성에 대해 알아보세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전용 오프로드 프로세서 스토리지 효율성은 연속적인 물리적 블록을 순차적으로 패킹하고, 전용 오프로드 프로세서를 사용하여 32k 데이터 압축을 수행합니다. 32k 압축을 사용하면 볼륨 수준에서 공간을 절약하는 8k 적응형 압축을 사용하는 시스템과 달리, 애그리게이트 수준에서 공간을 절약할 수 있습니다. 전용 오프로드 프로세서 스토리지 효율성을 사용하는 시스템은 온도에 민감한 스토리지 효율성(TSSE)을 사용하지 않으므로, 압축이 핫 데이터 또는 콜드 데이터 여부에 따라 결정되지 않습니다. 따라서 성능 영향 없이 즉각적인 공간 절약이 실현됩니다.

다음 시스템에서는 전용 오프로드 프로세서 스토리지 효율성이 지원됩니다. 나열된 AFF 시스템에서는 기본적으로 활성화되어 있습니다.


NOTE: AFF A20 플랫폼은 전용 오프로드 프로세서 스토리지 효율성을 지원하지 않습니다. AFF A20 시스템의 경우 SnapMirror 기술을 사용하여 마이그레이션된 데이터는 메인 CPU를 사용하여 자동으로 32k 인라인 압축으로 변환됩니다.

* AFF A 시리즈 시스템: AFF A90, AFF A70, AFF A50, AFF A30
* AFF A1K 를 참조하십시오
* AFF C-Series 시스템: AFF C80, AFF C60, AFF C30
* FAS 시스템: FAS90, FAS70, FAS50


다음 시스템의 경우 스토리지 효율성이 자동으로 활성화되며 별도 구성이 필요하지 않습니다. 이는 새로 생성된 모든 씬 프로비저닝 볼륨과 기존 데이터(다른 시스템에서 이동된 볼륨 포함)에 적용됩니다. 중복 제거는 공간 보장 설정과 관계없이 활성화됩니다. 압축 및 데이터 압축 기능은 공간 보장 설정이 '없음'으로 되어 있어야 합니다. 볼륨 이동 또는 SnapMirror 기술을 사용하여 마이그레이션된 데이터는 자동으로 32k 인라인 압축으로 변환됩니다.

* AFF A 시리즈 시스템: AFF A90, AFF A70, AFF A50, AFF A30
* AFF A1K 를 참조하십시오
* AFF C-Series 시스템: AFF C80, AFF C60, AFF C30


다음 시스템의 경우, 스토리지 효율성은 ONTAP 9.15.1 이상 버전으로 업그레이드하기 전에 스토리지 효율성이 활성화된 기존 씬 프로비저닝 볼륨에만 기본적으로 활성화됩니다. 새로 생성되는 볼륨에서는 ONTAP CLI 또는 ONTAP REST API를 사용하여 스토리지 효율성을 활성화할 수 있습니다. 볼륨 이동 또는 SnapMirror 기술을 사용하여 마이그레이션된 데이터는 원래 플랫폼에서 압축이 활성화된 경우에만 32k 인라인 압축으로 변환됩니다.

* FAS90를 참조하십시오
* FAS70를 참조하십시오
* FAS50


컨트롤러를 지원되는 시스템 중 하나로 업그레이드하는 방법에 대한 자세한 내용은  https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["ONTAP 하드웨어 업그레이드 설명서"^]을 참조하십시오.
