---
permalink: concepts/builtin-storage-efficiency-concept.html 
sidebar: sidebar 
keywords: storage efficiency, built-in, platform, controller, offload, aff a1k, aff a90, aff a70, fas90, fas70, aff a50, aff a30 
summary: 특정 AFF 및 FAS 플랫폼에서는 전용 오프로드 프로세서 저장 효율성이 기본적으로 활성화되어 있습니다. 이러한 플랫폼은 온도에 민감한 저장 효율성을 사용하지 않습니다.  압축은 데이터가 차가워질 때까지 기다리지 않고 시작되며 전용 오프로드 프로세서를 사용하여 수행됩니다. 
---
= ONTAP 전용 오프로드 프로세서 스토리지 효율성에 대해 알아보세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전용 오프로드 프로세서 저장 효율성은 연속적인 물리적 블록의 순차적 패킹을 수행하고 32k 데이터 압축을 위해 전용 오프로드 프로세서를 사용합니다.  32k 압축을 사용하면 8k 적응형 압축을 사용하는 플랫폼과 달리 볼륨 수준에서 공간 절약이 실현되는 것과 달리 집계 수준에서 공간 절약이 실현됩니다.  전용 오프로드 프로세서 스토리지 효율성을 사용하는 플랫폼은 온도 민감 스토리지 효율성(TSSE)을 사용하지 않습니다. 즉, 압축은 핫 데이터나 콜드 데이터에 기반하지 않습니다.  이를 통해 성능에 영향을 미치지 않으면서 즉각적인 공간 절약 효과를 얻을 수 있습니다.

다음 플랫폼과 ONTAP 버전에서는 전용 오프로드 프로세서 스토리지 효율성이 기본적으로 활성화되어 있습니다.


NOTE: AFF A20 플랫폼은 전용 오프로드 프로세서 저장 효율성을 지원하지 않습니다.  AFF A20 플랫폼의 경우 SnapMirror 기술을 사용하여 마이그레이션된 데이터는 메인 CPU를 사용하여 자동으로 32k 인라인 압축으로 변환됩니다.

[cols="2"]
|===
| 플랫폼 | ONTAP 버전입니다 


 a| 
* AFF A1K 를 참조하십시오
* AFF A90 를 참조하십시오
* AFF A70 를 참조하십시오
* FAS90를 참조하십시오
* FAS70를 참조하십시오

| 9.15.1 이상 


 a| 
* AFF A50 를 참조하십시오
* AFF A30 를 참조하십시오

| 9.16.1 이상 
|===
다음 플랫폼의 경우 스토리지 효율성이 자동으로 활성화되므로 구성이 필요하지 않습니다.  이는 새로 생성된 모든 씬 프로비저닝 볼륨과 기존 데이터(다른 플랫폼에서 이동된 볼륨 포함)에 적용됩니다.  중복 제거는 공간 보장 설정에 관계없이 활성화됩니다.  압축과 데이터 압축은 모두 공간 보장을 없음으로 설정해야 합니다.  볼륨 이동이나 SnapMirror 기술을 사용하여 마이그레이션된 데이터는 자동으로 32k 인라인 압축으로 변환됩니다.

* AFF A1K 를 참조하십시오
* AFF A90 를 참조하십시오
* AFF A70 를 참조하십시오
* AFF A50 를 참조하십시오
* AFF A30 를 참조하십시오


다음 플랫폼의 경우, ONTAP 9.15.1 이상으로 업그레이드하기 전에 스토리지 효율성이 활성화되었던 기존 씬 프로비저닝 볼륨에서만 스토리지 효율성이 기본적으로 활성화됩니다.  CLI 또는 REST API 방법을 사용하여 새로 생성된 볼륨에서 스토리지 효율성을 활성화할 수 있습니다.  볼륨 이동이나 SnapMirror 기술을 사용하여 마이그레이션된 데이터는 원래 플랫폼에서 압축이 활성화된 경우에만 32k 인라인 압축으로 변환됩니다.

* FAS90를 참조하십시오
* FAS70를 참조하십시오


지원되는 플랫폼 중 하나로 컨트롤러를 업그레이드하는 방법에 대한 정보는 다음을 참조하세요. https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["ONTAP 하드웨어 업그레이드 설명서"^] .
