---
permalink: concepts/rdma-concept.html 
sidebar: sidebar 
keywords: Remote Direct Memory Access, NFS over RDMA, RoCE, intercluster 
summary: 'ONTAP의 RDMA(Remote Direct Memory Access) 솔루션은 지연 시간에 민감한 고대역폭 워크로드를 지원합니다. RDMA를 사용하면 스토리지 시스템 메모리와 호스트 시스템 메모리 간에 데이터를 직접 복사할 수 있으므로 CPU 중단과 오버헤드가 줄어듭니다' 
---
= RDMA 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP의 RDMA(Remote Direct Memory Access) 솔루션은 지연 시간에 민감한 고대역폭 워크로드를 지원합니다. RDMA를 사용하면 스토리지 시스템 메모리와 호스트 시스템 메모리 간에 데이터를 직접 복사하여 CPU 중단과 오버헤드를 피할 수 있습니다.



== RDMA 상의 NFS

ONTAP 9.10.1부터 구성할 수 있습니다 link:../nfs-rdma/index.html["RDMA 상의 NFS"] 지원되는 NVIDIA GPU가 있는 호스트에서 GPU 가속 워크로드에 NVIDIA GPUDirect 스토리지를 사용할 수 있도록 합니다.


NOTE: RDMA는 SMB 프로토콜을 지원하지 않습니다.



== 클러스터 인터커넥트 RDMA

클러스터 인터커넥트 RDMA는 지연 시간을 단축하고, 페일오버 시간을 줄이고, 클러스터 노드 간의 통신을 가속화합니다.

ONTAP 9.10.1부터 X1151A 클러스터 NIC와 함께 사용할 경우 특정 하드웨어 시스템에서 클러스터 상호 연결 RDMA가 지원됩니다. ONTAP 9.13.1부터 X91153A NIC는 클러스터 인터커넥트 RDMA도 지원합니다. 표를 참조하여 다양한 ONTAP 릴리스에서 지원되는 시스템에 대해 알아보십시오.

|===
| 시스템 | 지원되는 ONTAP 버전 


 a| 
* AFF A50 를 참조하십시오
* AFF A30 를 참조하십시오
* AFF A20 를 참조하십시오
* AFF C80 를 참조하십시오
* AFF C60 를 참조하십시오
* AFF C30 를 참조하십시오
* ASA A50
* ASA A30
* ASA A20

| ONTAP 9.16.1 이상 


 a| 
* AFF A1K 를 참조하십시오
* AFF A90 를 참조하십시오
* AFF A70 를 참조하십시오
* ASA A1K
* ASA A90
* ASA A70
* FAS90를 참조하십시오
* FAS70를 참조하십시오

| ONTAP 9.15.1 이상 


 a| 
* AFF A400
* ASA A400

| ONTAP 9.10.1 이상 


 a| 
* AFF A900 탑재
* ASA A900
* FAS9500

| ONTAP 9.13.1 이상 
|===
적절한 스토리지 시스템 설정을 감안하면 클러스터 인터커넥트 RDMA를 사용하기 위해 추가 구성이 필요하지 않습니다.
