---
sidebar: sidebar 
permalink: concepts/sysmgr-integration-bluexp-concept.html 
keywords: netapp, ontap, system manager, experience, integrate, integration, bluexp, hybrid, cloud, dashboard, multicloud 
summary: BlueXP의 System Manager를 사용하여 ONTAP 9.10.1 이상 릴리스를 관리할 수 있습니다. 이 통합을 통해 통합된 제어 플레인을 사용하여 하이브리드 멀티클라우드 인프라를 효율적으로 관리하고, 익숙한 System Manager 사용자 인터페이스를 그대로 유지할 수 있습니다. 
---
= ONTAP 시스템 관리자를 BlueXP와 통합
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
BlueXP의 System Manager를 사용하여 ONTAP 9.10.1 이상 릴리스를 관리할 수 있습니다. 이 통합을 통해 통합된 제어 플레인을 사용하여 하이브리드 멀티클라우드 인프라를 효율적으로 관리하고, 익숙한 System Manager 사용자 인터페이스를 그대로 유지할 수 있습니다.

BlueXP를 사용하면 클라우드 스토리지(예: Cloud Volumes ONTAP)를 생성하고 관리하고, NetApp 데이터 서비스(예: Cloud Backup)를 사용하고, 다양한 온프레미스 및 엣지 스토리지 장치를 제어할 수 있습니다.

BlueXP는 클러스터를 검색하고 관리하는 두 가지 방법을 제공합니다.

* System Manager(ONTAP 9.12.1 이상)를 통한 관리를 위한 직접 검색
* 커넥터를 통한 검색


커넥터는 사용자 환경에 설치되는 소프트웨어입니다. 이를 통해 System Manager를 통해 관리 기능에 액세스하고 데이터 복제, 백업 및 복구, 데이터 분류, 데이터 계층화 등의 기능을 제공하는 BlueXP 클라우드 서비스에 액세스할 수 있습니다.

에 대해 자세히 link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html["BlueXP를 사용한 사내 ONTAP 클러스터 관리"^]알아보십시오.

.단계
. BlueXP에 로그인하세요.
+
.. BlueXP 로그인이 있다면 사용하세요.
.. 처음이시라면 NetApp 지원 사이트 자격 증명으로 로그인을 선택하고 BlueXP 로그인 페이지에 자격 증명을 입력하세요.


. 커넥터 또는 직접 검색을 사용하여 BlueXP에서 온프레미스 클러스터를 검색하세요. 자세한 내용은 다음 링크를 참조하세요. https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html[온프레미스 ONTAP 클러스터 검색^].
+
.. 의 방법을 link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-direct.html["직접 발견된 클러스터를 관리합니다."^]알아보십시오.
.. 의 방법을 link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-connector.html["커넥터를 사용하여 검색된 클러스터를 관리합니다."^]알아보십시오.


. System Manager를 사용하여 온프레미스 클러스터를 관리하세요. [ 내 작업 환경] 캔버스에서 클러스터를 선택하고 [서비스] 목록에서 [System Manager]를 클릭하세요.
+
.. 에 대해 자세히 link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-direct.html["직접 발견된 클러스터 관리"^]알아보십시오.
.. 의 방법을 link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-connector.html["커넥터를 사용하여 검색된 클러스터를 관리합니다."^]알아보십시오.






== BlueXP 및 ONTAP 9.12.1

참고: ONTAP 9.12.1을 사용하는 경우 BlueXP를 사용해 보라는 메시지가 나타납니다.

+ 클러스터가 BlueXP에 연결되어 있는 경우 로그인 프롬프트가 표시됩니다.

. BlueXP * 링크를 따라가려면 * Continue to BlueXP * 를 클릭합니다.
+

NOTE: 시스템 설정이 외부 네트워크를 차단하면 BlueXP에 액세스할 수 없습니다.  BlueXP를 사용하여 System Manager에 액세스하려면 시스템에서 "`cloudmanager.cloud.netapp.com`" 주소에 액세스할 수 있는지 확인해야 합니다.  그렇지 않으면 프롬프트에서 ONTAP 시스템과 함께 설치된 System Manager 버전을 사용하도록 선택할 수 있습니다.

. BlueXP 로그인 페이지에서 * NetApp Support 사이트 자격 증명으로 로그인 * 을 선택하고 자격 증명을 입력합니다.
+
이미 BlueXP를 사용했고 이메일과 비밀번호를 사용하여 로그인한 경우, 계속해서 해당 로그인 옵션을 사용해야 합니다.

+
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html["BlueXP 로그인에 대해 자세히 알아보십시오"^].

. 메시지가 표시되면 새 BlueXP 계정의 이름을 입력하세요.
+
대부분의 경우, BlueXP는 클러스터의 데이터를 기반으로 자동으로 계정을 생성합니다.

. 클러스터의 클러스터 관리자 자격 증명을 입력합니다.


.결과
System Manager가 표시되고 이제 BlueXP에서 클러스터를 관리할 수 있습니다.



== BlueXP에 대해 자세히 알아보십시오

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["BlueXP 개요"^]
* https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/index.html["BlueXP를 통해 NetApp AFF 및 FAS 시스템을 관리하십시오"^]

