---
permalink: nfs-rdma/configure-nics-task.html 
sidebar: sidebar 
keywords: networking, NICs, NFS over RDMA, NVIDIA, NFS, system manager, ports, ethernet ports 
summary: 이 문서에서는 ONTAP에서 RDMA 상의 NFS를 사용하기 위해 NIC에 대한 요구 사항과 클라이언트 시스템 및 스토리지 플랫폼 구성 프로세스를 모두 수행하는 방법을 설명합니다. 
---
= RDMA를 통해 NFS용 NIC를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
RDMA를 통한 NFS를 사용하려면 클라이언트 시스템과 스토리지 플랫폼 모두에 NIC 구성이 필요합니다.



== 스토리지 플랫폼 구성

대상 RNIC 지원에 대한 자세한 내용은 를 https://hwu.netapp.com/["NetApp Hardware Universe를 참조하십시오"^]참조하십시오.

고가용성(HA) 구성을 사용하는 경우 두 노드 모두 동일한 RNIC를 사용하여 RDMA 페일오버를 지원해야 합니다. NIC는 RoCE를 지원해야 합니다.

* ONTAP 9.10.1부터 다음 명령을 사용하여 RDMA 오프로드 프로토콜 목록을 볼 수 있습니다.
+
[source, cli]
----
network port show -rdma-protocols roce
----
* ONTAP 9.16.1부터 우선 순위 흐름 제어(PFC)를 사용하는 것이 좋습니다. 다음 명령을 사용하여 PFC를 구성합니다 `network port modify`.
+
[source, cli]
----
network port modify -node <nodename> -port <portname> -flowcontrol-admin pfc -pfc-queues-admin 3
----
* ONTAP 9.16.1 이전에는 기본 전역 흐름 제어(GFC)를 사용하는 것이 좋습니다. 흐름 제어 설정이 변경된 경우 다음 명령을 사용하여 GFC를 `network port modify` 구성합니다.
+
[source, cli]
----
network port modify -node <nodename> -port <portname> -flowcontrol-admin full
----




== 클라이언트 시스템 구성

RDMA 기반 NFS에 대해 지원되는 클라이언트 운영 체제에 대한 자세한 내용은 를 https://imt.netapp.com/matrix/["NetApp 상호 운용성 매트릭스(IMT)"^]참조하십시오. RoCE v2 지원 RNIC에 대해서는 해당 RNIC 공급업체 설명서를 참조하십시오.

클라이언트와 서버를 직접 연결할 수 있지만 페일오버 성능을 향상시키려면 스위치를 사용하는 것이 좋습니다.

클라이언트, 서버, 모든 스위치 및 스위치의 모든 포트는 점보 프레임을 사용하여 구성해야 합니다. 클라이언트 및 스위치의 흐름 제어 구성은 ONTAP의 흐름 제어 구성과 일치해야 합니다. ONTAP 9.16.1부터 ONTAP, 스위치 및 클라이언트에서 우선 순위 흐름 제어를 활성화하고 구성하는 것이 가장 좋습니다. ONTAP 9.16.1 이전에는 전역 흐름 제어를 사용하는 것이 좋습니다.

이 구성이 확인되면 RDMA를 사용하여 NFS 내보내기를 마운트할 수 있습니다.

[role="tabbed-block"]
====
.시스템 관리자
--
ONTAP 9.12.1 이상을 사용하여 System Manager를 사용하여 RDMA를 통해 NFS와 네트워크 인터페이스를 구성해야 합니다.

.단계
. RDMA가 지원되는지 확인합니다. Network > Ethernet Ports * 로 이동하여 그룹 보기에서 해당 노드를 선택합니다. 노드를 확장할 때 지정된 포트에 대한 * RDMA 프로토콜 * 필드를 확인합니다. 값 * RoCE * 는 RDMA가 지원됨을 나타내고 대시(*- *)는 지원되지 않음을 나타냅니다.
. VLAN을 추가하려면 * + VLAN * 을 선택합니다. 적절한 노드를 선택합니다. 포트 * 드롭다운 메뉴에서 사용 가능한 포트가 RDMA를 지원하는 경우 * RoCE Enabled * 라는 텍스트가 표시됩니다. RDMA를 지원하지 않으면 텍스트가 표시되지 않습니다.
. 의 워크플로를 따릅니다 xref:../task_nas_enable_linux_nfs.html[NFS를 사용하여 Linux 서버용 NAS 스토리지를 설정합니다] 새 NFS 서버를 구성합니다.
+
네트워크 인터페이스를 추가할 때 * RoCE 포트 사용 * 을 선택할 수 있습니다. RDMA 상에서 NFS를 사용하려는 네트워크 인터페이스에 대해 이 옵션을 선택합니다.



--
.CLI를 참조하십시오
--
. 다음 명령을 사용하여 NFS 서버에서 RDMA 액세스가 활성화되어 있는지 확인합니다.
+
`vserver nfs show-vserver <SVM_name>`

+
기본적으로 -RDMA가 활성화되어 있어야 합니다. 그렇지 않은 경우 NFS 서버에서 RDMA 액세스를 설정합니다.

+
`vserver nfs modify -vserver <SVM_name> -rdma enabled`

. RDMA를 통해 NFSv4.0을 통해 클라이언트를 마운트합니다.
+
.. proto 매개 변수의 입력은 서버 IP 프로토콜 버전에 따라 다릅니다. IPv4인 경우 를 사용합니다 `proto=rdma`. IPv6인 경우 를 사용합니다 `proto=rdma6`.
.. NFS 타겟 포트를 로 지정합니다 `port=20049` 표준 포트 2049 대신:
+
`mount -o vers=4,minorversion=0,proto=rdma,port=20049 <Server_IP_address>:/<volume_path> <mount_point>`



. * 선택 사항 *: 클라이언트를 마운트 해제해야 하는 경우 명령을 실행합니다 `unmount <mount_path>`


--
====
.추가 정보
* xref:../nfs-config/create-server-task.html[NFS 서버를 생성합니다]
* xref:../task_nas_enable_linux_nfs.html[NFS를 사용하여 Linux 서버용 NAS 스토리지를 설정합니다]

