---
permalink: pnfs/pnfs-commands.html 
sidebar: sidebar 
keywords: tr-4063, pnfs, commands, technical report 
summary: 이러한 ONTAP CLI 명령을 사용하여 pNFS를 구성하고, 문제를 해결하고, 통계를 수집합니다. 
---
= pNFS 명령, 통계 및 이벤트 로그
:allow-uri-read: 


[role="lead"]
이러한 ONTAP CLI 명령은 특히 pNFS와 관련이 있습니다. 이를 사용하여 구성, 문제 해결 및 통계 수집이 가능합니다.



== NFSv4.1을 활성화하십시오

[listing]
----
nfs modify -vserver SVM -v4.1 enabled
----


== pNFS를 활성화합니다

[listing]
----
nfs modify -vserver SVM -v4.1-pnfs enabled
----


== pNFS 장치 표시(고급 권한)

[listing]
----
pnfs devices show -vserver SVM
----
[listing]
----
Vserver Name     Mapping ID      Volume MSID     Mapping Status  Generation
---------------  --------------- --------------- --------------- -------------
SVM              17              2157024470      notavailable    2
SVM              18              2157024463      notavailable    2
SVM              19              2157024469      available       3
SVM              20              2157024465      available       4
SVM              21              2157024467      available       3
SVM              22              2157024462      available       1
----


== pNFS 장치 매핑 표시(고급 권한)

[listing]
----
pnfs devices mappings show -vserver SVM
----
[listing]
----
Vserver Name    Mapping ID      Dsid            LIF IP
--------------  --------------- --------------- --------------------
SVM             19              2449            10.x.x.x
SVM             20              2512            10.x.x.y
SVM             21              2447            10.x.x.x
SVM             22              2442            10.x.x.y
----


== pNFS 특정 성능 카운터 캡처(고급 권한)

[listing]
----
statistics start -object nfsv4_1 -vserver SVM -sample-id [optional-name]
----


== pNFS 특정 성능 카운터 보기(고급 권한)

[listing]
----
statistics show -object nfsv4_1 -vserver SVM
----


== pNFS 특정 카운터 목록 보기(고급 권한)

[listing]
----
statistics catalog counter show -object nfsv4_1 -counter *layout*|*device*
----
[listing]
----
Object: nfsv4_1

Counter                     Description
--------------------------- ----------------------------------------------
getdeviceinfo_avg_latency   Average latency of NFSv4.1 GETDEVICEINFO operations.
getdeviceinfo_error         The number of failed NFSv4.1 GETDEVICEINFO operations.
getdeviceinfo_percent       Percentage of NFSv4.1 GETDEVICEINFO operations.
getdeviceinfo_success       The number of successful NFSv4.1 GETDEVICEINFO operations.
getdeviceinfo_total         Total number of NFSv4.1 GETDEVICEINFO operations.
getdevicelist_avg_latency   Average latency of NFSv4.1 GETDEVICELIST operations.
getdevicelist_error         The number of failed NFSv4.1 GETDEVICELIST operations.
getdevicelist_percent       Percentage of NFSv4.1 GETDEVICELIST operations.
getdevicelist_success       The number of successful NFSv4.1 GETDEVICELIST operations.
getdevicelist_total         Total number of NFSv4.1 GETDEVICELIST operations.
layoutcommit_avg_latency    Average latency of NFSv4.1 LAYOUTCOMMIT operations.
layoutcommit_error          The number of failed NFSv4.1 LAYOUTCOMMIT operations.
layoutcommit_percent        Percentage of NFSv4.1 LAYOUTCOMMIT operations.
layoutcommit_success        The number of successful NFSv4.1 LAYOUTCOMMIT operations.
layoutcommit_total          Total number of NFSv4.1 LAYOUTCOMMIT operations.
layoutget_avg_latency       Average latency of NFSv4.1 LAYOUTGET operations.
layoutget_error             The number of failed NFSv4.1 LAYOUTGET operations.
layoutget_percent           Percentage of NFSv4.1 LAYOUTGET operations.
layoutget_success           The number of successful NFSv4.1 LAYOUTGET operations.
layoutget_total             Total number of NFSv4.1 LAYOUTGET operations.
layoutreturn_avg_latency    Average latency of NFSv4.1 LAYOUTRETURN operations.
layoutreturn_error          The number of failed NFSv4.1 LAYOUTRETURN operations.
layoutreturn_percent        Percentage of NFSv4.1 LAYOUTRETURN operations.
layoutreturn_success        The number of successful NFSv4.1 LAYOUTRETURN operations.
layoutreturn_total          Total number of NFSv4.1 LAYOUTRETURN operations.
----


== NFS에 대한 활성 네트워크 연결 보기

SVM에 여러 TCP 연결이 이루어지고 있는지 확인하려면 다음을 수행하십시오. `network connections active show` 명령.

예를 들어, NFS 세션 트렁크를 보고 싶다면 노드당 서로 다른 인터페이스에서 동일한 클라이언트의 연결을 찾으세요.

[listing]
----
cluster::*> network connections active show -node cluster-0* -vserver PNFS
              Vserver   Interface         Remote
      CID Ctx Name      Name:Local Port   Host:Port            Protocol/Service
--------- --- --------- ----------------- -------------------- ----------------
Node: node-01
2304333128 14 PNFS      data1:2049        ubuntu22-224:740     TCP/nfs
2304333144 10 PNFS      data3:2049        ubuntu22-224:864     TCP/nfs
2304333151  5 PNFS      data1:2049        ubuntu22-226:848     TCP/nfs
2304333167 15 PNFS      data3:2049        ubuntu22-226:684     TCP/nfs
Node: node-02
2497668321 12 PNFS      data2:2049        ubuntu22-224:963     TCP/nfs
2497668337 18 PNFS      data4:2049        ubuntu22-224:859     TCP/nfs
2497668344 14 PNFS      data2:2049        ubuntu22-226:675     TCP/nfs
2497668360  7 PNFS      data4:2049        ubuntu22-226:903     TCP/nfs
----


== 연결된 클라이언트의 NFS 버전 정보 보기

NFS 연결도 볼 수 있습니다. `nfs connected-clients show` 명령. 표시된 클라이언트 목록은 지난 48시간 동안 활성 NFS 트래픽이 있었던 클라이언트라는 점을 명심하세요. 유휴 NFS 클라이언트(아직 마운트되어 있더라도)는 마운트에 액세스할 때까지 표시되지 않을 수 있습니다. 최근에 액세스한 클라이언트만 표시하도록 필터링하려면 다음을 지정하세요. `-idle-time` 특징.

예를 들어, pNFS SVM에서 지난 10분 동안 활동이 있었던 클라이언트를 보려면 다음을 수행합니다.

[listing]
----
cluster::*> nfs connected-clients show -vserver PNFS -idle-time <10m>

 Node: node-01

Vserver: PNFS Data-Ip: 10.x.x.x Local Remote Client-Ip Protocol Volume Policy Idle-Time Reqs Reqs Trunking

10.x.x.a nfs4.2 PNFS_root default 9m 10s 0 149 false 10.x.x.a nfs4.2 FG_0001 default 9m 10s 135847 0 false 10.x.x.b nfs4.2 PNFS_root default 8m 12s 0 157 false 10.x.x.b nfs4.2 FG_0001 default 8m 12s 52111 0 false
----
.관련 정보
* link:pnfs-overview.html["ONTAP 의 병렬 NFS(pNFS)에 대해 알아보세요"]

