---
permalink: nfs-admin/nfsv4-acls-concept.html 
sidebar: sidebar 
keywords: nfsv4, acls, work 
summary: 'NFSv4 ACL을 사용하는 클라이언트는 시스템의 파일 및 디렉토리에 대한 ACL을 설정하고 볼 수 있습니다. 새 파일 또는 하위 디렉토리가 ACL이 있는 디렉토리에 생성되면 새 파일 또는 하위 디렉토리는 적절한 상속 플래그로 태그가 지정된 ACL의 모든 ACE(액세스 제어 항목)를 상속합니다.' 
---
= ONTAP SVM에 대한 NFSv4 ACL에 대해 알아보세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFSv4 ACL을 사용하는 클라이언트는 시스템의 파일 및 디렉토리에 대한 ACL을 설정하고 볼 수 있습니다. 새 파일 또는 하위 디렉토리가 ACL이 있는 디렉토리에 생성되면 새 파일 또는 하위 디렉토리는 적절한 상속 플래그로 태그가 지정된 ACL의 모든 ACE(액세스 제어 항목)를 상속합니다.

NFSv4 요청의 결과로 파일이나 디렉토리가 생성되면 결과 파일 또는 디렉토리의 ACL은 파일 생성 요청에 ACL이 포함되는지, 표준 UNIX 파일 액세스 권한만 포함되는지, 상위 디렉토리에 ACL이 있는지 여부에 따라 달라집니다.

* 요청에 ACL이 포함된 경우 해당 ACL이 사용됩니다.
* 요청에 표준 UNIX 파일 액세스 권한만 포함되어 있지만 상위 디렉토리에 ACL이 있는 경우 ACE에 적절한 상속 플래그가 지정된 경우 상위 디렉토리의 ACL에 있는 ACE는 새 파일 또는 디렉토리에 의해 상속됩니다.
+
[NOTE]
====
상위 ACL은 '-v4.0-acl'이 'off'로 설정되어 있어도 상속된다.

====
* 요청에 표준 UNIX 파일 액세스 권한만 있고 상위 디렉토리에 ACL이 없는 경우 클라이언트 파일 모드를 사용하여 표준 UNIX 파일 액세스 권한을 설정합니다.
* 요청에 표준 UNIX 파일 액세스 권한만 있고 상위 디렉토리에 상속할 수 없는 ACL이 있는 경우 새 객체는 모드 비트로만 생성됩니다.


[NOTE]
====
매개 변수가 또는 `vserver export-policy rule` 패밀리의 명령을 사용하여 `vserver nfs` 로 `restricted` 설정된 경우 `-chown-mode` NFSv4 ACL을 사용하여 설정된 온디스크 사용 권한이 루트 사용자가 파일 소유권을 변경할 수 있는 경우에도 수퍼 사용자만 파일 소유권을 변경할 수 있습니다. 이 절차에서 설명하는 명령에 대한 자세한 내용은 를 link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP 명령 참조입니다"^]참조하십시오.

====