---
sidebar: sidebar 
permalink: anti-ransomware/enable-arp-ai-with-au.html 
keywords: ransomware, arp, enable, ai, automatic, update, upgrade, autonomous ransomware protection 
summary: ONTAP 9.16.1부터 FlexVol 설치에 대해 ARP/AI를 자동으로 활성화하거나 필수 조건을 충족한 후 수동으로 활성화합니다. 
---
= ONTAP ARP/AI 활성화
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 9.16.1부터 ARP는 위협 탐지 및 대응을 개선하기 위해 인공지능을 활용한 자율 랜섬웨어 보호(ARP/AI)를 도입했습니다. 클러스터를 SAN용 ONTAP 9.17.1 또는 NAS용 ONTAP 9.16.1로 업그레이드하면 FlexVol 볼륨에 ARP가 이미 활성화되어 있는 경우 해당 볼륨에 대해 ARP/AI가 자동으로 활성화됩니다. ARP 또는 ONTAP 활성화하지 않은 경우 link:../update/enable-automatic-updates-task.html["자동 업데이트"] 클러스터의 경우 이 절차에 설명된 시나리오 중 하나를 따라야 합니다.


IMPORTANT: ARP/AI 지원이 있는 ONTAP 버전으로 업그레이드하기 전에 link:../upgrade/arp-warning-clear.html["기존 ARP 검색을 닫습니다"] .

.시작하기 전에
* ARP/AI를 사용하려면 FlexVol 볼륨이 있어야 합니다. FlexGroup 볼륨이 있는 경우, ONTAP 9.16.1 이상으로 업그레이드해도 ARP/AI 이전에 사용되었던 ARP 모델은 계속 작동합니다.



NOTE: (NAS 환경에만 해당) ONTAP 9.16.1 이상으로 업그레이드하면 FlexVol 볼륨이 있는 기존 ARP 인스턴스에 대해 ARP가 활성화되고 자동으로 활성화됩니다. ARP/AI는 광범위한 머신 러닝 모델을 기반으로 학습되므로 학습 기간이 더 이상 필요하지 않습니다. 업그레이드 전에 완료되지 않은 학습 기간은 자동으로 종료되고 볼륨은 활성 ARP/AI로 전환됩니다.

.단계
. 사용자의 구성에 해당하는 시나리오를 따릅니다.
+
** *SAN 환경에만 해당*
+
*** * FlexVol 볼륨이 있는 ONTAP 9.17.1 이상을 실행하는 새 클러스터와 기존 클러스터의 경우*: ONTAP 9.17.1 이상으로 업그레이드하거나 설치하는 경우 다음을 수행해야 합니다. link:enable-task.html["ARP 활성화"] 보호하려는 볼륨에서 ARP를 활성화합니다. System Manager 또는 CLI를 사용하여 ARP를 활성화하면 ARP/AI 기능이 자동으로 활성화됩니다. SAN 볼륨에서 활성화되면 link:respond-san-entropy-eval-period.html["ARP/AI는 평가 기간 동안 지속적으로 데이터를 모니터링합니다."] 워크로드가 ARP에 적합한지 확인하고 감지를 위한 최적의 암호화 임계값을 설정합니다.


** *NAS 환경에만 해당*
+
*** *FlexVol 볼륨*과 함께 ONTAP 9.16.1 이상을 실행하는 새 클러스터의 경우:link:enable-task.html["ARP를 활성화합니다"]. ARP는 기본적으로 활성화되어 있지 않습니다. 를 활성화하면 보호하려는 FlexVol 볼륨에서 ARP/AI 기능이 자동으로 활성화됩니다.
*** *최근 ONTAP 9.16.1 이상으로 업그레이드하고 ARP가 활성화된 기존 클러스터의 경우*: 별도의 조치가 필요하지 않습니다. ARP/AI는 보호하도록 선택한 FlexVol 볼륨에서 자동으로 새로운 ARP 위협 보호 방식으로 설정됩니다.
*** *ARP가 활성화되지 않은 최근에 ONTAP 9.16.1 이상으로 업그레이드된 기존 클러스터의 경우*:link:enable-task.html["ARP를 활성화합니다"]. /AI가 자동으로 새로운 ARP 위협 보호 방법이 됩니다.




. ARP/AI가 활성화된 후 ARP/AI 보호 업데이트를 전달하고 설치할지 여부를 결정합니다. link:arp-ai-automatic-updates.html["자동 또는 수동"] .


.관련 정보
* link:arp-ai-automatic-updates.html["ARP/AI를 업데이트합니다"]

