---
sidebar: sidebar 
permalink: anti-ransomware/modify-snapshot-options-arpai.html 
keywords: ARP AI, arpai, snapshot settings, retention, arw snap, autonomous ransomware protection AI, ONTAP 9.17.1, SAN snapshot parameters, machine learning ransomware 
summary: 잠재적인 랜섬웨어 위협에 대응하여 자동으로 생성되는 ARP/AI 스냅샷의 생성 및 보존 기간 설정을 조정하십시오. 
---
= 자동으로 생성되는 ONTAP ARP/AI 스냅샷에 대한 설정을 조정합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.16.1부터 CLI를 사용하여 랜섬웨어 공격이 의심되는 경우 자동으로 생성되는 Autonomous Ransomware Protection with AI(ARP/AI) 스냅샷의 보존 설정을 제어할 수 있습니다.


NOTE: ONTAP 9.15.1 이하 버전을 사용 중인 경우 link:modify-snapshot-options-arp.html["자동 생성된 ARP 스냅샷에 대한 설정 조정"]을 참조하십시오.

.시작하기 전에
ARP/AI 스냅샷 옵션은 link:../system-admin/types-svms-concept.html["노드 SVM"]에서만 수정할 수 있으며, 다른 SVM 유형에서는 수정할 수 없습니다.

.단계
. 현재 ARP/AI 스냅샷 설정을 모두 표시합니다.
+
[source, cli]
----
options -option-name arw*
----
. 선택한 현재 ARP/AI 스냅샷 설정을 표시합니다.
+
[source, cli]
----
options -option-name <arw_setting_name>
----
. ARP/AI 스냅샷 설정 수정:
+
[source, cli]
----
options -option-name <arw_setting_name> -option-value <arw_setting_value>
----
+
ONTAP 9.16.1 이상 버전에서는 다음 설정을 수정할 수 있습니다.

+
[cols="1,3,1"]
|===
| 설정 | 설명 | ARP/AI 지원 버전 


| `arw.snap.max.count`  a| 
볼륨에 동시에 존재할 수 있는 최대 ARP/AI 스냅샷 수를 지정합니다. 전체 ARP/AI 스냅샷 수가 이 제한을 초과하지 않도록 오래된 스냅샷은 삭제됩니다.
 a| 
ONTAP 9.16.1 이상



| `arw.snap.create.interval.hours`  a| 
ARP/AI 스냅샷 생성 간격(시간 단위)을 지정합니다. 데이터 엔트로피 기반 공격이 의심되고 가장 최근에 생성된 스냅샷이 지정된 간격보다 오래된 경우 새로운 ARP/AI 스냅샷이 생성됩니다.
 a| 
ONTAP 9.16.1 이상



| `arw.snap.normal.retain.interval.hours`  a| 
ARP/AI 스냅샷을 보존할 기간(시간 단위)을 지정합니다. ARP/AI 스냅샷이 보존 임계값에 도달하면 삭제됩니다.
 a| 
ONTAP 9.16.1 (9.17.1 이상 버전에서 사용이 중단됨)



| `arw.snap.max.retain.interval.days`  a| 
ARP/AI 스냅샷을 보존할 수 있는 최대 기간(일)을 지정합니다. 이 기간보다 오래된 ARP/AI 스냅샷은 해당 볼륨에 대한 공격이 보고되지 않으면 삭제됩니다.


NOTE: ARP/AI가 위협을 감지하면 최대 보존 기간이 무시됩니다.  위협에 대응하여 생성된 ARP/AI 스냅샷은 사용자가 위협에 대응할 때까지 보존됩니다.  위협을 오탐으로 표시하면  `arw.snap.retain.hours.after.clear.suspect.false.alert`에서 지정한 보존 타이머가 ARP/AI 스냅샷에 적용됩니다.  해당 타이머가 만료되면 표준 보존 설정이 다시 적용됩니다.
 a| 
ONTAP 9.16.1 (9.17.1 이상 버전에서 사용이 중단됨)



| `arw.snap.create.interval.hours.post.max.count`  a| 
볼륨에 이미 최대 개수의 ARP/AI 스냅샷이 포함되어 있을 때 ARP/AI 스냅샷 간의 간격(_시간 단위_)을 지정합니다. 최대 개수에 도달하면 새 복사본을 위한 공간을 확보하기 위해 ARP/AI 스냅샷이 삭제됩니다. 이전 복사본을 보존하기 위해 생성 속도를 줄이려면 이 옵션을 사용하십시오.
 a| 
ONTAP 9.16.1 (9.17.1 이상 버전에서 사용이 중단됨)



| `arw.snap.new.extns.interval.hours`  a| 
새로운 파일 확장자가 감지될 때 생성되는 ARP/AI 스냅샷의 간격(시간 단위)을 지정합니다. 새로운 파일 확장자가 감지되고 이전 스냅샷이 지정된 간격보다 오래된 경우 새로운 ARP/AI 스냅샷이 생성됩니다. 이 옵션은 엔트로피 기반 스냅샷의 간격을 지정하는 `arw.snap.create.interval.hours`과 별개로 존재합니다.
 a| 
ONTAP 9.16.1 (9.17.1 이상 버전에서 사용이 중단됨)



| `arw.snap.low.encryption.retain.duration.hours`  a| 
암호화 활동이 적은 기간 동안 생성된 ARP/AI 스냅샷의 보존 기간을 시간 단위로 지정합니다.
 a| 
ONTAP 9.17.1 이상



| `arw.snap.retain.hours.after.clear.suspect.false.alert`  a| 
관리자가 공격 인시던트를 거짓 양성으로 표시한 후 예방 조치로 ARP/AI 스냅샷이 보존되는 간격을 _시간 단위_로 지정합니다.
 a| 
ONTAP 9.16.1 이상



| `arw.snap.retain.hours.after.clear.suspect.real.attack`  a| 
관리자가 공격 인시던트를 실제 공격으로 표시한 후 예방 조치로 ARP/AI 스냅샷이 보존되는 간격을 _시간 단위_로 지정합니다.
 a| 
ONTAP 9.16.1 이상



| `arw.snap.surge.interval.days`  a| 
IO 급증에 대응하여 생성되는 ARP/AI 스냅샷 간의 간격(일)을 지정합니다. 이 옵션은 ARP/AI 급증 스냅샷의 보존 기간(일)도 지정합니다.
 a| 
ONTAP 9.16.1 이상



| `arw.high.encryption.alert.enabled`  a| 
높은 수준의 암호화에 대한 알림을 활성화합니다.  `on`(기본값)으로 설정하면 ONTAP는 암호화 비율이  `arw.high.encryption.percentage.threshold`에 지정된 임계값을 초과할 때 알림을 보냅니다.
 a| 
ONTAP 9.17.1 이상



| `arw.high.encryption.percentage.threshold`  a| 
볼륨의 최대 암호화 비율을 지정합니다. 암호화 비율이 이 임계값을 초과하면 ONTAP은 이를 공격으로 간주하고 ARP/AI 스냅샷을 생성합니다. `arw.high.encryption.alert.enabled`이 옵션을 적용하려면 `on`로 설정해야 합니다.
 a| 
ONTAP 9.17.1 이상



| `arw.snap.high.encryption.retain.duration.hours`  a| 
높은 암호화 임계값 이벤트 중에 생성된 스냅샷의 보존 기간 간격을 _시간_ 단위로 지정합니다.
 a| 
ONTAP 9.17.1 이상

|===
. SAN 환경에서 ARP/AI를 사용하는 경우 다음 평가 기간 설정을 수정할 수도 있습니다.
+
[cols="1,3,1"]
|===
| 설정 | 설명 | 지원되는 버전 


| `arw.block_device.auto.learn.threshold.min_value`  a| 
블록 장치에 대한 평가의 자동 학습 단계 동안 최소 암호화 임계값 백분율 값을 지정합니다.
 a| 
ONTAP 9.17.1 이상



| `arw.block_device.auto.learn.threshold.max_value`  a| 
블록 장치에 대한 평가의 자동 학습 단계 동안 최대 암호화 임계값 백분율 값을 지정합니다.
 a| 
ONTAP 9.17.1 이상



| `arw.block_device.evaluation.phase.min_hours`  a| 
암호화 임계값이 설정되기 전에 평가 단계가 실행되어야 하는 최소 간격(시간)을 지정합니다.
 a| 
ONTAP 9.17.1 이상



| `arw.block_device.evaluation.phase.max_hours`  a| 
암호화 임계값이 설정되기 전에 평가 단계가 실행되어야 하는 최대 간격(시간)을 지정합니다.
 a| 
ONTAP 9.17.1 이상



| `arw.block_device.evaluation.phase.min_data_ingest_size_GB`  a| 
암호화 임계값이 설정되기 전에 평가 단계에서 수집해야 하는 최소 데이터 양(GB)을 지정합니다.
 a| 
ONTAP 9.17.1 이상



| `arw.block_device.evaluation.phase.alert.enabled`  a| 
차단 장치에 대한 ARP/AI 평가 단계에서 알림을 활성화할지 여부를 지정합니다. 기본값은 `True`입니다.
 a| 
ONTAP 9.17.1 이상



| `arw.block_device.evaluation.phase.alert.threshold`  a| 
블록 장치에 대한 ARP/AI 평가 단계에서 임계값 백분율을 지정합니다. 암호화 비율이 이 임계값을 초과하면 경고가 발생합니다.
 a| 
ONTAP 9.17.1 이상

|===


.관련 정보
* link:learn-about-arpai.html#arp-ai-snapshots["위협 평가 및 ARP/AI 스냅샷"]
* link:entropy-eval-period-arpai.html["SAN 볼륨에 대한 ARP/AI 엔트로피 평가 기간"]

