---
sidebar: sidebar 
permalink: anti-ransomware/modify-snapshot-options-arp.html 
keywords: ARP, snapshot settings, retention, arw snap, autonomous ransomware protection, ONTAP 9.11.1, NAS, deprecated settings, learning mode, legacy ARP snapshot settings, ONTAP 9.15.1 or earlier 
summary: 'NAS 볼륨에서 발생할 수 있는 랜섬웨어 위협에 대응하여 자동으로 생성되는 ARP 스냅샷의 생성 및 보존 설정을 조정합니다(ONTAP 9.11.1~9.15.1).' 
---
= ONTAP ARP 스냅샷 자동 생성 설정 조정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.11.1부터 CLI를 사용하여 의심되는 랜섬웨어 공격에 대응하여 자동으로 생성되는 ARP(자율적 랜섬웨어 방어) 스냅샷의 보존 설정을 제어할 수 있습니다.


NOTE: ONTAP 9.16.1 이상을 실행 중인 경우 link:modify-snapshot-options-arpai.html["자동으로 생성되는 ARP/AI 스냅샷에 대한 설정 조정"]을 참조하십시오.

.시작하기 전에
ARP 스냅샷 옵션은 link:../system-admin/types-svms-concept.html["노드 SVM"]에서만 수정할 수 있으며 다른 SVM 유형에서는 수정할 수 없습니다.


NOTE: 이 섹션에 나열된 설정은 ONTAP 9.11.1부터 9.15.1까지 적용됩니다. ONTAP 9.16.1 이상으로 업그레이드한 경우 link:modify-snapshot-options-arpai.html["ARP/AI 스냅샷 설정"]을 사용하십시오.

.단계
. 모든 현재 ARP 스냅샷 설정 표시:
+
[source, cli]
----
options -option-name arw*
----
. 선택한 현재 ARP 스냅샷 설정 표시:
+
[source, cli]
----
options -option-name <arw_setting_name>
----
. ARP 스냅샷 설정 수정:
+
[source, cli]
----
options -option-name <arw_setting_name> -option-value <arw_setting_value>
----
+
다음 설정을 수정할 수 있습니다(ONTAP 9.11.1~9.15.1).

+
[cols="1,3,1"]
|===
| 설정 | 설명 | ARP를 지원하는 버전 


| `arw.snap.max.count`  a| 
볼륨에 동시에 존재할 수 있는 최대 ARP 스냅샷 수를 지정합니다. 전체 ARP 스냅샷 수가 이 제한을 초과하지 않도록 오래된 스냅샷은 삭제됩니다.
 a| 
ONTAP 9.11.1~9.15.1



| `arw.snap.create.interval.hours`  a| 
ARP 스냅샷 생성 간격(시간 단위)을 지정합니다. 데이터 엔트로피 기반 공격이 의심되고 가장 최근에 생성된 스냅샷이 지정된 간격보다 오래된 경우 새 ARP 스냅샷이 생성됩니다.
 a| 
ONTAP 9.11.1~9.15.1



| `arw.snap.normal.retain.interval.hours`  a| 
ARP 스냅샷이 보존되는 기간(시간)을 지정합니다. ARP 스냅샷이 보존 임계값에 도달하면 삭제됩니다.
 a| 
ONTAP 9.11.1 ~ 9.15.1 (9.17.1 이상 버전에서는 더 이상 사용되지 않음)



| `arw.snap.max.retain.interval.days`  a| 
ARP 스냅샷을 보존할 수 있는 최대 지속 시간을 days_로 지정합니다. 이 기간보다 오래된 ARP 스냅샷은 볼륨에 보고된 공격이 없으면 삭제됩니다.


NOTE: 중간 수준의 위협이 감지되면 최대 보존 기간은 무시됩니다. 위협에 대응하여 생성된 ARP 스냅샷은 사용자가 위협에 대응할 때까지 보존됩니다. 위협을 오탐으로 표시하면 ONTAP은 해당 볼륨의 ARP 스냅샷을 삭제합니다.
 a| 
ONTAP 9.11.1 ~ 9.15.1 (9.17.1 이상 버전에서는 더 이상 사용되지 않음)



| `arw.snap.create.interval.hours.post.max.count`  a| 
볼륨에 이미 최대 개수의 ARP 스냅샷이 포함되어 있는 경우 ARP 스냅샷 간의 간격(_시간 단위_)을 지정합니다. 최대 개수에 도달하면 새 복사본을 위한 공간을 확보하기 위해 ARP 스냅샷이 삭제됩니다. 이전 복사본을 보존하기 위해 생성 속도를 줄이려면 이 옵션을 사용하십시오.
 a| 
ONTAP 9.11.1 ~ 9.15.1 (9.17.1 이상 버전에서는 더 이상 사용되지 않음)



| `arw.snap.new.extns.interval.hours`  a| 
새 파일 확장자가 감지될 때 생성되는 ARP 스냅샷의 간격(시간 단위)을 지정합니다. 새 파일 확장자가 감지되고 이전 스냅샷이 지정된 간격보다 오래된 경우 새 ARP 스냅샷이 생성됩니다. 이 옵션은 엔트로피 기반 스냅샷의 간격을 지정하는 `arw.snap.create.interval.hours`과 별개로 존재합니다.
 a| 
ONTAP 9.11.1 ~ 9.15.1 (9.17.1 이상 버전에서는 더 이상 사용되지 않음)



| `arw.snap.surge.interval.days`  a| 
IO 급증에 대한 응답으로 생성된 ARP 스냅샷 간의 간격(일)을 지정합니다. 이 옵션은 ARP 급증 스냅샷의 보존 기간(일)도 지정합니다.
 a| 
ONTAP 9.11.1~9.15.1

|===


.관련 정보
* link:learn-about-arp.html#arp-snapshots["위협 평가 및 ARP 스냅샷"]
* link:modify-snapshot-options-arpai.html["ARP/AI 스냅샷 설정 조정(ONTAP 9.16.1 이상)"]

