---
sidebar: sidebar 
permalink: anti-ransomware/respond-abnormal-task.html 
keywords: abnormal activity, data entropy, unusual file extensions, potential ransomware attack, false positive, ransomware attack, abnormal activity notification, ransomware alert, detected abnormal volume, suspected file types, attack report, anti-ransomware attack, ransomware ems 
summary: ONTAP의 ARP 알림에 대해 알아보고 랜섬웨어 공격이 발생하는지 여부와 대응 방법을 확인하십시오. 
---
= ONTAP ARP가 감지한 비정상적인 활동에 응답합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ARP(Autonomous 랜섬웨어 Protection)가 보호 볼륨에서 비정상적인 활동을 감지하면 경고를 표시합니다. 알림을 평가하여 활동이 허용 가능한지(가양성) 또는 공격이 악의적으로 보이는지 여부를 결정해야 합니다. 공격을 범주화한 후 의심스러운 파일에 대한 경고 및 알림을 지울 수 있습니다.

ONTAP에서 비정상 상태를 감지하면 최상의 복구 지점을 만들기 위해 볼륨도 link:index.html#threat-assessment-and-arp-snapshots["ARP 스냅샷"]생성됩니다. ARP 스냅샷은 기본적으로 2-5일 동안 유지됩니다.

공격을 분류할 때 이러한 ARP 스냅샷은 즉시 삭제되거나(ONTAP 9.15.1 이하) 범주화 작업에 의해 시작된 단축 기간 동안 보존됩니다(ONTAP 9.16.1 이상).


NOTE: ONTAP 9.11.1부터 ARP 스냅샷에 대한 를 수정할 수 xref:modify-automatic-snapshot-options-task.html[보존 설정]있습니다.

.이 작업에 대해
ARP는 높은 데이터 엔트로피, 데이터 암호화와 비정상적인 볼륨 활동 및 비정상적인 파일 확장자의 조합을 감지할 때 의심되는 파일 목록을 표시합니다.

ARP 경고가 발생하면 다음 두 가지 방법 중 하나로 파일 활동을 지정하여 응답합니다.

* *긍정 오류*
+
식별된 파일 유형이 작업 부하에 필요합니다. 이 파일 유형은 무시해도 됩니다.

* * 잠재적 랜섬웨어 공격 *
+
식별된 파일 유형이 작업 부하에서 예기치 않은 유형이므로 잠재적 공격으로 간주해야 합니다.



두 경우 모두 알림 업데이트 및 삭제 후 정상적인 모니터링이 재개됩니다. ARP는 후속 파일 활동을 모니터링하기 위해 사용자의 선택을 사용하여 위협 평가 프로파일에 평가를 기록합니다.

공격이 의심되는 경우에는 알림을 지우기 전에 공격이 공격인지 여부를 확인하고, 공격에 대한 대응 및 보호된 데이터를 복원해야 합니다. link:index.html#how-to-recover-data-in-ontap-after-a-ransomware-attack["랜섬웨어 공격에서 복구하는 방법에 대해 자세히 알아보십시오"].


NOTE: 전체 볼륨을 복원하는 경우 지울 알림이 없습니다.

.시작하기 전에
ARP는 활성 상태여야 하며 학습 모드가 아니어야 합니다.

.단계
System Manager 또는 ONTAP CLI를 사용하여 비정상적인 활동에 대응할 수 있습니다.

[role="tabbed-block"]
====
.시스템 관리자
--
. "비정상적인 활동" 알림을 받으면 링크를 따라갑니다. 또는 * Volumes * 개요의 * Security * 탭으로 이동합니다.
+
경고는 * Events * 메뉴의 * Overview * 창에 표시됩니다.

. 비정상적인 볼륨 활동 감지에 대한 메시지가 나타나면 의심되는 파일 유형을 확인합니다.
+
보안 * 탭에서 의심되는 파일 형식을 검토하는 옵션을 선택합니다.

. Suspected File Types * 대화 상자에서 각 파일 형식을 검사하여 "False positive" 또는 "잠재적 랜섬웨어 공격"으로 표시합니다.
+
[cols="25,75"]
|===


| 이 값을 선택한 경우... | 이 작업 수행... 


 a| 
거짓 양성
 a| 
.. 업데이트 * 및 * 의심되는 파일 형식 지우기 * 를 선택하여 결정을 기록하십시오.
+

NOTE: ONTAP 9.13.1 부터, ARP 설정을 보호하기 위해 MAV를 사용하는 경우, 의심스러운 작업이 하나 이상의 추가 관리자의 승인을 얻으라는 메시지를 표시합니다. link:../multi-admin-verify/request-operation-task.html["모든 관리자로부터 승인을 받아야 합니다"] MAV 승인 그룹과 연관되거나 작업이 실패합니다.

+
이 작업을 수행하면 의심되는 파일에 대한 경고 알림이 지워집니다. 그런 다음 ARP는 볼륨의 정상적인 모니터링을 재개합니다. ONTAP 9.15.1 이하 버전의 경우 의심스러운 파일 유형을 지우면 ARP 스냅샷이 자동으로 삭제됩니다. ONTAP 9.16.1 이상의 ARP/AI의 경우 ARP 스냅샷은 범주화 작업에 의해 트리거된 축약 보존 기간 후에 자동으로 삭제됩니다.





 a| 
잠재적인 랜섬웨어 공격
 a| 
.. 공격에 대응하고link:recover-data-task.html["보호된 데이터를 복원합니다"]
.. 업데이트 * 및 * 의심되는 파일 유형 지우기 * 를 선택하여 결정을 기록하고 정상적인 ARP 모니터링을 재개합니다.


이렇게 하면 공격 보고서가 지워집니다. 전체 볼륨을 복원한 경우 지울 것으로 의심되는 파일 유형 알림이 없습니다. ONTAP 9.15.1 이하 버전의 경우 볼륨을 복원하면 ARP 스냅샷이 자동으로 삭제됩니다. ONTAP 9.16.1 이상의 ARP/AI의 경우 ARP 스냅샷은 범주화 작업에 의해 트리거된 축약 보존 기간 후에 자동으로 삭제됩니다.

|===


--
.CLI를 참조하십시오
--
. 랜섬웨어 공격이 의심되는 경우 다음 사항을 통지하여 공격의 시간 및 심각도를 확인하십시오.
+
[source, cli]
----
security anti-ransomware volume show -vserver <svm_name> -volume <vol_name>
----
+
샘플 출력:

+
....
Vserver Name: vs0
Volume Name: vol1
State: enabled
Attack Probability: moderate
Attack Timeline: 9/14/2021 01:03:23
Number of Attacks: 1
....
+
EMS 메시지를 확인할 수도 있습니다.

+
[source, cli]
----
event log show -message-name callhome.arw.activity.seen
----
. 공격 보고서를 생성하고 출력 위치를 기록합니다.
+
[source, cli]
----
security anti-ransomware volume attack generate-report -vserver <svm_name> -volume <vol_name> -dest-path <[svm_name:]vol_name/[sub-dir-name]>
----
+
명령 예:

+
[listing]
----
security anti-ransomware volume attack generate-report -vserver vs0 -volume vol1 -dest-path vs0:vol1
----
+
샘플 출력:

+
[listing]
----
Report "report_file_vs0_vol1_14-09-2021_01-21-08" available at path "vs0:vol1/"
----
. 관리 클라이언트 시스템에서 보고서를 봅니다. 예를 들면 다음과 같습니다.
+
....
cat report_file_vs0_vol1_14-09-2021_01-21-08
....
. 파일 확장명 평가에 따라 다음 작업 중 하나를 수행합니다.
+
** 거짓 양성
+
다음 명령을 실행하여 결정 사항을 기록하고 허용된 항목 목록에 새로운 확장명을 추가하며 정상적인 자율 랜섬웨어 방어 모니터링을 재개합니다.

+
[source, cli]
----
anti-ransomware volume attack clear-suspect -vserver <svm_name> -volume <vol_name> [<extension identifiers>] -false-positive true
----
+
다음 선택적 매개 변수를 사용하여 특정 확장만 위양성으로 식별합니다.

+
*** `[-extension <text>, … ]`: 파일 확장자
+
이 `clear-suspect` 작업을 수행하면 의심되는 파일에 대한 경고 알림이 지워집니다. 그런 다음 ARP는 볼륨의 정상적인 모니터링을 재개합니다. ONTAP 9.15.1 이하 버전의 경우 의심스러운 파일 유형을 지우면 ARP 스냅샷이 자동으로 삭제됩니다. ONTAP 9.16.1 이상의 ARP/AI의 경우 ARP 스냅샷은 범주화 작업에 의해 트리거된 축약 보존 기간 후에 자동으로 삭제됩니다.



** 잠재적인 랜섬웨어 공격
+
공격에 대응하고link:../anti-ransomware/recover-data-task.html["ARP 생성 백업 스냅샷으로부터 데이터를 복구합니다"] 데이터가 복구되면 다음 명령을 실행하여 결정을 기록하고 정상적인 ARP 모니터링을 재개합니다.

+
[source, cli]
----
anti-ransomware volume attack clear-suspect -vserver <svm_name> -volume <vol_name> [<extension identifiers>] -false-positive false
----
+
다음 선택적 매개 변수를 사용하여 특정 확장만 잠재적 랜섬웨어로 식별하십시오.

+
*** `[-extension <text>, … ]`: 파일 확장자
+
이 `clear-suspect` 작업은 공격 보고서를 지웁니다. 전체 볼륨을 복원한 경우 지울 것으로 의심되는 파일 유형 알림이 없습니다. ONTAP 9.15.1 이하 버전의 경우 볼륨을 복원하면 ARP 스냅샷이 자동으로 삭제됩니다. ONTAP 9.16.1 이상의 ARP/AI의 경우 ARP 스냅샷은 범주화 작업에 의해 트리거된 축약 보존 기간 후에 자동으로 삭제됩니다.





. MAV를 사용하고 있고 예상되는 경우 `clear-suspect` 작업에 추가 승인이 필요합니다. 각 MAV 그룹 승인자는 다음을 수행해야 합니다.
+
.. 요청 표시:
+
[source, cli]
----
security multi-admin-verify request show
----
.. 정상적인 랜섬웨어 방지 모니터링 재개 요청을 승인합니다.
+
[source, cli]
----
security multi-admin-verify request approve -index[<number returned from show request>]
----
+
마지막 그룹 승인자에 대한 응답은 볼륨이 수정되었고 가양성이 기록되었음을 나타냅니다.



. MAV를 사용하고 있고 MAV 그룹 승인자인 경우 의심스러운 요청을 거부할 수도 있습니다.
+
[source, cli]
----
security multi-admin-verify request veto -index[<number returned from show request>]
----


--
====
.관련 정보
* link:https://kb.netapp.com/onprem%2Fontap%2Fda%2FNAS%2FUnderstanding_Autonomous_Ransomware_Protection_attacks_and_the_Autonomous_Ransomware_Protection_snapshot#["KB: 자율 랜섬웨어 보호 공격과 자율 랜섬웨어 보호 스냅샷 이해"^].
* link:modify-automatic-snapshot-options-task.html["자동 스냅샷 옵션을 수정합니다"]..

