---
sidebar: sidebar 
permalink: anti-ransomware/switch-learning-to-active-mode.html 
keywords: ransomware, arp, mode, switch, active, learning, autonomous ransomware protection 
summary: NAS 환경에서 ARP 9.15.1 및 이전 버전의 경우 ARP 지원 볼륨을 학습 모드에서 활성 모드로 수동 또는 자동으로 전환합니다. 
---
= 학습 기간 후에 ONTAP ARP에서 활성 모드로 전환합니다
:allow-uri-read: 


[role="lead"]
NAS 환경의 경우, ARP 지원 볼륨을 학습 모드에서 활성 모드로 수동 또는 자동으로 전환할 수 있습니다. ONTAP 9.15.1 이하 버전에서 ARP를 사용하거나 FlexGroup 볼륨에서 ARP를 실행하는 경우 모드를 전환해야 합니다.

ARP가 권장 최소 30일의 학습 모드 실행을 완료하면 수동으로 액티브 모드로 전환할 수 있습니다. ONTAP 9.13.1부터 ARP는 최적의 학습 기간 간격을 자동으로 결정하고 전환을 자동화하며, 이는 30일 전에 발생할 수 있습니다.

ONTAP 9.16.1 이상의 FlexVol 볼륨에서 ARP를 사용하는 경우 ARP/AI 보호가 활성화되고 자동으로 활성화됩니다. 학습 기간은 필요하지 않습니다.


NOTE: 기존 볼륨에서 학습 및 활성 모드는 볼륨의 기존 데이터가 아닌 새로 기록된 데이터에만 적용됩니다. ARP에 대해 볼륨이 활성화된 후 새 데이터를 기반으로 이전 일반 데이터 트래픽의 특성이 가정되기 때문에 기존 데이터는 스캔되고 분석되지 않습니다.



== 학습 기간 후 수동으로 활성 모드로 전환합니다

ONTAP 9.10.1~9.15.1 및 FlexGroup 볼륨이 포함된 ARP의 경우 학습 기간이 완료된 후 시스템 관리자나 ONTAP CLI를 사용하여 ARP 학습 모드에서 활성 모드로 수동으로 전환할 수 있습니다.

.이 작업에 대해
이 절차에 설명된 학습 기간 후 활성 모드로 수동 전환하는 작업은 NAS 환경에만 해당됩니다.

.단계
시스템 관리자나 ONTAP CLI를 사용하여 학습 모드에서 활성 모드로 전환할 수 있습니다.

[role="tabbed-block"]
====
.시스템 관리자
--
. 스토리지 > 볼륨 * 을 선택한 다음 활성 모드에 사용할 준비가 된 볼륨을 선택합니다.
. 볼륨 * 개요의 * 보안 * 탭에서 안티 랜섬웨어 상자에서 * 활성 모드로 전환 * 을 선택합니다.
. Anti-랜섬웨어 * 상자에서 볼륨의 ARP 상태를 확인할 수 있습니다.


--
.CLI를 참조하십시오
--
. 보호된 볼륨을 자동으로 활성 모드로 전환하지 않은 경우 이를 수정하여 활성 모드로 전환합니다.
+
[source, cli]
----
security anti-ransomware volume enable -volume <vol_name> -vserver <svm_name>
----
+
볼륨 수정 명령을 사용하여 활성 모드로 전환할 수도 있습니다.

+
[source, cli]
----
volume modify -volume <vol_name> -vserver <svm_name> -anti-ransomware-state enabled
----
. 볼륨의 ARP 상태를 확인합니다.
+
[source, cli]
----
security anti-ransomware volume show
----


--
====


== 학습 모드에서 활성 모드로 자동 전환

ONTAP 9.13.1부터 ARP 분석에 적응형 학습 기능이 추가되었으며, 학습 모드에서 활성 모드로의 전환은 자동으로 이루어집니다. ARP가 학습 모드에서 활성 모드로 자동 전환하는 자율적인 결정은 다음 옵션의 구성 설정을 기반으로 합니다.

[listing]
----
 -anti-ransomware-auto-switch-minimum-incoming-data-percent
 -anti-ransomware-auto-switch-duration-without-new-file-extension
 -anti-ransomware-auto-switch-minimum-learning-period
 -anti-ransomware-auto-switch-minimum-file-count
 -anti-ransomware-auto-switch-minimum-file-extension
----
자동 전환을 활성화하면 모든 조건이 충족되지 않더라도 최대 30일 후에 볼륨이 자동으로 활성 모드로 전환됩니다. 이 30일 제한은 고정되어 있으며 변경할 수 없습니다.

기본값을 포함한 ARP 구성 옵션에 대한 자세한 내용은 를 참조하십시오 link:https://docs.netapp.com/us-en/ontap-cli/security-anti-ransomware-volume-auto-switch-to-enable-mode-show.html["ONTAP 명령 참조입니다"^].

.관련 정보
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+anti-ransomware+volume["보안 랜섬웨어 볼륨"^]

