---
sidebar: sidebar 
permalink: snapmirror-active-sync/cloud-mediator-requirements-concept.html 
keywords: SM-BC, SMBC, ONTAP, Cloud Mediator, prerequisites, requirements, configuration, firewall, latency, proxy, certificate, snapmirror active sync 
summary: ONTAP Cloud Mediator를 설치하려면 특정 요구 사항을 충족해야 합니다. 
---
= ONTAP Cloud Mediator 구성을 준비하세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
당신 전에 link:cloud-mediator-config-task.html["ONTAP Cloud Mediator 구성"] , 전제 조건이 충족되었는지 확인해야 합니다.



== 방화벽 요구 사항

도메인 컨트롤러의 방화벽 설정은 HTTPS 트래픽을 허용해야 합니다.  `api.bluexp.netapp.com` 두 클러스터 모두에서.



== 프록시 서버 요구 사항

SnapMirror Active Sync에 프록시 서버를 사용하는 경우 프록시 서버가 생성되었고 다음 프록시 서버 정보가 있는지 확인하세요.

* HTTPS 프록시 IP
* 포트
* 사용자 이름
* 암호




== 숨어 있음

NetApp 콘솔 클라우드 서버와 SnapMirror Active Sync 클러스터 피어 간의 권장 ping 지연 시간은 200ms 미만입니다.



== 루트 CA 인증서

.클러스터에서 인증서를 확인하세요
ONTAP 에는 잘 알려진 루트 CA 인증서가 미리 설치되어 있으므로 대부분의 경우 NetApp 콘솔 서버의 루트 CA 인증서를 설치할 필요가 없습니다. ONTAP Cloud Mediator 구성을 시작하기 전에 클러스터를 확인하여 인증서가 있는지 확인할 수 있습니다.

예:

[listing]
----
C1_cluster% openssl s_client -showcerts -connect api.bluexp.netapp.com:443 -servername api.bluexp.netapp.com | egrep "s:|i:"

depth=4 C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services
verify error:num=19:self-signed certificate in certificate chain
verify return:1
depth=4 C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services
verify return:1
depth=3 C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust RSA Certification Authority
verify return:1
depth=2 C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication Root R46
verify return:1
depth=1 C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication CA OV R36
verify return:1
depth=0 C=US, ST=California, O=NetApp, Inc., CN=cloud.netapp.com
verify return:1
 0 s:C=US, ST=California, O=NetApp, Inc., CN=cloud.netapp.com
   i:C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication CA OV R36
 1 s:C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication CA OV R36
   i:C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication Root R46
 2 s:C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication Root R46
   i:C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust RSA Certification Authority
 3 s:C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust RSA Certification Authority
   i:C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services
 4 s:C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services
   i:C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services

C1_cluster::> security certificate show -common-name Sectigo*|USERTrust*|AAA*
Vserver    Serial Number   Certificate Name                       Type
---------- --------------- -------------------------------------- ------------
C1_sti245-vsim-ocvs024k_1775534714 42F2CCDA1B6937445F15FE752810B8F4 SectigoPublicServerAuthenticationRootE46 server-ca
    Certificate Authority: Sectigo Public Server Authentication Root E46
          Expiration Date: Wed Mar 21 19:59:59 2046

C1_sti245-vsim-ocvs024k_1775534714 758DFD8BAE7C0700FAA925A7E1C7AD14 SectigoPublicServerAuthenticationRootR46 server-ca
    Certificate Authority: Sectigo Public Server Authentication Root R46
          Expiration Date: Wed Mar 21 19:59:59 2046

C1_sti245-vsim-ocvs024k_1775534714 5C8B99C55A94C5D27156DECD8980CC26 USERTrustECCCertificationAuthority server-ca
    Certificate Authority: USERTrust ECC Certification Authority
          Expiration Date: Mon Jan 18 18:59:59 2038

C1_sti245-vsim-ocvs024k_1775534714 01FD6D30FCA3CA51A81BBC640E35032D USERTrustRSACertificationAuthority server-ca
    Certificate Authority: USERTrust RSA Certification Authority
          Expiration Date: Mon Jan 18 18:59:59 2038

----
.설치된 인증서에 대한 프록시 서버를 확인하세요
NetApp 콘솔에서 ONTAP Cloud Mediator 서비스에 연결하기 위해 프록시를 사용하는 경우 프록시 서버의 루트 CA 인증서가 ONTAP 에 설치되어 있는지 확인하세요.

예:

[listing]
----
C1_cluster% openssl s_client -showcerts -proxy <ip:port> -connect api.bluexp.netapp.com:443 -servername api.bluexp.netapp.com |egrep "s:|i:"
----
.CA 인증서를 다운로드하세요:
필요한 경우 인증 기관 웹사이트에서 루트 CA 인증서를 다운로드하여 클러스터에 설치할 수 있습니다.

예:

[listing]
----
C1_cluster::> security certificate install -type server-ca -vserver C1_cluster

C2_cluster::> security certificate install -type server-ca -vserver C2_cluster
----