---
sidebar: sidebar 
permalink: snapmirror-active-sync/cloud-mediator-config-task.html 
keywords: SM-BC, SMBC, cluster, peering, ONTAP Cloud Mediator, initialize, snapmirror active sync 
summary: SnapMirror Active Sync와 함께 ONTAP Cloud Mediator를 사용하는 경우 먼저 BlueXP 서비스와 클라이언트 정보가 구성되어 있는지 확인해야 합니다. 
---
= SnapMirror Active Sync를 위한 ONTAP Cloud Mediator 구성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 9.17.1부터 ONTAP Cloud Mediator를 사용하여 각 클러스터의 상태를 모니터링하여 비즈니스 연속성을 확보할 수 있습니다. ONTAP Cloud Mediator는 클라우드 기반 서비스입니다. SnapMirror Active Sync와 함께 ONTAP Cloud Mediator를 사용하는 경우, 먼저 BlueXP 서비스와 클라이언트 정보가 구성되어 있는지 확인하고 클러스터 피어링이 제대로 작동하는지 확인해야 합니다.

ONTAP Mediator와 마찬가지로 ONTAP Cloud Mediator는 SnapMirror 활성 동기화 관계에서 ONTAP 클러스터가 사용하는 고가용성(HA) 메타데이터를 위한 영구적이고 펜싱된 저장소를 제공합니다. ONTAP Cloud Mediator는 쿼럼 결정을 지원하는 동기식 노드 상태 쿼리 기능을 제공하고, 컨트롤러 활성 상태 감지를 위한 ping 프록시 역할을 합니다.


IMPORTANT: ONTAP 9.17.1과 함께 SnapMirror Active Sync 및 ONTAP Mediator 또는 ONTAP Cloud Mediator를 사용하는 경우 다음에서 *알려진 문제 및 제한 사항*을 검토해야 합니다.link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 릴리즈 노트"] 이러한 구성에 대한 중요한 정보는 다음을 참조하세요.

.시작하기 전에
ONTAP Cloud Mediator를 구성하기 전에 다음 정보를 확인해야 합니다.

* 클러스터가 구성되었습니다.
+
link:cluster-config-task.html["SnapMirror 활성 동기화를 위한 ONTAP 클러스터 구성"]

* 유효한 BlueXP 구독이 있습니다.
+
link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-subscribe-standard-mode.html["BlueXP 데이터 서비스 구독(표준 모드)"]

* BlueXP 콘솔에서 BlueXP 조직 ID를 복사하고 ONTAP Cloud Mediator 구성 시 사용할 BlueXP 멤버 서비스 계정을 생성했습니다. 서비스 계정을 생성할 때 조직은 ONTAP Cloud Mediator를 구성한 구독으로 설정해야 합니다. 범주는 *애플리케이션*으로, 역할 유형은 * ONTAP Mediator 설정 역할*로 설정해야 합니다. 역할을 생성할 때 클라이언트 ID와 클라이언트 비밀번호를 저장해야 합니다.
+
link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-iam-manage-members-permissions.html#add-members["BlueXP 멤버 및 서비스 계정 추가"]



.단계
System Manager나 ONTAP CLI를 사용하여 ONTAP Cloud Mediator를 추가할 수 있습니다.

[role="tabbed-block"]
====
.시스템 관리자
--
. *보호 > 개요 > 중재자*로 이동하여 *추가*를 선택합니다.
. *중개자 추가* 창에서 중개자 유형으로 *클라우드*를 선택하고 다음 정보를 입력합니다.
+
** BlueXP 조직 ID
** BlueXP 클라이언트 ID
** BlueXP 클라이언트 비밀번호


. 클러스터 피어를 선택하세요.
. HTTP 프록시를 사용 중이고 아직 구성하지 않은 경우 로컬 및 원격 호스트에 대한 HTTP 프록시 정보를 입력합니다.
+
각 클러스터 피어에 대해 다른 프록시 서버를 사용하는 것이 좋습니다.

. 선택 사항: 특히 프록시 서버를 사용하는 경우 ONTAP 에 루트 CA 인증서를 설치해야 하는 경우 제공된 텍스트 상자에 인증서를 붙여넣습니다.
. 추가 * 를 선택합니다.
. *보호 > 개요*로 이동하여 SnapMirror Active Sync 클러스터와 ONTAP Cloud Mediator 간의 관계 상태를 확인합니다.


--
.CLI를 참조하십시오
--
. ONTAP Cloud Mediator 구성: 
`snapmirror mediator add -peer-cluster <peerClusterName> -type cloud -bluexp-org-id <BlueXP Organization ID> -service-account-client-id <Service Account Client ID> -use-http-proxy-local <true|false> -use-http-proxy-remote <true|false>`
. ONTAP Cloud Mediator 상태 확인: 
`snapmirror mediator show`
+
예:

+
[listing]
----
C1_cluster::> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status Type
---------------- ---------------- ----------------- ------------- -------
0.0.0.0          C2_cluster       connected         true          cloud
----


--
====