---
sidebar: sidebar 
permalink: snapmirror-active-sync/cloud-mediator-requirements-concept.html 
keywords: SM-BC, SMBC, ONTAP, Cloud Mediator, prerequisites, requirements, configuration, firewall, latency, proxy, certificate, snapmirror active sync 
summary: ONTAP Cloud Mediator를 설치하려면 특정 요구 사항을 충족해야 합니다. 
---
= ONTAP Cloud Mediator 구성을 준비하세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
당신 전에 link:cloud-mediator-config-task.html["ONTAP Cloud Mediator 구성"] , 전제 조건이 충족되었는지 확인해야 합니다.



== 방화벽 요구 사항

도메인 컨트롤러의 방화벽 설정은 HTTPS 트래픽을 허용해야 합니다.  `api.bluexp.netapp.com` 두 클러스터 모두에서.



== 프록시 서버 요구 사항

SnapMirror Active Sync에 프록시 서버를 사용하는 경우 프록시 서버가 생성되었고 다음 프록시 서버 정보가 있는지 확인하세요.

* HTTPS 프록시 IP
* 포트
* 사용자 이름
* 암호




== 숨어 있음

BlueXP 클라우드 서버와 SnapMirror Active Sync 클러스터 피어 간의 권장 ping 지연 시간은 200ms 미만입니다.



== 루트 CA 인증서

.클러스터에서 인증서를 확인하세요
ONTAP 에는 잘 알려진 루트 CA 인증서가 미리 설치되어 있으므로 대부분의 경우 BlueXP 서버의 루트 CA 인증서를 설치할 필요가 없습니다. ONTAP Cloud Mediator 구성을 시작하기 전에 클러스터를 확인하여 인증서가 있는지 확인할 수 있습니다.

예:

[listing]
----
C1_cluster% openssl s_client -showcerts -connect api.bluexp.netapp.com:443|egrep "s:|i:"
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root G2
verify return:1
depth=1 C = US, O = Microsoft Corporation, CN = Microsoft Azure RSA TLS Issuing CA 04
verify return:1
depth=0 C = US, ST = WA, L = Redmond, O = Microsoft Corporation, CN = *.azureedge.net
verify return:1
 0 s:/C=US/ST=WA/L=Redmond/O=Microsoft Corporation/CN=*.azureedge.net
   i:/C=US/O=Microsoft Corporation/CN=Microsoft Azure RSA TLS Issuing CA 04
 1 s:/C=US/O=Microsoft Corporation/CN=Microsoft Azure RSA TLS Issuing CA 04
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G2
 2 s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G2
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G2 <====

C1_cluster::> security certificate show -common-name DigiCert*
Vserver    Serial Number   Certificate Name                       Type
---------- --------------- -------------------------------------- ------------
C1_cluster 0CE7E0EXXXXX46FE8FE560FC1BFXXXXX DigiCertAssuredIDRootCA server-ca
    Certificate Authority: DigiCert Assured ID Root CA
          Expiration Date: Mon Nov 10 05:30:00 2031

C1_cluster 0B931C3XXXXX67EA6723BFC3AF9XXXXX DigiCertAssuredIDRootG2 server-ca
    Certificate Authority: DigiCert Assured ID Root G2
          Expiration Date: Fri Jan 15 17:30:00 2038

C1_cluster 0BA15AFXXXXXA0B54944AFCD24AXXXXX DigiCertAssuredIDRootG3 server-ca
    Certificate Authority: DigiCert Assured ID Root G3
          Expiration Date: Fri Jan 15 17:30:00 2038

C1_cluster 083BE05XXXXX46B1A1756AC9599XXXXX DigiCertGlobalRootCA server-ca
    Certificate Authority: DigiCert Global Root CA
          Expiration Date: Mon Nov 10 05:30:00 2031

C1_cluster 033AF1EXXXXXA9A0BB2864B11D0XXXXX DigiCertGlobalRootG2 server-ca
    Certificate Authority: DigiCert Global Root G2
          Expiration Date: Fri Jan 15 17:30:00 2038

C1_cluster 055556BXXXXXA43535C3A40FD5AXXXXX DigiCertGlobalRootG3 server-ca
    Certificate Authority: DigiCert Global Root G3
          Expiration Date: Fri Jan 15 17:30:00 2038

C1_cluster 02AC5C2XXXXX409B8F0B79F2AE4XXXXX DigiCertHighAssuranceEVRootCA server-ca
    Certificate Authority: DigiCert High Assurance EV Root CA
          Expiration Date: Mon Nov 10 05:30:00 2031

C1_cluster 059B1B5XXXXX2132E23907BDA77XXXXX DigiCertTrustedRootG4 server-ca
    Certificate Authority: DigiCert Trusted Root G4
          Expiration Date: Fri Jan 15 17:30:00 2038
----
.설치된 인증서에 대한 프록시 서버를 확인하세요
BlueXP 에서 ONTAP Cloud Mediator 서비스에 연결하기 위해 프록시를 사용하는 경우 프록시 서버의 루트 CA 인증서가 ONTAP 에 설치되어 있는지 확인하세요.

예:

[listing]
----
C1_cluster% openssl s_client -showcerts -proxy <ip:port> -connect api.bluexp.netapp.com:443 |egrep "s:|i:"
----
.CA 인증서를 다운로드하세요:
필요한 경우 인증 기관 웹사이트에서 루트 CA 인증서를 다운로드하여 클러스터에 설치할 수 있습니다.

예:

[listing]
----
C1_cluster::> security certificate install -type server-ca -vserver C1_cluster

C2_cluster::> security certificate install -type server-ca -vserver C2_cluster
----