---
sidebar: sidebar 
permalink: snapmirror-active-sync/cluster-config-task.html 
keywords: SM-BC, SMBC, cluster, peering, ONTAP, Mediator, ONTAP Cloud Mediator, initialize, snapmirror active sync 
summary: SnapMirror Active Sync와 함께 ONTAP Mediator 또는 ONTAP Cloud Mediator를 사용하는 경우 먼저 클러스터가 올바르게 구성되었는지 확인해야 합니다. 
---
= SnapMirror 활성 동기화를 위한 ONTAP 클러스터 구성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror 액티브 싱크는 장애 조치 발생 시 데이터를 보호하기 위해 피어링된 클러스터를 사용합니다. SnapMirror 액티브 싱크를 위해 ONTAP Mediator 또는 ONTAP Cloud Mediator를 구성하기 전에 먼저 클러스터가 올바르게 구성되었는지 확인해야 합니다.

.시작하기 전에
ONTAP Mediator 또는 ONTAP Cloud Mediator를 구성하기 전에 다음 사항을 확인해야 합니다.

. 클러스터 간에는 클러스터 피어링 관계가 존재합니다.
+

NOTE: 클러스터 피어 관계를 위한 SnapMirror 액티브 동기화에 기본 IPspace가 필요합니다. 사용자 지정 IPspace는 지원되지 않습니다.

+
link:../peering/create-cluster-relationship-93-later-task.html["클러스터 피어 관계 생성"]

. SVM은 각 클러스터에 생성됩니다.
+
link:../smb-config/create-svms-data-access-task.html["SVM 생성"]

. 각 클러스터의 SVM 사이에는 피어 관계가 존재합니다.
+
link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["SVM 피어링 관계 생성"]

. 볼륨은 LUN에 대해 존재합니다.
+
link:../smb-config/create-volume-task.html["볼륨을 생성하는 중입니다"]

. SAN 구성을 위한 SAN LIF(FC 또는 iSCSI 중 해당하는 것)가 두 클러스터의 각 노드에 최소 하나 이상 생성되거나, 보조 클러스터로 복제하기 위한 NAS LIF(NFS 또는 SMB 중 해당하는 것)가 기본 클러스터의 각 노드에 최소 하나 이상 생성되어야 합니다.
+
link:../san-admin/manage-lifs-all-san-protocols-concept.html["클러스터 SAN 환경에서 LIF에 대한 고려 사항"]

+
link:../networking/create_a_lif.html["LIF 생성"]

+
link:../nfs-config/index.html["NFS 구성에 대해 알아보기"]

+
link:../smb-config/index.html["SMB 구성에 대해 알아보기"]

. SAN 전용: 필요한 LUN이 생성되어 igroup에 매핑되며, 이 igroup은 애플리케이션 호스트의 이니시에이터에 LUN을 매핑하는 데 사용됩니다.
+
link:../san-admin/provision-storage.html["LUN을 생성하고 igroup을 매핑합니다"]

. 애플리케이션 호스트를 다시 스캔하여 새로운 LUN 또는 볼륨이 있는지 확인합니다.

