---
sidebar: sidebar 
permalink: snapmirror-active-sync/delete-fails-takeover-task.html 
keywords: troubleshooting, SM-BC, SMBC, SnapMirror, delete, takeover, consistency group, snapmirror active sync 
summary: 'ONTAP 9.9.1이 클러스터에 설치되면 다음을 실행합니다.  `snapmirror delete` SnapMirror 활성 동기화 일관성 그룹 관계가 인수 상태인 경우 명령이 실패합니다.' 
---
= takover 상태에서 SnapMirror 삭제 작업이 실패합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


.문제:
[role="lead"]
ONTAP 9.9.1이 클러스터에 설치되면 다음을 실행합니다.  `snapmirror delete` SnapMirror 활성 동기화 일관성 그룹 관계가 인수 상태인 경우 명령이 실패합니다.

....
C2_cluster::> snapmirror delete  vs1:/cg/dd

Error: command failed: RPC: Couldn't make connection
....
.해결 방법
SnapMirror 활성 동기화 관계에 있는 노드가 인수 상태인 경우 "-force" 옵션을 true로 설정하여 SnapMirror 삭제 및 해제 작업을 수행합니다.

....
C2_cluster::> snapmirror delete  vs1:/cg/dd -force true

Warning: The relationship between source "vs0:/cg/ss" and destination
         "vs1:/cg/dd" will be deleted, however the items of the destination
         Consistency Group might not be made writable, deletable, or modifiable
         after the operation. Manual recovery might be required.
Do you want to continue? {y|n}: y
Operation succeeded: snapmirror delete for the relationship with destination "vs1:/cg/dd".
....