---
sidebar: sidebar 
permalink: snapmirror-active-sync/limits-reference.html 
keywords: SM-BC, SMBC, restrictions, consistency group, endpoint limits, solaris, aix, hp-ux, fanout, snapmirror active sync 
summary: SnapMirror 액티브 동기화를 사용할 때 몇 가지 추가적인 제한 사항과 제한 사항이 있습니다. 
---
= SnapMirror 활성 동기화에 대한 개체 제한
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror 액티브 동기화를 사용하기 위한 준비를 할 때는 다음 개체 제한에 유의하십시오.



== 클러스터의 일관성 그룹

SnapMirror 액티브 동기화가 있는 클러스터의 일관성 그룹 제한은 관계에 따라 계산되며 사용되는 ONTAP 버전에 따라 달라집니다. 제한은 플랫폼에 독립적입니다.

|===
| ONTAP 버전입니다 | 최대 관계 수 


| ONTAP 9.11.1 이상 | 50 * 


| ONTAP 9.10.1 | 20 


| ONTAP 9.9.1 | 5 
|===
{Asterisk} ONTAP 9.16.1부터 SnapMirror 액티브 동기화는 대칭 액티브/액티브 구성의 4노드 클러스터를 지원합니다. 4노드 클러스터에서는 100개의 일관성 그룹이 지원됩니다.



== 정합성 보장 그룹당 볼륨

SnapMirror 활성 동기화가 있는 일관성 그룹당 최대 볼륨 수는 플랫폼과는 별개입니다.

|===
| ONTAP 버전입니다 | 일관성 그룹 관계에서 지원되는 최대 볼륨 수입니다 


| ONTAP 9.15.1 이상 | 80 


| ONTAP 9.10.1 - 9.14.1 | 16 


| ONTAP 9.9.1 | 12 
|===


== 볼륨

SnapMirror 활성 동기화의 볼륨 제한은 관계 수가 아닌 끝점 수를 기준으로 계산됩니다. 12개의 볼륨이 있는 일관성 그룹은 운영 클러스터와 보조 클러스터 모두에서 12개의 엔드포인트를 지원합니다. SnapMirror 활성 동기화와 SnapMirror 동기식 관계는 모두 총 엔드포인트 수에 기여합니다.


IMPORTANT: 이러한 제한 사항은 FAS, AFF 및 최신 ASA 시스템에 적용됩니다. ASA R2 시스템(ASA A1K, ASA A90, ASA A70, ASA A50, ASA A30 또는 ASA A20)을 사용하는 경우 을 참조하십시오.link:https://docs.netapp.com/us-en/asa-r2/data-protection/manage-consistency-groups.html["ASA r2 설명서"^]

플랫폼당 최대 엔드포인트는 다음 표에 나와 있습니다.

|===
| S. 아니요 | 플랫폼 3+| SnapMirror 활성 동기화에 대한 HA당 엔드포인트 3+| HA당 전체 동기화 및 SnapMirror 활성 동기화 엔드포인트 


|  |  | ONTAP 9.11.1 이상 | ONTAP 9.10.1 | ONTAP 9.9.1 | ONTAP 9.11.1 이상 | ONTAP 9.10.1 | ONTAP 9.9.1 


| 1 | AFF | 400 * | 200 | 60 | 400 | 200 | 80 


| 2 | ASA | 400 * | 200 | 60 | 400 | 200 | 80 
|===
{Asterisk} ONTAP 9.16.1부터 SnapMirror 액티브 동기화는 대칭 액티브/액티브 구성의 4노드 클러스터를 지원합니다. 4노드 클러스터의 총 제한은 800개입니다.



== SAN 오브젝트 제한

SAN 오브젝트 제한사항은 다음 표에 나와 있습니다. 이 제한은 플랫폼에 관계없이 적용됩니다.

|===
| SnapMirror 활성 동기화 관계의 개체입니다 | 카운트 


| 볼륨당 LUN  a| 
* 256(ONTAP 9.9.1 - ONTAP 9.15.0)
* 512(ONTAP 9.15.1 이상)




| 2 x 2 SnapMirror 액티브 동기화 솔루션당 고유 LUN 수입니다 | 4,096개 


| 4 x 4 SnapMirror Active-Sync 솔루션당 고유 LUN 수(ONTAP 9.16.1부터 사용 가능) | 6,144 


| SVM당 LIF(SnapMirror 활성 동기화 관계의 하나 이상의 볼륨 포함) | 256 


| 노드당 클러스터 간 LIF | 4 


| 클러스터당 클러스터 간 LIF | 8 
|===
.관련 정보
* link:https://hwu.netapp.com/["Hardware Universe"^]
* link:../consistency-groups/limits.html["정합성 보장 그룹 제한"^]

