---
sidebar: sidebar 
permalink: snapmirror-active-sync/use-cases-concept.html 
keywords: SM-BC, SMBC, overview, benefits, use cases, architecture, snapmirror active sync 
summary: SnapMirror Active sync protect application with LUN을 사용하여 애플리케이션을 투명하게 페일오버할 수 있으므로 재해 발생 시 무중단 업무 운영을 보장할 수 있습니다. 
---
= SnapMirror Active Sync의 사용 사례
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
전 세계적으로 연결된 비즈니스 환경의 수요로 인해 사이버 공격, 정전 또는 자연재해와 같은 운영 중단이 발생할 경우 데이터 손실 없이 비즈니스 크리티컬 애플리케이션 데이터를 빠르게 복구해야 합니다. 이러한 수요는 금융 및 일반 데이터 보호 규정(GDPR)과 같은 규정 명령을 준수하는 것과 같은 분야에서 더욱 높아지고 있습니다.

SnapMirror 액티브 동기화는 다음과 같은 사용 사례를 제공합니다.

.제로 복구 시간 목표(RTO)를 위한 애플리케이션 구축
SnapMirror Active Sync 배포에는 기본 클러스터와 보조 클러스터가 있습니다. 기본 클러스터의 LUN  `1LP` ) 거울이 있어요 (`L1s` ) 보조 LUN에 있습니다. 두 LUN은 동일한 직렬 ID를 공유하며 호스트에 읽기-쓰기 LUN으로 보고됩니다. 그러나 비대칭 구성에서는 읽기 및 쓰기 작업이 기본 LUN으로만 처리됩니다.  `1LP` . 미러에 대한 모든 쓰기  `L1S` 대리인을 통해 제공됩니다.

.제로 RTO 또는 투명한 애플리케이션 페일오버(TAF)를 위한 애플리케이션 구축
TAF는 호스트 MPIO 소프트웨어 기반 경로 페일오버를 통해 스토리지에 대한 무중단 액세스를 구현합니다. 두 LUN 복사본(예: 기본 볼륨(L1P) 및 미러 볼륨(L1S))은 동일한 ID(일련 번호)를 가지며 호스트에 읽기/쓰기 가능으로 보고됩니다. 그러나 비대칭 구성에서는 읽기 및 쓰기가 기본 볼륨에서만 처리됩니다. 미러 볼륨에 대한 I/O는 기본 볼륨으로 프록시됩니다. 호스트에서 L1에 대한 기본 경로는 비대칭 논리 단위 액세스(ALUA) 액세스 상태가 활성 최적화(A/O)인 경우 VS1:N1입니다. ONTAP Mediator는 구축 과정의 일부로 필요하며, 주로 기본 볼륨의 스토리지 중단 시 페일오버(계획된 또는 계획되지 않은)를 수행합니다.

TAF는 자동 장애 조치(Automated Failover)와 자동 장애 조치 이중화(Automated Failover Duplex)의 두 가지 모드로 작동합니다. 자동 장애 조치를 사용하면 읽기 및 쓰기 작업이 기본 볼륨에서만 처리되므로, 자체적으로 쓰기 작업을 처리할 수 없는 미러 복사본에 대한 IO는 기본 복사본으로 프록시됩니다. 자동 장애 조치 이중화를 사용하면 기본 복사본과 보조 복사본 모두 IO를 처리할 수 있으므로 프록시가 필요하지 않습니다.

ONTAP 9.17.1에서 호스트 액세스에 NVMe를 사용하는 경우 자동 장애 조치 이중화만 지원됩니다.

SnapMirror Active Sync는 애플리케이션 호스트 다중 경로 소프트웨어에서 스토리지 어레이와의 애플리케이션 호스트 통신에 필요한 우선 순위 및 액세스 가용성을 통해 알려진 경로를 사용할 수 있도록 하는 메커니즘인 ALUA를 사용합니다. ALUA는 LUN을 소유한 컨트롤러에 대한 활성 최적화 경로를 최적화되지 않은 활성 경로로 표시하며, 기본 경로에 장애가 발생할 경우에만 사용됩니다.

NVMe 프로토콜을 사용하는 SnapMirror 액티브 싱크는 ANA를 사용하며, 이를 통해 애플리케이션 호스트는 보호되는 NVMe 네임스페이스에 대한 최적화된 경로와 최적화되지 않은 경로를 검색할 수 있습니다. ONTAP NVMe 타겟은 적절한 경로 상태를 게시하여 애플리케이션 호스트가 보호되는 NVMe 네임스페이스에 대한 최적의 경로를 사용할 수 있도록 합니다.

.클러스터된 애플리케이션
VMware Metro Storage Cluster, Oracle RAC 및 SQL을 사용하는 Windows Failover Clustering을 비롯한 클러스터형 애플리케이션은 동시 액세스가 필요하므로 성능 오버헤드 없이 VM을 다른 사이트로 페일오버할 수 있습니다. SnapMirror 액티브 동기식 대칭 액티브/액티브는 양방향 복제 기능을 통해 로컬에서 IO를 제공하여 클러스터 애플리케이션의 요구사항을 충족합니다. ONTAP 9.16.1부터 대칭 액티브/액티브가 4노드 클러스터 구성에서 지원되고 ONTAP 9.15.1의 2노드 클러스터 제한에서 확장됩니다.

.재해 시나리오
지리적으로 분산된 사이트 간에 애플리케이션을 위해 여러 볼륨을 동기식으로 복제합니다. 운영 중단 시 보조 복사본으로 자동으로 페일오버하여 계층 1 애플리케이션에 비즈니스 연속성을 제공할 수 있습니다. 기본 클러스터를 호스팅하는 사이트에 재해가 발생하면 호스트 다중 경로 소프트웨어는 클러스터를 통과하는 모든 경로를 중지로 표시하고 보조 클러스터의 경로를 사용합니다. 그 결과 ONTAP 중재자가 미러 복사본에 대해 무중단 페일오버를 수행합니다.

.Windows 페일오버
SnapMirror 액티브 동기화는 사용하기 쉬운 애플리케이션 레벨 세분화 및 자동 페일오버를 통해 유연성을 제공합니다. SnapMirror Active Sync는 IP 네트워크를 통한 검증된 SnapMirror 동기식 복제를 사용하여 LAN 또는 WAN을 통해 데이터를 고속으로 복제하여 가상 환경과 물리적 환경 모두에서 Oracle, Microsoft SQL Server 등과 같은 비즈니스 크리티컬 애플리케이션의 데이터 가용성과 빠른 데이터 복제를 실현합니다.

SnapMirror Active Sync를 사용하면 전체 사이트 장애가 발생하더라도 미션 크리티컬 비즈니스 서비스가 계속 운영되고 TAF는 2차 복사본에 대한 것입니다. 이 페일오버를 트리거하는 데 수동 개입이나 추가 스크립팅이 필요하지 않습니다.
