---
permalink: smb-admin/configure-metadata-cache-smb.html 
sidebar: sidebar 
keywords: enable, smb, metadata, cache, store, path, file, attribute, data, performance, client, workload, how smb metadata caching works 
summary: SMB 메타데이터 캐시가 설정되면 제한된 시간 동안 경로 및 파일 속성 데이터를 저장합니다. 따라서 공통 워크로드를 사용하는 SMB 1.0 클라이언트의 SMB 성능이 향상될 수 있습니다. 
---
= SMB 공유에 대한 메타데이터 캐시를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
메타데이터 캐싱을 사용하면 SMB 1.0 클라이언트에서 파일 속성 캐싱을 통해 파일 및 폴더 특성에 더 빠르게 액세스할 수 있습니다. 공유별로 특성 캐싱을 설정하거나 해제할 수 있습니다. 메타데이터 캐시가 설정된 경우 캐시된 항목에 대한 라이브 시간 을 구성할 수도 있습니다. 클라이언트가 SMB 2.x 또는 SMB 3.0을 통해 공유에 접속하는 경우에는 메타데이터 캐싱을 구성할 필요가 없습니다.

SMB 메타데이터 캐시가 설정되면 제한된 시간 동안 경로 및 파일 속성 데이터를 저장합니다. 따라서 공통 워크로드를 사용하는 SMB 1.0 클라이언트의 SMB 성능이 향상될 수 있습니다.

특정 작업의 경우 SMB는 경로 및 파일 메타데이터에 대한 여러 개의 동일한 쿼리를 포함할 수 있는 상당한 양의 트래픽을 생성합니다. SMB 메타데이터 캐싱을 사용하여 캐시에서 정보를 가져오는 방식으로 SMB 1.0 클라이언트의 중복 쿼리 수를 줄이고 성능을 향상할 수 있습니다.

[NOTE]
====
가능성은 낮지만 메타데이터 캐시가 오래된 정보를 SMB 1.0 클라이언트에 제공할 수도 있습니다. 귀사의 환경에서 이러한 위험을 감당할 수 없는 경우 이 기능을 활성화하지 마십시오.

====


== ONTAP SMB 메타데이터 캐시 활성화

SMB 메타데이터 캐시를 설정하여 SMB 1.0 클라이언트의 SMB 성능을 향상할 수 있습니다. 기본적으로 SMB 메타데이터 캐싱은 해제되어 있습니다.

.단계
. 새 공유 또는 기존 공유에서 SMB 메타데이터 캐싱을 활성화합니다.
+
** 새 공유를 생성할 때 SMB 메타데이터 캐싱을 활성화합니다.
+
[source, cli]
----
vserver cifs share create -vserver <SVM_name> -share-name <share_name> -path <path> -share-properties attributecache
----
** 기존 공유에서 SMB 메타데이터 캐싱 활성화:
+
[source, cli]
----
vserver cifs share properties add -vserver <SVM_name> -share-name <share_name> -share-properties attributecache
----






== ONTAP SMB 메타데이터 캐시 항목의 수명 구성

SMB 메타데이터 캐시 항목의 수명을 구성하여 사용자 환경에서 SMB 메타데이터 캐시 성능을 최적화할 수 있습니다. 기본값은 10초입니다.

.시작하기 전에
SMB 메타데이터 캐시 기능을 활성화해야 합니다. SMB 메타데이터 캐싱이 설정되어 있지 않으면 SMB 캐시 TTL 설정이 사용되지 않습니다.

.단계
. 새 공유 또는 기존 공유에서 SMB 메타데이터 캐시 항목의 수명을 구성합니다.
+
** 새 공유를 생성할 때 SMB 메타데이터 캐시 항목의 수명을 구성합니다.
+
[source, cli]
----
vserver cifs share create -vserver <SVM_name> -share-name <share_name> -path <path> -attribute-cache-ttl [integerh][integerm][integers]
----
** 기존 공유에서 SMB 메타데이터 캐시 항목의 수명을 구성합니다.
+
[source, cli]
----
vserver cifs share modify -vserver <SVM_name> -share-name <share_name> -attribute-cache-ttl [integerh][integerm][integers]
----




공유를 생성하거나 수정할 때 추가 공유 구성 옵션과 속성을 지정할 수 있습니다. 에 대한 자세한 내용은 `vserver cifs share` link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs+share["ONTAP 명령 참조입니다"^]을 참조하십시오.
