---
permalink: smb-admin/delete-branchcache-config-task.html 
sidebar: sidebar 
keywords: command, deleting, delete, branchcache, service, storage, virtual, machine, svm, exist, hash, delete the branchcache configuration 
summary: 스토리지 가상 머신에서 BranchCache 서비스를 삭제하는 데 사용하는 명령은 기존 해시를 삭제할지 유지할지에 따라 다릅니다. 
---
= ONTAP SMB 공유에서 BranchCache 구성을 삭제합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이전에 BranchCache를 구성했지만 SVM(스토리지 가상 시스템)이 캐시된 콘텐츠를 계속 제공하지 않도록 하려면 CIFS 서버에서 BranchCache 구성을 삭제할 수 있습니다. 구성을 삭제할 때 어떤 일이 발생하는지 알고 있어야 합니다.

구성을 삭제하면 ONTAP에서 해당 SVM에 대한 구성 정보를 클러스터에서 제거하고 BranchCache 서비스를 중지합니다. ONTAP에서 SVM의 해시 저장소를 삭제할 것인지 여부를 선택할 수 있습니다.

BranchCache 구성을 삭제해도 BranchCache 사용 클라이언트의 액세스가 중단되지 않습니다. 그 후 BranchCache를 사용하는 클라이언트가 이미 캐시된 콘텐츠에 대한 기존 SMB 연결에 대한 메타데이터 정보를 요청하면 ONTAP는 Microsoft 정의 오류로 응답하여 클라이언트가 실제 콘텐츠를 요청하는 두 번째 요청을 보냅니다. CIFS 서버는 콘텐츠 요청에 응답하여 SVM에 저장된 실제 콘텐츠를 전송합니다

BranchCache 구성이 삭제된 후 SMB 공유는 BranchCache 기능을 알리지 않습니다. 새 SMB 연결을 사용하여 이전에 캐시되지 않은 콘텐츠에 액세스하려면 클라이언트는 SMB 읽기 요청을 정상적으로 처리합니다.

SVM(스토리지 가상 시스템)에서 BranchCache 서비스를 삭제하는 데 사용하는 명령은 기존 해시를 삭제하거나 유지할지 여부에 따라 달라집니다.

.단계
. 적절한 명령을 실행합니다.
+
|===
| 원하는 작업 | 그런 다음 다음을 입력합니다. 


 a| 
BranchCache 구성을 삭제하고 기존 해시를 삭제합니다
 a| 
'vserver cifs BranchCache delete -vserver_vserver_name_-flush-hash true



 a| 
BranchCache 구성을 삭제하지만 기존 해시는 그대로 둡니다
 a| 
'vserver cifs BranchCache delete -vserver_vserver_name_-flush-hash false

|===


.예
다음 예에서는 SVM VS1 상의 BranchCache 구성을 삭제하고 기존 해시를 모두 삭제합니다.

[listing]
----
cluster1::> vserver cifs branchcache delete -vserver vs1 -flush-hashes true
----