---
permalink: smb-admin/determine-snapshot-copies-available-task.html 
sidebar: sidebar 
keywords: view, snapshot, copies, copy, previous, version, enable, policy, applied, apply, contain, share, previous, version, access, determine whether snapshot copies are available for previous versions use 
summary: 활성화된 스냅샷 정책이 공유를 포함하는 볼륨에 적용되고 볼륨 구성에서 스냅샷에 대한 액세스를 허용하는 경우에만 이전 버전 탭에서 스냅샷을 볼 수 있습니다. 스냅샷 가용성을 확인하는 것은 이전 버전 액세스 권한을 가진 사용자를 지원할 때 유용합니다. 
---
= ONTAP SMB 스냅샷을 이전 버전에서 사용할 수 있는지 확인하세요.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
활성화된 스냅샷 정책이 공유를 포함하는 볼륨에 적용되고 볼륨 구성에서 스냅샷에 대한 액세스를 허용하는 경우에만 이전 버전 탭에서 스냅샷을 볼 수 있습니다. 스냅샷 가용성을 확인하는 것은 이전 버전 액세스 권한을 가진 사용자를 지원할 때 유용합니다.

.단계
. 공유 데이터가 있는 볼륨에 자동 스냅샷이 설정되어 있는지 여부와 클라이언트가 스냅샷 디렉토리에 액세스할 수 있는지 여부를 확인합니다. `volume show -vserver vserver-name -volume volume-name -fields vserver,volume,snapdir-access,snapshot-policy,snapshot-count`
+
이 출력에는 볼륨과 연결된 스냅샷 정책, 클라이언트 스냅샷 디렉토리 액세스 사용 여부 및 사용 가능한 스냅샷 수가 표시됩니다.

. 연결된 스냅샷 정책이 설정되었는지 확인합니다. `volume snapshot policy show -policy policy-name`
. 사용 가능한 스냅샷 나열: `volume snapshot show -volume volume_name`
+
스냅샷 정책 및 스냅샷 스케줄을 구성하고 관리하는 방법에 대한 자세한 내용은 을 참조하십시오.link:../data-protection/index.html["데이터 보호"]



.예
다음 예에서는 "'data1""의 공유 데이터 및 사용 가능한 스냅숏을 포함하는 "'data1" 볼륨과 연관된 스냅숏 정책에 대한 정보를 표시합니다.

[listing]
----
cluster1::> volume show -vserver vs1 -volume data1 -fields vserver,volume,snapshot-policy,snapdir-access,snapshot-count
vserver  volume snapdir-access snapshot-policy snapshot-count
-------- ------ -------------- --------------- --------------
vs1      data1  true           default         10

cluster1::> volume snapshot policy show -policy default
Vserver: cluster1
                   Number of Is
Policy Name        Schedules Enabled Comment
------------------ --------- ------- ----------------------------------
default                    3 true    Default policy with hourly, daily & weekly schedules.
    Schedule         Count     Prefix                 SnapMirror Label
    ---------------- -----     ---------------------- -------------------
    hourly               6     hourly                 -
    daily                2     daily                  daily
    weekly               2     weekly                 weekly

cluster1::> volume snapshot show -volume data1
                                                             ---Blocks---
Vserver  Volume  Snapshot                  State        Size Total% Used%
-------- ------- ------------------------- -------- -------- ------ -----
vs1      data1
                 weekly.2012-12-16_0015    valid       408KB     0%    1%
                 daily.2012-12-22_0010     valid       420KB     0%    1%
                 daily.2012-12-23_0010     valid       192KB     0%    0%
                 weekly.2012-12-23_0015    valid       360KB     0%    1%
                 hourly.2012-12-23_1405    valid       196KB     0%    0%
                 hourly.2012-12-23_1505    valid       196KB     0%    0%
                 hourly.2012-12-23_1605    valid       212KB     0%    0%
                 hourly.2012-12-23_1705    valid       136KB     0%    0%
                 hourly.2012-12-23_1805    valid       200KB     0%    0%
                 hourly.2012-12-23_1905    valid       184KB     0%    0%
----
.관련 정보
* xref:create-snapshot-config-previous-versions-access-task.adoc[이전 버전 액세스를 활성화하기 위한 스냅샷 구성 생성]
* link:../data-protection/index.html["데이터 보호"]

