---
permalink: smb-admin/disable-enable-branchcache-task.html 
sidebar: sidebar 
keywords: disable, enable, branchcache, storage, virtual, machine, svm, changing, change, operating, mode, operate, per-share, automatic, branch, office, client, cache 
summary: 스토리지 가상 머신에서 BranchCache 운영 모드를 비활성화로 변경하여 BranchCache를 비활성화할 수 있습니다. 운영 모드를 변경하여 공유별로 BranchCache 서비스를 제공하거나 모든 공유에 대해 자동으로 제공하도록 설정하여 언제든지 BranchCache를 활성화할 수 있습니다. 
---
= ONTAP SVM에서 BranchCache를 비활성화 또는 활성화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이전에 BranchCache를 구성했지만 지사 클라이언트에서 캐시된 콘텐츠를 사용하지 않도록 하려면 CIFS 서버에서 캐싱을 비활성화할 수 있습니다. BranchCache를 비활성화할 때 발생하는 상황을 알고 있어야 합니다. BranchCache 운영 모드를 비활성화로 변경하여 스토리지 가상 머신에서 BranchCache를 비활성화할 수 있습니다. 운영 모드를 공유별로 BranchCache 서비스를 제공하거나 모든 공유에 대해 자동으로 제공하도록 변경하면 언제든지 BranchCache를 활성화할 수 있습니다.

BranchCache를 사용하지 않도록 설정하면 ONTAP는 더 이상 해시를 계산하지 않고 요청 클라이언트로 메타데이터를 보내지 않습니다. 그러나 파일 액세스는 중단되지 않습니다. 그 후 BranchCache를 사용하는 클라이언트가 액세스할 콘텐츠에 대한 메타데이터 정보를 요청하면 ONTAP는 Microsoft 정의 오류로 응답하여 클라이언트가 실제 콘텐츠를 요청하는 두 번째 요청을 보냅니다. CIFS 서버는 콘텐츠 요청에 따라 SVM(스토리지 가상 머신)에 저장된 실제 콘텐츠를 전송합니다.

CIFS 서버에서 BranchCache를 사용하지 않도록 설정한 후 SMB 공유는 BranchCache 기능을 알리지 않습니다. 새 SMB 연결에서 데이터에 액세스하기 위해 클라이언트는 SMB 읽기 요청을 정상적으로 처리합니다.

언제든지 CIFS 서버에서 BranchCache를 다시 설정할 수 있습니다.

* BranchCache를 비활성화하면 해시 저장소가 삭제되지 않으므로 요청된 해시가 여전히 유효하다면 ONTAP는 해시 요청을 다시 활성화한 후 해시 요청에 응답할 때 저장된 해시를 사용할 수 있습니다.
* BranchCache를 사용하지 않는 동안 BranchCache 사용 공유에 SMB 연결을 설정한 클라이언트는 BranchCache를 나중에 다시 사용하도록 설정한 경우 BranchCache 지원을 받지 않습니다.
+
이는 ONTAP가 SMB 세션을 설정할 때 공유에 대한 BranchCache 지원을 광고하기 때문입니다. BranchCache를 사용하지 않는 동안 BranchCache 사용 공유에 세션을 설정한 클라이언트는 이 공유에 대해 캐시된 콘텐츠를 사용하려면 연결을 끊고 다시 연결해야 합니다.



[NOTE]
====
CIFS 서버에서 BranchCache를 해제한 후에 해시 저장소를 저장하지 않으려면 수동으로 삭제할 수 있습니다. BranchCache를 다시 사용하도록 설정하는 경우 해시 저장소 디렉터리가 있는지 확인해야 합니다. BranchCache를 다시 사용하도록 설정한 후 BranchCache 사용 공유는 BranchCache 기능을 광고합니다. ONTAP는 BranchCache 사용 클라이언트가 새 요청을 할 때 새 해시를 생성합니다.

====
.단계
. 적절한 명령을 실행합니다.
+
|===
| 원하는 작업 | 그런 다음 다음을 입력합니다. 


 a| 
BranchCache를 비활성화합니다
 a| 
'vserver cifs BranchCache modify -vserver vserver_name -operating-mode disable'



 a| 
공유당 BranchCache를 설정합니다
 a| 
'vserver cifs BranchCache modify -vserver vserver_name -operating-mode per-share'



 a| 
모든 공유에 대해 BranchCache를 사용하도록 설정합니다
 a| 
'vserver cifs BranchCache modify -vserver vserver_name -operating-mode all-공유'

|===
. BranchCache 작동 모드가 'vserver cifs BranchCache show -vserver vserver vserver_name' 설정으로 구성되어 있는지 확인합니다


.예
다음 예에서는 SVM VS1 에서 BranchCache를 사용하지 않도록 설정합니다.

[listing]
----
cluster1::> vserver cifs branchcache modify -vserver vs1 -operating-mode disable

cluster1::> vserver cifs branchcache show -vserver vs1

                                 Vserver: vs1
          Supported BranchCache Versions: enable_all
                      Path to Hash Store: /hash_data
          Maximum Size of the Hash Store: 20GB
Encryption Key Used to Secure the Hashes: -
        CIFS BranchCache Operating Modes: disable
----