---
permalink: smb-admin/disable-branchcache-single-share-task.html 
sidebar: sidebar 
keywords: offer, caching, service, certain, share, offer, cache, disable, branchcache, exist, smb, disable branchcache on a single smb share 
summary: 이전에 캐시된 콘텐츠를 제공한 특정 공유에 캐싱 서비스를 제공하지 않으려면 기존 SMB 공유에서 BranchCache를 사용하지 않도록 설정할 수 있습니다. 
---
= SMB 공유에서 BranchCache를 해제합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
특정 SMB 공유에서 BranchCache 캐싱 서비스를 제공하지 않고 나중에 이러한 공유에 캐싱 서비스를 제공하려는 경우 공유별로 BranchCache를 사용하지 않도록 설정할 수 있습니다. BranchCache가 모든 공유에서 캐싱을 제공하도록 구성되었지만 모든 캐싱 서비스를 일시적으로 해제하려면 BranchCache 구성을 수정하여 모든 공유에서 자동 캐싱을 중지할 수 있습니다.

SMB 공유의 BranchCache가 이후에 처음 설정된 후 비활성화되면 ONTAP는 요청된 클라이언트로 메타데이터 전송을 중지합니다. 데이터가 필요한 클라이언트는 콘텐츠 서버(SVM(Storage Virtual Machine)의 CIFS 서버)에서 직접 데이터를 검색합니다.



[[disable-branchcache-on-a-single-ontap-smb-share]]
== 단일 ONTAP SMB 공유에서 BranchCache 비활성화

이전에 캐시된 콘텐츠를 제공한 특정 공유에 캐싱 서비스를 제공하지 않으려면 기존 SMB 공유에서 BranchCache를 사용하지 않도록 설정할 수 있습니다.

.단계
. 다음 명령을 입력합니다.
+
[source, cli]
----
vserver cifs share properties remove -vserver <SVM_name> -share-name <share_name> -share-properties branchcache
----
+
BranchCache 공유 속성이 제거됩니다. 다른 적용된 공유 속성은 그대로 유지됩니다.



.예
다음 명령을 실행하면 이름이 "data2"인 기존 SMB 공유에서 BranchCache가 비활성화됩니다.

[listing]
----
cluster1::> vserver cifs share show -vserver vs1 -share-name data2

                      Vserver: vs1
                        Share: data2
     CIFS Server NetBIOS Name: VS1
                         Path: /data2
             Share Properties: oplocks
                               browsable
                               changenotify
                               attributecache
                               branchcache
           Symlink Properties: -
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: 10s
                  Volume Name: -
                Offline Files: manual
Vscan File-Operations Profile: standard

cluster1::> vserver cifs share properties remove -vserver vs1 -share-name data2 -share-properties branchcache

cluster1::> vserver cifs share show -vserver vs1 -share-name data2

                      Vserver: vs1
                        Share: data2
     CIFS Server NetBIOS Name: VS1
                         Path: /data2
             Share Properties: oplocks
                               browsable
                               changenotify
                               attributecache
           Symlink Properties: -
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: 10s
                  Volume Name: -
                Offline Files: manual
Vscan File-Operations Profile: standard
----


[[stop-automatic-caching-on-all-ontap-smb-shares]]
== 모든 ONTAP SMB 공유에서 자동 캐싱 중지

BranchCache 구성에서 각 SVM(스토리지 가상 머신)의 모든 SMB 공유에 대한 캐싱을 자동으로 설정하는 경우 BranchCache 구성을 수정하여 모든 SMB 공유의 컨텐츠를 자동으로 캐싱하지 않도록 할 수 있습니다.

.이 작업에 대해
모든 SMB 공유에서 자동 캐싱을 중지하려면 BranchCache 운영 모드를 공유 기준 캐싱으로 변경합니다.

.단계
. 모든 SMB 공유에서 자동 캐싱을 중지하도록 BranchCache를 구성합니다.
+
[source, cli]
----
vserver cifs branchcache modify -vserver <SVM_name> -operating-mode per-share
----
. BranchCache 구성이 올바른지 확인하십시오.
+
[source, cli]
----
vserver cifs branchcache show -vserver <SVM_name>
----


.예
다음 명령을 실행하면 스토리지 가상 머신(SVM, 이전의 Vserver)의 BranchCache 구성이 변경되어 모든 SMB 공유에서 자동 캐싱을 중지합니다.

[listing]
----
cluster1::> vserver cifs branchcache modify -vserver vs1 -operating-mode per-share

cluster1::> vserver cifs branchcache show -vserver vs1

                                 Vserver: vs1
          Supported BranchCache Versions: enable_all
                      Path to Hash Store: /hash_data
          Maximum Size of the Hash Store: 20GB
Encryption Key Used to Secure the Hashes: -
        CIFS BranchCache Operating Modes: per_share
----
.관련 정보
xref:configure-branchcache-enabled-shares-concept.adoc[BranchCache 지원 공유 구성에 대해 알아보세요]
