---
permalink: smb-admin/enable-disable-local-users-groups-authentication.html 
sidebar: sidebar 
keywords: local, user, group, access, control, ntfs, security-style, data, enable, authentication, disable, enable or disable local users and groups functionality 
summary: NTFS 보안 스타일 데이터의 액세스 제어에 로컬 사용자 및 그룹을 사용하려면 먼저 로컬 사용자 및 그룹 기능을 활성화해야 합니다. 또한 SMB 인증에 로컬 사용자를 사용하려면 로컬 사용자 인증 기능을 활성화해야 합니다. 
---
= 로컬 ONTAP SMB 사용자 및 그룹 기능을 활성화 또는 비활성화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NTFS 보안 스타일 데이터의 액세스 제어에 로컬 사용자 및 그룹을 사용하려면 먼저 로컬 사용자 및 그룹 기능을 활성화해야 합니다. 또한 SMB 인증에 로컬 사용자를 사용하려면 로컬 사용자 인증 기능을 활성화해야 합니다.

로컬 사용자 및 그룹 기능 및 로컬 사용자 인증은 기본적으로 사용됩니다. 이 옵션이 설정되어 있지 않으면 로컬 사용자 및 그룹을 구성하고 사용할 수 있도록 설정하기 전에 설정해야 합니다. 언제든지 로컬 사용자 및 그룹 기능을 사용하지 않도록 설정할 수 있습니다.

로컬 사용자 및 그룹 기능을 명시적으로 해제하는 것 외에도, 클러스터의 노드가 해당 기능을 지원하지 않는 ONTAP 릴리즈로 되돌려지는 경우 ONTAP는 로컬 사용자 및 그룹 기능을 비활성화합니다. 클러스터의 모든 노드에서 지원하는 ONTAP 버전이 실행될 때까지 로컬 사용자 및 그룹 기능이 활성화되지 않습니다.

.관련 정보
* xref:manage-local-user-accounts.html[로컬 사용자 계정을 수정합니다]
* xref:manage-local-groups.html[로컬 그룹을 수정합니다]
* xref:manage-local-privileges.html[로컬 또는 도메인 사용자 또는 그룹에 권한을 추가합니다]




[[enable-or-disable-local-users-and-groups-on-ontap-smb-servers]]
== ONTAP SMB 서버에서 로컬 사용자 및 그룹 활성화 또는 비활성화

SVM(스토리지 가상 머신)에서 SMB 액세스를 위해 로컬 사용자 및 그룹을 설정하거나 해제할 수 있습니다. 로컬 사용자 및 그룹 기능은 기본적으로 활성화되어 있습니다.

.이 작업에 대해
SMB 공유 및 NTFS 파일 권한을 구성할 때 로컬 사용자 및 그룹을 사용할 수 있으며 SMB 연결을 생성할 때 로컬 사용자를 인증에 사용할 수도 있습니다. 로컬 사용자를 인증에 사용하려면 로컬 사용자 및 그룹 인증 옵션도 활성화해야 합니다.

.단계
. 권한 수준을 고급으로 설정합니다.
+
[source, cli]
----
set -privilege advanced
----
. 로컬 사용자 및 그룹 활성화 또는 비활성화:
+
** 로컬 사용자 및 그룹 활성화:
+
[source, cli]
----
vserver cifs options modify -vserver <SVM_name> -is-local-users-and-groups-enabled true
----
** 로컬 사용자 및 그룹 비활성화:
+
[source, cli]
----
vserver cifs options modify -vserver <SVM_name> -is-local-users-and-groups-enabled false
----


. 관리자 권한 레벨로 돌아갑니다.
+
[source, cli]
----
set -privilege admin
----


.예
다음 예에서는 SVM VS1 에서 로컬 사용자 및 그룹 기능을 사용하도록 설정합니다.

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options modify -vserver vs1 -is-local-users-and-groups-enabled true

cluster1::*> set -privilege admin
----
.관련 정보
* xref:manage-local-user-accounts.adoc[로컬 사용자 계정을 관리합니다] == ONTAP SMB 서버에서 로컬 사용자 인증 활성화 또는 비활성화


SVM(스토리지 가상 머신)에서 SMB 액세스에 대한 로컬 사용자 인증을 설정하거나 해제할 수 있습니다. 기본값은 로컬 사용자 인증을 허용하는 것입니다. 이는 SVM이 도메인 컨트롤러에 연결할 수 없거나 도메인 레벨 액세스 제어를 사용하지 않도록 선택하는 경우에 유용합니다.

.시작하기 전에
CIFS 서버에서 로컬 사용자 및 그룹 기능을 설정해야 합니다.

.이 작업에 대해
언제든지 로컬 사용자 인증을 활성화 또는 비활성화할 수 있습니다. SMB 연결을 생성할 때 인증에 로컬 사용자를 사용하려면 CIFS 서버의 로컬 사용자 및 그룹 옵션도 설정해야 합니다.

.단계
. 권한 수준을 고급으로 설정합니다.
+
[source, cli]
----
set -privilege advanced
----
. 로컬 사용자 인증 활성화 또는 비활성화:
+
** 로컬 사용자 인증 활성화:
+
[source, cli]
----
vserver cifs options modify -vserver <SVM_name> -is-local-auth-enabled true
----
** 로컬 사용자 인증 비활성화:
+
[source, cli]
----
vserver cifs options modify -vserver <SVM_name> -is-local-auth-enabled false
----


. 관리자 권한 레벨로 돌아갑니다.
+
[source, cli]
----
set -privilege admin
----


.예
다음 예에서는 SVM VS1 에서 로컬 사용자 인증을 사용합니다.

[listing]
----
cluster1::>set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options modify -vserver vs1 -is-local-auth-enabled true

cluster1::*> set -privilege admin
----
.관련 정보
* xref:local-user-authentication-concept.adoc[로컬 사용자 인증에 대해 알아보세요]
* xref:enable-disable-local-users-groups-authentication.html[서버에서 로컬 사용자 및 그룹 활성화 또는 비활성화]

