---
permalink: smb-admin/manage-local-user-accounts.html 
sidebar: sidebar 
keywords: modify, local, user, account, change, exist, name, description, enable, disable, rename, compromise, administrative, modify local user accounts 
summary: 로컬 사용자 계정을 활성화하여 SMB를 통해 SVM 데이터에 액세스할 수 있도록 허용하거나, 비활성화하여 액세스를 차단할 수 있습니다. 또한 계정을 수정하여 사용자의 전체 이름, 설명 또는 활성화 상태를 업데이트할 수 있습니다. 필요한 경우, 사용자 이름이 유출되는 등의 관리상의 이유로 계정 이름을 변경할 수 있습니다. 사용자가 속한 로컬 그룹도 확인할 수 있으며, 이를 통해 파일 및 폴더 액세스 권한을 파악하고 액세스 문제를 해결하는 데 도움이 됩니다. 
---
= 로컬 ONTAP SMB 사용자 계정을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
로컬 사용자 계정을 활성화하여 SMB를 통해 SVM 데이터에 액세스할 수 있도록 허용하거나, 비활성화하여 액세스를 차단할 수 있습니다. 또한 계정을 수정하여 사용자의 전체 이름, 설명 또는 활성화 상태를 업데이트할 수 있습니다. 필요한 경우, 사용자 이름이 유출되는 등의 관리상의 이유로 계정 이름을 변경할 수 있습니다. 사용자가 속한 로컬 그룹도 확인할 수 있으며, 이를 통해 파일 및 폴더 액세스 권한을 파악하고 액세스 문제를 해결하는 데 도움이 됩니다.

|===
| 원하는 작업 | 명령 입력... 


 a| 
로컬 사용자의 암호 변경
 a| 
`vserver cifs users-and-groups local-user set-password -vserver <SVM_name> -user-name <user_name>`



 a| 
로컬 사용자 계정을 활성화하거나 비활성화합니다
 a| 
`vserver cifs users-and-groups local-user modify -vserver <SVM_name> -user-name <user_name> -is-account-disabled {true|false}`



 a| 
사용자에 대한 자세한 계정 정보를 표시합니다
 a| 
`vserver cifs users-and-groups local-user show -instance -vserver <SVM_name> -user-name <user_name>`



 a| 
지정된 로컬 사용자의 로컬 사용자 구성원 정보를 표시합니다
 a| 
`vserver cifs users-and-groups local-user show-membership -user-name <user_name>`



 a| 
이 로컬 사용자가 구성원인 로컬 그룹의 로컬 사용자 구성원 정보를 표시합니다
 a| 
'vserver cifs users-and-groups local-user show-membership_group_name_'



 a| 
지정된 SVM(스토리지 가상 머신)과 연결된 로컬 사용자의 사용자 구성원 정보를 표시합니다.
 a| 
`vserver cifs users-and-groups local-user show-membership -vserver <SVM_name>`



 a| 
지정된 SVM의 모든 로컬 사용자에 대한 세부 정보를 표시합니다
 a| 
`vserver cifs users-and-groups local-user show-membership -instance -vserver <SVM_name>`



 a| 
SVM(스토리지 가상 시스템)의 모든 사용자에 대한 정보 표시
 a| 
`vserver cifs users-and-groups local-user show -vserver <SVM_name>`



 a| 
로컬 사용자의 설명을 수정합니다
 a| 
`vserver cifs users-and-groups local-user modify -vserver <SVM_name> -user-name <user_name> -description text`

설명에 공백이 포함된 경우 큰따옴표로 묶어야 합니다.



 a| 
로컬 사용자의 전체 이름을 수정합니다
 a| 
`vserver cifs users-and-groups local-user modify -vserver <SVM_name> -user-name <user_name> -full-name text`

전체 이름에 공백이 포함된 경우 큰따옴표로 묶어야 합니다.



 a| 
로컬 사용자 계정의 이름을 바꿉니다
 a| 
`vserver cifs users-and-groups local-user rename -vserver <SVM_name> -user-name <user_name> -new-user-name <new_user_name>`

로컬 사용자의 이름을 변경할 때 새 사용자 이름은 이전 사용자 이름과 동일한 CIFS 서버에 연결된 상태로 유지되어야 합니다.

|===
.예
다음 예에서는 스토리지 가상 머신(SVM, 이전 명칭 Vserver)의 로컬 사용자 "'cifs_server\sue""를 "'cifs_server\sue_new""로 바꿉니다.1

[listing]
----
cluster1::> vserver cifs users-and-groups local-user rename -user-name CIFS_SERVER\sue -new-user-name CIFS_SERVER\sue_new -vserver vs1
----
.예
다음 예제는 SVM VS1 의 모든 로컬 사용자에 대한 정보를 표시합니다.

[listing]
----
cluster1::> vserver cifs users-and-groups local-user show -vserver vs1
Vserver  User Name                   Full Name     Description
-------- --------------------------- ------------- -------------
vs1      CIFS_SERVER\Administrator   James Smith   Built-in administrator account
vs1      CIFS_SERVER\sue             Sue   Jones
----
.예
다음 예에서는 스토리지 가상 머신(SVM, 이전 명칭 Vserver) VS1 과 연관된 로컬 사용자 ""cifs_server\sue""의 암호를 설정합니다.

[listing]
----
cluster1::> vserver cifs users-and-groups local-user set-password -user-name CIFS_SERVER\sue -vserver vs1

Enter the new password:
Confirm the new password:
----
.예
다음 예에서는 SVM VS1 상의 모든 로컬 사용자에 대한 구성원 정보를 표시합니다. 사용자 "'cifs_server\Administrator'"는 "'BUILTIN\Administrators'" 그룹의 구성원이고 "'cifs_server\sue'"는 "'cifs_server\G1"" 그룹의 구성원입니다.

[listing]
----
cluster1::> vserver cifs users-and-groups local-user show-membership -vserver vs1
Vserver    User Name                    Membership
---------- ---------------------------- ------------------------
vs1        CIFS_SERVER\Administrator    BUILTIN\Administrators
           CIFS_SERVER\sue              CIFS_SERVER\g1
----
.관련 정보
* 에 대한 자세한 내용은 `vserver cifs` link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs["ONTAP 명령 참조입니다"^]을 참조하십시오.
* xref:enable-disable-password-complexity-local-users-task.adoc[로컬 사용자에 대한 암호 복잡성 구성]
* xref:display-server-security-settings-task.adoc[서버 보안 설정에 대한 정보 표시]




[[delete-local-ontap-smb-user-accounts]]
== 로컬 ONTAP SMB 사용자 계정 삭제

CIFS 서버에 대한 로컬 SMB 인증이 더 이상 필요하지 않거나 SVM에 포함된 데이터에 대한 액세스 권한을 결정하기 위해 SVM(스토리지 가상 시스템)에서 로컬 사용자 계정을 삭제할 수 있습니다.

.이 작업에 대해
로컬 사용자를 삭제할 때 다음 사항에 유의하십시오.

* 파일 시스템이 변경되지 않았습니다.
+
이 사용자를 참조하는 파일 및 디렉토리의 Windows 보안 설명자는 조정되지 않습니다.

* 로컬 사용자에 대한 모든 참조는 멤버 자격 및 권한 데이터베이스에서 제거됩니다.
* Administrator와 같이 잘 알려진 표준 사용자는 삭제할 수 없습니다.


.단계
. 삭제하려는 로컬 사용자 계정의 이름을 확인하세요.
+
[source, cli]
----
vserver cifs users-and-groups local-user show -vserver <SVM_name>
----
. 로컬 사용자를 삭제합니다.
+
[source, cli]
----
vserver cifs users-and-groups local-user delete -vserver <SVM_name> -user-name <user_name>
----
. 사용자 계정이 삭제되었는지 확인하십시오.
+
[source, cli]
----
vserver cifs users-and-groups local-user show -vserver <SVM_name>
----


다음 예에서는 SVM VS1 관련 로컬 사용자 ""cifs_server\sue""를 삭제합니다.

[listing]
----
cluster1::> vserver cifs users-and-groups local-user show -vserver vs1
Vserver  User Name                   Full Name      Description
-------- --------------------------- -------------- -------------
vs1      CIFS_SERVER\Administrator   James Smith    Built-in administrator account
vs1      CIFS_SERVER\sue             Sue   Jones


cluster1::> vserver cifs users-and-groups local-user delete -vserver vs1 -user-name CIFS_SERVER\sue

cluster1::> vserver cifs users-and-groups local-user show -vserver vs1
Vserver      User Name                   Full Name      Description
-------- --------------------------- -------------- -------------
vs1      CIFS_SERVER\Administrator   James Smith    Built-in administrator account
----