---
permalink: smb-admin/manage-local-groups.html 
sidebar: sidebar 
keywords: modify, exist, local, group, description, exist, local, group, renaming, rename, modify local groups 
summary: 기존 로컬 그룹에 대한 설명을 변경하거나 그룹의 이름을 변경하여 기존 로컬 그룹을 수정할 수 있습니다. 
---
= 로컬 ONTAP SMB 그룹 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
설명을 업데이트하거나 이름을 변경하여 로컬 그룹을 수정할 수 있습니다. 또한 클러스터 또는 특정 스토리지 가상 머신(SVM)의 모든 로컬 그룹을 확인하고 각 그룹에 속한 사용자를 볼 수 있습니다. 이 정보는 SVM에서 파일 액세스 및 사용자 권한 문제를 해결하는 데 도움이 될 수 있습니다.

[cols="2,4a"]
|===
| 원하는 작업 | 명령 사용... 


 a| 
클러스터의 모든 로컬 그룹 표시
 a| 
'vserver cifs users-and-groups local-group show'를 참조하십시오



 a| 
SVM에 모든 로컬 그룹 표시
 a| 
`vserver cifs users-and-groups local-group show -vserver <SVM_name>`



 a| 
클러스터의 모든 로컬 그룹 구성원 표시
 a| 
'vserver cifs users-and-groups local-group show-ups'



 a| 
SVM의 모든 로컬 그룹 구성원 표시
 a| 
`vserver cifs users-and-groups local-group show-members -vserver <SVM_name>`



 a| 
로컬 그룹 설명을 수정합니다
 a| 
`vserver cifs users-and-groups local-group modify -vserver <SVM_name> -group-name <group_name> -description text`

설명에 공백이 포함된 경우 큰따옴표로 묶어야 합니다.



 a| 
로컬 그룹의 이름을 바꿉니다
 a| 
`vserver cifs users-and-groups local-group rename -vserver <SVM_name> -group-name <group_name> -new-group-name <new_group_name>`

|===
.명령 예
[%collapsible]
====
.예
다음 예에서는 로컬 그룹 ""cifs_server\engineering""의 이름을 ""cifs_server\engineering_new""로 바꿉니다.

[listing]
----
cluster1::> vserver cifs users-and-groups local-group rename -vserver vs1 -group-name CIFS_SERVER\engineering -new-group-name CIFS_SERVER\engineering_new
----
다음 예에서는 로컬 그룹 ""cifs_server\engineering""의 설명을 수정합니다.

[listing]
----
cluster1::> vserver cifs users-and-groups local-group modify -vserver vs1 -group-name CIFS_SERVER\engineering -description "New Description"
----
.예
다음 예제는 SVM VS1 의 모든 로컬 그룹에 대한 정보를 표시합니다.

[listing]
----
cluster1::> vserver cifs users-and-groups local-group show -vserver vs1
Vserver  Group Name                  Description
-------- --------------------------- ----------------------------
vs1      BUILTIN\Administrators      Built-in Administrators group
vs1      BUILTIN\Backup Operators    Backup Operators group
vs1      BUILTIN\Power Users         Restricted administrative privileges
vs1      BUILTIN\Users               All users
vs1      CIFS_SERVER\engineering
vs1      CIFS_SERVER\sales
----
.예
다음 예는 SVM VS1 로컬 그룹의 모든 구성원에 대한 정보를 표시합니다.

[listing]
----
cluster1::> vserver cifs users-and-groups local-group show-members -vserver vs1
Vserver   Group Name                   Members
--------- ---------------------------- ------------------------
vs1       BUILTIN\Administrators       CIFS_SERVER\Administrator
                                       AD_DOMAIN\Domain Admins
                                       AD_DOMAIN\dom_grp1
          BUILTIN\Users                AD_DOMAIN\Domain Users
                                       AD_DOMAIN\dom_usr1
          CIFS_SERVER\engineering      CIFS_SERVER\james
----
====


[[delete-local-ontap-smb-groups]]
== 로컬 ONTAP SMB 그룹 삭제

SVM(스토리지 가상 시스템)에서 로컬 그룹을 삭제하여 해당 SVM과 관련된 데이터에 대한 액세스 권한을 결정하거나 SVM 사용자 권한(권한)을 그룹 멤버에 할당할 필요가 없는 경우 해당 로컬 그룹을 삭제할 수 있습니다.

.이 작업에 대해
로컬 그룹을 삭제할 때 다음 사항에 유의하십시오.

* 파일 시스템이 변경되지 않았습니다.
+
이 그룹을 참조하는 파일 및 디렉토리의 Windows 보안 설명자는 조정되지 않습니다.

* 그룹이 없으면 오류가 반환됩니다.
* special_everyone_group은 삭제할 수 없습니다.
* BUILTIN\Administrators__BUILTIN\Users_와 같은 기본 제공 그룹은 삭제할 수 없습니다.


.단계
. SVM에서 로컬 그룹 목록을 표시하여 삭제하려는 로컬 그룹의 이름을 확인합니다.
+
[source, cli]
----
vserver cifs users-and-groups local-group show -vserver <SVM_name>
----
. 로컬 그룹 삭제:
+
[source, cli]
----
vserver cifs users-and-groups local-group delete -vserver <SVM_name> -group-name <group_name>
----
. 그룹이 삭제되었는지 확인합니다.
+
[source, cli]
----
vserver cifs users-and-groups local-group show -vserver <SVM_name>
----


.명령 예
[%collapsible]
====
다음 예에서는 SVM VS1 관련 로컬 그룹 ""cifs_server\sales""를 삭제합니다.

[listing]
----
cluster1::> vserver cifs users-and-groups local-group show -vserver vs1
Vserver   Group Name                   Description
--------- ---------------------------- ----------------------------
vs1       BUILTIN\Administrators       Built-in Administrators group
vs1       BUILTIN\Backup Operators     Backup Operators group
vs1       BUILTIN\Power Users          Restricted administrative privileges
vs1       BUILTIN\Users                All users
vs1       CIFS_SERVER\engineering
vs1       CIFS_SERVER\sales

cluster1::> vserver cifs users-and-groups local-group delete -vserver vs1 -group-name CIFS_SERVER\sales

cluster1::> vserver cifs users-and-groups local-group show -vserver vs1
Vserver   Group Name                   Description
--------- ---------------------------- ----------------------------
vs1       BUILTIN\Administrators       Built-in Administrators group
vs1       BUILTIN\Backup Operators     Backup Operators group
vs1       BUILTIN\Power Users          Restricted administrative privileges
vs1       BUILTIN\Users                All users
vs1       CIFS_SERVER\engineering
----
====


[[add-a-member-to-a-local-ontap-smb-group]]
== 로컬 ONTAP SMB 그룹에 멤버를 추가합니다

로컬 사용자, 도메인 사용자 또는 도메인 그룹을 추가하여 로컬 그룹 멤버십을 관리할 수 있습니다. 이는 그룹에 적용된 액세스 제어를 기반으로 데이터에 대한 액세스를 제어하거나 사용자에게 해당 그룹과 관련된 권한을 부여하려는 경우에 유용합니다.

.이 작업에 대해
* special_everyone_group에 사용자를 추가할 수 없습니다.
* 사용자를 추가하려면 로컬 그룹이 있어야 합니다.
* 사용자를 로컬 그룹에 추가하려면 사용자가 있어야 합니다.
* 로컬 그룹을 다른 로컬 그룹에 추가할 수 없습니다.
* 도메인 사용자 또는 그룹을 로컬 그룹에 추가하려면 Data ONTAP에서 SID에 대한 이름을 확인할 수 있어야 합니다.


.단계
. 그룹에 구성원 추가:
+
[source, cli]
----
vserver cifs users-and-groups local-group add-members -vserver _vserver_name_ -group-name _group_name_ -member-names name[,...]
----


로컬 사용자, 도메인 사용자 또는 도메인 그룹의 쉼표로 구분된 목록을 지정하여 지정된 로컬 그룹에 추가할 수 있습니다.

.명령 예
[%collapsible]
====
다음 예에서는 SVM VS1 상의 로컬 그룹 "sMB_server\sue"와 도메인 그룹 "AD_DOM\DOM_ENG"를 로컬 그룹 "sMB_server\engineering"에 추가합니다.

[listing]
----
cluster1::> vserver cifs users-and-groups local-group add-members -vserver vs1 -group-name SMB_SERVER\engineering -member-names SMB_SERVER\sue,AD_DOMAIN\dom_eng
----
====


[[remove-a-member-from-a-local-ontap-smb-group]]
== 로컬 ONTAP SMB 그룹에서 구성원을 제거합니다

로컬 사용자, 도메인 사용자 또는 도메인 그룹을 제거하여 로컬 그룹 구성원 자격을 관리할 수 있습니다. 이는 그룹에 적용된 액세스 제어를 기반으로 데이터에 대한 액세스를 제어하거나 사용자에게 해당 그룹과 관련된 권한을 부여하려는 경우에 유용합니다.

.이 작업에 대해
* special_everyone_group에서 구성원을 제거할 수 없습니다.
* 구성원을 제거할 그룹이 있어야 합니다.
* ONTAP는 그룹에서 제거하려는 구성원 이름을 해당 SID로 확인할 수 있어야 합니다.


.단계
. 그룹에서 구성원 제거:
+
[source, cli]
----
vserver cifs users-and-groups local-group remove-members -vserver _vserver_name_ -group-name _group_name_ -member-names name[,...]
----


로컬 사용자, 도메인 사용자 또는 도메인 그룹의 쉼표로 구분된 목록을 지정하여 지정된 로컬 그룹에서 제거할 수 있습니다.

.명령 예
[%collapsible]
====
다음 예에서는 SVM VS1 로컬 그룹 "sMB_server\sue"와 "sMB_server\james"를 SVM VS1 로컬 그룹 "sMB_server\engineering"에서 제거합니다.

[listing]
----
cluster1::> vserver cifs users-and-groups local-group remove-members -vserver vs1 -group-name SMB_SERVER\engineering -member-names SMB_SERVER\sue,SMB_SERVER\james
----
====


[[update-ontap-smb-domain-user-and-group-names-in-local-databases]]
== 로컬 데이터베이스에서 ONTAP SMB 도메인 사용자 및 그룹 이름 업데이트

CIFS 서버의 로컬 그룹에 도메인 사용자 및 그룹을 추가할 수 있습니다. 이러한 도메인 개체는 클러스터의 로컬 데이터베이스에 등록됩니다. 도메인 개체의 이름이 변경된 경우 로컬 데이터베이스를 수동으로 업데이트해야 합니다.

.이 작업에 대해
도메인 이름을 업데이트할 SVM(스토리지 가상 시스템)의 이름을 지정해야 합니다.

.단계
. 권한 수준을 고급으로 설정합니다.
+
[source, cli]
----
set -privilege advanced
----
. 스토리지 가상 머신과 연결된 도메인 사용자 및 그룹의 이름을 업데이트합니다.
+
[source, cli]
----
vserver cifs users-and-groups update-names -vserver <SVM_name>
----
. 업데이트에 성공한 도메인 사용자 및 그룹과 업데이트에 실패한 도메인 사용자 및 그룹을 표시합니다.
+
[source, cli]
----
vserver cifs users-and-groups update-names -vserver <SVM_name> -display-failed-only false|true
----
. 업데이트에 대한 모든 상태 정보를 표시하지 않으려면 다음 명령을 사용하십시오.
+
[source, cli]
----
vserver cifs users-and-groups update-names -vserver <SVM_name> -suppress-all-output true
----
. 관리자 권한 레벨로 돌아갑니다.
+
[source, cli]
----
set -privilege admin
----


.명령 예
[%collapsible]
====
다음 예에서는 스토리지 가상 머신(SVM, 이전의 Vserver) VS1 과 관련된 도메인 사용자 및 그룹의 이름을 업데이트합니다. 마지막 업데이트 시 업데이트해야 할 종속 이름 체인이 있습니다.

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs users-and-groups update-names -vserver vs1

   Vserver:           vs1
   SID:               S-1-5-21-123456789-234565432-987654321-12345
   Domain:            EXAMPLE1
   Out-of-date Name:  dom_user1
   Updated Name:      dom_user2
   Status:            Successfully updated

   Vserver:           vs1
   SID:               S-1-5-21-123456789-234565432-987654322-23456
   Domain:            EXAMPLE2
   Out-of-date Name:  dom_user1
   Updated Name:      dom_user2
   Status:            Successfully updated

   Vserver:           vs1
   SID:               S-1-5-21-123456789-234565432-987654321-123456
   Domain:            EXAMPLE1
   Out-of-date Name:  dom_user3
   Updated Name:      dom_user4
   Status:            Successfully updated; also updated SID "S-1-5-21-123456789-234565432-987654321-123457"
                      to name "dom_user5"; also updated SID "S-1-5-21-123456789-234565432-987654321-123458"
                      to name "dom_user6"; also updated SID "S-1-5-21-123456789-234565432-987654321-123459"
                      to name "dom_user7"; also updated SID "S-1-5-21-123456789-234565432-987654321-123460"
                      to name "dom_user8"

The command completed successfully. 7 Active Directory objects have been updated.

cluster1::*> set -privilege admin
----
====
.관련 정보
에 대한 자세한 내용은 `vserver cifs` link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs["ONTAP 명령 참조입니다"^]을 참조하십시오.
