---
permalink: smb-admin/previous-versions-view-manage-snapshot-data-task.html 
sidebar: sidebar 
keywords: windows, client, machine, previous, version, tab, properties, restore, data, store, snapshot, copies, copy, storage, virtual, machine, svm, administrator, use the previous versions tab to view and manage snapshot copy data 
summary: 'Windows 클라이언트 시스템의 사용자는 Windows 속성 창의 이전 버전 탭을 사용하여 SVM(스토리지 가상 시스템) 관리자의 개입 없이 스냅샷에 저장된 데이터를 복원할 수 있습니다.' 
---
= 이전 버전 탭을 사용하여 스냅샷 데이터를 보고 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows 클라이언트 시스템의 사용자는 Windows 속성 창의 이전 버전 탭을 사용하여 SVM(스토리지 가상 시스템) 관리자의 개입 없이 스냅샷에 저장된 데이터를 복원할 수 있습니다.

.이 작업에 대해
관리자가 공유를 포함하는 볼륨에 스냅샷을 설정하고 관리자가 스냅샷을 표시하도록 공유를 구성한 경우에는 이전 버전 탭을 사용하여 SVM에 저장된 데이터의 스냅샷에서 데이터를 보고 관리할 수 있습니다.

.단계
. Windows 탐색기에서 CIFS 서버에 저장된 데이터의 매핑된 드라이브 컨텐츠를 표시합니다.
. 스냅샷을 보거나 관리할 매핑된 네트워크 드라이브에서 파일 또는 폴더를 마우스 오른쪽 단추로 클릭합니다.
. 속성 * 을 클릭합니다.
+
선택한 파일 또는 폴더의 속성이 표시됩니다.

. 이전 버전 * 탭을 클릭합니다.
+
선택한 파일 또는 폴더의 사용 가능한 스냅샷 목록이 폴더 버전: 상자에 표시됩니다. 나열된 스냅샷은 스냅샷 이름 접두사 및 생성 타임스탬프로 식별됩니다.

. 폴더 버전: * 상자에서 관리할 파일 또는 폴더의 복사본을 마우스 오른쪽 단추로 클릭합니다.
. 적절한 작업을 수행합니다.
+
|===
| 원하는 작업 | 다음을 수행합니다. 


 a| 
해당 스냅샷의 데이터를 봅니다
 a| 
열기 * 를 클릭합니다.



 a| 
해당 스냅샷에서 데이터 복제본을 생성합니다
 a| 
복사 * 를 클릭합니다.

|===
+
스냅샷의 데이터는 읽기 전용입니다. 이전 버전 탭에 나열된 파일과 폴더를 수정하려면 쓰기 가능한 위치에 수정할 파일 및 폴더의 복사본을 저장하고 복사본을 수정해야 합니다.

. 스냅샷 데이터 관리를 마친 후 * 확인 * 을 클릭하여 * 속성 * 대화 상자를 닫습니다.
+
이전 버전 탭을 사용하여 스냅샷 데이터를 보고 관리하는 방법에 대한 자세한 내용은 Microsoft TechNet 라이브러리를 참조하십시오.



.관련 정보
http://technet.microsoft.com/en-us/library/["Microsoft TechNet 라이브러리: technet.microsoft.com/en-us/library/"]
