---
permalink: smb-admin/security-styles-their-effects-concept.html 
sidebar: sidebar 
keywords: unix, ntfs, mixed, unified, security, style, effect, permission, handle, data, what the security styles and their effects are 
summary: 보안 스타일에는 UNIX, NTFS, 혼합, 통합의 네 가지 유형이 있습니다. 각 보안 스타일은 데이터 권한 처리 방식에 서로 다른 영향을 미칩니다. 목적에 맞는 적절한 보안 스타일을 선택하려면 이러한 차이점을 이해해야 합니다. 
---
= ONTAP SMB 보안 스타일과 그 영향에 대해 알아보십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead lead"]
UNIX, NTFS, 혼합 및 통합 등 네 가지 보안 유형이 있습니다. 각 보안 스타일은 데이터에 대한 사용 권한이 처리되는 방식에 다른 영향을 줍니다. 용도에 맞는 적절한 보안 스타일을 선택할 수 있도록 다양한 효과를 이해해야 합니다.

보안 스타일은 클라이언트 유형이 데이터에 액세스할 수 있거나 액세스할 수 없는 형식을 결정하지 않는다는 점을 이해하는 것이 중요합니다. 보안 스타일은 ONTAP에서 데이터 액세스를 제어하는 데 사용하는 권한 유형과 이러한 권한을 수정할 수 있는 클라이언트 유형만 결정합니다.

예를 들어, 볼륨이 UNIX 보안 스타일을 사용하는 경우에도 SMB 클라이언트는 ONTAP의 멀티 프로토콜 특성으로 인해 데이터에 액세스(적절하게 인증 및 승인)할 수 있습니다. 그러나 ONTAP에서는 UNIX 클라이언트만 기본 툴을 사용하여 수정할 수 있는 UNIX 권한을 사용합니다.

[cols="5"]
|===
| 보안 스타일 | 사용 권한을 수정할 수 있는 클라이언트입니다 | 클라이언트가 사용할 수 있는 권한 | 결과적으로 효율적인 보안 스타일을 제공합니다 | 파일에 액세스할 수 있는 클라이언트입니다 


| Unix | NFS 를 참조하십시오  a| 
* NFSv3 모드 비트
* NFSv4.x ACL

| Unix | NFS 및 SMB 


| NTFS입니다 | 중소기업 | NTFS ACL | NTFS입니다 | NFS 및 SMB 


| 혼합 | NFS 또는 SMB  a| 
* NFSv3 모드 비트
* NFSv4.x ACL
* NTFS ACL

 a| 
* UNIX(NFSv3 모드 비트 및 NFSv4.x ACL용)
* NTFS(NTFS ACL용)

| NFS 및 SMB 


| 통합(ONTAP 9.4 및 이전 릴리즈에서 무한 확장 볼륨에만 해당) | NFS 또는 SMB  a| 
* NFSv3 모드 비트
* NFSv4.1 ACL
* NTFS ACL

 a| 
* UNIX(NFSv3 모드 비트 및 NFSv4.1 ACL용)
* NTFS(NTFS ACL용)

| NFS 및 SMB 
|===
FlexVol 볼륨은 UNIX, NTFS 및 혼합 보안 스타일을 지원합니다. 보안 스타일이 혼합 또는 통합된 경우 사용자가 보안 스타일을 개별적으로 설정하므로 사용자가 마지막으로 권한을 수정한 클라이언트 유형에 따라 유효 사용 권한이 달라집니다. 권한을 수정한 마지막 클라이언트가 NFSv3 클라이언트인 경우 사용 권한은 UNIX NFSv3 모드 비트입니다. 마지막 클라이언트가 NFSv4 클라이언트인 경우 사용 권한은 NFSv4 ACL입니다. 마지막 클라이언트가 SMB 클라이언트인 경우 사용 권한은 Windows NTFS ACL입니다.

통합 보안 스타일은 ONTAP 9.5 이상 릴리스에서 더 이상 지원되지 않는 무한 볼륨에서만 사용할 수 있습니다. 자세한 내용은 을 참조하십시오 xref:../flexgroup/index.html[FlexGroup 볼륨 관리 개요].

그만큼  `show-effective-permissions` 매개변수를 사용하여  `vserver security file-directory` 명령을 사용하면 지정된 파일이나 폴더 경로에 대해 Windows 또는 UNIX 사용자에게 부여된 유효 권한을 표시할 수 있습니다. 또한 선택적 매개 변수를 `-share-name` 사용하면 효과적인 공유 권한을 표시할 수 있습니다. 에 대한 자세한 내용은 `vserver security file-directory show-effective-permissions` link:https://docs.netapp.com/us-en/ontap-cli/vserver-security-file-directory-show-effective-permissions.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

[NOTE]
====
ONTAP는 처음에 일부 기본 파일 권한을 설정합니다. 기본적으로 UNIX, 혼합 및 통합 보안 스타일 볼륨의 모든 데이터에 대한 효과적인 보안 스타일은 UNIX이고, 기본 보안 스타일에 의해 허용되는 대로 클라이언트에 의해 구성될 때까지 유효 사용 권한 유형은 UNIX 모드 비트(별도로 지정하지 않는 경우 0755)입니다. 기본적으로 NTFS 보안 스타일 볼륨의 모든 데이터에 대한 효과적인 보안 스타일은 NTFS이며 ACL을 통해 모든 사람에게 모든 권한을 제공할 수 있습니다.

====
.관련 정보
* link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP 명령 참조입니다"^]



NOTE: 보안 스타일은 FlexVol 볼륨(루트 볼륨 또는 데이터 볼륨 모두)과 qtree에 설정할 수 있습니다. 보안 스타일은 생성 시 수동으로 설정하거나, 자동으로 상속받거나, 나중에 변경할 수 있습니다. == ONTAP SVM에서 사용할 SMB 보안 스타일을 결정하세요

볼륨에 사용할 보안 스타일을 결정하는 데 도움이 되도록 두 가지 요소를 고려해야 합니다. 기본 요소는 파일 시스템을 관리하는 관리자 유형입니다. 2차 요소는 볼륨의 데이터에 액세스하는 사용자 또는 서비스의 유형입니다.

볼륨에 보안 스타일을 구성할 때는 최상의 보안 스타일을 선택하고 사용 권한 관리 문제를 피하기 위해 환경의 요구 사항을 고려해야 합니다. 다음 고려 사항을 통해 결정을 내릴 수 있습니다.

[cols="2,4"]
|===
| 보안 스타일 | 다음 경우에 선택... 


 a| 
Unix
 a| 
* 파일 시스템은 UNIX 관리자가 관리합니다.
* 대부분의 사용자는 NFS 클라이언트입니다.
* 데이터에 액세스하는 애플리케이션은 UNIX 사용자를 서비스 계정으로 사용합니다.




 a| 
NTFS입니다
 a| 
* 파일 시스템은 Windows 관리자가 관리합니다.
* 대부분의 사용자는 SMB 클라이언트입니다.
* 데이터에 액세스하는 응용 프로그램은 Windows 사용자를 서비스 계정으로 사용합니다.




 a| 
혼합
 a| 
파일 시스템은 UNIX 관리자와 Windows 관리자 모두에서 관리되며 사용자는 NFS 클라이언트와 SMB 클라이언트로 구성됩니다.

|===


== ONTAP SMB 보안 스타일 상속에 대해 알아보십시오

새 FlexVol 볼륨 또는 qtree를 생성할 때 보안 스타일을 지정하지 않으면 보안 스타일이 다른 방식으로 상속됩니다.

보안 스타일은 다음과 같은 방식으로 상속됩니다.

* FlexVol 볼륨은 SVM이 포함된 루트 볼륨의 보안 스타일을 상속합니다.
* qtree는 포함된 FlexVol 볼륨의 보안 스타일을 상속합니다.
* 파일 또는 디렉토리는 포함된 FlexVol 볼륨 또는 qtree의 보안 스타일을 상속합니다.

