---
permalink: mediator/host-maintenance-task.html 
sidebar: sidebar 
keywords: mediator, maintain, host, maintenance, package update, kernel upgrade, change hostname, change IP, self-signed certificate, self signed certificate 
summary: 최적의 성능을 위해 ONTAP Mediator의 호스트 OS를 정기적으로 유지 관리하세요. 
---
= ONTAP 중재자를 위한 호스트 OS를 유지 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
최적의 성능을 얻으려면 ONTAP Mediator의 호스트 OS를 정기적으로 유지 관리하세요.



== 호스트를 재부팅합니다

클러스터가 정상일 때만 호스트를 재부팅하세요. ONTAP Mediator가 오프라인인 동안에는 클러스터가 장애에 대응할 수 없습니다. 재부팅하기 전에 유지관리 시간을 설정하세요.

ONTAP Mediator는 재부팅 중에 자동으로 다시 시작되고 ONTAP 클러스터와 이전에 구성된 관계를 다시 입력합니다.



== 호스트 패키지 업데이트

커널을 제외한 모든 라이브러리나 yum 패키지를 업데이트합니다.  변경 사항을 적용하려면 필요한 경우 호스트를 재부팅하세요.  호스트를 재부팅하기 전에 서비스 창을 예약하세요.

를 설치하는 경우 `yum-utils` 패키지를 사용하려면 를 사용합니다 `needs-restarting` 명령을 사용하여 패키지 변경 사항을 탐지하려면 재부팅해야 합니다.

변경 사항이 즉시 적용되지 않으므로 ONTAP Mediator 종속성을 업데이트한 후 재부팅하세요.



== 호스트 OS 커널 업그레이드

SCST는 사용 중인 커널에 맞게 컴파일해야 합니다.  OS를 업데이트하려면 유지관리 시간을 예약해야 합니다.

.단계
호스트 OS 커널을 업그레이드하려면 다음 단계를 따르세요.


NOTE: 커널을 업그레이드하기 전에 OS와 ONTAP Mediator 버전이 호환되는지 확인하세요.  지원되는 버전은 다음을 참조하세요.link:whats-new-concept.html#os-support-matrix["OS 지원 매트릭스"] .

. ONTAP 중재자를 중단하세요.
. SCST 패키지를 제거하려면 다음을 참조하세요.<<호스트 유지관리 수행>> .  (SCST는 업그레이드 메커니즘을 제공하지 않습니다.)
. OS를 업그레이드하고 재부팅합니다.
. SCST 패키지를 다시 설치합니다.
. ONTAP Mediator를 다시 활성화합니다.




== 호스트 유지관리 수행

VM 커널을 업그레이드하면 SCST 모듈과의 호환성 문제가 발생할 수 있습니다.  SCST를 수동으로 제거했다가 다시 설치합니다.



=== 1단계: SCST 제거

SCST를 제거하려면 ONTAP Mediator 버전용 tar 번들을 사용하세요.

.단계
. 다음 표에 표시된 대로 적절한 SCST 번들을 다운로드하고 압축을 풉니다.
+
[cols="50,50"]
|===


| 이 버전의 경우... | 이 tar 번들을 사용합니다... 


 a| 
ONTAP 중재자 1.11
 a| 
scst-3.9.tar.gz



 a| 
ONTAP 중재자 1.10
 a| 
scst-3.9.tar.gz



 a| 
ONTAP 중재자 1.9.1
 a| 
scst-3.8.0.tar.bz2



 a| 
ONTAP 중재자 1.9
 a| 
scst-3.8.0.tar.bz2



 a| 
ONTAP 중재자 1.8
 a| 
scst-3.8.0.tar.bz2



 a| 
ONTAP 중재자 1.7
 a| 
scst - 3.7.0.tar.bz2



 a| 
ONTAP 중재자 1.6
 a| 
scst - 3.7.0.tar.bz2



 a| 
ONTAP 중재자 1.5
 a| 
scst - 3.6.0.tar.bz2



 a| 
ONTAP 중재자 1.4
 a| 
scst - 3.6.0.tar.bz2



 a| 
ONTAP 중재자 1.3
 a| 
scst - 3.5.0.tar.bz2



 a| 
ONTAP 중재자 1.1
 a| 
scst - 3.4.0.tar.bz2



 a| 
ONTAP 중재자 1.0
 a| 
scst - 3.3.0.tar.bz2

|===
+
.. 오픈 소스 패키지에 액세스하세요link:https://scst.sourceforge.net/downloads.html["SCST 소스포지 다운로드"^] .
.. *출시된 버전 다운로드*를 선택하세요.
.. 번들을 VM으로 추출합니다.


. 다음 제거 명령을 실행하세요. `scst` 예배 규칙서:
+
.. `systemctl stop mediator-scst`
.. `make scstadm_uninstall`
.. `make iscsi_uninstall`
.. `make usr_uninstall`
.. `make scst_uninstall`
.. `depmod`






=== 2단계: SCST 설치

SCST를 수동으로 설치하려면 ONTAP Mediator의 설치된 버전에 사용되는 SCST tar 번들이 필요합니다(참조).<<scst-bundle-table,SCST 테이블>> ).


NOTE: ONTAP Mediator를 설치하기 전에 이 단계를 수행하세요.  사용 중인 SCST 버전이 ONTAP Mediator 설치 프로그램과 함께 제공되는 버전보다 최신인 경우 설치 프로그램은 이 단계를 건너뜁니다.

. 다음 설치 명령을 실행하세요. `scst` 예배 규칙서:
+
.. `make 2release`
.. `make scst_install`
.. `make usr_install`
.. `make iscsi_install`
.. `make scstadm_install`
.. `depmod`
+
[NOTE]
====
처음으로 설치를 수행하고 ONTAP Mediator를 미리 설치하려면 다음 단계로 넘어가기 전에 다음 명령을 실행하세요.

`mkdir -p /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys`

====
.. `cp scst/src/certs/scst_module_key.der /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/`
.. `patch /etc/init.d/scst < /opt/netapp/lib/ontap_mediator/systemd/scst.patch`
+

NOTE: 처음 설치할 때 ONTAP Mediator보다 SCST를 먼저 설치한 경우 이 단계를 건너뜁니다.  설치 프로그램은 관련 SCST 패치를 적용합니다.



. 선택적으로 Secure Boot가 활성화되어 있는 경우 재부팅하기 전에 다음 단계를 수행하십시오.
+
.. 각 파일 이름을 결정하세요 `scst_vdisk` , `scst` , 그리고 `iscsi_scst` 모듈:
+
....
[root@localhost ~]# modinfo -n scst_vdisk
[root@localhost ~]# modinfo -n scst
[root@localhost ~]# modinfo -n iscsi_scst
....
.. 커널 릴리스를 확인합니다.
+
....
[root@localhost ~]# uname -r
....
.. 각 모듈 파일에 커널을 서명합니다.
+
....
[root@localhost ~]# /usr/src/kernels/<KERNEL-RELEASE>/scripts/sign-file \sha256 \
/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/scst_module_key.priv \
/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/scst_module_key.der \
_module-filename_
....
.. 펌웨어와 함께 UEFI 키를 설치합니다.
+
UEFI 키 설치 지침은 다음 웹 사이트에서 확인할 수 있습니다.

+
`/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/README.module-signing`

+
생성된 UEFI 키는 다음 위치에 있습니다.

+
`/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/scst_module_key.der`



. 시스템을 재부팅하세요:
+
`reboot`





== 호스트가 호스트 이름 또는 IP로 변경됩니다

.이 작업에 대해
* ONTAP Mediator를 설치한 Linux 호스트에서 이 작업을 수행합니다.
* ONTAP Mediator를 설치한 후 호스트 이름이나 IP 주소가 변경되어 자체 서명 인증서가 더 이상 유효하지 않은 경우에만 이 작업을 수행하세요.
* 임시 자체 서명 인증서가 신뢰할 수 있는 타사 인증서로 대체된 후에는 이 작업을 사용하여 인증서를 다시 생성할 수 없습니다.  자체 서명된 인증서가 없으면 이 절차를 사용할 수 없습니다.


.단계
현재 호스트에 대한 임시 자체 서명 인증서를 만듭니다.

. ONTAP Mediator를 다시 시작하세요:
+
`./make_self_signed_certs.sh overwrite`

+
[listing]
----
[root@xyz000123456 ~]# cd /opt/netapp/lib/ontap_mediator/ontap_mediator/server_config
[root@xyz000123456 server_config]# ./make_self_signed_certs.sh overwrite

Adding Subject Alternative Names to the self-signed server certificate
#
# OpenSSL example configuration file.
Generating self-signed certificates
Generating RSA private key, 4096 bit long modulus (2 primes)
..................................................................................................................................................................++++
........................................................++++
e is 65537 (0x010001)
Generating a RSA private key
................................................++++
.............................................................................................................................................++++
writing new private key to 'ontap_mediator_server.key'
-----
Signature ok
subject=C = US, ST = California, L = San Jose, O = "NetApp, Inc.", OU = ONTAP Core Software, CN = ONTAP Mediator, emailAddress = support@netapp.com
Getting CA Private Key

[root@xyz000123456 server_config]# systemctl restart ontap_mediator
----

