---
permalink: mediator/upgrade-host-os-mediator-task.html 
sidebar: sidebar 
keywords: mediator, new, release, update, install, 
summary: 설치 프로세스의 일부로 호스트 운영 체제를 업그레이드한 다음 ONTAP 중재자를 업그레이드합니다. 
---
= 호스트 OS 및 ONTAP 중재자를 업그레이드합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 중재자를 위한 호스트 OS를 최신 버전으로 업그레이드하려면 먼저 ONTAP 중재자를 제거해야 합니다.

.이 작업에 대해
leapp 업그레이드 도구를 사용하여 ONTAP 중재자를 최신 주요 버전(예: 7.x에서 8.x)으로 업그레이드하는 경우 도구가 시스템에 등록된 리포지토리에 설치된 RPM의 새 버전을 감지하기 때문에 ONTAP 중재자를 제거해야 합니다.

rpm 파일은 ONTAP 중재자 설치 프로그램의 일부로 설치되었기 때문에 해당 검색에 포함됩니다. 그러나 .rpm 파일은 설치 프로그램의 일부로 압축 해제되었고 등록된 리포지토리에서 다운로드되지 않았으므로 업그레이드를 찾을 수 없습니다. 이 경우 leapp-upgrade 도구가 패키지를 제거합니다.

지원 사례를 분류하는 데 사용될 로그 파일을 보존하려면 OS를 업그레이드하기 전에 파일을 백업하고 ONTAP Mediator 패키지를 다시 설치한 후 복원해야 합니다. ONTAP Mediator 에 연결된 ONTAP 클러스터는 ONTAP Mediator 설치 후 다시 연결해야 합니다.


NOTE: 다음 단계를 순서대로 수행해야 합니다. ONTAP Mediator를 다시 설치한 직후 ontap_mediator를 중지하고 로그 파일을 교체한 후 다시 시작해야 합니다. 이는 로그가 손실되지 않도록 하기 위한 조치입니다.

.단계
. 로그 파일을 백업합니다.
+
....
[rootmediator-host ~]# tar -czf ontap_mediator_file_backup.tgz -C /opt/netapp/lib/ontap_mediator ./log ./ontap_mediator/server_config/ontap_mediator.user_config.yaml
[rootmediator-host ~]# tar -tf ontap_mediator_file_backup.tgz
./log/
./log/ontap_mediator.log
./log/scstadmin.log
./log/ontap_mediator_stdout.log
./log/ontap_mediator_requests.log
./log/install_20230419134611.log
./log/scst.log
./log/ontap_mediator_syslog.log
./ontap_mediator/server_config/ontap_mediator.user_config.yaml
[rootmediator-host ~]#
....
. leapp-upgrade 툴을 사용하여 업그레이드를 수행합니다.
+
....
[rootmediator-host ~]# leapp preupgrade --target 8.4
  ..<snip upgrade checks>..
  ..<fix issues found>..
[rootmediator-host ~]# leapp upgrade --target 8.4
  ..<snip upgrade>..
[rootmediator-host ~]# cat /etc/os-release | head -2
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
[rootmediator-host ~]#
....
. ONTAP 중재자를 다시 설치합니다.
+

NOTE: 로그 파일 손실을 방지하기 위해 ONTAP 중재자를 재설치한 후 바로 나머지 단계를 수행하십시오.

+
....
[rootmediator-host ~]# ontap-mediator-1.10/ontap-mediator-1.10

ONTAP Mediator: Self Extracting Installer

  ..<snip installation>..
[rootmediator-host ~]#
....
. ontap_mediator를 중지합니다.
+
....
[rootmediator-host ~]# systemctl stop ontap_mediator
[rootmediator-host ~]#
....
. 로그 파일을 교체합니다.
+
....
[rootmediator-host ~]# tar -xf ontap_mediator_log_backup.tgz -C /opt/netapp/lib/ontap_mediator
[rootmediator-host ~]#
....
. ontap_mediator를 시작합니다.
+
....
[rootmediator-host ~]# systemctl start ontap_mediator
[rootmediator-host ~]#
....
. 모든 ONTAP 클러스터를 업그레이드된 ONTAP 중재자로 다시 연결합니다
+
.IP를 통한 MetroCluster 절차
[%collapsible]
====
....
siteA::> metrocluster configuration-settings mediator show
Mediator IP     Port    Node                    Configuration Connection
                                                Status        Status
--------------- ------- ----------------------- ------------- -----------
172.31.40.122
                31784   siteA-node2             true          false
                        siteA-node1             true          false
                        siteB-node2             true          false
                        siteB-node2             true          false
siteA::> metrocluster configuration-settings mediator remove
Removing the mediator and disabling Automatic Unplanned Switchover. It may take a few minutes to complete.
Please enter the username for the mediator: mediatoradmin
Please enter the password for the mediator:
Confirm the mediator password:
Automatic Unplanned Switchover is disabled for all nodes...
Removing mediator mailboxes...
Successfully removed the mediator.

siteA::> metrocluster configuration-settings mediator add -mediator-address 172.31.40.122
Adding the mediator and enabling Automatic Unplanned Switchover. It may take a few minutes to complete.
Please enter the username for the mediator: mediatoradmin
Please enter the password for the mediator:
Confirm the mediator password:
Successfully added the mediator.

siteA::> metrocluster configuration-settings mediator show
Mediator IP     Port    Node                    Configuration Connection
                                                Status        Status
--------------- ------- ----------------------- ------------- -----------
172.31.40.122
                31784   siteA-node2             true          true
                        siteA-node1             true          true
                        siteB-node2             true          true
                        siteB-node2             true          true
siteA::>
....
====
+
.SnapMirror 활성 동기화 절차
[%collapsible]
====
SnapMirror 액티브 동기화의 경우 /opt/netapp 디렉토리 외부에 TLS 인증서를 설치한 경우 다시 설치할 필요가 없습니다. 기본 생성 자체 서명 인증서를 사용하거나 /opt/NetApp 디렉토리에 사용자 지정 인증서를 저장한 경우 해당 인증서를 백업 및 복원해야 합니다.

....
peer1::> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
172.31.49.237    peer2            unreachable       true

peer1::> snapmirror mediator remove -mediator-address 172.31.49.237 -peer-cluster peer2

Info: [Job 39] 'mediator remove' job queued

peer1::> job show -id 39
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
39     mediator remove      peer1      peer1-node1    Success
     Description: Removing entry in mediator

peer1::> security certificate show -common-name ONTAPMediatorCA
Vserver    Serial Number   Certificate Name                       Type
---------- --------------- -------------------------------------- ------------
peer1
        4A790360081F41145E14C5D7CE721DC6C210007F
                        ONTAPMediatorCA                        server-ca
    Certificate Authority: ONTAP Mediator CA
        Expiration Date: Mon Apr 17 10:27:54 2073

peer1::> security certificate delete -common-name ONTAPMediatorCA *
1 entry was deleted.

 peer1::> security certificate install -type server-ca -vserver peer1

Please enter Certificate: Press <Enter> when done
  ..<snip ONTAP Mediator CA public key>..

You should keep a copy of the CA-signed digital certificate for future reference.

The installed certificate's CA and serial number for reference:
CA: ONTAP Mediator CA
serial: 44786524464C5113D5EC966779D3002135EA4254

The certificate's generated name for reference: ONTAPMediatorCA

peer2::> security certificate delete -common-name ONTAPMediatorCA *
1 entry was deleted.

peer2::> security certificate install -type server-ca -vserver peer2

 Please enter Certificate: Press <Enter> when done
..<snip ONTAP Mediator CA public key>..


You should keep a copy of the CA-signed digital certificate for future reference.

The installed certificate's CA and serial number for reference:
CA: ONTAP Mediator CA
serial: 44786524464C5113D5EC966779D3002135EA4254

The certificate's generated name for reference: ONTAPMediatorCA

peer1::> snapmirror mediator add -mediator-address 172.31.49.237 -peer-cluster peer2 -username mediatoradmin

Notice: Enter the mediator password.

Enter the password:
Enter the password again:

Info: [Job: 43] 'mediator add' job queued

peer1::> job show -id 43
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
43     mediator add         peer1      peer1-node2    Success
    Description: Creating a mediator entry

peer1::> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
172.31.49.237    peer2            connected         true

peer1::>

....
====


.관련 정보
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-delete.html["보안 인증서 삭제"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-install.html["보안 인증서 설치"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-show.html["보안 인증서가 표시됩니다"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-mediator-add.html["스냅미러 중재자 추가"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-mediator-remove.html["스냅미러 중재자 제거"^]

