---
permalink: mediator/verify-code-signature-task.html 
sidebar: sidebar 
keywords: mediator, new, release, update, install, verify, code, signature 
summary: 중재자 설치 패키지를 설치하기 전에 ONTAP 중재자 코드 서명을 확인해야 합니다. 
---
= ONTAP 중재자 코드 서명을 확인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp 설치 전에 ONTAP Mediator 코드 서명을 확인할 것을 권장합니다. 이 단계는 선택 사항입니다.

.시작하기 전에
ONTAP Mediator 코드 서명을 확인하기 전에 시스템이 이러한 요구 사항을 충족하는지 확인하세요.

[NOTE]
====
* 2025년 6월 15일부터 코드 서명 검증 인증서가 만료되어 ONTAP Mediator 1.9 및 1.8를 설치하거나 업그레이드할 수 없습니다. 대신 ONTAP Mediator 1.11 또는 1.10을 설치하거나 업그레이드하세요.
* 시스템이 아래 요구 사항을 충족하지 않는 경우 확인 프로세스가 필요하지 않으며 로 직접 이동할 수 있습니다link:install-mediator-pkg-task.html["ONTAP 중재자 설치 패키지를 설치합니다"].


====
* 기본 검증을 위한 OpenSSL 버전 1.0.2에서 3.0까지
* TSA(Time Stamping Authority) 작업을 위한 OpenSSL 버전 1.1.0 이상
* OCSP 검증을 위한 공용 인터넷 액세스


다운로드 패키지에는 다음 파일이 포함되어 있습니다.

[cols="50,50"]
|===


| 파일 | 설명 


 a| 
`ONTAP-Mediator-production.pub`
 a| 
서명을 확인하는 데 사용되는 공개 키입니다



 a| 
`csc-prod-chain-ONTAP-Mediator.pem`
 a| 
공공 인증 CA 신뢰 체인



 a| 
`csc-prod-ONTAP-Mediator.pem`
 a| 
키를 생성하는 데 사용되는 인증서입니다



 a| 
`ontap-mediator-1.11.0`
 a| 
버전 1.11에 대한 제품 설치 실행 파일



 a| 
`ontap-mediator-1.11.0.sig`
 a| 
SHA-256 해시된 후 csc-prod 키를 사용하여 RSA에 서명하여 설치 관리자를 서명합니다



 a| 
`ontap-mediator-1.11.0.sig.tsr`
 a| 
설치 관리자의 서명에 OCSCP가 사용할 해지 요청입니다



 a| 
`ontap-mediator-1.11.0.tsr`
 a| 
타임스탬프 서명 요청 파일입니다



 a| 
`tsa-prod-ONTAP-Mediator.pem`
 a| 
TSR의 공개 인증서



 a| 
`tsa-prod-chain-ONTAP-Mediator.pem`
 a| 
TSR의 공개 인증서 CA 체인

|===
.단계
. 에 대해 해지 확인을 수행합니다 `csc-prod-ONTAP-Mediator.pem` 온라인 인증서 상태 프로토콜(OCSP)을 사용합니다.
+
.. 인증서의 OCSP URL을 찾으세요.  개발자 인증서는 URI를 제공하지 않을 수 있습니다.
+
[listing]
----
openssl x509 -noout -ocsp_uri -in csc-prod-chain-ONTAP-Mediator.pem
----
.. 인증서에 대한 OCSP 요청을 생성합니다.
+
[listing]
----
openssl ocsp -issuer csc-prod-chain-ONTAP-Mediator.pem -CAfile csc-prod-chain-ONTAP-Mediator.pem -cert csc-prod-ONTAP-Mediator.pem  -reqout req.der
----
.. OCSP Manager에 연결하여 OCSP 요청을 보냅니다.
+
[listing]
----
openssl ocsp -issuer csc-prod-chain-ONTAP-Mediator.pem -CAfile csc-prod-chain-ONTAP-Mediator.pem -cert csc-prod-ONTAP-Mediator.pem  -url ${ocsp_uri} -resp_text -respout resp.der -verify_other csc-prod-chain-ONTAP-Mediator.pem
----


. CSC의 신뢰 체인과 로컬 호스트에 대한 만료 날짜를 확인합니다.
+
`openssl verify`

+

NOTE: 를 클릭합니다 `openssl` 경로의 버전에 유효한 값이 있어야 합니다 `cert.pem` (자체 서명 안 됨).

+
[listing]
----
openssl verify -untrusted csc-prod-chain-ONTAP-Mediator.pem -CApath ${OPENSSLDIR} csc-prod-ONTAP-Mediator.pem  # Failure action: The Code-Signature-Check certificate has expired or is invalid. Download a newer version of the ONTAP Mediator.
openssl verify -untrusted tsa-prod-chain-ONTAP-Mediator.pem -CApath ${OPENSSLDIR} tsa-prod-ONTAP-Mediator.pem  # Failure action: The Time-Stamp certificate has expired or is invalid. Download a newer version of the ONTAP Mediator.
----
. 확인하다 `ontap-mediator-1.11.0.sig.tsr` 그리고 `ontap-mediator-1.11.0.tsr` 연관된 인증서를 사용하는 파일:
+
[role="tabbed-block"]
====
.오픈SSL 3.x
--
`openssl ts -verify -data ontap-mediator-1.11.0.sig -in ontap-mediator-1.11.0.sig.tsr -CAfile tsa-prod-chain-ONTAP-Mediator.pem -untrusted tsa-prod-ONTAP-Mediator.pem`

--
.오픈SSL 1.x
--
`openssl ts -verify -data ontap-mediator-1.11.0 -in ontap-mediator-1.11.0.tsr -CAfile tsa-prod-chain-ONTAP-Mediator.pem -partial_chain`

--
====
+

NOTE: `.tsr`파일에는 설치 프로그램과 관련된 타임스탬프 응답과 코드 서명이 포함되어 있습니다.  처리 과정에서는 타임스탬프에 TSA의 유효한 서명이 있고 입력 파일이 변경되지 않았음을 확인합니다.  귀하의 기기는 로컬에서 검증을 수행합니다.  TSA 서버에 접속할 필요가 없습니다.

. 키에 대한 서명 확인:
+
`openssl -dgst -verify`

+
[listing]
----
openssl dgst -sha256 -verify ONTAP-Mediator-production.pub -signature ontap-mediator-1.11.0.sig ontap-mediator-1.11.0
----

