---
sidebar: sidebar 
permalink: data-protection/cloud-backup-using-cbs-task.html 
keywords: cloud, data, backup, back up, storage, volume, lun, connector, secret key, access key, bluexp back and recovery service, Cloud Backup service, CBS, restore data, protect volumes, ipspace, storagegrid, storage grid, archive, archival, archiving, cost, calculator, glacier, deep archive 
summary: ONTAP 9.19.1부터 System Manager는 NetApp Backup and Recovery 서비스를 사용하여 클라우드에 데이터를 백업하는 것을 더 이상 지원하지 않습니다. 대신 NetApp Console을 사용하여 NetApp Backup and Recovery 서비스를 구성하고 클라우드 대상에 대한 SnapMirror 관계를 생성해야 합니다. 
---
= NetApp Backup and Recovery를 사용하여 데이터 백업
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 9.19.1부터 System Manager는 NetApp Backup and Recovery 서비스를 사용하여 클라우드에 데이터를 백업하는 것을 더 이상 지원하지 않습니다. 대신 NetApp Console을 사용하여 NetApp Backup and Recovery 서비스를 구성하고 클라우드 대상에 대한 SnapMirror 관계를 생성해야 합니다.

백업 및 복구는 FlexVol 읽기-쓰기 볼륨과 데이터 보호(DP) 볼륨을 지원합니다.  ONTAP 9.12.1부터 백업 및 복구는 FlexGroup 볼륨과 SnapLock 볼륨을 지원합니다.

자세히 알아보세요 link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["NetApp 백업 및 복구"^] .

.시작하기 전에
NetApp Console에서 계정을 설정하려면 다음 절차를 수행해야 합니다. 서비스 계정의 경우 "Account Admin" 역할을 생성해야 합니다.

. link:https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html["NetApp 콘솔에서 계정 만들기"^] .
. link:https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html["NetApp 콘솔에서 콘솔 에이전트 만들기"^]다음 클라우드 공급자 중 하나와 함께:
+
** Microsoft Azure를 참조하십시오
** AWS(Amazon Web Services)
** Google Cloud Platform(GCP)
** StorageGRID(ONTAP 9.10.1)
+

NOTE: ONTAP 9.10.1부터 NetApp 콘솔이 온프레미스에 배포된 경우에만 StorageGRID 클라우드 백업 공급자로 선택할 수 있습니다.  콘솔 에이전트는 온프레미스에 설치해야 하며 NetApp 콘솔 SaaS(Software-as-a-Service) 애플리케이션을 통해 사용할 수 있어야 합니다.



. link:https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["NetApp 콘솔에서 NetApp 백업 및 복구 구독"^](적절한 라이센스가 필요합니다).
. link:https://docs.netapp.com/us-en/console-setup-admin/concept-identity-and-access-management.html["NetApp 콘솔을 사용하여 액세스 키와 비밀 키 생성"^] .




== NetApp Console과 NetApp Backup and Recovery를 사용하여 ONTAP 백업을 관리하세요

ONTAP 9.19.1부터 System Manager는 NetApp Backup and Recovery를 더 이상 지원하지 않습니다. link:https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-backup-manage.html["NetApp Backup and Recovery를 사용하여 ONTAP 시스템의 백업을 관리하세요"^]에서 NetApp Console과 함께 NetApp Backup and Recovery를 사용하는 방법에 대한 자세한 내용을 참조하십시오.



== 백업 파일에서 데이터를 복원합니다

데이터 복원, 관계 업데이트, 관계 삭제 등의 백업 관리 작업은 NetApp 콘솔을 사용하는 경우에만 수행할 수 있습니다. . link:https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-backup-manage.html["백업 파일에서 데이터를 복원합니다"^] 자세한 내용은.
