---
permalink: data-protection/define-rule-policy-task.html 
sidebar: sidebar 
keywords: define, rule, policy, data protection 
summary: '"볼트" 또는 "볼트 대칭 복사" 정책 유형의 사용자 정의 정책의 경우 초기화 및 업데이트 중에 전송되는 스냅샷을 결정하는 규칙을 하나 이상 정의해야 합니다. "볼트" 또는 "볼트 대칭 복사" 정책 유형으로 기본 정책에 대한 규칙을 정의할 수도 있습니다.' 
---
= ONTAP SnapMirror 정책에 대한 규칙을 정의합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
또는 `mirror-vault` 정책 유형을 사용하는 사용자 지정 정책의 경우 `vault` 초기화 및 업데이트 중에 전송되는 스냅샷을 결정하는 규칙을 하나 이상 정의해야 합니다. 또는 `mirror-vault` 정책 유형을 사용하여 기본 정책에 대한 규칙을 정의할 수도 `vault` 있습니다.

.이 작업에 대해
또는 `mirror-vault` 정책 유형을 사용하는 모든 정책에는 `vault` 복제할 스냅샷을 지정하는 규칙이 있어야 합니다. 예를 들어 이 규칙은 `bi-monthly` SnapMirror 레이블이 할당된 스냅샷만 복제해야 함을 `bi-monthly` 나타냅니다. 소스에서 스냅샷 정책을 구성할 때 SnapMirror 레이블을 지정합니다.

각 정책 유형은 하나 이상의 시스템 정의 규칙과 연결됩니다. 이러한 규칙은 정책 유형을 지정할 때 정책에 자동으로 할당됩니다. 아래 표에는 시스템 정의 규칙이 나와 있습니다.

[cols="3*"]
|===


| 시스템 정의 규칙 | 정책 유형에 사용됩니다 | 결과 


 a| 
SM_생성됨
 a| 
비동기 미러, 미러 볼트, 동기화, StrictSync
 a| 
SnapMirror에 의해 생성된 스냅샷은 초기화 및 업데이트 시 전송됩니다.



 a| 
ALL_SOURCE_SNAPSHOTS 를 선택합니다
 a| 
비동기식 - 미러
 a| 
초기화 및 업데이트 시 소스의 새 스냅샷이 전송됩니다.



 a| 
매일
 a| 
볼트, 미러 볼트
 a| 
초기화 및 업데이트 시 SnapMirror 레이블이 있는 소스의 새 스냅샷이 `daily` 전송됩니다.



 a| 
매주
 a| 
볼트, 미러 볼트
 a| 
초기화 및 업데이트 시 SnapMirror 레이블이 있는 소스의 새 스냅샷이 `weekly` 전송됩니다.



 a| 
매월
 a| 
대칭 복사 - 볼트
 a| 
초기화 및 업데이트 시 SnapMirror 레이블이 있는 소스의 새 스냅샷이 `monthly` 전송됩니다.



 a| 
app_consistent
 a| 
동기화, StrictSync
 a| 
소스에 SnapMirror 레이블이 있는 스냅샷은 `app_consistent` 동기식으로 대상에 복제됩니다. ONTAP 9.7부터 지원됩니다.

|===
""비동기 미러" 정책 유형을 제외하고 필요에 따라 기본 또는 사용자 지정 정책에 대한 추가 규칙을 지정할 수 있습니다. 예를 들면 다음과 같습니다.

* 기본 정책의 경우 `MirrorAndVault` 소스의 스냅샷을 SnapMirror 레이블과 일치시키기 위해 `bi-monthly` 이라는 규칙을 생성할 수 `bi-monthly` 있습니다.
* 정책 유형이 지정된 사용자 지정 정책의 경우 `mirror-vault` 소스의 스냅숏을 SnapMirror 레이블과 일치시키기 위해 `bi-weekly` 이라는 규칙을 만들 수 `bi-weekly` 있습니다.


.단계
. 정책의 규칙 정의:
+
'스냅샷 정책 추가 규칙 -vserver_SVM_-policy_policy_for_rule_-snapmirror-label_snapmirror-label_-keep_retention_count_'

+
에 대한 자세한 내용은 `snapmirror policy add-rule` link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-add-rule.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

+
다음 예제에서는 기본 MirorAndVault 정책에 SnapMirror 레이블 '격월'이 있는 규칙을 추가합니다.

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy MirrorAndVault -snapmirror-label bi-monthly -keep 6
----
+
다음 예에서는 사용자 지정 my_SnapVault 정책에 SnapMirror 레이블 "격주"가 포함된 규칙을 추가합니다.

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy my_snapvault -snapmirror-label bi-weekly -keep 26
----
+
다음 예에서는 사용자 지정 'Sync' 정책에 SnapMirror 레이블 'app_consistent'가 포함된 규칙을 추가합니다.

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy Sync -snapmirror-label app_consistent -keep 1
----
+
그런 다음 이 SnapMirror 레이블과 일치하는 소스 클러스터에서 스냅샷을 복제할 수 있습니다.

+
[listing]
----
cluster_src::> snapshot create -vserver vs1 -volume vol1 -snapshot snapshot1 -snapmirror-label app_consistent
----

