---
permalink: data-protection/delete-svm-replication-relationship-task.html 
sidebar: sidebar 
keywords: delete, svm, replication, relationship 
summary: SnapMirror delete 및 SnapMirror 릴리즈 명령을 사용하여 SVM 복제 관계를 삭제할 수 있습니다. 그런 다음 불필요한 대상 볼륨을 수동으로 삭제할 수 있습니다. 
---
= ONTAP SVM 복제 관계를 삭제합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
및 `snapmirror release` 명령을 사용하여 SVM 복제 관계를 삭제할 수 있습니다 `snapmirror delete`. 그런 다음 불필요한 대상 볼륨을 수동으로 삭제할 수 있습니다. 이 절차에서 설명하는 명령에 대한 자세한 내용은 를 link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP 명령 참조입니다"^]참조하십시오.

.이 작업에 대해
이 `snapmirror release` 명령은 SnapMirror에서 생성된 스냅샷을 소스에서 삭제합니다. 옵션을 사용하여 스냅샷을 보존할 수 `-relationship-info-only` 있습니다.

.단계
. 타겟 SVM 또는 타겟 클러스터에서 다음 명령을 실행하여 복제 관계를 중단하십시오.
+
'스냅미러 break-source-path_SVM_:-destination-path_SVM_:'

+
[NOTE]
====
'-source-path' 및 '-destination-path' 옵션에서 SVM 이름 뒤에 콜론(:)을 입력해야 합니다. 아래 예를 참조하십시오.

====
+
다음 예에서는 소스 SVM의 vm1과 대상 SVM의 vm_backup 간의 관계를 나눕니다.

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm1: -destination-path svm_backup:
----
+
에 대한 자세한 내용은 `snapmirror break` link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-break.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

. 타겟 SVM 또는 타겟 클러스터에서 다음 명령을 실행하여 복제 관계를 삭제합니다.
+
'스냅샷 삭제-소스-경로_SVM_:-대상-경로_SVM_:'

+
[NOTE]
====
'-source-path' 및 '-destination-path' 옵션에서 SVM 이름 뒤에 콜론(:)을 입력해야 합니다. 아래 예를 참조하십시오.

====
+
다음 예에서는 소스 SVM의 vm1과 대상 SVM의 vm_backup 간의 관계를 삭제합니다.

+
[listing]
----
cluster_dst::> snapmirror delete -source-path svm1: -destination-path svm_backup:
----
+
에 대한 자세한 내용은 `snapmirror delete` link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

. 소스 클러스터 또는 소스 SVM에서 다음 명령을 실행하여 소스 SVM에서 복제 관계 정보를 해제합니다.
+
'스냅미러 해제 - source-path_SVM_: - destination-path_SVM_:'

+
[NOTE]
====
'-source-path' 및 '-destination-path' 옵션에서 SVM 이름 뒤에 콜론(:)을 입력해야 합니다. 아래 예를 참조하십시오.

====
+
다음 예에서는 소스 SVM의 vm1에서 지정된 복제 관계에 대한 정보를 해제합니다.

+
[listing]
----
cluster_src::> snapmirror release -source-path svm1: -destination-path svm_backup:
----
+
에 대한 자세한 내용은 `snapmirror release` link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["ONTAP 명령 참조입니다"^]을 참조하십시오.


