---
permalink: data-protection/delete-volume-replication-relationship-task.html 
sidebar: sidebar 
keywords: delete, volume, replication, relationship, replicate, synchronous, snapmirror, quiese, pause 
summary: SnapMirror 삭제 및 SnapMirror 릴리즈 명령을 사용하여 볼륨 복제 관계를 삭제할 수 있습니다. 그런 다음 불필요한 대상 볼륨을 수동으로 삭제할 수 있습니다. 
---
= ONTAP와의 볼륨 복제 관계를 삭제합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
및 `snapmirror release` 명령을 사용하여 볼륨 복제 관계를 삭제할 수 `snapmirror delete` 있습니다. 그런 다음 불필요한 대상 볼륨을 수동으로 삭제할 수 있습니다. 이 절차에서 설명하는 명령에 대한 자세한 내용은 를 link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP 명령 참조입니다"^]참조하십시오.

.이 작업에 대해
이 `snapmirror release` 명령은 SnapMirror에서 생성된 스냅샷을 소스에서 삭제합니다. 옵션을 사용하여 스냅샷을 보존할 수 `-relationship-info-only` 있습니다.

.단계
. 복제 관계를 중지합니다.
+
`snapmirror quiesce -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
[listing]
----
cluster_dst::> snapmirror quiesce -destination-path svm_backup:volA_dst
----
+
에 대한 자세한 내용은 `snapmirror quiesce` link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

. (선택 사항) 대상 볼륨이 읽기/쓰기 볼륨이어야 하는 경우 복제 관계를 끊으십시오. 대상 볼륨을 삭제할 계획이거나 읽기/쓰기가 필요한 볼륨이 없는 경우 이 단계를 건너뛸 수 있습니다.
+
`snapmirror break -source-path <SVM:volume>|<cluster://SVM/volume>, …​ -destination-path <SVM:volume>|<cluster://SVM/volume>, …​`

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm1:volA -destination-path svm_backup:volA_dst
----
+
에 대한 자세한 내용은 `snapmirror break` link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-break.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

. 복제 관계를 삭제합니다.
+
`snapmirror delete -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ...`

+
[NOTE]
====
대상 클러스터 또는 대상 SVM에서 이 명령을 실행해야 합니다.

====
+
다음 예에서는 svm1의 소스 볼륨 VolA와 sm_backup의 대상 볼륨 VolA_dst 간의 관계를 삭제합니다.

+
[listing]
----
cluster_dst::> snapmirror delete -source-path svm1:volA -destination-path svm_backup:volA_dst
----
+
에 대한 자세한 내용은 `snapmirror delete` link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

. 소스 SVM에서 복제 관계 정보 해제:
+
`snapmirror release -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ...`

+
[NOTE]
====
소스 클러스터 또는 소스 SVM에서 이 명령을 실행해야 합니다.

====
+
다음 예에서는 소스 SVM의 vm1에서 지정된 복제 관계에 대한 정보를 해제합니다.

+
[listing]
----
cluster_src::> snapmirror release -source-path svm1:volA -destination-path svm_backup:volA_dst
----
+
에 대한 자세한 내용은 `snapmirror release` link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["ONTAP 명령 참조입니다"^]을 참조하십시오.


