---
permalink: data-protection/example-configure-vault-vault-cascade-task.html 
sidebar: sidebar 
keywords: example, configure, vault-vault, cascade 
summary: '한 번에 한 단계씩 복제 관계를 구성하는 방법을 구체적으로 보여 주는 예가 나와 있습니다. 예제에 구성된 볼트-볼트 캐스케이드 배포를 사용하여 "y-weekly"라는 레이블이 붙은 251개 이상의 스냅샷을 보존할 수 있습니다.' 
---
= 예: 볼트-볼트 계단식 배열 설정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
한 번에 한 단계씩 복제 관계를 구성하는 방법을 구체적으로 보여 주는 예가 나와 있습니다. 이 예제에서 구성한 볼트-볼트 캐스케이드 배포를 사용하여 라벨이 붙은 251개 이상의 스냅샷을 보존할 수 `my-weekly` 있습니다.

.시작하기 전에
* 소스 및 타겟 클러스터와 SVM을 피어링해야 합니다.
* ONTAP 9.2 이상을 실행해야 합니다. 볼트 볼트 볼트 계단식 전환은 이전 ONTAP 릴리즈에서 지원되지 않습니다.


.이 작업에 대해
이 예제에서는 다음을 가정합니다.

* 소스 클러스터에 SnapMirror 레이블, `my-weekly` 및 `my-monthly` 을 사용하여 스냅샷을 구성했습니다. `my-daily`
* 2차 및 3차 대상 클러스터에 이라는 대상 볼륨을 구성했습니다. `volA`
* 2차 및 3차 대상 클러스터에서 이름이 지정된 복제 작업 일정을 구성했습니다. `my_snapvault`


이 예에서는 두 개의 사용자 지정 정책을 기반으로 복제 관계를 생성하는 방법을 보여 줍니다.

* 이 `snapvault_secondary` 정책은 2차 대상 클러스터에 매일 7개, 주별 52개 및 월별 180개의 스냅샷을 보존합니다.
* 는 `snapvault_tertiary policy` 3차 대상 클러스터에 매주 250개의 스냅샷을 보존합니다.


.단계
. 보조 대상 클러스터에서 정책을 생성합니다 `snapvault_secondary`.
+
`cluster_secondary::> snapmirror policy create -policy snapvault_secondary -type vault -comment "Policy on secondary for vault to vault cascade" -vserver svm_secondary`

. 보조 대상 클러스터에서 정책에 대한 규칙을 정의합니다 `my-daily`.
+
'cluster_secondary::> snapmirror policy add-rule-policy snapvault_secondary-snapmirror-label my-daily-keep 7-vserver svm_secondary'

. 보조 대상 클러스터에서 정책에 대한 규칙을 정의합니다 `my-weekly`.
+
'cluster_secondary::> snapmirror policy add-rule-policy snapvault_secondary-snapmirror-label my-weekly-keep 52-vserver svm_secondary'

. 보조 대상 클러스터에서 정책에 대한 규칙을 정의합니다 `my-monthly`.
+
'cluster_secondary::> SnapMirror 정책 add-rule-policy snapvault_secondary-snapmirror-label my-monthly-keep 180-vserver svm_secondary'

. 보조 대상 클러스터에서 정책을 확인합니다.
+
'cluster_secondary:::> snapmirror policy show snapvault_secondary-instance'

+
[listing]
----
                     Vserver: svm_secondary
      SnapMirror Policy Name: snapvault_secondary
      SnapMirror Policy Type: vault
                Policy Owner: cluster-admin
                 Tries Limit: 8
           Transfer Priority: normal
   Ignore accesstime Enabled: false
     Transfer Restartability: always
 Network Compression Enabled: false
             Create Snapshot: false
                     Comment: Policy on secondary for vault to vault cascade
       Total Number of Rules: 3
                  Total Keep: 239
                       Rules: SnapMirror Label     Keep  Preserve Warn Schedule Prefix
                              ----------------     ----  -------- ---- -------- ------
                              my-daily                7  false       0 -        -
                              my-weekly              52  false       0 -        -
                              my-monthly            180  false       0 -        -
----
. 보조 대상 클러스터에서 소스 클러스터와의 관계를 생성합니다.
+
'cluster_secondary::> snapmirror create-source-path svm_primary: VolA-destination-path svm_secondary: VolA-type XDP - schedule my_SnapVault-policy SnapVault_secondary'

. 보조 대상 클러스터에서 소스 클러스터와의 관계를 초기화합니다.
+
'cluster_secondary::> snapmirror initialize-source-path svm_primary: VolA-destination-path svm_secondary: VolA'

. 3차 대상 클러스터에서 `snapvault_tertiary` 정책을 생성합니다.
+
`cluster_tertiary::> snapmirror policy create -policy snapvault_tertiary -type vault -comment "Policy on tertiary for vault to vault cascade" -vserver svm_tertiary`

. 3차 대상 클러스터에서 정책에 대한 규칙을 정의합니다 `my-weekly`.
+
'cluster_tertiary::> SnapMirror 정책 add-rule-policy snapvault_tertiary-snapmirror-label my-weekly-keep 250-vserver svm_tertiary'

. 3차 대상 클러스터에서 정책을 확인합니다.
+
'cluster_tertiary:::> snapmirror policy show snapvault_tertiary-instance'

+
[listing]
----
                     Vserver: svm_tertiary
      SnapMirror Policy Name: snapvault_tertiary
      SnapMirror Policy Type: vault
                Policy Owner: cluster-admin
                 Tries Limit: 8
           Transfer Priority: normal
   Ignore accesstime Enabled: false
     Transfer Restartability: always
 Network Compression Enabled: false
             Create Snapshot: false
                     Comment: Policy on tertiary for vault to vault cascade
       Total Number of Rules: 1
                  Total Keep: 250
                       Rules: SnapMirror Label     Keep  Preserve Warn Schedule Prefix
                              ----------------     ----  -------- ---- -------- ------
                              my-weekly             250  false       0 -        -
----
. 3차 대상 클러스터에서 2차 클러스터와의 관계를 생성합니다.
+
'cluster_tertiary::> snapmirror create-source-path svm_secondary: VolA-destination-path svm_tertiary: VolA-type XDP - schedule my_SnapVault-policy SnapVault_tertiary'

. 3차 대상 클러스터에서 2차 클러스터와의 관계를 초기화합니다.
+
'cluster_tertiary::> snapmirror initialize-source-path svm_secondary: VolA-destination-path svm_tertertiary: VolA'


