---
permalink: data-protection/manage-storage-efficiency-task.html 
sidebar: sidebar 
keywords: snapmirror, efficiency, manage, storage, snap mirror, compression, compress, postprocess, post-process, update relationship, volume 
summary: SnapMirror를 사용하여 소스 볼륨과 타겟 볼륨 간에 스토리지 효율성을 유지하려면 타겟 볼륨에서 사후 처리 압축을 비활성화해야 합니다 
---
= ONTAP SnapMirror 볼륨에서 스토리지 효율성 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror는 타겟 볼륨에 사후 처리 데이터 압축이 활성화되어 있는 경우를 제외하고 소스 및 타겟 볼륨에서 스토리지 효율성을 유지합니다. 이 경우 타겟 볼륨에서 스토리지 효율성이 모두 손실됩니다. 이 문제를 해결하려면 타겟 볼륨에서 사후 처리 압축을 비활성화하고 관계를 수동으로 업데이트하며 스토리지 효율성을 다시 활성화해야 합니다.

.이 작업에 대해
명령을 사용하여 볼륨에 효율성이 활성화되어 있는지 여부를 확인할 수 `volume efficiency show` 있습니다. 에 대한 자세한 내용은 `volume efficiency show` link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-show.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

SnapMirror 감사 로그를 보고 전송 설명을 찾아 SnapMirror에서 스토리지 효율성이 유지되는지 확인할 수 있습니다. 전송 설명이 `transfer_desc=Logical Transfer with Storage Efficiency`표시되면 SnapMirror는 스토리지 효율성을 유지하는 것입니다. 전송 설명이 `transfer_desc=Logical Transfer`표시되면 SnapMirror는 스토리지 효율성을 유지하는 것이 아닙니다. 예를 들면 다음과 같습니다.

[listing]
----
Fri May 22 02:13:02 CDT 2020 ScheduledUpdate[May 22 02:12:00]:cc0fbc29-b665-11e5-a626-00a09860c273 Operation-Uuid=39fbcf48-550a-4282-a906-df35632c73a1 Group=none Operation-Cookie=0 action=End source=<sourcepath> destination=<destpath> status=Success bytes_transferred=117080571 network_compression_ratio=1.0:1 transfer_desc=Logical Transfer - Optimized Directory Mode
----
.시작하기 전에
* 소스 및 타겟 클러스터와 SVM을 피어링해야 합니다.
+
https://docs.netapp.com/us-en/ontap-system-manager-classic/peering/index.html["클러스터 및 SVM 피어링"^]

* 타겟 볼륨에서 사후 처리 압축을 비활성화해야 합니다.
* 스토리지를 사용한 논리적 전송: ONTAP 9.3부터 스토리지 효율성을 다시 활성화하기 위해 더 이상 수동 업데이트가 필요하지 않습니다. SnapMirror에서 사후 처리 압축이 비활성화되었다고 감지하면 다음 예약 업데이트에서 스토리지 효율성을 자동으로 다시 활성화합니다. 소스와 대상 모두 ONTAP 9.3을 실행해야 합니다.
* ONTAP 9.3부터 AFF 시스템은 타겟 볼륨을 쓰기 가능한 상태로 만든 후 FAS 시스템과 다른 방식으로 스토리지 효율성 설정을 관리합니다.
+
** 다음을 사용하여 대상 볼륨을 쓰기 가능하게 만든 후  `snapmirror break` 명령을 실행하면 볼륨의 캐싱 정책이 자동으로 설정됩니다.  `auto` (기본값).
+
[NOTE]
====
이 동작은 FlexVol 볼륨에만 적용되며 FlexGroup 볼륨에는 적용되지 않습니다.

====
+
에 대한 자세한 내용은 `snapmirror break` link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-break.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

** 재동기화 시 캐싱 정책이 자동으로 설정됩니다.  `none` 원래 설정과 관계없이 중복 제거 및 인라인 압축은 자동으로 비활성화됩니다. 필요에 따라 설정을 수동으로 수정해야 합니다.




[NOTE]
====
스토리지 효율성을 활성화한 수동 업데이트는 시간이 오래 걸릴 수 있습니다. 사용량이 적은 시간에 작업을 실행할 수 있습니다.

====
.단계
. 복제 관계를 업데이트하고 스토리지 효율성을 다시 설정합니다.
+
[source, cli]
----
snapmirror update -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ... -enable-storage-efficiency true
----
+
[NOTE]
====
이 명령은 타겟 SVM 또는 타겟 클러스터에서 실행해야 합니다. 소스와 대상에 공통 스냅샷이 없는 경우 명령이 실패합니다.  `snapmirror initialize`관계를 다시 초기화하는 데 사용합니다. 에 대한 자세한 내용은 `snapmirror initialize` link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

====
+
다음 예에서는 svm1의 소스 볼륨 VolA와 sm_backup의 대상 볼륨 VolA_dst 간의 관계를 업데이트하고 스토리지 효율성을 다시 활성화합니다.

+
[listing]
----
cluster_dst::> snapmirror update -source-path svm1:volA -destination-path svm_backup:volA_dst -enable-storage-efficiency true
----
+
에 대한 자세한 내용은 `snapmirror update` link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["ONTAP 명령 참조입니다"^]을 참조하십시오.


