---
permalink: data-protection/manage-local-snapshot-copies-concept.html 
sidebar: sidebar 
keywords: manage, local, snapshot, copy, storage, performance overhead, copies, image, restore, flexvol, flexgroup 
summary: 스냅샷은 볼륨의 읽기 전용 시점 이미지입니다. 이미지는 마지막 스냅샷 이후 파일의 변경 사항만 기록하기 때문에 최소한의 저장 공간을 사용하고 성능 오버헤드를 거의 일으키지 않습니다. 
---
= 로컬 ONTAP 스냅샷 관리에 대해 자세히 알아보십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스냅샷 _ 은(는) 볼륨의 읽기 전용 시점 이미지입니다. 이미지는 마지막 스냅샷 이후 파일의 변경 사항만 기록하기 때문에 최소한의 저장 공간을 사용하고 성능 오버헤드를 거의 일으키지 않습니다.

스냅샷을 사용하여 볼륨의 전체 내용을 복원하거나 개별 파일 또는 LUN을 복구할 수 있습니다. 스냅샷은 볼륨의 디렉토리에 저장됩니다. `.snapshot`

ONTAP 9.4 이상에서는 FlexVol volume 최대 1023개의 스냅샷을 포함할 수 있습니다.  ONTAP 9.3 이하 버전에서는 볼륨에 최대 255개의 스냅샷을 포함할 수 있습니다.

[NOTE]
====
ONTAP 9.8부터 FlexGroup 볼륨에는 1023개의 스냅샷이 포함될 수 있습니다. 자세한 내용은 을 link:../flexgroup/protect-snapshot-copies-task.html["스냅샷을 사용하여 FlexGroup 볼륨을 보호합니다"]참조하십시오.

====
일반적인 ONTAP 스냅샷 유형에는 여러 가지가 있습니다.

* `sched_created`: 사전 정의된 일정(예: 시간별, 일별, 주별 또는 월별)을 기반으로 ONTAP 스냅샷 정책에 의해 자동으로 생성되는 스냅샷입니다.
* `sm_created`: SnapMirror 복제 전송(업데이트 또는 초기화 작업)의 결과로 자동으로 생성되는 스냅샷입니다.
* `application_created`: SnapCenter 또는 SnapDrive와 같은 호스트 레벨 또는 데이터베이스 레벨 통합 소프트웨어에서 생성된 스냅샷입니다.
* `user_created`: 관리자가 ONTAP CLI 또는 System Manager를 사용하여 수동으로 트리거한 스냅샷입니다.
* `sv_created`: 스토리지 가상 머신(SVM) DR 또는 특정 보호 워크플로와 같은 클러스터 작업 중에 자동으로 생성되는 스냅샷입니다.
* `luns_created`: LUN 또는 NVMe 네임스페이스 클론의 상태를 백업하거나 캡처하기 위해 생성된 스냅샷입니다.

