---
permalink: data-protection/preserve-snapshot-copy-primary-source-volume-task.html 
sidebar: sidebar 
keywords: ensure, snapshot, copy, mirror-vault, deployment 
summary: SnapMirror snapshot-owner create 명령을 사용하여 미러 볼트 배포의 보조 서버에서 레이블 지정된 스냅샷을 보존할 수 있습니다. 이렇게 하면 볼트 관계 업데이트를 위한 공통 스냅샷이 존재하게 됩니다. 
---
= ONTAP 미러 볼트 배포에서 공통 스냅샷을 보장합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다  `snapmirror snapshot-owner create` 미러-볼트 배포 환경에서 보조 노드에 레이블이 지정된 스냅샷을 보존하는 명령입니다. 이렇게 하면 볼트 관계 업데이트를 위한 공통 스냅샷이 생성됩니다.

.이 작업에 대해
미러 볼트 팬 아웃 또는 캐스케이드 배포를 함께 사용하는 경우 소스 및 대상 볼륨에 공통 스냅샷이 없으면 업데이트가 실패한다는 점에 유의해야 합니다.

SnapMirror는 업데이트를 수행하기 전에 항상 소스 볼륨의 스냅샷을 생성하므로 미러 볼트 팬아웃 또는 캐스케이드 배포에서는 미러 관계에 문제가 되지 않습니다.

그러나 SnapMirror는 볼트 관계를 업데이트할 때 원본 볼륨의 스냅샷을 생성하지 않기 때문에 볼트 관계의 문제일 수 있습니다. 볼트 관계의 원본과 대상 모두에 공통 스냅샷이 하나 이상 있는지 확인하려면 을 사용해야 `snapmirror snapshot-owner create` 합니다. link:supported-deployment-config-concept.html["데이터 보호 팬아웃 및 캐스케이드 구축에 대해 자세히 알아보십시오"]..

.단계
. 소스 볼륨에서 보존하려는 레이블이 지정된 스냅샷에 소유자를 할당합니다.
+
`snapmirror snapshot-owner create -vserver <SVM> -volume <volume> -snapshot <snapshot> -owner <owner>`

+
다음 예에서는 `ApplicationA` 스냅샷의 소유자로 `snap1` 할당합니다.

+
[listing]
----
clust1::> snapmirror snapshot-owner create -vserver vs1 -volume vol1
-snapshot snap1 -owner ApplicationA
----
+
자세히 알아보세요  `snapmirror snapshot-owner create` 에서 link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-snapshot-owner-create.html["ONTAP 명령 참조입니다"^] .

. 에 설명된 대로 미러 관계를 업데이트합니다 link:update-replication-relationship-manual-task.html["복제 관계를 수동으로 업데이트합니다"].
+
또는 미러 관계의 예약된 업데이트를 기다릴 수 있습니다.

. 레이블이 지정된 스냅샷을 볼트 대상으로 전송:
+
`snapmirror update -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ... -source-snapshot snapshot`

+
다음 예에서는 `snap1` 스냅샷을 전송합니다::
+
--
[listing]
----
clust1::> snapmirror update -vserver vs1 -volume vol1
-source-snapshot snap1
----
볼트 관계가 업데이트될 때 레이블이 지정된 스냅샷이 보존됩니다.

에 대한 자세한 내용은 `snapmirror update` link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

--


. 소스 볼륨에서 레이블이 지정된 스냅샷에서 소유자를 제거합니다.
+
'스냅샷-소유자 삭제 - vserver_SVM_-volume_volume_-snapshot_snapshot_-owner_owner_'

+
다음 예에서는 스냅샷 소유자로서 `snap1` 를 제거합니다 `ApplicationA`.

+
[listing]
----
clust1::> snapmirror snapshot-owner delete -vserver vs1 -volume vol1
-snapshot snap1 -owner ApplicationA
----
+
에 대한 자세한 내용은 `snapmirror snapshot-owner delete` link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-snapshot-owner-delete.html["ONTAP 명령 참조입니다"^]을 참조하십시오.


