---
permalink: data-protection/restore-single-file-lun-task.html 
sidebar: sidebar 
keywords: restore, single file, lun, nvme, namespace, snapmirror, destination, snapshot, copy, snap mirror, baseline, 
summary: 단일 파일, LUN, 스냅샷에서 파일 또는 LUN 세트를 복원하거나 SnapMirror 대상 볼륨에서 NVMe 네임스페이스를 복원할 수 있습니다. ONTAP 9.7부터는 SnapMirror 동기식 대상에서 NVMe 네임스페이스를 복원할 수도 있습니다. 파일을 원래 소스 볼륨이나 다른 볼륨으로 복원할 수 있습니다. 
---
= ONTAP를 통해 SnapMirror 대상에서 단일 파일, LUN 또는 NVMe 네임스페이스를 복원합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
단일 파일, LUN, 스냅샷에서 파일 또는 LUN 세트를 복원하거나 SnapMirror 대상 볼륨에서 NVMe 네임스페이스를 복원할 수 있습니다. ONTAP 9.7부터는 SnapMirror 동기식 대상에서 NVMe 네임스페이스를 복원할 수도 있습니다. 파일을 원래 소스 볼륨이나 다른 볼륨으로 복원할 수 있습니다.

.시작하기 전에
SnapMirror 동기 대상(ONTAP 9.5부터 지원됨)에서 파일 또는 LUN을 복구하려면 먼저 관계를 삭제하고 해제해야 합니다.

.이 작업에 대해
파일 또는 LUN(대상 볼륨)을 복원하는 볼륨은 읽기-쓰기 볼륨이어야 합니다.

* SnapMirror는 소스 및 대상 볼륨에 공통 스냅샷이 있는 경우 _ 증가분 복구 _ 를 수행합니다(일반적으로 원래 소스 볼륨으로 복구할 때와 마찬가지로).
* 그렇지 않으면 SnapMirror가 _baseline restore_를 수행하여 지정된 스냅샷과 해당 스냅샷이 참조하는 모든 데이터 블록이 대상 볼륨으로 전송됩니다.


.단계
. 대상 볼륨의 스냅샷을 나열합니다.
+
`volume snapshot show -vserver <SVM> -volume volume`

+
에 대한 자세한 내용은 `volume snapshot show` link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-show.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

+
다음 예는 대상의 스냅샷을 보여 `vserverB:secondary1` 줍니다.

+
[listing]
----

cluster_dst::> volume snapshot show -vserver vserverB -volume secondary1

Vserver     Volume      Snapshot                State    Size  Total% Used%
-------     ------      ---------- ----------- ------   -----  ------ -----
vserverB    secondary1  hourly.2013-01-25_0005  valid   224KB     0%    0%
                        daily.2013-01-25_0010   valid   92KB      0%    0%
                        hourly.2013-01-25_0105  valid   228KB     0%    0%
                        hourly.2013-01-25_0205  valid   236KB     0%    0%
                        hourly.2013-01-25_0305  valid   244KB     0%    0%
                        hourly.2013-01-25_0405  valid   244KB     0%    0%
                        hourly.2013-01-25_0505  valid   244KB     0%    0%

7 entries were displayed.
----
. SnapMirror 대상 볼륨의 스냅샷에서 단일 파일 또는 LUN 또는 파일 또는 LUN 집합 복구:
+
`snapmirror restore -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ... -source-snapshot snapshot -file-list <source_file_path,@destination_file_path>`

+
에 대한 자세한 내용은 `snapmirror restore` link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-restore.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

+
[NOTE]
====
이 명령은 타겟 SVM 또는 타겟 클러스터에서 실행해야 합니다.

====
+
다음 명령을 실행하면 `daily.2013-01-25_0010` 원래 대상 볼륨의 스냅샷과 `file2` 파일이 원래 소스 볼륨의 `secondary1` 활성 파일 시스템의 동일한 위치로 `primary1` 복원됩니다. `file1`

+
[listing]
----

cluster_dst::> snapmirror restore -source-path vserverB:secondary1 -destination-path vserverA:primary1 -source-snapshot daily.2013-01-25_0010 -file-list /dir1/file1,/dir2/file2

[Job 3479] Job is queued: snapmirror restore for the relationship with destination vserverA:primary1
----
+
다음 명령을 실행하면 `daily.2013-01-25_0010` 원래 대상 볼륨의 `secondary1` 스냅샷과 `file2` 파일이 원래 소스 볼륨의 활성 파일 시스템의 다른 위치로 `primary1` 복원됩니다. `file1`

+
대상 파일 경로는 @ 기호와 원본 소스 볼륨의 루트에서 파일 경로로 시작합니다. 이 예에서는 file1 이 /dir1/file1로 복구되고 file2 가 기본 y1의 /dir2.new/file2 로 복원됩니다.

+
[listing]
----

cluster_dst::> snapmirror restore -source-path vserverB:secondary1 -destination-path vserverA:primary1 -source-snapshot daily.2013-01-25_0010 -file-list /dir/file1,@/dir1/file1.new,/dir2/file2,@/dir2.new/file2

[Job 3479] Job is queued: snapmirror restore for the relationship with destination vserverA:primary1
----
+
다음 명령을 실행하면 `file3` 원래 대상 볼륨의 `secondary1` 스냅샷과 `daily.2013-01-25_0010` 파일이 원래 소스 볼륨의 활성 파일 시스템의 다른 위치로 복원되고 `file1` 에서 `snap1` 의 활성 파일 시스템의 `primary1` 동일한 위치로 `primary1` 복원됩니다. `file2`

+
이 예에서는 파일 'file1'이 '/dir1/file1'로 복원되고 새 파일3이 '/dir3.new/file3'로 복원됩니다.

+
[listing]
----

cluster_dst::> snapmirror restore -source-path vserverB:secondary1 -destination-path vserverA:primary1 -source-snapshot daily.2013-01-25_0010 -file-list /dir/file1,@/dir1/file1.new,/dir2/file2,/dir3/file3,@/dir3.new/file3

[Job 3479] Job is queued: snapmirror restore for the relationship with destination vserverA:primary1
----

