---
permalink: data-protection/snapmirror-unified-replication-concept.html 
sidebar: sidebar 
keywords: snapmirror, unified, replication 
summary: SnapMirror 통합 복제를 사용하면 동일한 대상 볼륨에 재해 복구 및 아카이빙을 구성할 수 있습니다. 통합 복제가 적절한 경우 필요한 보조 스토리지의 양을 줄이고 기본 전송 수를 제한하며 네트워크 트래픽을 줄일 수 있습니다. 
---
= ONTAP SnapMirror 통합 복제에 대해 알아보십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror_Unified replication_을 사용하면 동일한 대상 볼륨에 재해 복구 및 아카이빙을 구성할 수 있습니다. 통합 복제가 적절한 경우 필요한 보조 스토리지의 양을 줄이고 기본 전송 수를 제한하며 네트워크 트래픽을 줄일 수 있습니다.



== 통합 데이터 보호 관계의 초기화 방법

SnapMirror와 마찬가지로 통합 데이터 보호는 처음 호출할 때 기본 전송을 수행합니다. 관계에 대한 SnapMirror 정책에서는 기본 내용과 모든 업데이트를 정의합니다.

기본 통합 데이터 보호 정책에 따른 기본 전송은 `MirrorAndVault` 소스 볼륨의 스냅샷을 생성한 다음 해당 복사본과 이 복사본이 타겟 볼륨에 참조하는 데이터 블록을 전송합니다. 볼트 보관과 마찬가지로, 통합 데이터 보호에는 기준선에 이전 스냅샷이 포함되지 않습니다.



== 통합 데이터 보호 관계를 업데이트하는 방법

정책에 따라 업데이트될 때마다 `MirrorAndVault` SnapMirror는 소스 볼륨의 스냅샷을 생성하고 해당 스냅샷과 마지막 업데이트 이후 생성된 모든 스냅샷을 스냅샷 정책 규칙에 정의된 레이블과 일치하는 레이블이 있는 경우 전송합니다. 정책의 다음 출력에서 다음 `snapmirror policy show` 사항에 `MirrorAndVault` 유의하십시오.

* `Create Snapshot` 는 SnapMirror에서 관계를 업데이트할 때 스냅샷을 생성함을 나타내는 ""true"" `MirrorAndVault`입니다.
* `MirrorAndVault` 에는 SnapMirror가 관계를 업데이트할 때 SnapMirror에 의해 생성된 스냅샷과 소스에 일치하는 레이블이 있는 스냅샷이 모두 전송됨을 나타내는 "'sm_created'", "'daily'" 및 "'weekly" 규칙이 있습니다.


[listing]
----
cluster_dst::> snapmirror policy show -policy MirrorAndVault -instance

                     Vserver: vs0
      SnapMirror Policy Name: MirrorAndVault
      SnapMirror Policy Type: mirror-vault
                Policy Owner: cluster-admin
                 Tries Limit: 8
           Transfer Priority: normal
   Ignore accesstime Enabled: false
     Transfer Restartability: always
 Network Compression Enabled: false
             Create Snapshot: true
                     Comment: A unified SnapMirror synchronous and SnapVault policy for
                              mirroring the latest file system and daily and weekly snapshots.
       Total Number of Rules: 3
                  Total Keep: 59
                       Rules: SnapMirror Label     Keep  Preserve Warn Schedule Prefix
                              ----------------     ----  -------- ---- -------- ------
                              sm_created              1  false       0 -        -
                              daily                   7  false       0 -        -
                              weekly                 52  false       0 -        -
----


== Unified7년 정책입니다

사전 구성된 `Unified7year` 정책은 과 정확히 동일하게 `MirrorAndVault` 작동합니다. 단, 네 번째 규칙은 월별 스냅샷을 전송하고 7년 동안 보존한다는 점이 다릅니다.

[listing]
----

                       Rules: SnapMirror Label     Keep  Preserve Warn Schedule Prefix
                              ----------------     ----  -------- ---- -------- ------
                              sm_created              1  false       0 -        -
                              daily                   7  false       0 -        -
                              weekly                 52  false       0 -        -
                              monthly                84  false       0 -        -
----


== 데이터 손상을 방지합니다

통합 복제는 초기화할 때 SnapMirror에서 생성한 스냅샷으로 기본 전송 내용을 제한합니다. 업데이트할 때마다 SnapMirror는 소스의 다른 스냅샷을 생성하고 스냅샷 정책 규칙에 정의된 레이블과 일치하는 레이블이 있는 새 스냅샷과 해당 스냅샷을 전송합니다.

대상에 마지막으로 전송된 스냅샷의 복사본을 생성하여 업데이트된 스냅샷이 손상되는 것을 방지할 수 있습니다. 이 ""로컬 복사본""은 소스의 보존 규칙에 관계없이 보존되므로 SnapMirror에 의해 원래 전송된 스냅샷을 소스에서 더 이상 사용할 수 없는 경우에도 대상에서 해당 복제본을 사용할 수 있습니다.



== 통합 데이터 복제를 사용하는 경우

전체 미러 유지 관리의 이점을 통합 복제가 2차 스토리지의 양을 줄이고 기본 전송 수를 제한하며 네트워크 트래픽을 감소시켜 주는 이점과 비교하여 평가해야 합니다.

통합 복제의 적절성을 결정하는 주요 요인은 활성 파일 시스템의 변경률입니다. 예를 들어, 기존 미러는 데이터베이스 트랜잭션 로그의 시간별 스냅샷을 저장하는 볼륨에 더 적합합니다.

.관련 정보
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-show.html["스냅미러 정책 보기"^]

