---
permalink: release-notes/whats-new-9171.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 9.17.1' 
summary: ONTAP 9.17.1에서 사용할 수 있는 새로운 기능에 대해 알아보세요. 
---
= ONTAP 9.17.1의 새로운 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.17.1에서 사용할 수 있는 새로운 기능에 대해 알아보세요.

최신 ONTAP 9 릴리스에서 알려진 문제, 제한 사항 및 업그레이드 주의 사항에 대한 자세한 내용은 를 참조하십시오 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 릴리즈 노트"^]. 릴리스 정보에 액세스하려면 NetApp 계정으로 로그인하거나 계정을 만들어야 합니다.

* 새로운 기능 및 향상된 기능에 대해 알아봅니다 https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["ONTAP MetroCluster 기능"^].
* 에 대해 알아보세요  https://docs.netapp.com/us-en/asa-r2/release-notes/whats-new-9171.html["NetApp ASA r2 시스템을 위한 새롭고 향상된 ONTAP 소프트웨어 기능"^] .
* 에 대해 알아보세요  https://docs.netapp.com/us-en/ontap-systems/whats-new.html["AFF, ASA 및 FAS 시스템과 지원되는 스위치에 대한 새롭고 향상된 지원"^] .
* 의 업데이트에 대해 알아봅니다 https://docs.netapp.com/us-en/ontap-automation/whats_new.html["ONTAP REST API를 참조하십시오"^].


최신 버전의 ONTAP로 업그레이드하려면 를 참조하십시오link:../upgrade/create-upgrade-plan.html["ONTAP 업그레이드를 준비합니다"].



== 데이터 보호

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
xref:../nvme/support-limitations.html#features[NVMe를 통한 호스트 액세스를 위한 SnapMirror 활성 동기화 지원]
 a| 
SnapMirror Active Sync는 NVMe/TCP를 사용하는 VMware 워크로드에 대한 NVMe 액세스 지원과 2노드 ONTAP 클러스터에 대한 NVMe/FC 호스트 액세스를 추가합니다. VMware 워크로드의 NVMe/TCP 지원은 VMware 버그가 해결되어야 가능합니다.



 a| 
xref:../snapmirror-active-sync/index.html[SnapMirror Active Sync를 통한 ONTAP Cloud Mediator 지원]
 a| 
ONTAP Cloud Mediator는 ONTAP 9.17.1에 도입되었으며 SnapMirror 액티브 동기화 관계를 지원합니다. ONTAP Mediator와 마찬가지로 클라우드 기반 Mediator는 SnapMirror 액티브 동기화 관계에 대한 쿼럼 감시 역할을 하여 투명한 장애 조치를 보장하는 동시에 제3자 사이트 유지 관리의 운영 복잡성을 줄여줍니다.

|===


== S3 오브젝트 스토리지

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
xref:../s3-multiprotocol/index.html[ONTAP S3 NAS 버킷의 CopyObject 작업 지원]
 a| 
CopyObject 작업은 ONTAP S3 NAS 버킷 내에서 지원됩니다.



 a| 
xref:../s3-multiprotocol/create-nas-bucket-task.html[S3 NAS 버킷을 연결 경로에 연결하기 위한 지원]
 a| 
ONTAP CLI를 사용하여 S3 NAS 버킷을 생성할 때, 버킷을 연결 경로 대신 볼륨에 연결하도록 선택할 수 있습니다. 볼륨에 연결하면 볼륨이 마운트 해제되거나 마운트되는 등 경로가 변경되면 연결 경로가 자동으로 업데이트됩니다.



 a| 
xref:../s3-multiprotocol/index.html#object-multipart-upload[태그 지정 및 메타데이터를 위한 S3 다중 프로토콜 지원]
 a| 
태그 지정 및 사용자 메타데이터 키/값 쌍은 다중 프로토콜(S3 및 NAS) 환경에서 CreateMultipartUpload 작업에서 지원됩니다.

|===


== 보안

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
xref:../system-admin/use-hsts-task.html[HTTP Strict Transport Security(HSTS) 지원]
 a| 
ONTAP 웹 서비스에 대해 HTTP Strict Transport Security를 지원하여 사용자 브라우저와 ONTAP 간의 안전한 HTTPS 통신을 시행할 수 있습니다.



 a| 
xref:../networking/ipsec-prepare.html[링크 집계 그룹을 통한 IPsec 하드웨어 오프로드]
 a| 
ONTAP 9.16.1에서 도입된 하드웨어 오프로드 지원을 확장하여 링크 집계 그룹에 대한 IPsec 하드웨어 오프로드를 지원합니다.



 a| 
xref:../networking/ipsec-prepare.html[IPsec 포스트퀀텀 사전 공유 키 지원]
 a| 
ONTAP 미래의 양자 컴퓨터 공격으로부터 보호하기 위해 IPsec에 대한 포스트퀀텀 사전 공유 키를 지원합니다.



 a| 
xref:../encryption-at-rest/manage-keys-barbican-task.html[OpenStack Barbican 키 관리자 지원]
 a| 
ONTAP NetApp 볼륨 암호화(NVE) 키에 대한 OpenStack의 Barbican 키 관리자를 지원합니다.



 a| 
xref:../authentication/configure-jit-elevation-task.html[JIT(Just in Time) 권한 승격 지원]
 a| 
ONTAP 역할 기반 액세스 제어(RBAC)를 위한 JIT 권한 승격을 지원합니다. 사용자는 구성된 역할에 대한 임시 권한 승격을 요청하여 필요에 따라 권한이 부여된 명령에 액세스할 수 있습니다. 클러스터 관리자는 JIT 권한 승격에 액세스할 수 있는 사용자, 액세스 허용 시점 및 기간을 설정할 수 있습니다.



 a| 
xref:../system-admin/configure-saml-authentication-task.html[SAML 인증을 위한 Entra IdP 및 IdP 그룹 지원 지원]
 a| 
ONTAP SAML ID 공급자로 Microsoft Entra를 지원합니다. 또한 IdP에서 제공하는 그룹 정보를 ONTAP 역할에 매핑할 수 있습니다.



 a| 
xref:../system-admin/audit-manage-cross-cluster-requests.html[클러스터 간 요청 감사]
 a| 
시작 소스 클러스터와 대상(실행) 클러스터 모두에서 감사 작업을 구성하고 실행할 수 있습니다. 이전 릴리스에서는 클라이언트 요청을 수신하는 클러스터에서만 감사를 수행했습니다. 이 기능을 사용하면 클러스터 간 요청을 처리하는 피어링된 클러스터도 해당 활동을 로깅합니다. 이러한 감사 작업은 ONTAP 내에서 시작된 모든 SET 또는 GET 요청으로 활성화 및 확장될 수 있습니다.



 a| 
xref:../anti-ransomware/index.html[자율형 랜섬웨어 보호를 통한 SAN 지원]
 a| 
ARP는 암호화 기반 이상 탐지 기능을 갖춘 SAN 볼륨을 지원하고, 상세한 엔트로피 통계를 위한 새로운 명령을 도입하며, 이전에 NAS에 집중되었던 System Manager의 랜섬웨어 보호 메시징 기능을 통합합니다. 구성 가능한 탐지 임계값과 더욱 확정적인 스냅샷 보존 기능은 다양한 워크로드에 대한 유연성을 높여줍니다.

|===


== 스토리지 리소스 관리 기능 향상

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
xref:../task_nas_file_system_analytics_enable.html[새 볼륨에 대해 기본적으로 FSA가 활성화됨]
 a| 
NAS 프로토콜에 할당된 ONTAP 클러스터에서 새로 생성된 SVM에 생성된 볼륨에는 기본적으로 파일 시스템 분석(FSA)이 활성화되어 있습니다. FSA는 볼륨이 생성되는 즉시 자동으로 활성화되어 추가 구성 없이 즉각적인 분석 기능을 제공합니다.



 a| 
xref:../flexgroup/fast-directory-delete-asynchronous-task.html[FlexGroup 볼륨에서 직접 삭제 진행 상황을 보기 위한 향상된 지원]
 a| 
ONTAP CLI 명령  `volume file async-delete show` 클라이언트에서 실행된 비동기 삭제 작업을 포함하도록 향상되었습니다.

|===