---
permalink: release-notes/whats-new-9161.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 9.16.1' 
summary: ONTAP 9.16.1에서 사용 가능한 새로운 기능에 대해 알아보십시오. 
---
= ONTAP 9.16.1의 새로운 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.16.1에서 사용 가능한 새로운 기능에 대해 알아보십시오.

최신 ONTAP 9 릴리스에서 알려진 문제, 제한 사항 및 업그레이드 주의 사항에 대한 자세한 내용은 를 참조하십시오 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 릴리즈 노트"^]. 릴리스 정보에 액세스하려면 NetApp 계정으로 로그인하거나 계정을 만들어야 합니다.

* 새로운 기능 및 향상된 기능에 대해 알아봅니다 https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["ONTAP MetroCluster 기능"^].
* 에 대해 알아보세요  https://docs.netapp.com/us-en/asa-r2/release-notes/whats-new-9171.html["NetApp ASA r2 시스템을 위한 새롭고 향상된 ONTAP 소프트웨어 기능"^] .
* 에 대해 알아보세요  https://docs.netapp.com/us-en/ontap-systems/whats-new.html["AFF, ASA 및 FAS 시스템과 지원되는 스위치에 대한 새롭고 향상된 지원"^] .
* 의 업데이트에 대해 알아봅니다 https://docs.netapp.com/us-en/ontap-automation/whats_new.html["ONTAP REST API를 참조하십시오"^].


최신 버전의 ONTAP로 업그레이드하려면 를 참조하십시오link:../upgrade/create-upgrade-plan.html["ONTAP 업그레이드를 준비합니다"].



== 데이터 보호

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
xref:../snapmirror-active-sync/index.html[SnapMirror 액티브 동기화에 대한 다중 노드 지원]
 a| 
이전의 2노드 제한에서 확장된 SnapMirror 액티브 동기화는 4노드 클러스터를 지원하므로 대규모 워크로드를 위한 데이터 복제가 가능합니다.



 a| 
xref:../data-protection/cloud-backup-with-snapmirror-task.html[팬아웃 관계를 구축하기 위한 SnapMirror 클라우드 지원]
 a| 
SnapMirror 클라우드는 동일한 소스 볼륨 또는 FlexGroup에서 두 개의 서로 다른 오브젝트 저장소로 팬아웃 관계를 지원합니다. 팬아웃은 두 개의 오브젝트 저장소와 오브젝트 저장소의 한 개 또는 두 개의 버킷으로 구성될 수 있습니다.



 a| 
xref:../data-protection/cloud-backup-with-snapmirror-task.html[마이그레이션된 볼륨에서 SnapMirror 클라우드 백업 지원]
 a| 
SnapMirror 클라우드는 기존 ONTAP REST API를 사용하여 클라우드로 마이그레이션된 볼륨을 백업할 수 있습니다. 새로운 기능은 기준 변경 작업을 수행할 필요 없이 클라우드의 마이그레이션된 볼륨에서 동일한 대상 오브젝트 저장소 엔드포인트로 SnapMirror 클라우드 백업을 지원합니다. FlexVol 볼륨과 FlexGroup 볼륨이 모두 지원됩니다.

|===


== 네트워킹

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
xref:../networking/configure_virtual_ip_vip_lifs.html#set-up-border-gateway-protocol-bgp[BGP 피어 그룹에 대한 MD5 인증 지원]
 a| 
ONTAP는 BGP 피어 그룹에서 MD5 인증을 지원하여 BGP 세션을 보호합니다. MD5를 사용하면 승인된 피어 사이에서만 BGP 세션을 설정 및 처리할 수 있으므로 공격자가 BGP 업데이트를 스푸핑하여 네트워크에 잘못된 라우팅 정보를 주입하려는 경로 하이재킹과 같은 공격을 방지할 수 있습니다.



 a| 
xref:../networking/ipsec-prepare.html[IPsec 하드웨어 오프로드 지원]
 a| 
IP 보안(IPsec)은 클라이언트와 ONTAP 노드 간의 모든 IP 트래픽을 보호하는 데 사용할 수 있는 이동 중인 데이터 보안 옵션입니다. 이 프로토콜은 처음에 ONTAP 9 .8에서 사용할 수 있었으며 소프트웨어로만 구현되었습니다. ONTAP 9.16.1부터 암호화 및 무결성 검사와 같은 계산 집약적인 특정 작업을 스토리지 노드에 설치된 지원되는 NIC(Network Interface Controller) 카드로 오프로드할 수 있습니다. 이 하드웨어 오프로드 옵션을 사용하면 IPsec으로 보호되는 네트워크 트래픽의 성능과 처리량을 크게 향상시킬 수 있습니다.

|===


== S3 오브젝트 스토리지

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
S3 오브젝트 메타데이터 및 태깅을 위한 멀티프로토콜 S3 버킷 지원
 a| 
ONTAP 9.16.1부터 S3 오브젝트 태깅은 비멀티프로토콜 ONTAP S3 버킷에서 NAS 및 S3 멀티프로토콜 ONTAP S3 버킷으로 확장됩니다. 태그는 S3 프로토콜에서만 표시됩니다. S3 클라이언트를 사용하여 S3 오브젝트에 적용함으로써 https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-tagging.html["태그 및 메타데이터"^] ONTAP에 오브젝트 또는 파일로 저장된 데이터에서 라이프사이클, 비용 청구, 데이터 범주 및 사용자 지정 워크플로우를 정의하는 데 도움이 됩니다. Bedrock 또는 Athena와 같은 AWS 데이터 서비스와 통합할 경우 태그 및 메타데이터가 이 서비스에서 제공하는 Data Processing의 핵심이 됩니다.


NOTE: 네이티브 S3 버킷에서 태그 및 사용자 정의 메타데이터에 대한 지원은 ONTAP 9.9.1부터 시작되었습니다.



 a| 
xref:../s3-multiprotocol/index.html[멀티프로토콜 S3 버킷은 다중 부분 업로드를 지원합니다]
 a| 
멀티 파트 업로드는 처음부터 멀티프로토콜 ONTAP S3 버킷이 지원되던 핵심 S3 기능입니다. ONTAP 9.16.1부터 이 핵심 기능은 NAS 및 S3 멀티프로토콜 ONTAP S3 버킷으로 확장됩니다.



 a| 
xref:../s3-config/cors-integration.html[ONTAP S3 버킷에 대한 CORS(Cross-Origin Resource Sharing) 지원]
 a| 
CORS(Cross-Origin Resource Sharing)로 웹 애플리케이션의 잠재력을 최대한 활용하십시오. CORS를 사용하면 한 도메인의 클라이언트 응용 프로그램과 다른 도메인의 리소스 간에 원활한 상호 작용이 가능합니다. CORS 지원을 통합하면 리소스에 대한 선택적 교차 오리진 액세스를 통해 ONTAP S3 기반 웹 애플리케이션의 역량을 강화할 수 있습니다.



 a| 
xref:../s3-snapshots/index.html[ONTAP는 ONTAP S3 버킷의 스냅샷 생성을 지원합니다]
 a| 
ONTAP S3 버킷의 읽기 전용 시점 스냅샷을 생성할 수 있습니다. S3 스냅샷 기능을 사용하면 스냅샷을 수동으로 생성하거나 스냅샷 정책을 통해 스냅샷을 자동으로 생성할 수 있습니다. 또한, S3 스냅샷을 확인, 탐색, 삭제하고, S3 클라이언트를 통해 스냅샷 콘텐츠를 복원할 수 있습니다.

|===


== 산

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
xref:../san-admin/enable-space-allocation.html[NVMe 공간 할당 취소가 기본적으로 활성화되어 있습니다]
 a| 
NVMe 네임스페이스에 대해 공간 할당("홀 펀칭" 및 "매핑 해제"라고도 함)이 기본적으로 활성화됩니다. 공간 할당 해제를 통해 호스트가 네임스페이스에서 사용되지 않는 블록을 할당 해제하여 공간을 재확보할 수 있습니다. 특히 데이터 회전율이 높은 파일 시스템의 경우 전반적인 스토리지 효율성이 크게 향상됩니다.

|===


== 보안

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
xref:../multi-admin-verify/index.html#rule-protected-commands[다중 관리자 확인을 위해 확장된 규칙 보호 명령 집합입니다]
 a| 
관리자는 다중 관리자 검증 규칙을 생성하여 작업 생성, 삭제 및 수정, 일관성 그룹 스냅샷 생성 및 삭제, 기타 명령 등 일관성 그룹을 보호할 수 있습니다.



 a| 
xref:../anti-ransomware/index.html[AI 개선(ARP/AI)을 통한 자율적 랜섬웨어 방어]
 a| 
ARP는 새로운 AI 기능으로 업그레이드되어 99%의 정밀도와 리콜로 랜섬웨어 공격을 감지하고 이에 대응할 수 있습니다. AI는 포괄적인 데이터 세트에서 훈련되기 때문에 FlexVol 볼륨에서 실행되는 ARP에 대한 학습 기간이 더 이상 없으며 ARP/AI가 즉시 활성 모드에서 시작됩니다. ARP/AI에는 최신 위협에 대한 지속적인 보호 및 복원력을 보장하는 자동 업데이트 기능도 포함되어 있습니다.


NOTE: ARP/AI 기능은 현재 NAS만 지원합니다. 자동 업데이트 기능은 System Manager에서 배포할 새 보안 파일의 가용성을 표시하지만 이러한 업데이트는 NAS 워크로드 보호에만 적용됩니다.



 a| 
xref:../nvme/set-up-tls-secure-channel-nvme-task.html[TLS를 통한 NVMe/TCP 1.3]
 a| 
IPSec에 비해 간소화된 구성과 향상된 성능으로 프로토콜 계층에서 NVMe/TCP를 "유선"으로 보호합니다.



 a| 
FabricPool 개체 저장소 통신을 위한 TLS 1.3 지원
 a| 
ONTAP는 FabricPool 개체 저장소 통신에 TLS 1.3을 지원합니다.



 a| 
xref:../authentication/overview-oauth2.html[Microsoft Entra ID용 OAuth 2.0]
 a| 
ONTAP 9.14.1에서 처음 도입된 OAuth 2.0 지원은 Microsoft Entra ID 인증 서버(이전의 Azure AD)를 지원하는 데 있어 표준 OAuth 2.0 클레임이 추가되었습니다. 또한 UUID 스타일 값에 기반한 Entra ID 표준 그룹 클레임은 새로운 그룹 및 역할 매핑 기능을 통해 지원됩니다. Entra ID로 테스트되었지만 지원되는 인증 서버에서 사용할 수 있는 새로운 외부 역할 매핑 기능도 도입되었습니다.

|===


== 스토리지 효율성

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
xref:../volumes/qtrees-partition-your-volumes-concept.html[지연 시간 메트릭 및 기간별 통계를 포함하도록 qtree 성능 모니터링을 확장했습니다]
 a| 
이전 ONTAP 릴리즈에서는 초당 I/O 작업, 읽기/쓰기 등 다양한 범주에서 처리 성능을 비롯한 qtree 사용을 위한 강력한 실시간 메트릭을 제공합니다. ONTAP 9.16.1부터 실시간 지연 시간 통계에 액세스하고 보관된 기록 데이터를 볼 수도 있습니다. 이러한 새로운 기능을 통해 IT 스토리지 관리자는 시스템 성능에 대한 보다 정확한 통찰력을 얻고 장기간에 걸친 추세를 분석할 수 있습니다. 이를 통해 데이터 센터 및 클라우드 스토리지 리소스의 운영 및 계획과 관련하여 정보에 입각한 의사 결정을 내릴 수 있습니다.

|===


== 스토리지 리소스 관리 기능 향상

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
xref:../volumes/manage-svm-capacity.html[스토리지 제한이 설정된 SVM에서 데이터 보호 볼륨 지원]
 a| 
스토리지 제한이 설정된 SVM은 데이터 보호 볼륨을 포함할 수 있습니다. 계단식 배열, 동기식 재해 복구 관계 및 복원 관계가 없는 비동기식 재해 복구 관계의 FlexVol 볼륨이 지원됩니다.

[NOTE]
====
ONTAP 9.15.1 및 이전 릴리즈에서는 데이터 보호 볼륨, SnapMirror 관계 볼륨 또는 MetroCluster 구성을 포함하는 모든 SVM에 대해 스토리지 한도를 구성할 수 없습니다.

====


 a| 
xref:../flexgroup/enable-adv-capacity-flexgroup-task.html[FlexGroup 고급 용량 배포 지원]
 a| 
고급 용량 균형 조정을 사용하면 매우 큰 파일이 확장되어 구성원 볼륨 한 개에 있는 공간을 사용할 때 FlexGroup 구성원 볼륨 간에 파일 내의 데이터를 분산할 수 있습니다.



 a| 
xref:../svm-migrate/index.html[MetroCluster 구성 마이그레이션에 대한 SVM 데이터 이동성 지원]
 a| 
ONTAP은 다음 MetroCluster SVM 마이그레이션을 지원합니다.

* 비 MetroCluster 구성과 MetroCluster IP 구성 간에 SVM 마이그레이션
* 2개의 MetroCluster IP 구성 간에 SVM 마이그레이션
* MetroCluster FC 구성에서 MetroCluster IP 구성으로 SVM 마이그레이션


|===


== 시스템 관리자

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
xref:../authentication-access-control/webauthn-mfa-overview.html[System Manager에서 피싱 방지 WebAuthn 다중 요소 인증 지원]
 a| 
ONTAP 9.16.1은 WebAuthn MFA 로그인을 지원하므로 System Manager에 로그인할 때 하드웨어 보안 키를 두 번째 인증 방법으로 사용할 수 있습니다.

|===