---
permalink: release-notes/whats-new-9191.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 9.19.1' 
summary: ONTAP 9.19.1에서 새롭게 제공되는 기능에 대해 알아보세요. 
---
= ONTAP 9.19.1의 새로운 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.19.1에서 새롭게 제공되는 기능에 대해 알아보세요.

최신 ONTAP 9 릴리스에서 알려진 문제, 제한 사항 및 업그레이드 주의 사항에 대한 자세한 내용은 를 참조하십시오 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 릴리즈 노트"^]. 릴리스 정보에 액세스하려면 NetApp 계정으로 로그인하거나 계정을 만들어야 합니다.

* 새로운 기능 및 향상된 기능에 대해 알아봅니다 https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["ONTAP MetroCluster 기능"^].
* 에 대해 알아보세요  https://docs.netapp.com/us-en/ontap-afx/release-notes/whats-new-9171.html["NetApp AFX 스토리지 시스템을 위한 새롭고 향상된 ONTAP 소프트웨어 기능"^] .
* 에 대해 알아보세요  https://docs.netapp.com/us-en/asa-r2/release-notes/whats-new-9171.html["NetApp ASA r2 스토리지 시스템을 위한 새롭고 향상된 ONTAP 소프트웨어 기능"^] .
* 에 대해 알아보세요  https://docs.netapp.com/us-en/ontap-systems/whats-new.html["AFF, ASA 및 FAS 시스템과 지원되는 스위치에 대한 새롭고 향상된 지원"^] .
* 의 업데이트에 대해 알아봅니다 https://docs.netapp.com/us-en/ontap-automation/whats_new.html["ONTAP REST API를 참조하십시오"^].


최신 버전의 ONTAP로 업그레이드하려면 를 참조하십시오link:../upgrade/create-upgrade-plan.html["ONTAP 업그레이드를 준비합니다"].



== 데이터 보호

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
xref:../snapmirror-active-sync/interoperability-reference.html[SnapMirror 액티브 싱크는 AIX에서 투명한 애플리케이션 페일오버를 지원합니다.]
 a| 
SnapMirror 액티브 동기화의 대칭형 액티브/액티브는 2노드 클러스터의 AIX 환경에서 RPO가 0인 투명한 페일오버를 지원합니다.



 a| 
xref:../data-protection/cloud-backup-with-snapmirror-task.html#restore-from-the-cloud[SnapMirror 클라우드 지원 한도가 S3 버킷 100개로 증가했습니다.]
 a| 
SnapMirror 클라우드에서 지원하는 S3 버킷 수를 100개로 늘렸습니다.



 a| 
xref:../snaplock/snapshot-lock-concept.html[SnapMirror 동기식은 변조 방지 스냅샷 잠금을 지원합니다.]
 a| 
SnapMirror 동기식 버전에서는 변조 방지 스냅샷 잠금 기능을 사용할 수 있습니다.



 a| 
xref:../data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html[SnapMirror 동기식 기능은 예약된 스냅샷을 대상 볼륨으로 복제하는 것을 지원합니다.]
 a| 
SnapMirror 동기 기능을 사용하면 예약된 스냅샷을 대상 볼륨으로 복제할 수 있습니다.

|===


== 네트워킹

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
SVM이 지원하는 NFS 버전 관리
 a| 
NFSv4.2 지원은 NFSv4.1 설정과 독립적으로 관리되므로 각 SVM은 필요에 따라 NFSv4.2 기능을 알리거나 숨길 수 있습니다. 기본적으로 새 NFS 서비스가 생성될 때 관리자가 명시적으로 비활성화하지 않는 한 NFSv4.2가 활성화됩니다.

* xref:../nfs-admin/enable-disable-nfs-task.html[ONTAP SVM에 대해 NFSv4.2를 활성화 또는 비활성화합니다]
* https://docs.netapp.com/us-en/ontap/task_nas_enable_linux_nfs.html["ONTAP 시스템 관리자를 사용하여 NFS를 사용하여 Linux 서버에 NAS 스토리지 활성화"]




 a| 
xref:../concepts/path-failover-concept.html#nas-path-failover[LIF 페일오버 개선]
 a| 
ONTAP 시스템 정의 페일오버 그룹 정책은 NAS 데이터 LIF의 페일오버 대상을 동적으로 확장하여 클러스터 내 사용 가능한 모든 노드의 브로드캐스트 도메인에 있는 사용 가능한 포트를 포함할 수 있도록 합니다. 시스템 정의 정책은 모든 페일오버 그룹에 적용할 수 있습니다. ONTAP 9.19.1 이전 버전에서는 이 정책이 적용된 LIF는 클러스터 내에서 다른 하나의 노드로만 페일오버할 수 있었습니다. 해당 노드가 쿼럼을 충족하지 못하면 다른 노드를 사용할 수 있더라도 LIF는 페일오버되지 않았습니다.

|===


== 산

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
xref:../san-config/configure-fc-nvme-hosts-ha-pairs-reference.html[직접 연결 FC 구성 지원]
 a| 
FC 및 FC-NVMe 호스트를 ONTAP 스토리지에 연결하는 데 FC 스위치는 필요하지 않습니다. 호스트는 AFF, ASA 및 FAS 시스템의 FC 어댑터 포트에 직접 연결할 수 있습니다. 이러한 직접 연결은 특히 단순성이 중요한 원격 사이트 및 하이브리드 환경에서 유용합니다.



 a| 
xref:../san-admin/multipath-automatic-lif-failover-support.html[AFF 시스템에서 액티브-액티브 다중 경로 지원]
 a| 
AFF 시스템은 SAN 환경에서 액티브-액티브 다중 경로를 지원합니다. 액티브-액티브 구성에서 LUN 또는 네임스페이스를 소유하는 HA 쌍 내의 모든 경로는 액티브 최적화되어 스토리지 페일오버 발생 시 호스트가 페일오버 경로의 ALUA 또는 ANA 전환을 기다리지 않고 I/O를 재개할 수 있습니다. 이를 통해 페일오버 시간을 단축하여 SAN 고객은 기존에는 ASA 시스템에서만 가능했던 무중단 경로 복원력과 로드 밸런싱 기능을 AFF 시스템에서 미션 크리티컬 워크로드에 적용할 수 있습니다.



 a| 
xref:../san-admin/multipath-automatic-lif-failover-support.html[자동 SAN LIF 페일오버에 대한 지원 강화]
 a| 
AFF 및 ASA 시스템에서는 활성-활성 및 활성-활성-SCSI 전용 다중 경로 구성의 iSCSI 프로토콜 LIF와 활성-활성 다중 경로 구성의 NVMe/TCP 프로토콜 LIF에 대해 자동 LIF 페일오버가 지원됩니다.



 a| 
link:https://docs.netapp.com/us-en/ontap-fli/get-started/learn-about-data-migration.html["iSCSI 프로토콜에 대한 외부 LUN 가져오기 지원"^]
 a| 
FLI(Foreign LUN Import)는 백엔드 연결을 위해 iSCSI 프로토콜을 지원합니다.

|===


== S3 오브젝트 스토리지

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
xref:../s3-config/create-modify-bucket-policy-task.html[ONTAP S3는 적용을 통한 조건부 쓰기 및 삭제를 지원합니다]
 a| 
조건을 사용하여 객체 업로드에 대한 조건부 쓰기 및 객체 삭제에 대한 조건부 삭제를 적용할 수 있습니다. 조건부 쓰기 및 삭제는 객체의 덮어쓰기 또는 의도치 않은 삭제를 방지하는 방법을 제공합니다.



 a| 
xref:../s3-config/regenerate-access-keys.html[ONTAP S3 키]
 a| 
기존 액세스 키가 만료되더라도 S3 리소스에 대한 사용자 액세스를 유지하기 위해 ONTAP 클러스터 관리자는 각 S3 사용자에 대해 두 번째 액세스 키를 생성할 수 있습니다.

|===


== 보안

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
System Manager UI에서 ARP 워크로드 특성이 제거되었습니다.
 a| 
System Manager에서 자율형 랜섬웨어 방지(ARP) 워크로드 특성(기준 통계 및 급증 통계 포함)이 더 이상 표시되지 않습니다. 급증 활동이 실제 랜섬웨어 공격 또는 수동 조정이 필요한 상황으로 오해되는 경우가 빈번했기 때문에 해당 정보가 제거되었습니다.

ARP 동작 및 탐지는 변경되지 않았으며, System Manager에서 이러한 세부 정보를 표시하는 방식만 영향을 받습니다. 서지 통계는 고급 분석을 위해 ONTAP CLI 및 REST API 옵션을 사용하여 계속 사용할 수 있습니다



 a| 
xref:../anti-ransomware/use-cases-restrictions-concept.html#supported-configurations[SnapMirror 동기식 및 SnapMirror 활성 동기화에 대한 자율형 랜섬웨어 보호 지원]
 a| 
ARP/AI는 지원되는 플랫폼에서 SnapMirror 동기식(NAS 및 SAN) 및 SnapMirror 활성 동기화 SAN 관계에 참여하는 볼륨을 지원합니다. ARP/AI는 FAS, AFF 및 AFX 시스템의 SnapMirror 동기식 관계에서 기본 볼륨을, AFF 및 ASA r2 시스템의 SnapMirror 활성 동기화 SAN 관계에서 기본 볼륨을 보호할 수 있습니다. ARP/AI는 관계에서 활성 상태인 읽기/쓰기 가능 기본 볼륨에서 실행되어 기본 볼륨 전용 ARP 스냅샷을 생성하고 머신 러닝 기반 랜섬웨어 탐지 기능을 제공합니다.


NOTE: ONTAP 9.19.1 RC로 업그레이드하고 SnapMirror 동기 또는 SnapMirror 활성 동기화 관계에 있는 볼륨에서 ARP를 활성화하면 관계가 일시적으로 동기화되지 않을 수 있습니다. 이 현상은 일시적이며, 별도의 조치 없이 관계가 자동으로 재동기화됩니다.



 a| 
xref:../networking/configure-tls-offload.html[TLS 오프로드 구성]
 a| 
TLS 오프로드를 구성하면 지원되는 이더넷 카드의 리소스를 활용하여 TLS 핸드셰이크 후 성능을 향상시킬 수 있습니다. 이 기능은 암호화 및 복호화를 오프로드하여 CPU 오버헤드를 줄이고 성능을 개선합니다.

|===


== 스토리지 효율성

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
xref:../flexcache/index.html[NAS 성능 향상]
 a| 
ONTAP 9.19.1은 작은 NAS 디렉터리의 목록 조회 요청을 처리하는 데 더 많은 CPU 리소스를 제공합니다. 이 개선 사항은 수백에서 수천 대의 클라이언트가 동시에 동일한 2MB 이하(약 25,000개 파일)의 작은 NAS 디렉터리를 조회하는 고객에게 유용합니다.

이 개선 사항은 디렉터리 목록을 조회하는 클라이언트 수가 많은 경우 로컬 FlexCache 볼륨과 같은 임시 해결책을 사용할 필요성을 줄여줍니다. 클라이언트 수가 적은 경우에는 성능에 부정적인 영향을 미치지 않습니다. 이 성능 향상은 자동으로 적용되며 구성이 필요하지 않습니다.

|===


== 스토리지 리소스 관리 기능 향상

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
xref:../concepts/capacity-measurements.html[향상된 볼륨 공간 보고]
 a| 
 `volume show-space` 명령을 사용하여 볼륨 내 공간 사용량에 대한 세부 정보를 볼 수 있습니다. ONTAP 9.19.1부터 공간 보고에 사용되는 디렉토리가 명령 출력에 포함됩니다.



 a| 
xref:../performance-admin/guarantee-throughput-qos-task.html[자동 QoS 처리량 상한 증가를 제어하는 기본 설정을 수정하는 기능에 대한 지원이 제공됩니다.]
 a| 
QoS 정책 그룹이 단기적인 성능 향상 요구에 대응하여 QoS 처리량 상한을 자동으로 높이는 방식을 제어하는 기본 설정을 수정할 수 있습니다. 이러한 설정은 ONTAP 9.18.1 이하 버전에서는 수정할 수 없습니다.

|===


== 시스템 관리자

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
xref:../concept-svm-admin-dashboard-sm.html[새로운 ONTAP System Manager 대시보드를 사용하여 SVM을 모니터링하고 관리합니다]
 a| 
새로운 전용 대시보드를 통해 SVM 관리자는 자신의 SVM을 모니터링하고 관리할 수 있습니다. 이는 특히 테넌트 기반 ONTAP 환경에서 유용하며, 클러스터 관리자가 각 테넌트에 SVM 대시보드를 제공할 수 있습니다.

|===


== 업그레이드

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
xref:../upgrade/automated-pre-checks.html[자동 업그레이드 사전 점검을 위한 향상된 보고]
 a| 
자동화된 업그레이드 전 검사를 실행할 때 오류와 경고가 별도로 표시되어 업그레이드 전에 해결해야 할 문제를 쉽게 파악할 수 있습니다.

|===