---
permalink: fabricpool/move-volume-task.html 
sidebar: sidebar 
keywords: aggregate, local tier, moving, volume, fabricpool, fabric pool, tiering, policy, policies, block, capacity, cold data, 
summary: '로컬 계층, 연결된 클라우드 계층 및 볼륨(볼륨 계층화 정책)에서 발생하는 변경 사항이 기능에 큰 영향을 미칠 수 있으므로 FabricPool에서 볼륨 이동이 어떻게 작동하는지 이해하는 것이 중요합니다.' 
---
= 볼륨을 FabricPool 지원 ONTAP 로컬 계층으로 이동
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A는 link:../volumes/move-volume-task.html["볼륨 이동"]ONTAP가 하나의 로컬 계층(소스)에서 다른 타겟(타겟)으로 볼륨을 중단 없이 이동하는 방법입니다. 하드웨어 라이프사이클 관리, 클러스터 확장 및 로드 밸런싱이 가장 일반적인 이유이지만 볼륨 이동은 다양한 이유로 수행할 수 있습니다.

로컬 계층, 연결된 클라우드 계층 및 볼륨(볼륨 계층화 정책)에서 발생하는 변경 사항이 기능에 큰 영향을 미칠 수 있으므로 FabricPool에서 볼륨 이동이 어떻게 작동하는지 이해하는 것이 중요합니다.


NOTE: ONTAP 9.7 이전에는 System Manager에서 _aggregate_를 사용하여 _ 로컬 계층을 설명합니다. ONTAP 버전에 관계없이 ONTAP CLI에서는 _aggregate_라는 용어를 사용합니다. 로컬 계층에 대한 자세한 내용은 을 link:../disks-aggregates/index.html["디스크 및 로컬 계층"]참조하십시오.



== 대상 로컬 계층

볼륨 이동의 타겟 로컬 계층에 연결된 클라우드 계층이 없는 경우 클라우드 계층에 저장된 소스 볼륨의 데이터가 타겟 로컬 계층의 로컬 계층에 기록됩니다.

ONTAP 9.8부터 볼륨을 활성화한 경우 link:determine-data-inactive-reporting-task.html["비활성 데이터 보고"]FabricPool는 볼륨의 Heat Map을 사용하여 콜드 데이터가 대상 로컬 계층에 기록되는 즉시 계층화를 시작합니다.

ONTAP 9.8 이전에는 볼륨을 다른 로컬 계층으로 이동하면 로컬 계층에서 블록의 비활성 기간이 재설정됩니다. 예를 들어, 로컬 계층에 20일 동안 비활성 상태였지만 아직 계층화되지 않은 데이터가 있는 자동 볼륨 계층화 정책을 사용하는 볼륨은 볼륨 이동 후 데이터 온도가 0일로 재설정됩니다.



== 최적화된 볼륨 이동

ONTAP 9.6부터 볼륨 이동의 타겟 로컬 계층이 소스 로컬 계층과 동일한 버킷을 사용할 경우 버킷에 저장된 소스 볼륨의 데이터가 로컬 계층으로 다시 이동하지 않습니다. 계층화된 데이터는 사용되지 않고 핫 데이터만 로컬 계층 간에 이동되어야 합니다. 이렇게 최적화된 볼륨 이동을 통해 네트워크 효율성이 크게 향상됩니다.

예를 들어, 300TB의 최적화된 볼륨 이동은 300TB의 콜드 데이터가 한 로컬 계층에서 다른 로컬 계층으로 이동하더라도 개체 저장소에 대한 300TB의 읽기 및 300TB의 쓰기가 트리거되지 않음을 의미합니다.

최적화되지 않은 볼륨 이동은 추가 네트워크 및 컴퓨팅 트래픽(읽기/가져오기 및 쓰기/출력)을 생성하여 ONTAP 클러스터 및 오브젝트 저장소에 대한 수요를 증가시키며, 퍼블릭 오브젝트 저장소로 계층화할 때 비용이 상승할 가능성이 있습니다.

[NOTE]
====
일부 구성은 최적화된 볼륨 이동과 호환되지 않습니다.

* 볼륨 이동 중에 계층화 정책 변경
* 서로 다른 암호화 키를 사용하는 소스 및 대상 로컬 계층
* FlexClone 볼륨
* FlexClone 상위 볼륨
* MetroCluster(ONTAP 9.8 이상에서 최적화된 볼륨 이동 지원)
* 동기화되지 않은 FabricPool 미러 버킷


====
볼륨 이동의 대상 로컬 계층에 연결된 클라우드 계층이 있는 경우 클라우드 계층에 저장된 소스 볼륨의 데이터가 먼저 대상 로컬 계층의 로컬 계층에 기록됩니다. 그런 다음 이 접근 방식이 볼륨의 계층화 정책에 적합한 경우 대상 로컬 계층의 클라우드 계층에 기록됩니다.

먼저 로컬 계층에 데이터를 기록하면 볼륨 이동 성능이 향상되고 컷오버 시간이 단축됩니다. 볼륨 이동을 수행할 때 볼륨 계층화 정책이 지정되지 않으면 타겟 볼륨이 소스 볼륨의 계층화 정책을 사용합니다.

볼륨 이동을 수행할 때 다른 계층화 정책을 지정하면 지정된 계층화 정책으로 타겟 볼륨이 생성되고 볼륨 이동이 최적화되지 않습니다.



=== 볼륨 메타데이터

볼륨 이동 최적화 여부와 관계없이 ONTAP은 로컬 및 계층형 데이터의 위치, 스토리지 효율성, 권한, 사용 패턴 등에 대한 상당한 양의 메타데이터를 저장합니다. 메타데이터는 항상 로컬 계층에 저장되며 계층화되지 않습니다. 볼륨이 한 로컬 계층에서 다른 로컬 계층으로 이동되는 경우 이 정보도 대상 로컬 계층으로 이동해야 합니다.



=== 기간

볼륨 이동에는 여전히 시간이 걸리며, 최적화된 볼륨 이동에는 계층화되지 않은 동일한 양의 데이터를 이동하는 데 걸리는 시간과 거의 같을 것으로 예상됩니다.

"처리량"이 보고된다는 것을 이해하는 것이 중요합니다.  `volume move show` 명령은 클라우드 계층에서 이동하는 데이터 측면에서 처리량을 나타내는 것이 아니라 로컬에서 업데이트되는 볼륨 데이터를 나타냅니다.


NOTE: SVM DR 관계에서는 소스 및 타겟 볼륨이 동일한 계층화 정책을 사용해야 한다.

.단계
. 명령을 사용하여 `volume move start` 볼륨을 소스 로컬 계층에서 대상 로컬 계층으로 이동합니다.


.볼륨 이동의 예
다음 예에서는 `vs1` SVM이라는 볼륨을 FabricPool 지원 로컬 계층으로 `dest_FabricPool` 이동합니다 `myvol2`.

[listing]
----
cluster1::> volume move start -vserver vs1 -volume myvol2
-destination-aggregate dest_FabricPool
----