---
permalink: fabricpool/move-volume-task.html 
sidebar: sidebar 
keywords: aggregate, local tier, moving, volume, fabricpool, fabric pool, tiering, policy, policies, block, capacity, cold data, 
summary: '로컬 계층, 연결된 클라우드 계층 및 볼륨(볼륨 계층화 정책)에서 발생하는 변경 사항이 기능에 큰 영향을 미칠 수 있으므로 FabricPool에서 볼륨 이동이 어떻게 작동하는지 이해하는 것이 중요합니다.' 
---
= 볼륨을 FabricPool 지원 ONTAP 로컬 계층으로 이동
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A는 link:../volumes/move-volume-task.html["볼륨 이동"]ONTAP가 하나의 로컬 계층(소스)에서 다른 타겟(타겟)으로 볼륨을 중단 없이 이동하는 방법입니다. 하드웨어 라이프사이클 관리, 클러스터 확장 및 로드 밸런싱이 가장 일반적인 이유이지만 볼륨 이동은 다양한 이유로 수행할 수 있습니다.

로컬 계층, 연결된 클라우드 계층 및 볼륨(볼륨 계층화 정책)에서 발생하는 변경 사항이 기능에 큰 영향을 미칠 수 있으므로 FabricPool에서 볼륨 이동이 어떻게 작동하는지 이해하는 것이 중요합니다.


NOTE: ONTAP 9.7 이전에는 System Manager에서 _aggregate_를 사용하여 _ 로컬 계층을 설명합니다. ONTAP 버전에 관계없이 ONTAP CLI에서는 _aggregate_라는 용어를 사용합니다. 로컬 계층에 대한 자세한 내용은 을 link:../disks-aggregates/index.html["디스크 및 로컬 계층"]참조하십시오.



== 대상 로컬 계층

볼륨 이동의 타겟 로컬 계층에 연결된 클라우드 계층이 없는 경우 클라우드 계층에 저장된 소스 볼륨의 데이터가 타겟 로컬 계층의 로컬 계층에 기록됩니다.

ONTAP 9.8부터 볼륨을 link:determine-data-inactive-reporting-task.html["비활성 데이터 보고"]활성화한 경우 FabricPool는 볼륨의 Heat Map을 사용하여 콜드 데이터가 대상 애그리게이트에 쓰이는 즉시 계층화를 시작합니다.

ONTAP 9.8 이전에는 볼륨을 다른 로컬 계층으로 이동하면 로컬 계층에서 블록의 비활성 기간이 재설정됩니다. 예를 들어, 로컬 계층에 20일 동안 비활성 상태였지만 아직 계층화되지 않은 데이터가 있는 자동 볼륨 계층화 정책을 사용하는 볼륨은 볼륨 이동 후 데이터 온도가 0일로 재설정됩니다.



== 최적화된 볼륨 이동

ONTAP 9.6부터 볼륨 이동의 타겟 로컬 계층이 소스 로컬 계층과 동일한 버킷을 사용할 경우 버킷에 저장된 소스 볼륨의 데이터가 로컬 계층으로 다시 이동하지 않습니다. 이렇게 최적화된 볼륨 이동을 통해 네트워크 효율성이 크게 향상됩니다.

[NOTE]
====
일부 구성은 최적화된 볼륨 이동과 호환되지 않습니다.

* 볼륨 이동 중에 계층화 정책 변경
* 소스 및 대상 애그리게이트에서 각각 다른 암호화 키를 사용
* FlexClone 볼륨
* FlexClone 상위 볼륨
* MetroCluster(ONTAP 9.8 이상에서 최적화된 볼륨 이동 지원)
* 동기화되지 않은 FabricPool 미러 버킷


====
볼륨 이동의 대상 로컬 계층에 연결된 클라우드 계층이 있는 경우 클라우드 계층에 저장된 소스 볼륨의 데이터가 먼저 대상 로컬 계층의 로컬 계층에 기록됩니다. 그런 다음 이 접근 방식이 볼륨의 계층화 정책에 적합한 경우 대상 로컬 계층의 클라우드 계층에 기록됩니다.

먼저 로컬 계층에 데이터를 기록하면 볼륨 이동 성능이 향상되고 컷오버 시간이 단축됩니다. 볼륨 이동을 수행할 때 볼륨 계층화 정책이 지정되지 않으면 타겟 볼륨이 소스 볼륨의 계층화 정책을 사용합니다.

볼륨 이동을 수행할 때 다른 계층화 정책을 지정하면 지정된 계층화 정책으로 타겟 볼륨이 생성되고 볼륨 이동이 최적화되지 않습니다.


NOTE: SVM DR 관계에서는 소스 및 타겟 볼륨이 동일한 계층화 정책을 사용해야 한다.

.단계
. 명령을 사용하여 `volume move start` 볼륨을 소스 로컬 계층에서 대상 로컬 계층으로 이동합니다.


.볼륨 이동의 예
다음 예에서는 `vs1` SVM이라는 볼륨을 FabricPool 지원 로컬 계층으로 `dest_FabricPool` 이동합니다 `myvol2`.

[listing]
----
cluster1::> volume move start -vserver vs1 -volume myvol2
-destination-aggregate dest_FabricPool
----