---
permalink: fabricpool/move-volume-task.html 
sidebar: sidebar 
keywords: aggregate, local tier, moving, volume, fabricpool, fabric pool, tiering, policy, policies, block, capacity, cold data, 
summary: 볼륨을 FabricPool로 이동할 때 이동 시 볼륨에 대한 계층화 정책을 지정하거나 변경할 수 있습니다. FabricPool 9.8부터 비활성 데이터 보고가 활성화된 비 FabricPool 볼륨을 이동할 때 ONTAP은 열 맵을 사용하여 참을 수 있는 블록을 읽고 콜드 데이터를 FabricPool 대상의 용량 계층으로 이동합니다. 
---
= 볼륨을 FabricPool 지원 ONTAP 로컬 계층으로 이동
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨을 FabricPool로 이동할 때 이동 시 볼륨에 대한 계층화 정책을 지정하거나 변경할 수 있습니다. FabricPool 9.8부터 비활성 데이터 보고가 활성화된 비 FabricPool 볼륨을 이동할 때 ONTAP은 열 맵을 사용하여 참을 수 있는 블록을 읽고 콜드 데이터를 FabricPool 대상의 용량 계층으로 이동합니다.


NOTE: ONTAP 9.7 이전에는 System Manager에서 _aggregate_를 사용하여 _ 로컬 계층을 설명합니다. ONTAP 버전에 관계없이 ONTAP CLI에서는 _aggregate_라는 용어를 사용합니다. 로컬 계층에 대한 자세한 내용은 을 link:../disks-aggregates/index.html["디스크 및 로컬 계층"]참조하십시오.

.시작하기 전에
계층화 정책을 변경하면 데이터가 콜드 상태가 되어 클라우드 계층으로 이동하는 데 걸리는 시간이 영향을 받을 수 있음을 이해해야 합니다.

link:tiering-policies-concept.html#what-happens-to-the-tiering-policy-when-you-move-a-volume["볼륨을 이동할 때 계층화 정책은 어떻게 됩니까"]

.이 작업에 대해
비 FabricPool 볼륨에 비활성 데이터 보고가 활성화되어 있는 경우 계층화 정책에 따라 볼륨을 `snapshot-only` FabricPool로 이동할 때 `auto` FabricPool은 히트 맵 파일에서 온도가 허용 가능한 블록을 읽고 계층화 정책이 비 FabricPool 볼륨에서 로 설정되면 `auto` FabricPool은 해당 온도를 사용하여 콜드 데이터를 FabricPool 대상의 용량 계층으로 직접 이동합니다.

ONTAP 9.8을 사용 중이고 FabricPool에서 비활성 데이터 보고 정보를 사용하여 데이터를 용량 계층으로 직접 이동하려는 경우 볼륨 이동 시 '-Tiering-Policy' 옵션을 사용해서는 안 됩니다. 이 옵션을 사용하면 FabricPool이 온도 데이터를 무시하고 ONTAP 9.8 이전의 릴리스의 이동 동작을 따릅니다.

.단계
. 볼륨을 FabricPool로 이동하려면 'volume move start' 명령을 사용합니다.
+
'-Tiering-policy' 선택적 매개 변수를 사용하면 볼륨에 대한 계층화 정책을 지정할 수 있습니다.

+
다음 계층화 정책 중 하나를 지정할 수 있습니다.

+
** '스냅샷 전용'(기본값)
** 자동
** 모두
** "없음" +link:tiering-policies-concept.html#types-of-fabricpool-tiering-policies["FabricPool 계층화 정책의 유형입니다"]




.볼륨을 FabricPool로 이동하는 예
다음 예에서는 "VS1" SVM의 ""myvol2""라는 볼륨을 "dest_FabricPool" FabricPool 지원 로컬 계층으로 이동합니다. 볼륨이 명시적으로 계층화 정책을 사용하도록 설정되어 `none` 있습니다.

[listing]
----
cluster1::> volume move start -vserver vs1 -volume myvol2
-destination-aggregate dest_FabricPool -tiering-policy none
----