---
permalink: fabricpool/setup-ontap-s3-cloud-tier-task.html 
sidebar: sidebar 
keywords: tr-4814, fabricpool, setting up, ontap s3, cloud tier, local tier, tiering, storage tiering, storage tier, lif 
summary: ONTAP 9.8 이상을 실행 중인 경우 ONTAP S3를 FabricPool의 클라우드 계층으로 설정할 수 있습니다. 
---
= ONTAP S3를 FabricPool 클라우드 계층으로 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.8 이상을 실행 중인 경우 ONTAP S3를 FabricPool의 클라우드 계층으로 설정할 수 있습니다.

.시작하기 전에
* 원격 클러스터에 연결된 LIF의 ONTAP S3 서버 이름과 IP 주소가 있어야 합니다.
+

NOTE: 서버 이름은 클라이언트 응용 프로그램에서 FQDN(정규화된 도메인 이름)으로 사용됩니다. ONTAP 외부에서 DNS 레코드가 사용 중인 SVM 데이터 LIF와 일치하는지 확인합니다.

* 로컬 클러스터에 있어야 <<create-lif,클러스터 간 LIF>>합니다.
+
로컬 클러스터 계층화를 위해 구성하면 로컬 계층(ONTAP CLI에서 스토리지 애그리게이트라고도 함)이 로컬 버킷에 연결됩니다. FabricPool는 클러스터 간 트래픽에 클러스터 LIF를 사용합니다.

+

NOTE: 클러스터 LIF 리소스가 포화 상태가 되면 성능 저하가 발생할 수 있습니다. 이를 방지하기 위해 NetApp은 로컬 버킷에 계층화할 때 로컬 계층의 HA 쌍, 로컬 버킷의 HA 쌍 등과 함께 4노드 이상 클러스터를 사용하는 것이 좋습니다. 단일 HA 쌍에서 로컬 버킷으로 계층화하는 것은 권장되지 않습니다.

* ONTAP S3를 사용하여 원격 FabricPool 용량(클라우드) 계층화를 사용하려면 FabricPool 클라이언트와 link:../s3-config/create-data-lifs-task.html["데이터 LIF 구성"]오브젝트 저장소 서버에 있어야 합니다link:../s3-config/create-intercluster-lifs-remote-fabricpool-tiering-task.html["인터클러스터 LIF를 구성합니다"].


.이 작업에 대해
ONTAP 9.8 이상에서 ONTAP S3 서버에 대해 로드 밸런싱이 활성화됩니다. 서버의 호스트 이름이 둘 이상의 IP 주소로 확인되는 경우 ONTAP는 반환된 모든 IP 주소(최대 16개의 IP 주소)를 사용하여 클라이언트 연결을 설정합니다. 연결이 설정되면 IP 주소가 라운드 로빈 방식으로 선택됩니다.

.단계
ONTAP System Manager 또는 ONTAP CLI를 사용하여 ONTAP S3를 FabricPool용 클라우드 계층으로 설정할 수 있습니다.

[role="tabbed-block"]
====
.시스템 관리자
--
. 스토리지 > 계층 > 클라우드 계층 추가 * 를 클릭하고 오브젝트 저장소 공급자로 ONTAP S3를 선택합니다.
. 요청된 정보를 완료합니다.
. 클라우드 미러를 생성하려면 * FabricPool 미러로 추가 * 를 클릭합니다.


FabricPool 미러는 데이터 저장소를 원활하게 대체할 수 있는 방법을 제공하므로 재해 발생 시 데이터를 사용할 수 있습니다.

--
.CLI를 참조하십시오
--
. S3 서버 및 LIF에 대한 항목을 DNS 서버에 추가합니다.
+
|===


| 옵션을 선택합니다 | 설명 


 a| 
* 외부 DNS 서버를 사용하는 경우 *
 a| 
DNS 서버 관리자에게 S3 서버 이름 및 IP 주소를 지정합니다.



 a| 
* 로컬 시스템의 DNS 호스트 테이블을 사용하는 경우 *
 a| 
다음 명령을 입력합니다.

[listing]
----
dns host create -vserver <svm_name> -address ip_address -hostname <s3_server_name>
----
|===
. '-provider-type ''ontap_s3' 파라미터를 사용하여 'storage aggregate object-store config create' 명령을 사용하여 ONTAP S3 구성 정보를 지정합니다.
+
** 로컬 ONTAP 시스템이 제공된 정보로 ONTAP S3 서버에 액세스할 수 없으면 'Storage aggregate object-store config create' 명령이 실패합니다.
** '-access-key' 매개 변수를 사용하여 ONTAP S3 서버에 요청을 승인하는 데 필요한 액세스 키를 지정할 수 있습니다.
** '-secret-password' 매개변수를 사용하여 ONTAP S3 서버에 대한 요청을 인증하는 암호(비밀 액세스 키)를 지정합니다.
** ONTAP S3 서버 암호가 변경되면 로컬 ONTAP 시스템에 저장된 해당 암호를 즉시 업데이트해야 합니다.
+
이렇게 하면 ONTAP S3 오브젝트 저장소에서 중단 없이 데이터에 액세스할 수 있습니다.

** 매개 변수를 로 `false` 설정하면 `-is-certificate-validation-enabled` ONTAP S3에 대한 인증서 검사가 비활성화됩니다. (`-is-certificate-validation-enabled true`타사 인증 기관에서 서명한 인증서를 사용하는 것이 좋습니다.


+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name myS3 -provider-type ONTAP_S3 -server myS3server
-container-name myS3container -access-key myS3key
-secret-password myS3pass
----
. 'Storage aggregate object-store config show' 명령을 사용하여 ONTAP_S3 구성 정보를 표시하고 확인합니다.
+
'Storage aggregate object-store config modify' 명령을 사용하면 FabricPool의 'ontap_s3' 구성 정보를 수정할 수 있습니다.



--
====
[[create-lif]]
.관련 정보
* link:../smb-config/create-lif-task.html["SMB용 LIF를 생성합니다"]
* link:../nfs-config/create-lif-task.html["NFS용 LIF를 생성합니다"]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-create.html["저장소 집계 객체-저장소 구성 생성"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-object-store-config-modify.html["저장소 집계 객체 저장소 구성 수정"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-show.html["저장소 집계 객체-저장소 구성 표시"^]

