---
permalink: fabricpool/tiering-policies-concept.html 
sidebar: sidebar 
keywords: understanding, fabricpool, tiering, policies, types, modify, volume, clone, cloud migration 
summary: FabricPool 계층화 정책을 사용하면 데이터가 핫 또는 콜드 데이터가 될 때 계층 간에 데이터를 효율적으로 이동할 수 있습니다. 계층화 정책을 이해하면 스토리지 관리 요구 사항에 적합한 정책을 선택할 수 있습니다. 
---
= FabricPool 볼륨 계층화 정책
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool 볼륨 계층화 정책은 볼륨에서 어떤 데이터가 계층화 대상이 될 수 있는지 결정하며, 계층화 최소 냉각 일수 매개변수는 데이터가 비활성 상태로 간주되어 계층화 대상이 되는 시점을 결정합니다.

[NOTE]
====
액세스 제어 목록(ACL), 디렉터리 구조 및 메타데이터는 계층화되지 않고 항상 로컬 계층에 유지됩니다.

====
매일 백그라운드에서 실행되는 티어링 스캔을 통해 콜드 블록을 찾습니다. 동일한 볼륨에서 충분한 수의 4KB 블록이 수집되면, 이 블록들을 연결하여 4MB 객체로 만들고 볼륨 티어링 정책에 따라 클라우드 티어로 이동시킵니다.

계층화 정책의 작동 방식을 이해하면 스토리지 관리 요구 사항에 맞는 올바른 정책을 선택하는 데 도움이 됩니다.



== 볼륨 계층화 정책 옵션

기본적으로 볼륨은 None 볼륨 계층화 정책을 사용합니다. 이에 대한 예외는 FabricPool 애그리게이트에 새로 생성되어 Snapshot-Only 볼륨 계층화 정책을 사용하는 FlexVol 볼륨입니다.

명령을 사용하여 FabricPool 볼륨의 계층화 상태를 확인할 수 있다 `volume object-store tiering show`. 에 대한 자세한 내용은 `volume object-store tiering show` link:https://docs.netapp.com/us-en/ontap-cli//volume-object-store-tiering-show.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

FabricPool 계층화 정책은 볼륨 레벨에서 지정됩니다. 다음 4가지 옵션을 사용할 수 있습니다.



=== 스냅샷 전용

 `snapshot-only` 계층화 정책은 액티브 파일 시스템과 더 이상 연결되지 않은 스냅샷 데이터를 계층화합니다. 기본적으로 스냅샷이 계층화될 자격을 얻으려면 2일 동안 활동이 없어야 합니다. 대부분의 데이터 보호 일정은 시간별 또는 일별로 설정되어 있으며, 계층화하기 전에 데이터를 로컬에서 읽습니다.

 `-tiering-minimum-cooling-days` 매개변수를  `volume create` 및  `volume modify` 명령의 고급 권한 수준에서 사용하여 티어링 최소 냉각 기간의 기본 설정을 수정할 수 있습니다. ONTAP 9.8 이상을 사용하는 경우 유효 값은 2일에서 183일까지입니다. ONTAP 9.8 이전 버전을 사용하는 경우 유효 값은 2일에서 63일까지입니다.

읽기 시 스냅샷 복사본과 관련된 콜드 블록은 콜드 상태를 유지하며 로컬 계층에 다시 기록되지 않습니다.



=== 자동

The `auto` 티어링 정책은 볼륨 내의 모든 콜드 데이터(스냅샷 및 액티브 파일 시스템)를 클라우드 티어로 이동합니다. 기본 티어링 최소 냉각 기간은 31일이며 액티브 파일 시스템과 스냅샷을 포함한 전체 볼륨에 적용됩니다.

볼륨 생성 및 볼륨 수정 명령의 고급 권한 수준에서 '-Tiering-Minimum-Cooling-Days' 매개 변수를 사용하여 계층화 최소 냉각 기간의 기본 설정을 수정할 수 있습니다. 유효한 값은 2 ~ 183일입니다.

티어링 정책이 Auto로 설정된 볼륨에서 무작위로 읽을 때 콜드 블록이 핫 블록으로 바뀌어 로컬 티어에 다시 기록됩니다.

계층화 정책이 Auto로 설정된 볼륨에서 순차적으로 읽을 때, 콜드 블록은 콜드 상태로 유지되며 클라우드 계층에 남아 있습니다. 이러한 블록은 로컬 계층에 다시 기록되지 않습니다.



=== 모두

The `all` 티어링 정책을 사용하면 볼륨의 모든 데이터가 즉시 콜드 데이터로 표시되고 가능한 한 빨리 클라우드 티어로 티어링이 시작됩니다.  `all` 티어링 정책을 사용하는 볼륨에서는 새 블록이 콜드 데이터가 될 때까지 48시간을 기다릴 필요가 없습니다.

계층화 검사가 실행되는 즉시 데이터가 클라우드 계층으로 이동하므로 계층화 최소 냉각 기간은 적용되지 않으며 설정을 수정할 수 없습니다.

계층화 정책이 All로 설정된 볼륨에서 콜드 블록을 읽으면 해당 블록은 콜드 상태로 클라우드 계층에 유지됩니다. 로컬 계층에는 기록되지 않습니다.

[NOTE]
====
를 클릭합니다 `all` 볼륨 계층화 정책은 정상적인 클라이언트 트래픽이 있는 읽기/쓰기 볼륨에서 사용하면 안 됩니다.

객체 스토리지는 파일이나 블록 스토리지처럼 트랜잭션 방식으로 작동하지 않습니다. '모든(All)' 계층화 정책을 사용하는 볼륨에 객체로 저장된 파일을 변경하면 새 객체가 생성되거나 기존 객체가 조각화되고, 읽기 성능이 저하되며, 스토리지 효율성이 떨어질 수 있습니다.

====


=== 없음

The `none` 계층화 정책은 볼륨의 데이터를 성능 계층에 유지하고 데이터 자체를 계층화하지 않습니다.

계층화 정책을 으로 설정합니다 `none` 새로운 계층화를 방지합니다. 이전에 클라우드 계층으로 이동된 볼륨 데이터는 핫 데이터가 되고 로컬 계층으로 자동으로 다시 이동될 때까지 클라우드 계층에 남아 있습니다.

데이터가 클라우드 계층으로 이동되지 않으므로 계층화 최소 냉각 기간은 적용되지 않으며 설정을 수정할 수 없습니다.

계층화 정책이 으로 설정된 볼륨의 콜드 블록입니다 `none` 읽으면 핫 데이터가 되고 로컬 계층에 기록됩니다.

'volume show' 명령 출력에는 볼륨의 계층화 정책이 표시됩니다. FabricPool에 사용된 적이 없는 볼륨은 출력에 "없음" 계층화 정책을 표시합니다.


NOTE: SVM DR 관계인 경우 소스 및 타겟 볼륨에서 FabricPool 애그리게이트를 사용할 필요가 없지만 동일한 계층화 정책을 사용해야 합니다.



== 볼륨 티어링 정책을 수정하면 어떻게 됩니까?

볼륨 수정 작업을 수행하여 볼륨의 계층화 정책을 수정할 수 있습니다. 계층화 정책을 변경하면 데이터가 콜드 상태가 되어 클라우드 계층으로 이동하는 데 걸리는 시간이 영향을 받을 수 있음을 이해해야 합니다.

* 계층화 정책을 '스냅샷 전용' 또는 '사용 안 함'에서 '자동'으로 변경하면 ONTAP는 사용자 데이터 블록이 이전에 클라우드 계층에 적합하지 않은 경우에도 이미 사용 중인 파일 시스템의 사용자 데이터 블록을 클라우드 계층으로 전송합니다.
* 계층화 정책을 다른 정책에서 로 `all` 변경하면 ONTAP는 액티브 파일 시스템 및 스냅샷의 모든 사용자 블록을 가능한 한 빨리 클라우드로 이동합니다. ONTAP 9.8 이전에는 다음 계층화 검사가 실행될 때까지 블록이 필요했습니다.
+
블록을 성능 계층으로 다시 이동할 수 없습니다.

* 계층화 정책을 'auto'에서 'napshot-only' 또는 'none'으로 변경해도 이미 클라우드 계층으로 이동된 액티브 파일 시스템 블록이 성능 계층으로 다시 이동되는 것은 아닙니다.
+
데이터를 성능 계층으로 다시 이동하는 데 볼륨 읽기가 필요합니다.

* 볼륨에 대한 계층화 정책을 변경할 때마다 계층화 최소 냉각 기간이 정책의 기본값으로 재설정됩니다.




== 볼륨을 이동할 때 계층화 정책은 어떻게 됩니까

* 다른 계층화 정책을 명시적으로 지정하지 않는 한, FabricPool 지원 Aggregate와 그 외부로 이동할 때 볼륨은 원래 계층화 정책을 유지합니다.
+
하지만 계층화 정책은 볼륨이 FabricPool 지원 애그리게이트에 있을 때만 적용됩니다.

* 대상에 대해 다른 계층화 정책을 지정하지 않으면 볼륨에 대한 '-Tiering-Minimum-Cooling-Days' 매개 변수의 기존 값이 볼륨과 함께 이동합니다.
+
다른 계층화 정책을 지정하는 경우 볼륨은 해당 정책에 대한 기본 계층화 최소 냉각 기간을 사용합니다. 대상이 FabricPool인지 여부에 관계없이 이 경우가 해당됩니다.

* 애그리게이트 전체에서 볼륨을 이동하는 동시에 계층화 정책을 수정할 수 있습니다.
* 볼륨 이동 작업에 자동 계층화 정책이 포함되는 경우 특히 주의해야 합니다.
+
소스 및 타겟이 FabricPool 지원 애그리게이트라고 가정하면 다음 표에는 'auto'와 관련된 정책 변경이 포함된 '볼륨 이동' 작업의 결과가 요약되어 있습니다.

+
|===


| 계층화 정책이 다음과 같은 볼륨을 이동하는 경우 | 다음으로 이동하여 계층화 정책을 변경합니다. | 그런 다음 볼륨 이동 후... 


 a| 
모두
 a| 
자동
 a| 
모든 데이터가 성능 계층으로 이동됩니다.



 a| 
'냅샷 전용', '없음' 또는 '자동'으로 표시됩니다
 a| 
자동
 a| 
데이터 블록이 이전에 소스에 있었던 것과 동일한 대상 계층으로 이동합니다.



 a| 
자동 또는 모두
 a| 
'냅샷 전용'
 a| 
모든 데이터가 성능 계층으로 이동됩니다.



 a| 
자동
 a| 
모두
 a| 
모든 사용자 데이터가 클라우드 계층으로 이동됩니다.



 a| 
'스냅샷 전용', '자동' 또는 '모두'입니다
 a| 
"없음"
 a| 
모든 데이터는 성능 계층에 보관됩니다.

|===




== 볼륨을 클론 복제할 때 계층화 정책은 어떻게 됩니까

* ONTAP 9.8부터 클론 볼륨은 항상 계층화 정책과 클라우드 검색 정책을 상위 볼륨에서 상속합니다.
+
ONTAP 9.8 이전 릴리즈에서는 상위 계층에 '모두' 계층화 정책이 있는 경우를 제외하고 클론이 상위 계층으로부터 계층화 정책을 상속합니다.

* 상위 볼륨에 클라우드 검색 정책이 없는 경우 해당 클론 볼륨에 클라우드 검색 정책이 '사용 안 함' 또는 '모두' 계층화 정책, 해당 클라우드 검색 정책 '기본값'이 있어야 합니다.
* 모든 클론 볼륨에 클라우드 검색 정책이 '사용 안 함'으로 되어 있지 않으면 상위 볼륨 클라우드 검색 정책을 '사용 안 함'으로 변경할 수 없습니다.


볼륨을 복제할 때 다음 Best Practice를 염두에 두십시오.

* 클론의 `-Tiering-policy ' 옵션과 ' Tiering-Minimum-Cooling-Days ' 옵션은 클론에만 적용되는 블록의 계층화 동작만 제어합니다. 따라서 동일한 양의 데이터를 이동하거나 모든 클론보다 적은 데이터를 이동하는 상위 FlexVol의 계층화 설정을 사용하는 것이 좋습니다
* 상위 FlexVol의 클라우드 검색 정책은 동일한 양의 데이터를 이동하거나 모든 클론의 검색 정책보다 더 많은 데이터를 이동해야 합니다




== 계층화 정책이 클라우드 마이그레이션과 작동하는 방식

FabricPool 클라우드 데이터 검색은 읽기 패턴에 따라 클라우드 계층에서 성능 계층으로 데이터 검색을 결정하는 계층화 정책을 통해 제어됩니다. 읽기 패턴은 순차적이거나 무작위일 수 있습니다.

다음 표에는 각 정책의 계층화 정책과 클라우드 데이터 검색 규칙이 나와 있습니다.

|===


| 계층화 정책 | 검색 동작 


 a| 
없음
 a| 
순차적 읽기 및 랜덤 읽기



 a| 
스냅샷 전용
 a| 
순차적 읽기 및 랜덤 읽기



 a| 
자동
 a| 
랜덤 읽기



 a| 
모두
 a| 
데이터를 검색할 수 없습니다

|===
ONTAP 9.8부터 클라우드 마이그레이션 제어 '클라우드 검색 정책' 옵션은 계층화 정책에 의해 제어되는 기본 클라우드 마이그레이션 또는 검색 동작을 재정의합니다.

다음 표에는 지원되는 클라우드 검색 정책과 검색 동작이 나와 있습니다.

|===


| 클라우드 검색 정책 | 검색 동작 


 a| 
기본값
 a| 
계층화 정책은 어떤 데이터를 다시 풀어야 할지 결정하므로 "기본값", "클라우드 검색 정책"을 통해 클라우드 데이터 검색에 대한 변경 사항은 없습니다. 이 정책은 호스팅된 애그리게이트 유형에 관계없이 모든 볼륨의 기본값입니다.



 a| 
읽기
 a| 
모든 클라이언트 기반 데이터 읽기는 클라우드 계층에서 성능 계층으로 가져옵니다.



 a| 
안 함
 a| 
클라우드 계층에서 성능 계층으로 클라이언트 기반 데이터를 끌어오는 기능은 없습니다



 a| 
승격
 a| 
* 계층화 정책의 경우 ""없음"", 모든 클라우드 데이터가 클라우드 계층에서 성능 계층으로 풀링됩니다
* 계층화 정책의 경우, "스냅샷 전용", AFS 데이터가 풀링됩니다.


|===
이 절차에서 설명하는 명령에 대한 자세한 내용은 를 link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP 명령 참조입니다"^]참조하십시오.
