---
permalink: system-admin/add-nodes-cluster-concept.html 
sidebar: sidebar 
keywords: add, node, cluster, create, expand 
summary: 클러스터가 생성된 후 노드를 추가하여 클러스터를 확장할 수 있습니다. 노드를 한 번에 하나만 추가할 수 있습니다. 
---
= ONTAP 클러스터에 노드를 추가합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터가 생성된 후 노드를 추가하여 클러스터를 확장할 수 있습니다. 노드를 한 번에 하나만 추가할 수 있습니다.

.시작하기 전에
* 하드웨어 요구 사항을 검토하고, 사이트를 준비하고, 하드웨어 구성 요소(컨트롤러, 스토리지 셸프 및 스위치)를 설치 및 케이블링하여 새 스토리지 시스템을 설치하고 구성하십시오. 자세한 내용은 다음 ONTAP 하드웨어 시스템 설명서를 참조하십시오.
+
** link:https://docs.netapp.com/us-en/ontap-systems/aff-landing/index.html["AFF 시스템"^]
** link:https://docs.netapp.com/us-en/ontap-systems/allsan-landing/index.html["ASA 시스템"^]
** link:https://docs.netapp.com/us-en/ontap-systems/afx/index.html["AFX 시스템"^]
** link:https://docs.netapp.com/us-en/ontap-systems/asa-r2/index.html["ASA R2 시스템"^]
** link:https://docs.netapp.com/us-en/ontap-systems/fas/index.html["FAS 시스템"^]


* 새 스토리지 시스템의 클러스터 포트에 대한 클러스터 스위치 모델의 케이블 연결 및 구성 고려 사항을 검토하십시오. link:https://docs.netapp.com/us-en/ontap-systems-switches/index.html["ONTAP 하드웨어 시스템용 스위치 설명서"^]을 참조하십시오.
+
.. *지원되는 스위치* 타일에서 *클러스터 스위치* 또는 *공유 스위치* 를 선택합니다.
.. 스위치 모델에 대한 *설치* 설명서를 선택합니다.
.. *케이블 연결 및 구성 고려 사항 검토* 항목을 검색하여 스토리지 시스템에 대해 검토하십시오.


* 다중 노드 클러스터에 노드를 추가하는 경우 클러스터의 모든 기존 노드가 정상 상태(로 표시됨)여야 합니다 `cluster show`. 에 대한 자세한 내용은 `cluster show` link:https://docs.netapp.com/us-en/ontap-cli/cluster-show.html["ONTAP 명령 참조입니다"^]을 참조하십시오.
* 스위치가 없는 2노드 클러스터에 노드를 추가하려면 NetApp 지원 클러스터 스위치를 사용하여 스위치가 없는 2노드 클러스터를 스위치 연결 클러스터로 변환해야 합니다.
+
[cols="1,2"]
|===
| 스위치 모델 | 마이그레이션 절차 


 a| 
Broadcom BES-53248
 a| 
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-bes-53248/migrate-to-2n-switched.html["스위치 방식의 NetApp 클러스터 환경으로 마이그레이션하세요"^]



 a| 
Cisco Nexus 9336C-FX2
 a| 
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-9336c-fx2/migrate-to-2n-switched-9336-cluster.html["2노드 스위치 클러스터로 마이그레이션"^]



 a| 
Cisco Nexus 9336C-FX2(공유 클러스터+스토리지)
 a| 
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-9336c-fx2-shared/migrate-from-switchless-cluster-dat-storage.html["직접 연결 스토리지를 사용하는 스위치가 없는 클러스터에서 마이그레이션"^]



 a| 
NVIDIA SN2100
 a| 
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/migrate-2n-switched-sn2100-cluster.html["NVIDIA SN2100 클러스터 스위치를 사용하여 2노드 스위치 클러스터로 마이그레이션하십시오"^]

|===
* 단일 노드 클러스터에 두 번째 노드를 추가하는 경우 두 번째 노드가 설치되었고 클러스터 네트워크를 구성해야 합니다.
* 클러스터에 SP 자동 구성이 설정되어 있는 경우 SP에 대해 지정된 서브넷에 사용 가능한 리소스가 있어야 연결 노드에서 지정된 서브넷을 사용하여 SP를 자동으로 구성할 수 있습니다.
* 새 노드의 노드 관리 LIF에 대해 다음 정보를 수집해야 합니다.
+
** 포트
** IP 주소입니다
** 넷마스크
** 기본 게이트웨이




.이 작업에 대해
노드는 HA Pair를 구성할 수 있도록 짝수여야 합니다. 클러스터에 노드를 추가하기 시작한 후 프로세스를 완료해야 합니다. 다른 노드를 추가하기 전에 노드가 클러스터의 일부여야 합니다.

.단계
. 클러스터에 추가할 노드의 전원을 켭니다.
+
노드가 부팅되고 노드 설정 마법사가 콘솔에서 시작됩니다.

+
[listing]
----
Welcome to node setup.

You can enter the following commands at any time:
  "help" or "?" - if you want to have a question clarified,
  "back" - if you want to change previously answered questions, and
  "exit" or "quit" - if you want to quit the setup wizard.
     Any changes you made before quitting will be saved.

To accept a default or omit a question, do not enter a value.

Enter the node management interface port [e0M]:
----
. 노드 설정 마법사를 종료합니다
+
노드 설정 마법사가 종료되고 설치 작업을 완료하지 않았다는 로그인 프롬프트가 나타납니다.

+
에 대한 자세한 내용은 `exit` link:https://docs.netapp.com/us-en/ontap-cli/exit.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

. admin 사용자 이름을 사용하여 admin 계정에 로그인합니다.
. 클러스터 설정 마법사를 시작합니다.
+
[listing]
----
::> cluster setup

Welcome to the cluster setup wizard.

You can enter the following commands at any time:
 "help" or "?" - if you want to have a question clarified,
 "back" - if you want to change previously answered questions, and
 "exit" or "quit" - if you want to quit the cluster setup wizard.
 Any changes you made before quitting will be saved.

You can return to cluster setup at any time by typing "cluster setup".
To accept a default or omit a question, do not enter a value....

Use your web browser to complete cluster setup by accessing
https://<node_mgmt_or_e0M_IP_address>

Otherwise, press Enter to complete cluster setup using the
command line interface:
----
+
[NOTE]
====
설정 GUI를 사용하여 클러스터를 설정하는 방법에 대한 자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/ontap/task_admin_add_nodes_to_cluster.html["노드 관리 문서"] . 에 대한 자세한 내용은 `cluster setup` link:https://docs.netapp.com/us-en/ontap-cli/cluster-setup.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

====
. Enter 키를 눌러 CLI를 사용하여 이 작업을 완료합니다. 새 클러스터를 생성하거나 기존 클러스터에 가입하라는 메시지가 표시되면 ' * join * '을 입력합니다.
+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
join
----
+
새 노드에서 실행 중인 ONTAP 버전이 기존 클러스터에서 실행 중인 버전과 다르면 시스템이 오류를 보고합니다 `System checks Error: Cluster join operation cannot be performed at this time`. 이는 정상적인 동작입니다. 계속하려면 `cluster add-node -allow-mixed-version-join true -cluster-ips <IP address> -node-names <new_node_name>` 클러스터의 기존 노드에서 advanced 권한 수준에서 명령을 실행하십시오.

. 프롬프트에 따라 노드를 설정하고 클러스터에 연결합니다.
+
** 프롬프트의 기본값을 그대로 사용하려면 Enter 키를 누릅니다.
** 프롬프트에 대한 값을 직접 입력하려면 값을 입력한 다음 Enter 키를 누릅니다.


. 추가할 각 추가 노드에 대해 위의 단계를 반복합니다.


.작업을 마친 후
클러스터에 노드를 추가한 후에는 각 HA 쌍에 대해 스토리지 페일오버를 설정해야 합니다.

.관련 정보
* link:../upgrade/concept_mixed_version_requirements.html#mixed-version-clusters-supported-for-ontap-software-upgrades["ONTAP 소프트웨어 업그레이드에 지원되는 혼합 버전 클러스터"]
* https://docs.netapp.com/us-en/ontap-cli/cluster-add-node.html["클러스터 추가 노드"^]

