---
permalink: system-admin/health-monitors-concept.html 
sidebar: sidebar 
keywords: available, cluster, health, monitors, errors, detect, events, alerts, delete 
summary: 클러스터의 여러 부분을 모니터링하는 상태 모니터가 여러 개 있습니다. 상태 모니터는 이벤트를 감지하고, 사용자에게 경고를 보내고, 이벤트를 삭제하여 ONTAP 시스템 내의 오류를 복구할 수 있도록 도와줍니다. 
---
= 사용 가능한 ONTAP 클러스터 상태 모니터에 대해 자세히 알아보십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터의 여러 부분을 모니터링하는 상태 모니터가 여러 개 있습니다. 상태 모니터는 이벤트를 감지하고, 사용자에게 경고를 보내고, 이벤트를 삭제하여 ONTAP 시스템 내의 오류를 복구할 수 있도록 도와줍니다.

|===
| 상태 모니터 이름(식별자) | 하위 시스템 이름(식별자) | 목적 


 a| 
이더넷 스위치
 a| 
스위치(스위치 - 상태)
 a| 
ONTAP 이더넷 스위치 상태 모니터(CSHM)는 분석을 위한 로그를 수집하는 동안 클러스터 및 스토리지 네트워크 스위치의 상태를 모니터링합니다. 기본적으로 CSHM은 5분마다 SNMPv2c를 통해 각 스위치를 폴링하여 지원 가능성, 모니터링 상태, 온도 센서, CPU 사용률, 인터페이스 구성 및 연결, 클러스터 스위치 이중화, 팬 및 전원 공급 장치 작업에 대한 정보를 바탕으로 리소스 테이블을 업데이트합니다. 또한, 구성된 경우 CSHM은 1시간마다 SSH/SCP를 통해 로그를 수집하며, 추가 분석을 위해 AutoSupport를 통해 로그를 전송합니다. 요청 시 CSHM은 SSH/SCP를 사용하여 보다 상세한 기술 지원 로그 수집을 수행할 수도 있습니다.

자세한 내용은 을 link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-cshm/config-overview.html["스위치 상태 모니터링"^] 참조하십시오.



 a| 
MetroCluster 패브릭
 a| 
스위치
 a| 
MetroCluster 구성 백엔드 Fabric 토폴로지를 모니터링하고 잘못된 케이블 연결 및 조닝, ISL 장애 등의 잘못된 구성을 감지합니다.



 a| 
MetroCluster 상태
 a| 
상호 연결, RAID 및 스토리지
 a| 
FC-VI 어댑터, FC 이니시에이터 어댑터, 좌측 애그리게이트 및 디스크, 클러스터 간 포트를 모니터링합니다



 a| 
노드 연결(노드 연결)
 a| 
CIFS 무중단 운영(CIFS-NDO)
 a| 
SMB 연결을 모니터링하여 Hyper-V 애플리케이션의 무중단 운영을 지원합니다.



 a| 
스토리지(SAS-connect)
 a| 
노드 레벨에서 쉘프, 디스크, 어댑터를 모니터링하여 적절한 경로와 연결을 설정합니다.



 a| 
시스템
 a| 
해당 없음
 a| 
다른 상태 모니터의 정보를 집계합니다.



 a| 
시스템 연결(시스템 연결)
 a| 
스토리지(SAS-connect)
 a| 
2개의 HA 클러스터 노드에 대한 적절한 경로에 대해 클러스터 레벨의 쉘프를 모니터링합니다.

|===