---
permalink: system-admin/ontap-implements-audit-logging-concept.html 
sidebar: sidebar 
keywords: ontap, implement, audit, logging, management, autosupport, ems, messages, log, cli, web, browser 
summary: 감사 로그에 기록된 관리 작업은 표준 AutoSupport 보고서에 포함되며, 특정 로깅 작업은 EMS 메시지에 포함됩니다. 또한 지정한 대상에 감사 로그를 전달할 수 있으며 CLI 또는 웹 브라우저를 사용하여 감사 로그 파일을 표시할 수 있습니다. 
---
= ONTAP 감사 로깅 구현에 대해 자세히 알아보십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
감사 로그에 기록된 관리 활동은 표준 AutoSupport 보고서에 포함되고, 특정 로깅 활동은 EMS 메시지에 포함됩니다. 또한 감사 로그를 지정한 대상으로 전송할 수 있으며, ONTAP CLI 또는 웹 브라우저를 사용하여 감사 로그 파일을 표시할 수 있습니다.

ONTAP 9.11.1부터 시스템 관리자를 사용하여 감사 로그 내용을 표시할 수 있습니다.

ONTAP 9.12.1부터 ONTAP는 감사 로그에 대한 변조 경고를 제공합니다. ONTAP는 매일 백그라운드 작업을 실행하여 audit.log 파일의 변조를 확인하고 변경 또는 변조된 로그 파일이 발견되면 EMS 경고를 보냅니다.

ONTAP 9.17.1부터 ONTAP 9.16.1 P4 이상 9.16.1 패치 릴리스에서는link:audit-manage-cross-cluster-requests.html["피어링된 클러스터에서 시작된 원격 관리 활동은 클러스터 간 작업을 사용하여 기록될 수도 있습니다."]. 이러한 활동에는 다른 클러스터에서 발생하는 사용자 중심 작업과 내부 작업이 포함됩니다

.ONTAP 에 기록된 관리 활동
ONTAP 클러스터에서 수행되는 관리 활동을 기록합니다. 여기에는 발행된 요청, 요청을 트리거한 사용자, 사용자의 액세스 방법, 요청 시간 등이 포함됩니다.

관리 활동은 다음 유형 중 하나일 수 있습니다.

* *SET 요청*:
+
** 이러한 요청은 일반적으로 표시되지 않는 명령이나 작업에 적용됩니다.
** 예를 들어, 'create', 'modify', 'delete' 명령을 실행하면 이러한 요청이 실행됩니다.
** SET 요청은 기본적으로 기록됩니다.


* *GET 요청*:
+
** 이러한 요청은 정보를 검색하여 관리 인터페이스에 표시합니다.
** 예를 들어 'show' 명령을 실행하면 이러한 요청이 실행됩니다.
** GET 요청은 기본적으로 기록되지 않지만 ONTAP CLI에서 전송된 GET 요청이 기록되는지 여부를 제어할 수 있습니다. (`-cliget` ), ONTAP API에서 (`-ontapiget` ), 또는 ONTAP REST API에서 (`-httpget` )이 파일에 기록됩니다.




.감사 로그 기록 및 회전
ONTAP 기록 관리 활동  `/mroot/etc/log/mlog/audit.log` 노드 파일입니다. CLI 명령용 세 가지 셸(클러스터셸, 노드셸, 비대화형 시스템셸)과 API 명령이 여기에 기록됩니다. 대화형 시스템셸 명령은 기록되지 않습니다. 감사 로그에는 클러스터의 모든 노드가 동기화되었는지 여부를 보여주는 타임스탬프가 포함됩니다.

Audit.log 파일은 AutoSupport Tool에 의해 지정된 수신인에게 전송된다. 또한 Splunk 또는 syslog 서버와 같이 지정한 외부 대상에 콘텐츠를 안전하게 전달할 수 있습니다.

Audit.log 파일은 매일 순환한다. 회전은 크기가 100MB에 도달하고 이전 48개 사본이 보존될 때도 발생합니다(최대 총 49개 파일). 감사 파일이 매일 회전을 수행하면 EMS 메시지가 생성되지 않습니다. 파일 크기 제한이 초과되어 Audit 파일이 회전하면 EMS 메시지가 발생한다.

GET 감사를 활성화할 때, 빠른 로그 순환으로 인한 데이터 손실을 방지하기 위해 로그 전달을 구성하는 것이 좋습니다. 자세한 내용은 다음 기술 자료 문서를 참조하세요. https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/Enabling_audit-log_forwarding["감사 로그 전달 활성화"^] .
