---
permalink: authentication/grant-access-active-directory-users-groups-task.html 
sidebar: sidebar 
keywords: enable, active directory, account access 
summary: '보안 로그인 create 명령을 사용하여 AD(Active Directory) 사용자 또는 그룹 계정을 활성화하여 admin 또는 data SVM에 액세스할 수 있습니다. AD 그룹의 모든 사용자는 그룹에 할당된 역할을 통해 SVM에 액세스할 수 있습니다.' 
---
= Active Directory ONTAP 계정 액세스를 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
명령을 사용하여 AD(Active Directory) 사용자 또는 그룹 계정을 활성화하여 관리자 또는 데이터 SVM에 액세스할 수 있습니다 `security login create`. AD 그룹의 모든 사용자는 그룹에 할당된 역할을 통해 SVM에 액세스할 수 있습니다. 에 대한 자세한 내용은 `security login create` link:https://docs.netapp.com/us-en/ontap-cli/security-login-create.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

.이 작업에 대해
* 계정이 SVM에 액세스하려면 먼저 클러스터 또는 SVM에 대한 AD 도메인 컨트롤러 액세스를 구성해야 합니다.
+
xref:enable-ad-users-groups-access-cluster-svm-task.adoc[Active Directory 도메인 컨트롤러 액세스 구성]

+
계정 액세스를 활성화하기 전이나 후에 이 작업을 수행할 수 있습니다.

* ONTAP 9.13.1 부터는 SSH 공개 키를 AD 사용자 암호와 함께 기본 또는 보조 인증 방법으로 사용할 수 있습니다.
+
SSH 공개 키를 기본 인증으로 사용하도록 선택하면 AD 인증이 수행되지 않습니다.

* ONTAP 9.11.1부터 AD LDAP 서버에서 지원되는 경우 를 사용할 수 link:../nfs-admin/ldap-fast-bind-nsswitch-authentication-task.html["ONTAP NFS SVM에 대한 nsswitch 인증을 위해 LDAP 빠른 바인딩을 사용합니다."]있습니다.
* 로그인 계정에 할당하려는 액세스 제어 역할이 확실하지 않은 경우 명령을 사용하여 나중에 역할을 추가할 수 `security login modify` 있습니다. 에 대한 자세한 내용은 `security login modify` link:https://docs.netapp.com/us-en/ontap-cli/security-login-modify.html["ONTAP 명령 참조입니다"^]을 참조하십시오.
+
xref:modify-role-assigned-administrator-task.adoc[관리자에게 할당된 역할 수정]




NOTE: AD 그룹 계정 액세스는 에서만 지원됩니다 `SSH`, `ontapi`, 및 `rest` 응용 프로그램. 다단계 인증에는 일반적으로 사용되는 SSH 공개 키 인증에서는 AD 그룹이 지원되지 않습니다.

.시작하기 전에
* 클러스터 시간은 AD 도메인 컨트롤러에서 5분 이내에 에 동기화되어야 합니다.
* 이 작업을 수행하려면 클러스터 관리자여야 합니다.


.단계
. AD 사용자 또는 그룹 관리자 계정을 사용하여 SVM에 액세스:
+
* AD 사용자용: *

+
[cols="1,1,1,4"]
|===
| ONTAP 버전 | 기본 인증 | 보조 인증 | 명령 


| 9.13.1 이상 | 공개 키 | 없음  a| 
[listing]
----
security login create -vserver <svm_name> -user-or-group-name <user_name> -application ssh -authentication-method publickey -role <role>
----


| 9.13.1 이상 | 도메인 | 공개 키  a| 
* 신규 사용자용 *

[listing]
----
security login create -vserver <svm_name> -user-or-group-name <user_name> -application ssh -authentication-method domain -second-authentication-method publickey -role <role>
----
* 기존 사용자의 경우 *

[listing]
----
security login modify -vserver <svm_name> -user-or-group-name <user_name> -application ssh -authentication-method domain -second-authentication-method publickey -role <role>
----


| 9.0 이상 | 도메인 | 없음  a| 
[listing]
----
security login create -vserver <svm_name> -user-or-group-name <user_name> -application <application> -authentication-method domain -role <role> -comment <comment> [-is-ldap-fastbind true]
----
|===
+
AD 그룹의 경우 *

+
[cols="1,1,1,4"]
|===
| ONTAP 버전입니다 | 기본 인증 | 보조 인증 | 명령 


| 9.0 이상 | 도메인 | 없음  a| 
[listing]
----
security login create -vserver <svm_name> -user-or-group-name <user_name> -application <application> -authentication-method domain -role <role> -comment <comment> [-is-ldap-fastbind true]
----
|===


.작업을 마친 후
AD 도메인 컨트롤러를 클러스터 또는 SVM에 액세스하도록 구성하지 않은 경우 계정이 SVM에 액세스하려면 먼저 액세스 권한을 구성해야 합니다.

xref:enable-ad-users-groups-access-cluster-svm-task.adoc[Active Directory 도메인 컨트롤러 액세스 구성]
