---
permalink: authentication/install-server-certificate-cluster-svm-ssl-server-task.html 
sidebar: sidebar 
keywords: generate, install, ca-signed, server, certificate, csr, signing request, signed 
summary: 운영 시스템에서 클러스터 또는 SVM을 SSL 서버로 인증하는 데 사용할 CA 서명 디지털 인증서를 설치하는 것이 좋습니다. 
---
= ONTAP에서 CA 서명 서버 인증서를 생성하고 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
운영 시스템에서 클러스터 또는 SVM을 SSL 서버로 인증하는 데 사용할 CA 서명 디지털 인증서를 설치하는 것이 좋습니다. 명령을 사용하여 인증서 서명 요청(CSR)을 생성하고, `security certificate install` 명령을 사용하여 인증 기관으로부터 받은 인증서를 설치할 수 `security certificate generate-csr` 있습니다. 및 `security certificate install` 에 대한 자세한 `security certificate generate-csr` 내용은 을 link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+certificate["ONTAP 명령 참조입니다"^]참조하십시오.



== 인증서 서명 요청을 생성합니다

'Security certificate generate -csr' 명령을 사용하여 CSR(인증서 서명 요청)을 생성할 수 있습니다. 요청을 처리한 후 CA(인증 기관)에서 서명된 디지털 인증서를 보냅니다.

.시작하기 전에
이 작업을 수행하려면 클러스터 또는 SVM 관리자여야 합니다.

.단계
. CSR 생성:
+
[source, cli]
----
security certificate generate-csr -common-name FQDN_or_common_name -size 512|1024|1536|2048 -country country -state state -locality locality -organization organization -unit unit -email-addr email_of_contact -hash-function SHA1|SHA256|MD5
----
+
다음 명령을 실행하면 미국 캘리포니아주 서니베일에 위치한 회사 부서의 `server1.companyname.com` 그룹에서 `IT` 사용할 수 있도록 해시 기능에서 `Software` 생성된 2048비트 개인 키가 포함된 CSR이 `SHA256` 생성됩니다. SVM 담당자 관리자의 이메일 주소는 입니다 `web@example.com`. 출력에 CSR과 개인 키가 표시됩니다.

+
.CSR 생성 예
[%collapsible]
====
[listing]
----
cluster1::>security certificate generate-csr -common-name server1.companyname.com -size 2048 -country US -state California -locality Sunnyvale -organization IT -unit Software -email-addr web@example.com -hash-function SHA256

Certificate Signing Request :
-----BEGIN CERTIFICATE REQUEST-----
<certificate_value>
-----END CERTIFICATE REQUEST-----


Private Key :
-----BEGIN RSA PRIVATE KEY-----
<key_value>
-----END RSA PRIVATE KEY-----

NOTE: Keep a copy of your certificate request and private key for future reference.
----
====
. CSR 출력에서 인증서 요청을 복사한 다음 전자 양식(예: 전자 메일)으로 신뢰할 수 있는 타사 CA로 보내 서명합니다.
+
요청을 처리한 후 CA는 서명된 디지털 인증서를 보냅니다. 개인 키와 CA 서명 디지털 인증서의 복사본을 유지해야 합니다.





== CA 서명 서버 인증서를 설치합니다

명령을 사용하여 SVM에 CA 서명 서버 인증서를 설치할 수 있습니다 `security certificate install`. ONTAP는 서버 인증서의 인증서 체인을 형성하는 CA(인증 기관) 루트 및 중간 인증서를 입력하라는 메시지를 표시합니다. 에 대한 자세한 내용은 `security certificate install` link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-install.html["ONTAP 명령 참조입니다"^]을 참조하십시오.

.시작하기 전에
이 작업을 수행하려면 클러스터 또는 SVM 관리자여야 합니다.

.단계
. CA 서명 서버 인증서 설치:
+
[source, cli]
----
security certificate install -vserver SVM_name -type certificate_type
----
+
[NOTE]
====
ONTAP 서버 인증서의 인증서 체인을 형성하는 CA 루트 및 중간 인증서를 입력하라는 메시지가 표시됩니다. 체인은 서버 인증서를 발급한 CA의 인증서로 시작되며 CA의 루트 인증서까지 범위가 될 수 있습니다. 누락된 중간 인증서는 서버 인증서 설치에 실패합니다.

====
+
다음 명령을 실행하면 SVM에 CA 서명 서버 인증서 및 중간 인증서를 설치합니다 `engData2`.

+
.CA 서명 서버 인증서 중간 인증서 설치 예
[%collapsible]
====
[listing]
----
cluster1::>security certificate install -vserver engData2 -type server
Please enter Certificate: Press <Enter> when done
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----


Please enter Private Key: Press <Enter> when done
-----BEGIN RSA PRIVATE KEY-----
<key_value>
-----END RSA PRIVATE KEY-----

Do you want to continue entering root and/or intermediate certificates {y|n}: y

Please enter Intermediate Certificate: Press <Enter> when done
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----


Do you want to continue entering root and/or intermediate certificates {y|n}: y

Please enter Intermediate Certificate: Press <Enter> when done
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----


Do you want to continue entering root and/or intermediate certificates {y|n}: n

You should keep a copy of the private key and the CA-signed digital certificate for future reference.
----
====

